/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

$(document).ready(function(){function v(b){if(l[b]===undefined)b=0;jQuery.each(l[b],function(a,d){$("select#cat_id").empty().append(d)})}function o(){if($("#custom_date_start").val()!="yyyy-mm-dd"&&$("#custom_date_end").val()!="yyyy-mm-dd"){focus_number=$("#date_range").children().length;$("#date_range").append('<option id="custom_date_option">'+$("#custom_date_start").val()+" to "+$("#custom_date_end").val()+"</option>");document.getElementById("date_range").options[focus_number].selected=true;$("#custom_date_picker").slideUp("fast");
oTable.fnDraw()}}function p(b,a,d){for(var f=0,e=b.length;f<e;f++)if(b[f].name==a)b[f].value=d}function m(b,a){for(var d=0,f=b.length;d<f;d++)if(b[d].name==a)return b[d].value;return null}$(".paginationLinks .first").hide();$(".paginationLinks .previous").hide();$(".toggle_all").toggle(function(){$("input.toggle").each(function(){this.checked=true})},function(){$("input.toggle").each(function(){this.checked=false})});$("#custom_date_start_span").datepicker({dateFormat:"yy-mm-dd",prevText:"<<",nextText:">>",
onSelect:function(b){$("#custom_date_start").val(b);o()}});$("#custom_date_end_span").datepicker({dateFormat:"yy-mm-dd",prevText:"<<",nextText:">>",onSelect:function(b){$("#custom_date_end").val(b);o()}});$("#custom_date_start, #custom_date_end").focus(function(){$(this).val()=="yyyy-mm-dd"&&$(this).val("")});$("#custom_date_start, #custom_date_end").keypress(function(){$(this).val().length>=9&&o()});var l=EE.file.directoryInfo,w=RegExp("!-!","g"),x=(new Date).getTime();(function(){jQuery.each(l,
function(b,a){jQuery.each(a,function(d,f){var e=new String;jQuery.each(f,function(i,n){e+='<option value="'+n[0]+'">'+n[1].replace(w,String.fromCharCode(160))+"</option>"});l[b][d]=e})})})();$("#dir_id").change(function(){v(this.value)});$("#date_range").change(function(){if($("#date_range").val()=="custom_date"){$("#custom_date_start").val("yyyy-mm-dd");$("#custom_date_end").val("yyyy-mm-dd");$("#custom_date_option").remove();$("#custom_date_picker").slideDown("fast")}else $("#custom_date_picker").hide()});
$("a.overlay").live("click",function(){$("#overlay").hide().removeData("overlay");$("#overlay .contentWrap img").remove();$("<img />").appendTo("#overlay .contentWrap").load(function(){var b=$(this).clone().appendTo(document.body).show(),a=b.width(),d=b.height(),f=$(window).width()*0.8,e=$(window).height()*0.8;f=f/a;e=e/d;e=f>e?e:f;b.remove();if(e<1){d*=e;a*=e;$(this).height(d).width(a)}$("#overlay").overlay({load:true,speed:100,top:"center"})}).attr("src",$(this).attr("href"));return false});$("#overlay").css("cursor",
"pointer").click(function(){$(this).fadeOut(100)});var c={iCacheLower:-1};if(EE.file.tableColumns==9){MyCols=[null,null,null,null,null,null,null,{bSortable:false},{bSortable:false}];MySortCol=6}else{MyCols=[null,null,null,null,null,null,{bSortable:false},{bSortable:false}];MySortCol=5}oTable=$("#file_form .mainTable").dataTable({sPaginationType:"full_numbers",bLengthChange:false,aaSorting:[[MySortCol,"desc"]],bFilter:false,sWrapper:false,sInfo:false,bAutoWidth:false,iDisplayLength:+EE.file.perPage,
aoColumns:MyCols,oLanguage:{sZeroRecords:EE.lang.noEntries,oPaginate:{sFirst:'<img src="'+EE.file.themeUrl+'images/pagination_first_button.gif" width="13" height="13" alt="&lt; &lt;" />',sPrevious:'<img src="'+EE.file.themeUrl+'images/pagination_prev_button.gif" width="13" height="13" alt="&lt; &lt;" />',sNext:'<img src="'+EE.file.themeUrl+'images/pagination_next_button.gif" width="13" height="13" alt="&lt; &lt;" />',sLast:'<img src="'+EE.file.themeUrl+'images/pagination_last_button.gif" width="13" height="13" alt="&lt; &lt;" />'}},
bProcessing:true,bServerSide:true,sAjaxSource:EE.BASE+"&C=content_files&M=file_ajax_filter&time="+x,fnServerData:function(b,a,d){function f(){if($(q).data("user_data")=="n")return"";return q.value}var e=+EE.file.pipe,i=false,n=m(a,"sEcho"),g=m(a,"iDisplayStart"),j=m(a,"iDisplayLength"),h=g+j,q=document.getElementById("keywords"),r=document.getElementById("file_type"),s=document.getElementById("dir_id"),t=document.getElementById("cat_id"),u=document.getElementById("date_range");a.push({name:"keywords",
value:f()},{name:"type",value:r.value},{name:"dir_id",value:s.value},{name:"cat_id",value:t.value},{name:"date_range",value:u.value});c.iDisplayStart=g;if(c.iCacheLower<0||g<c.iCacheLower||h>c.iCacheUpper)i=true;if(c.lastRequest&&!i){h=0;for(var y=a.length;h<y;h++)if(a[h].name!="iDisplayStart"&&a[h].name!="iDisplayLength"&&a[h].name!="sEcho")if(a[h].value!=c.lastRequest[h].value){i=true;break}}c.lastRequest=a.slice();if(i){if(g<c.iCacheLower){g-=j*(e-1);if(g<0)g=0}c.iCacheLower=g;c.iCacheUpper=g+
j*e;c.iDisplayLength=m(a,"iDisplayLength");p(a,"iDisplayStart",g);p(a,"iDisplayLength",j*e);a.push({name:"keywords",value:f()},{name:"type",value:r.value},{name:"dir_id",value:s.value},{name:"cat_id",value:t.value},{name:"date_range",value:u.value});$.getJSON(b,a,function(k){c.lastJson=jQuery.extend(true,{},k);c.iCacheLower!=c.iDisplayStart&&k.aaData.splice(0,c.iDisplayStart-c.iCacheLower);k.aaData.splice(c.iDisplayLength,k.aaData.length);d(k)})}else{json=jQuery.extend(true,{},c.lastJson);json.sEcho=
n;json.aaData.splice(0,g-c.iCacheLower);json.aaData.splice(j,json.aaData.length);d(json)}}});$("#keywords").keyup(function(){oTable.fnDraw()});$("select#dir_id").change(function(){oTable.fnDraw()});$("select#cat_id").change(function(){oTable.fnDraw()});$("select#file_type").change(function(){oTable.fnDraw()});$("select#date_range").change(function(){oTable.fnDraw()})});
