/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2010, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

$.tablesorter.addParser({id:"ee_filesize",is:function(){return false},format:function(f){f=f.replace(/[^0-9.]/g,"");return f*1E3},type:"numeric"});$.tablesorter.addParser({id:"ee_date",is:function(){return false},format:function(f,i,g){return $(g).attr("data-rawdate")},type:"numeric"});
$(document).ready(function(){function f(a){var e,b;e=$("#file_information_hold");b=$("#file_information_header");b.removeClass("closed");b.addClass("open");e.slideDown("fast");e.html('<p style="text-align: center;"><img src="'+EE.THEME_URL+'images/indicator.gif" alt="'+EE.lang.loading+'" /><br />'+EE.lang.loading+"...</p>");$.get(EE.BASE+"&C=content_files&M=file_info",{file:a},function(c){e.html(c)})}function i(a){$("#progress").html('<span class="notice">'+a+"</span>")}function g(){$(".toggle").unbind("click").click(function(){$(this).parent().parent().toggleClass("selected")});
$(".mainTable td").unbind("click").click(function(a){if(a.ctrlKey||a.metaKey){$(this).parent().toggleClass("selected");$(this).parent().find(".file_select :checkbox").attr("checked")?$(this).parent().find(".file_select :checkbox").attr("checked",""):$(this).parent().find(".file_select :checkbox").attr("checked","true")}})}$(".mainTable").tablesorter({headers:{1:{sorter:"ee_filesize"},3:{sorter:"ee_date"},4:{sorter:false},5:{sorter:false},6:{sorter:false}},widgets:["zebra"],sortList:[[0,0]]});$("#file_tools").show();
$("#download_selected").css("display","block");$("#showToolbarLink a").toggle(function(){$("#file_manager_tools").hide();$("#showToolbarLink a span").text(EE.lang.show_toolbar);$("#showToolbarLink").animate({marginRight:"20"});$("#file_manager_holder").animate({marginRight:"10"});$("#hideToolbarImg").hide();$("#showToolbarImg").css("display","inline")},function(){$("#showToolbarLink a span").text(EE.lang.hide_toolbar);$("#showToolbarLink").animate({marginRight:"264"});$("#file_manager_holder").animate({marginRight:"250"},
function(){$("#file_manager_tools").show();$("#showToolbarImg").hide();$("#hideToolbarImg").css("display","inline")})});$("#file_manager_tools h3 a").toggle(function(){$(this).parent().next("div").slideUp();$(this).toggleClass("closed")},function(){$(this).parent().next("div").slideDown();$(this).toggleClass("closed")});$("#file_manager_list h3").toggle(function(){document.cookie="exp_hide_upload_"+$(this).next().attr("id")+"=true";$(this).next().slideUp();$(this).toggleClass("closed")},function(){document.cookie=
"exp_hide_upload_"+$(this).next().attr("id")+"=false";$(this).next().slideDown();$(this).toggleClass("closed")});$("#file_manager_tools h3.closed").next("div").hide();$("#file_manager_tools h3.closed a").click();$("input[type=file]").ee_upload({url:EE.BASE+"&C=content_files&M=upload_file&is_ajax=true",onStart:function(){$("#progress").html('<p><img src="'+EE.THEME_URL+'images/indicator.gif" alt="'+EE.lang.loading+'" />'+EE.lang.uploading_file+"</p>").show();return{upload_dir:$("#upload_dir").val()}},
onComplete:function(a,e,b){if(typeof a==="object")if(a.success){var c="#dir_id_"+b.upload_dir;$.get(EE.BASE+"&C=content_files&ajax=true&directory="+b.upload_dir+"&enc_path="+a.enc_path,function(d){var h=$("<div />");h.append(d);h=h.find("tbody tr");$(c+" tbody").append(h);$(c+" tbody .no_files_warning").parent().remove();$(c+" table").trigger("update");$("table").trigger("sorton",[[[0,0]]]);g();$("#progress").html(a).slideUp("slow")},"html")}else i(a.error)}});$("#download_selected a").click(function(){var a=
$("#files_form").attr("action");$("#files_form").attr("action",a.replace(/delete_files_confirm/,"download_files"));$("#files_form").submit();$("#files_form").attr("action",a);return false});$("a#email_files").click(function(){alert("not yet functional");return false});$("#delete_selected_files a").click(function(){var a=$("#files_form").attr("action");$("#files_form").attr("action",a.replace(/download_files/,"delete_files_confirm"));$("#files_form").submit();return false});$(".toggle_all").toggle(function(){$(this).closest("table").find("tbody tr").addClass("selected");
$(this).closest("table").find("input.toggle").attr("checked",true)},function(){$(this).closest("table").find("tbody tr").removeClass("selected");$(this).closest("table").find("input.toggle").attr("checked",false)});$("input.toggle").each(function(){this.checked=false});g();$("a.overlay").live("click",function(){$("#overlay").hide().removeData("overlay");$("#overlay .contentWrap img").remove();$("<img />").appendTo("#overlay .contentWrap").load(function(){var a=$(this).clone().appendTo(document.body).show(),
e=a.width(),b=a.height(),c=$(window).width()*0.8,d=$(window).height()*0.8;c=c/e;d=d/b;d=c>d?d:c;a.remove();if(d<1){b*=d;e*=d;$(this).height(b).width(e)}$("#overlay").overlay({load:true,speed:100,top:"center"})}).attr("src",$(this).attr("href"));f($(this).parent().attr("id"));return false});$("#overlay").css("cursor","pointer").click(function(){$(this).fadeOut(100)})});
