/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

jQuery(document).ready(function(){function a(){var a=EE.SESS_TIMEOUT-6E4,c=EE.XID_TIMEOUT-6E4,d=a<c?a:c,f=!1,g,h;h=function(){b.ajax({type:"POST",dataType:"json",url:EE.BASE+"&C=login&M=refresh_xid",success:function(a){b("input[name='XID']").val(a.xid);EE.XID=a.xid;setTimeout(h,c)}})};g=function(){var a='<form><div id="logOutWarning" style="text-align:center"><p>'+EE.lang.session_expiring+'</p><label for="username">'+EE.lang.username+'</label>: <input type="text" id="log_backin_username" name="username" value="" style="width:100px" size="35" dir="ltr" id="username" maxlength="32"  />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label for="password">'+
EE.lang.password+'</label>: <input class="field" id="log_backin_password" type="password" name="password" value="" style="width:100px" size="32" dir="ltr" id="password" maxlength="32"  />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" id="submit" name="submit" value="'+EE.lang.login+'" class="submit" /><span id="logInSpinner"></span></div></form>',c;if(f===!0)return(void 0)(f),!1;else setTimeout(void 0,d);b.ee_notice(a,{type:"custom",open:!0,close_on_click:!1});c=b("#logOutWarning");c.find("#log_backin_username").focus();
c.find("input#submit").click(function(){var a=c.find("input#log_backin_username").val(),e=c.find("input#log_backin_password").val(),h=b(this),i=c.find("span#logInSpinner");h.hide();i.html('<img src="'+EE.PATH_CP_GBL_IMG+'loader_blackbg.gif" />');b.ajax({type:"POST",dataType:"json",url:EE.BASE+"&C=login&M=authenticate&is_ajax=true",data:{username:a,password:e,XID:EE.XID},success:function(a){f=!0;if(a.messageType==="success")b("input[name='XID']").val(a.xid),c.slideUp("fast"),b.ee_notice(a.message,
{type:"custom",open:!0}),setTimeout(b.ee_notice.destroy,1600),EE.XID=a.xid,f=!0,clearTimeout(g),setTimeout(g,d);else if(a.messageType==="failure")c.before('<div id="loginCheckFailure">'+a.message+"</div>"),i.hide("fast"),h.css("display","inline");else if(a.messageType==="logout")window.location.href=EE.BASE+"&C=login&M=logout&auto_expire=true"}});return!1})};EE.SESS_TYPE==="c"?setTimeout(h,c):setTimeout(g,d)}var b=jQuery;b(document).bind("ajaxComplete",function(b,a){if(a.status&&+a.status===401)window.location=
EE.BASE+"&"+a.responseText});!1 in document.createElement("input")&&EE.insert_placeholders();b('a[rel="external"]').click(function(){window.open(this.href);return!1});finalLogOutTimer=function(){var e=b('<div id="logOutConfirm">'+EE.lang.session_timeout+" </div>"),c=30,d=c,f,g,h,i;h=function(){window.location=EE.BASE+"&C=login&M=logout&auto_expire=true"};i=function(){if(c<1)return setTimeout(h,0);else c===d&&b(window).bind("unload.logout",h);e.dialog("option","title",EE.lang.logout+" ("+(c--||"...")+
")");f=setTimeout(i,1E3)};g={Cancel:function(){b(this).dialog("close")}};g[EE.lang.logout]=h;e.dialog({autoOpen:!1,resizable:!1,modal:!0,title:EE.lang.logout,position:"center",minHeight:"0",buttons:g,beforeClose:function(){clearTimeout(f);b(window).unbind("unload.logout");c=d;b.ajax({type:"POST",dataType:"json",url:EE.BASE+"&C=login&M=refresh_xid",success:function(c){b("input[name='XID']").val(c.xid);EE.XID=c.xid;b("#logOutWarning").slideUp("fast");a()}})}});b("#logOutConfirm").dialog("open");b(".ui-dialog-buttonpane button:eq(2)").focus();
i();return!1};EE.SESS_TIMEOUT&&a();EE.cp.show_hide_sidebar();EE.flashdata!==void 0&&EE.cp.display_notices();EE.notepad=function(){var a=b("#notePad"),c=b("#notepad_form"),d=b("#notePadTextEdit"),f=b("#notePadControls"),g=b("#notePadText").removeClass("js_show"),h=g.text(),i=d.val();return{init:function(){i&&g.html(i.replace(/</ig,"&lt;").replace(/>/ig,"&gt;").replace(/\n/ig,"<br />"));a.click(EE.notepad.show);f.find("a.cancel").click(EE.notepad.hide);c.submit(EE.notepad.submit);f.find("input.submit").click(EE.notepad.submit);
d.autoResize()},submit:function(){i=b.trim(d.val());var a=i.replace(/</ig,"&lt;").replace(/>/ig,"&gt;").replace(/\n/ig,"<br />");d.attr("readonly","readonly").css("opacity",0.5);f.find("#notePadSaveIndicator").show();b.post(c.attr("action"),{notepad:i,XID:EE.XID},function(){g.html(a||h).show();d.attr("readonly","").css("opacity",1).hide();f.hide().find("#notePadSaveIndicator").hide()},"json");return!1},show:function(){if(f.is(":visible"))return!1;var a="";g.hide().text()!==h&&(a=g.html().replace(/<br>/ig,
"\n").replace(/&lt;/ig,"<").replace(/&gt;/ig,">"));f.show();d.val(a).show().height(0).focus().trigger("keypress")},hide:function(){g.show();d.hide();f.hide();return!1}}}();EE.notepad.init();EE.cp.accessory_toggle();EE.cp.control_panel_search();b("h4","#quickLinks").click(function(){window.location.href=EE.BASE+"&C=myaccount&M=quicklinks"}).add("#notePad").hover(function(){b(".sidebar_hover_desc",this).show()},function(){b(".sidebar_hover_desc",this).hide()}).css("cursor","pointer");EE.cp.logout_confirm();
b(".js_show").show()});EE.namespace=function(a){var a=a.split("."),b=EE;a[0]==="EE"&&(a=a.slice(1));for(var e=0,c=a.length;e<c;e+=1)typeof b[a[e]]==="undefined"&&(b[a[e]]={}),b=b[a[e]];return b};EE.namespace("EE.cp");
EE.cp.accessory_toggle=function(){$("#accessoryTabs li a").click(function(a){a.preventDefault();var a=$(this).parent("li"),b=$("#"+this.className);a.hasClass("current")?(b.hide(),a.removeClass("current")):(a.siblings().hasClass("current")?(b.show().siblings(":not(#accessoryTabs)").hide(),a.siblings().removeClass("current")):b.slideDown(),a.addClass("current"))})};
EE.cp.control_panel_search=function(){var a=$("#search"),b=a.clone(),e=$("#cp_search_form").find(".searchButton"),c;c=function(){var d=$(this).attr("action"),f={cp_search_keywords:$("#cp_search_keywords").val(),XID:EE.XID};$.ajax({url:d,data:f,type:"POST",dataType:"html",beforeSend:function(){e.toggle()},success:function(d){e.toggle();a=a.replaceWith(b);b.html(d);$("#cp_reset_search").click(function(){b=b.replaceWith(a);$("#cp_search_form").submit(c);$("#cp_search_keywords").select();return!1})}});
return!1};$("#cp_search_form").submit(c)};
EE.cp.show_hide_sidebar=function(){var a={revealSidebarLink:"77%",hideSidebarLink:"100%"},b=$("#mainContent"),e=$("#sidebarContent"),c=b.height(),d=e.height(),f;EE.CP_SIDEBAR_STATE==="n"?(b.css("width","100%"),$("#revealSidebarLink").css("display","block"),$("#hideSidebarLink").hide(),e.show(),d=e.height(),e.hide()):(e.hide(),c=b.height(),e.show());f=d>c?d:c;$("#revealSidebarLink, #hideSidebarLink").click(function(){var d=$(this),h=d.siblings("a"),i=this.id==="revealSidebarLink";$.ajax({type:"POST",
dataType:"json",url:EE.BASE+"&C=myaccount&M=update_sidebar_status",data:{XID:EE.XID,show:i},success:function(){}});$("#sideBar").css({position:"absolute","float":"",right:"0"});d.hide();h.css("display","block");e.slideToggle();b.animate({width:a[this.id],height:i?f:c},function(){b.height("");$("#sideBar").css({position:"","float":"right"})});return!1})};
EE.cp.display_notices=function(){var a=$(".notice").filter("p.js_hide"),b={success:"message_success",notice:"message",error:"message_failure"},e=[],c=0,d,f;for(d in b)EE.flashdata.hasOwnProperty(b[d])&&(f=d==="error"?a.filter(".failure").slice(0,1):d==="success"?a.filter(".success").slice(0,1):a.slice(0,1),e[c++]={message:EE.flashdata[b[d]],type:d},f.remove());e.length&&$.ee_notice(e)};
EE.insert_placeholders=function(){$('input[type="text"]').each(function(){if(this.placeholder){var a=$(this),b=this.placeholder,e=a.css("color");a.val()==""&&a.data("user_data","n");a.focus(function(){a.css("color",e);a.val()===b&&(a.val(""),a.data("user_data","y"))}).blur(function(){if(a.val()===""||a.val===b)a.val(b).css("color","#888"),a.data("user_data","n")}).trigger("blur")}})};
EE.cp.logout_confirm=function(){$("#activeUser").one("mouseover",function(){var a=$('<div id="logOutConfirm">'+EE.lang.logout_confirm+" </div>"),b=30,e=b,c,d,f,g;f=function(){$.ajax({url:EE.BASE+"&C=login&M=logout",async:!$.browser.safari});window.location=EE.BASE+"&C=login&M=logout"};g=function(){if(b<1)return setTimeout(f,0);else b===e&&$(window).bind("unload.logout",f);a.dialog("option","title",EE.lang.logout+" ("+(b--||"...")+")");c=setTimeout(g,1E3)};d={Cancel:function(){$(this).dialog("close")}};
d[EE.lang.logout]=f;a.dialog({autoOpen:!1,resizable:!1,modal:!0,title:EE.lang.logout,position:"center",minHeight:"0",buttons:d,beforeClose:function(){clearTimeout(c);$(window).unbind("unload.logout");b=e}});$("a.logOutButton",this).click(function(){$("#logOutConfirm").dialog("open");$(".ui-dialog-buttonpane button:eq(2)").focus();g();return!1})})};
