/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		EllisLab Dev Team
 * @copyright	Copyright (c) 2003 - 2013, EllisLab, Inc.
 * @license		http://ellislab.com/expressionengine/user-guide/license.html
 * @link		http://ellislab.com
 * @since		Version 2.0
 * @filesource
 */

jQuery(document).ready(function(){var a=jQuery;a.ajaxPrefilter(function(b,c,d){var e=EE.XID,f=b.type.toUpperCase();_.has(b,"error")||d.error(function(a){_.defer(function(){throw[a.statusText,a.responseText];})});"POST"==f&&!1===b.crossDomain&&d.setRequestHeader("X-EEXID",e);eeResponseHeaders=a.merge({xid:function(a){EE.cp.xid.set(a)},redirect:function(a){window.location=EE.BASE+"&"+a.replace("//","/")},broadcast:function(b){EE.cp.broadcastEvents[b]();a(window).trigger("broadcast",b)}},c.eeResponseHeaders||
{});d.complete(function(a){!1===b.crossDomain&&_.each(eeResponseHeaders,function(b,d){var c=a.getResponseHeader("X-EE"+d);c&&b(c)})})});a(document).bind("ajaxComplete",function(a,c){c.status&&401===+c.status&&(window.location=EE.BASE+"&"+c.responseText)});!1 in document.createElement("input")&&EE.insert_placeholders();a('a[rel="external"]').click(function(){window.open(this.href);return!1});EE.importantMessage&&(msgBoxOpen=EE.importantMessage.state,msgContainer=a("#ee_important_message"),save_state=
function(){msgBoxOpen=!msgBoxOpen;document.cookie="exp_home_msg_state="+(msgBoxOpen?"open":"closed")},setup_hidden=function(){a.ee_notice.show_info(function(){a.ee_notice.hide_info();msgContainer.removeClass("closed").show();save_state()})},msgContainer.find(".msg_open_close").click(function(){msgContainer.hide();setup_hidden();save_state()}),msgBoxOpen||setup_hidden());EE.cp.zebra_tables();EE.cp.show_hide_sidebar();EE.cp.display_notices();EE.cp.deprecation_meaning();EE.notepad=function(){var b=a("#notePad"),
c=a("#notepad_form"),d=a("#notePadTextEdit"),e=a("#notePadControls"),f=a("#notePadText");notepad_empty=f.text();current_content=d.val();return{init:function(){current_content&&f.html(current_content.replace(/</ig,"&lt;").replace(/>/ig,"&gt;").replace(/\n/ig,"<br />"));b.click(EE.notepad.show);e.find("a.cancel").click(EE.notepad.hide);c.submit(EE.notepad.submit);e.find("input.submit").click(EE.notepad.submit);d.autoResize()},submit:function(){current_content=a.trim(d.val());var b=current_content.replace(/</ig,
"&lt;").replace(/>/ig,"&gt;").replace(/\n/ig,"<br />");d.attr("readonly","readonly").css("opacity",0.5);e.find("#notePadSaveIndicator").show();a.post(c.attr("action"),{notepad:current_content},function(a){f.html(b||notepad_empty).show();d.attr("readonly",!1).css("opacity",1).hide();e.hide().find("#notePadSaveIndicator").hide()},"json");return!1},show:function(){if(e.is(":visible"))return!1;var a="";f.hide().text()!==notepad_empty&&(a=f.html().replace(/<br>/ig,"\n").replace(/&lt;/ig,"<").replace(/&gt;/ig,
">"));e.show();d.val(a).show().height(0).focus().trigger("keypress")},hide:function(){f.show();d.hide();e.hide();return!1}}}();EE.notepad.init();EE.cp.accessory_toggle();EE.cp.control_panel_search();a("h4","#quickLinks").click(function(){window.location.href=EE.BASE+"&C=myaccount&M=quicklinks"}).add("#notePad").hover(function(){a(".sidebar_hover_desc",this).show()},function(){a(".sidebar_hover_desc",this).hide()}).css("cursor","pointer")});
EE.namespace=function(a){a=a.split(".");var b=EE;"EE"===a[0]&&(a=a.slice(1));for(var c=0,d=a.length;c<d;c+=1)"undefined"===typeof b[a[c]]&&(b[a[c]]={}),b=b[a[c]];return b};EE.namespace("EE.cp");
EE.cp.accessory_toggle=function(){$("#accessoryTabs li a").click(function(a){a.preventDefault();a=$(this).parent("li");var b=$("#"+this.className);a.hasClass("current")?(b.slideUp("fast"),a.removeClass("current")):(a.siblings().hasClass("current")?(b.show().siblings(":not(#accessoryTabs)").hide(),a.siblings().removeClass("current")):b.slideDown("fast"),a.addClass("current"))})};
EE.cp.control_panel_search=function(){var a=$("#search"),b=a.clone(),c=$("#cp_search_form").find(".searchButton"),d;d=function(){var e=$(this).attr("action"),f={cp_search_keywords:$("#cp_search_keywords").val()};$.ajax({url:e,data:f,type:"POST",dataType:"html",beforeSend:function(){c.toggle()},success:function(e){c.toggle();a=a.replaceWith(b);b.html(e);$("#cp_reset_search").click(function(){b=b.replaceWith(a);$("#cp_search_form").submit(d);$("#cp_search_keywords").select();return!1})}});return!1};
$("#cp_search_form").submit(d)};
EE.cp.show_hide_sidebar=function(){var a={revealSidebarLink:"77%",hideSidebarLink:"100%"},b=$("#mainContent"),c=$("#sidebarContent"),d=b.height(),e=c.height(),f;"n"===EE.CP_SIDEBAR_STATE?(b.css("width","100%"),$("#revealSidebarLink").css("display","block"),$("#hideSidebarLink").hide(),c.show(),e=c.height(),c.hide()):(c.hide(),d=b.height(),c.show());f=e>d?e:d;$("#revealSidebarLink, #hideSidebarLink").click(function(e){var g=$(this),l=g.siblings("a"),h="revealSidebarLink"===this.id;$.ajax({type:"POST",
dataType:"json",url:EE.BASE+"&C=myaccount&M=update_sidebar_status",data:{show:h},success:function(a){}});e.isTrigger||$(window).trigger("broadcast.sidebar",h);$("#sideBar").css({position:"absolute","float":"",right:"0"});g.hide();l.css("display","block");c.slideToggle();b.animate({width:a[this.id],height:h?f:d},function(){b.height("");$("#sideBar").css({position:"","float":"right"})});return!1});$(window).bind("broadcast.sidebar",function(a,b){$(b?"#revealSidebarLink":"#hideSidebarLink").filter(":visible").trigger("click")})};
EE.cp.display_notices=function(){var a=["success","notice","error"];$(".message.js_hide").each(function(){for(i in a)$(this).hasClass(a[i])&&$.ee_notice($(this).html(),{type:a[i]})})};
EE.insert_placeholders=function(){$('input[type="text"]').each(function(){if(this.placeholder){var a=$(this),b=this.placeholder,c=a.css("color");""==a.val()&&a.data("user_data","n");a.focus(function(){a.css("color",c);a.val()===b&&(a.val(""),a.data("user_data","y"))}).blur(function(){if(""===a.val()||a.val===b)a.val(b).css("color","#888"),a.data("user_data","n")}).trigger("blur")}})};
EE.cp.broadcastEvents=function(){var a=$("#idle-modal").dialog({autoOpen:!1,resizable:!1,title:EE.lang.session_idle,modal:!0,closeOnEscape:!1,position:"center",height:"auto",width:354});a.closest(".ui-dialog").find(".ui-dialog-titlebar-close").remove();a.find("form").on("submit",function(){var b=EE.BASE;$.ajax({type:"POST",url:this.action,data:$(this).serialize(),dataType:"json",success:function(c){"success"!=c.messageType?alert(c.message):(a.off("dialogbeforeclose"),a.dialog("close"),EE.BASE=c.base.replace(/&amp;/g,
"&"),c=function(a,c){return c.replace(b,EE.BASE)},$("a").prop("href",c),$("form").prop("action",c),$(window).trigger("broadcast.idleState","login"))},error:function(a){alert(a.message)}});return!1});var b={hasFocus:!0,modalActive:!1,idleCount:0,pingReceived:!1,modalThresholdReached:function(){var a=this.hasFocus&&80<this.idleCount||!this.hasFocus&&160<this.idleCount;return!1===this.modalActive&&!0===a},logoutThresholdReached:function(){return this.modalActive&&120<this.idleCount},resolve:function(){this.logoutThresholdReached()&&
(c.logout(),$(window).trigger("broadcast.idleState","logout"));b.modalThresholdReached()&&(c.modal(),$(window).trigger("broadcast.idleState","modal"),$.get(EE.BASE+"&C=login&M=logout"));0==this.idleCount&&!1===this.pingReceived&&$(window).trigger("broadcast.idleState","active");this.pingReceived=!1}},c={_default:function(){b.idleCount+=1},active:function(){b.idleCount=0;b.hasFocus=!1},focus:function(){b.idleCount=0;b.hasFocus=!0},blur:function(){b.idleCount=1;b.hasFocus=!1},interact:function(){b.hasFocus&&
(b.idleCount=0)},modal:function(){b.modalActive||(a.dialog("open"),a.on("dialogbeforeclose",$.proxy(this,"logout")),b.modalActive=!0);b.idleCount+=1},login:function(){EE.cp.xid.refresh(function(){a.off("dialogbeforeclose");a.dialog("close");b.modalActive=!1;b.idleCount=0})},logout:function(){window.location=EE.BASE+"&C=login&M=logout"}};({eventsRecorded:[],init:function(){this._bindEvents();this.tick()},tick:function(){this.eventsRecorded.length||(this.eventsRecorded=["_default"]);_.each(this.eventsRecorded,
function(a){c[a]()});b.resolve();this.eventsRecorded=[];setTimeout($.proxy(this,"tick"),15E3)},_bindEvents:function(){var a=$.proxy(this,"_track");$(window).on("broadcast.idleState",function(e,f){switch(f){case "active":a(f);b.pingReceived=!0;break;case "modal":case "login":case "logout":c[f]()}});$(window).bind("blur",_.partial(a,"blur"));$(window).bind("focus",_.partial(a,"focus"));$(document).on("DOMMouseScroll keydown mousedown mousemove mousewheel touchmove touchstart".split(" ").join(".idleState "),
_.throttle(_.partial(a,"interact"),2E3));$(".logOutButton").click(function(){$(window).trigger("broadcast.idleState","modal")})},_track:function(a){this.eventsRecorded.push(a)}}).init();return c}();
EE.cp.xid=function(){function a(a){$('input[name="XID"]').val(a);EE.XID=a}function b(b){$.get(EE.BASE+"&C=login&M=refresh_xid",function(c){"refresh"==c.message&&(e=new Date,a(c.xid),b&&b(c))})}var c=!1,d=!1,e=new Date,f=function(){d=!0;localStorage.removeItem("EE_XID",EE.XID)},k=function(a){c||d||localStorage.setItem("EE_XID",EE.XID)},g=function(a){if(c=a.persisted)(a=localStorage.getItem("EE_XID"))?EE.cp.xid.set(a):EE.cp.xid.refresh()};"onpagehide"in window&&(window.addEventListener("submit",f,!1),
window.addEventListener("pagehide",k,!1),window.addEventListener("pageshow",g,!1));setTimeout(function(){18E5<new Date-e&&b()},6E4);return{set:function(b){a(b)},refresh:function(a){b(a)}}}();EE.cp.deprecation_meaning=function(){$(".deprecation_meaning").click(function(a){a.preventDefault();$('<div class="alert">'+EE.developer_log.deprecation_meaning+" </div>").dialog({height:300,modal:!0,title:EE.developer_log.dev_log_help,width:460})})};
EE.cp.zebra_tables=function(a){a=a||$("table");a.jquery||(a=$(a));$(a).find("tr").removeClass("even odd").filter(":even").addClass("even").end().filter(":odd").addClass("odd")};EE.grid_cache=[];var Grid={bind:function(){EE.grid_cache.push(arguments)}};
(function(){var a=$("head script");if(2<a.length){var b=console.groupCollapsed?"groupCollapsed":"log";console[b]("Found third party scripts in <head> tag.");console.log("Please use cp->add_to_foot() to add scripts. jQuery and the EE global will be moved down in a future release.");a.slice(2).each(function(){console.log(this.src&&this.src||"[Inline Script]")});"groupCollapsed"==b&&console.groupEnd()}})();
