/**
 * Grid Namespace
 */

(function(c){var e=window.Grid={_eventHandlers:[],bind:function(a,b,c){void 0==this._eventHandlers[b]&&(this._eventHandlers[b]=[]);this._eventHandlers[b][a]=c}};e.Publish=function(a,b){this.root=c(a);this.blankRow=this.root.find("tr.blank_row");this.emptyField=this.root.find("tr.empty_field");this.rowContainer=this.root.find(".grid_row_container");this.settings=void 0!==b?b:EE.grid_field_settings[a.id];this.init();this.eventHandlers=[]};e.Publish.prototype={init:function(){this._bindSortable();this._bindAddButton();
this._bindDeleteButton();this._toggleRowManipulationButtons();this._fieldDisplay();this.blankRow.find(":input").attr("disabled","disabled")},_bindSortable:function(){var a=this;this.rowContainer.sortable({axis:"y",containment:"parent",handle:"td.grid_handle",cancel:"td.grid_sort_cancel",items:"tr.grid_row",sort:EE.sortable_sort_helper,helper:function(a,d){var e=d.children(),f=d.clone();f.children().each(function(a){c(this).width(e.eq(a).width())});return f},start:function(b,c){a._fireEvent("beforeSort",
c.item)},stop:function(b,c){a._fireEvent("afterSort",c.item)}})},_addMinimumRows:function(){var a=this._getRows().size(),b=this.settings.grid_min_rows-a;for(0==a&&0==b&&this.emptyField.show();0<b;)this._addRow(),b--},_toggleRowManipulationButtons:function(){var a=this._getRows().size();""!==this.settings.grid_max_rows&&this.root.find(".grid_button_add").toggle(a<this.settings.grid_max_rows);""!==this.settings.grid_min_rows&&this.root.find(".grid_button_delete").toggle(a>this.settings.grid_min_rows);
this.rowContainer.find("td.grid_handle").toggleClass("grid_sort_cancel",1==a)},_getRows:function(){return this.rowContainer.find("tr.grid_row").not(this.blankRow.add(this.emptyField))},_bindAddButton:function(){var a=this;this.root.find(".grid_button_add, .grid_link_add").on("click",function(b){b.preventDefault();a._addRow()})},_addRow:function(){el=this.blankRow.clone();el.removeClass("blank_row");el.html(el.html().replace(RegExp("new_row_[0-9]{1,}","g"),"new_row_"+this.rowContainer.find("tr").size()));
el.find(":input").removeAttr("disabled");this.rowContainer.append(el);this.emptyField.hide();this._toggleRowManipulationButtons();this._fireEvent("display",el)},_bindDeleteButton:function(){var a=this;this.root.on("click",".grid_button_delete",function(b){b.preventDefault();row=c(this).parents("tr.grid_row");a._fireEvent("remove",row);row.remove();a._toggleRowManipulationButtons();0==a._getRows().size()&&a.emptyField.show()})},_fieldDisplay:function(){var a=this;setTimeout(function(){a._getRows().each(function(){a._fireEvent("display",
c(this))});a._addMinimumRows()},500)},_fireEvent:function(a,b){if(void 0!==e._eventHandlers[a])for(var d in e._eventHandlers[a])b.find('td[data-fieldtype="'+d+'"]').each(function(){e._eventHandlers[a][d](c(this))})}};e.Settings=function(a){this.root=c("#grid_settings");this.settingsScroller=this.root.find("#grid_col_settings_container");this.settingsContainer=this.root.find("#grid_col_settings_container_inner");this.colTemplateContainer=c("#grid_col_settings_elements");this.blankColumn=this.colTemplateContainer.find(".grid_col_settings");
this.settings=a;this.init()};e.Settings.prototype={init:function(){this._bindResize();this._bindSortable();this._bindAddButton();this._bindCopyButton();this._bindDeleteButton();this._bindDeleteButton();this._toggleDeleteButtons();this._bindColTypeChange();this._bindSubmit();this._highlightErrors();this._bindAutoColName(this.root.find('div.grid_col_settings[data-field-name^="new_"]'));this._settingsDisplay();this.colTemplateContainer.find(":input").attr("disabled","disabled")},_bindResize:function(){var a=
this;c(document).ready(function(){a._resizeSettingsContainer();c(window).resize(function(){a._resizeSettingsContainer()});c("#field_type").change(function(){"grid"==c(this).val()&&a._resizeSettingsContainer()});a._resizeColContainer()})},_resizeSettingsContainer:function(){this.settingsScroller.width(500);this.settingsScroller.width(this.root.width()-this.root.find("#grid_col_settings_labels").width())},_resizeColContainer:function(a){this.settingsContainer.animate({width:this._getColumnsWidth()},
!0==a?400:0)},_getColumnsWidth:function(){var a=this.root.find(".grid_col_settings");return a.size()*a.width()+75},_bindSortable:function(){this.settingsContainer.sortable({axis:"x",containment:"parent",handle:"div.grid_data_type",items:".grid_col_settings",sort:EE.sortable_sort_helper})},_bindAddButton:function(){var a=this;this.root.find(".grid_button_add").on("click",function(b){b.preventDefault();a._insertColumn(a._buildNewColumn())})},_bindCopyButton:function(){var a=this;this.root.on("click",
"a.grid_col_copy",function(b){b.preventDefault();b=c(this).parents(".grid_col_settings");a._insertColumn(a._buildNewColumn(b),b)})},_bindDeleteButton:function(){var a=this;this.root.on("click",".grid_button_delete",function(b){b.preventDefault();var d=c(this).parents(".grid_col_settings");d.index()==c("#grid_settings .grid_col_settings:last").index()?(d.remove(),a._resizeColContainer(!0),a._toggleDeleteButtons()):d.animate({opacity:0},200,function(){d.html("");d.animate({width:0},200,function(){d.remove();
a._resizeColContainer(!0);a._toggleDeleteButtons()})})})},_toggleDeleteButtons:function(){var a=this.root.find(".grid_col_settings").size();this.root.find(".grid_button_delete").toggle(1<a)},_insertColumn:function(a,b){var d=c("#grid_settings .grid_col_settings:last");void 0==b&&(b=d);b.index()!=d.index()&&a.css({opacity:0});a.insertAfter(b);this._resizeColContainer();this._toggleDeleteButtons();b.index()==d.index()&&this.settingsScroller.animate({scrollLeft:this._getColumnsWidth()},700);a.animate({opacity:1},
400);this._bindAutoColName(a);this._fireEvent("displaySettings",c(".grid_col_settings_custom > div",a))},_bindAutoColName:function(a){a.each(function(a,d){c("input.grid_col_field_label",d).bind("keyup keydown",function(){c(this).ee_url_title(c(d).find("input.grid_col_field_name"),!0)})})},_buildNewColumn:function(a){a=void 0==a?this.blankColumn.clone():this._cloneWithFormValues(a);a.find('input[name$="\\[name\\]"]').attr("value","");var b="new_"+c(".grid_col_settings",this.root).size();a.html(a.html().replace(RegExp("(new_|col_id_)[0-9]{1,}",
"g"),b));a.attr("data-field-name",b);a.find(":input").removeAttr("disabled").removeClass("grid_settings_error");return a},_bindColTypeChange:function(){var a=this;this.root.on("change",".grid_data_type .grid_col_select",function(b){b=a.colTemplateContainer.find(".grid_col_settings_custom_field_"+c(this).val()+":last").clone();b.find(":input").removeAttr("disabled");var d=c(this).parents(".grid_col_settings").find(".grid_col_settings_custom");b.html(b.html().replace(RegExp("(new_|col_id_)[0-9]{1,}",
"g"),d.data("fieldName")));d.html(b);a._fireEvent("displaySettings",b)})},_bindSubmit:function(){var a=this;this.root.parents("form").submit(function(){c(".grid_col_settings_section input[type=text]").removeClass("grid_settings_error");grid_html=a._cloneWithFormValues(a.root.parent("#grid_settings_container"));c("<input/>",{type:"hidden",name:"grid_html",value:'<div id="grid_settings_container">'+grid_html.html()+"</div>"}).appendTo(a.root)})},_cloneWithFormValues:function(a){var b=a.clone();a.find(":input:enabled").each(function(){var a=
b.find(":input[name='"+c(this).attr("name")+"']:enabled");c(this).is("select")?a.find("option").removeAttr("selected").filter('[value="'+c(this).val()+'"]').attr("selected","selected"):"checkbox"==c(this).attr("type")?a.attr("checked",c(this).attr("checked")):"radio"==c(this).attr("type")?a.removeAttr("selected").filter("[value='"+c(this).val()+"']").attr("checked",c(this).attr("checked")):c(this).is("textarea")?a.html(c(this).val()):a.attr("value",c(this).val())});return b},_settingsDisplay:function(){var a=
this;this.root.find(".grid_col_settings").each(function(){a._fireEvent("displaySettings",c(".grid_col_settings_custom > div",this))})},_fireEvent:function(a,b){var d=b.data("fieldtype");if(void 0!==e._eventHandlers[a]&&void 0!=e._eventHandlers[a][d])e._eventHandlers[a][d](c(b))},_highlightErrors:function(){void 0!=this.settings.error_fields&&c.each(this.settings.error_fields,function(a,b){c('input[name="'+b+'"]').addClass("grid_settings_error")})}};EE.grid=function(a,b){return new e.Publish(a,b)};
EE.grid_settings=function(a){return new e.Settings(a)};"undefined"!==typeof _&&"undefined"!==EE.grid_cache&&_.each(EE.grid_cache,function(a){e.bind.apply(e,a)})})(jQuery);
