/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2010, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

function _access_edit_ajax(a,f,h,i){var k="";switch(i){case "no_auth_bounce":k=jQuery.param({template_id:f,no_auth_bounce:a.val()});break;case "enable_http_auth":k=jQuery.param({template_id:f,enable_http_auth:a.val()});break;case "access":i=!$(a).closest(".accessTable").length?$(".no_auth_bounce").val():$(a).closest(".accessTable").find(".no_auth_bounce").val();k=jQuery.param({template_id:f,member_group_id:h,new_status:a.val(),no_auth_bounce:i});break}$.ajax({type:"POST",url:EE.access_edit_url,data:"is_ajax=TRUE&XID="+
EE.XID+"&"+k,success:function(l){l!==""&&$.ee_notice(l,{duration:3E3,type:"success"})},error:function(l){l.responseText!==""&&$.ee_notice(l.responseText,{duration:3E3,type:"error"})}})}
function access_edit_ajax(a){var f,h;if(a.attr("name").substr(0,14)==="no_auth_bounce"){h=a.attr("name").substr(15)?a.attr("name").substr(15):$("input:hidden[name=template_id]").val();_access_edit_ajax(a,h,"","no_auth_bounce")}else if(a.attr("name").substr(0,16)==="enable_http_auth"){h=a.attr("name").substr(17)?a.attr("name").substr(17):$("input:hidden[name=template_id]").val();_access_edit_ajax(a,h,"","enable_http_auth")}else{f=a.attr("name").replace("access_","").split("_");h=f.length<2?$("input:hidden[name=template_id]").val():
f[1];_access_edit_ajax(a,h,f[0],"access")}}
function template_edit_ajax(){var a=$(this).closest(".accessRowHeader"),f,h,i,k,l,g,j,m,c,d;if(a.length<1)a=$(this).closest(".templateEditorTable");f=a.data("ajax_ids");if(!f){if($(this).hasClass("ignore_radio"))return false;return access_edit_ajax($(this))}h=f.id;f=f.group_id;i=a.find(".template_name").val();k=a.find(".template_type").val();l=a.find("select[name^=cache]").val();g=a.find(".refresh").val();j=a.find("select[name^=allow_php]").val();m=a.find("select[name^=php_parse_location]").val();c=
a.find(".hits").val();d=a.find(".template_size").val();a=jQuery.param({template_id:h,group_id:f,template_name:i,template_type:k,cache:l,refresh:g,hits:c,allow_php:j,php_parse_location:m,template_size:d});$.ajax({type:"POST",url:EE.template_edit_url,data:"is_ajax=TRUE&XID="+EE.XID+"&"+a,success:function(b){var e=$("#templateId_"+h);e.text(i);if(e.closest(".templateName").length){e=e.closest(".templateName").next().find("a");if(e.length){e=e.get(0);e.href=e.href.replace(/\/[^\/]*$/,"/"+i)}}else if($("#templateViewLink a.submit").length){e=
$("#templateViewLink a.submit");if(e.length){e=e.get(0);e.href=e.href.replace(/\/[^\/]*$/,"/"+i)}}$("#template_data").attr("rows",d);$("#hitsId_"+h).text(c);b!==""&&$.ee_notice(b,{duration:3E3,type:"success"})},error:function(b){b.responseText!==""&&$.ee_notice(b.responseText,{duration:3E3,type:"error"})}})}function hideSubRows(a,f){if(f)$(a).data(f)&&$(a).data(f).hide();else{hideSubRows(a,"prefsRow");hideSubRows(a,"accessRow")}}
function hideRow(a,f){a.hasClass("highlightRow")&&a.removeClass("highlightRow");if(a.data(f)){var h=a.data(f).is(":visible");hideSubRows(a);if(!h){a.addClass("highlightRow");a.data(f).show()}return true}hideSubRows(a);return false}function set_radio_buttons(a,f){a.find("input:radio").each(function(){var h,i;h=$(this).attr("id").split("_");i=h.slice(0,-1).join("_");h=h.slice(-1)[0];$(this).attr({id:i+"_"+f+"_"+h,name:i+"_"+f})})}
function bind_prefs_events(){$(".templateTable .accessTable").find("input:text").unbind("blur.manager_updated").bind("blur.manager_updated",template_edit_ajax);$(".templateTable .accessTable").find("input:radio").unbind("click.manager_updated").bind("click.manager_updated",template_edit_ajax);$(".templateTable .accessTable").find("select").unbind("change.manager_updated").bind("change.manager_updated",template_edit_ajax)}
(function(a){var f,h;a(document).ready(function(){function i(c,d){var b="input:radio[id$=_";if(d)b="input:radio[id$=_"+d+"_";c.find(".ignore_radio").click(function(){this.value==="y"&&c.find(b+"y]").filter(":not(.ignore_radio)").trigger("click");this.value==="n"&&c.find(b+"n]").filter(":not(.ignore_radio)").trigger("click");a(this).attr("checked","");return false})}function k(c,d,b){var e=a('<tr class="accessRowHeader"><td colspan="6">'+h+"</td></tr>");e.find(".no_auth_bounce").val(b.no_auth_bounce);
e.find(".no_auth_bounce").attr({id:"no_auth_bounce_"+c,name:"no_auth_bounce_"+c});e.find(".enable_http_auth").val(b.enable_http_auth);e.find(".enable_http_auth").attr({id:"enable_http_auth_"+c,name:"enable_http_auth_"+c});set_radio_buttons(e,c);a.each(b.access,function(n,q){var o=e.find("#access_"+n+"_"+c+"_y"),p=e.find("#access_"+n+"_"+c+"_n");if(q.access===true){o.attr("checked","checked");p.attr("checked","")}else{p.attr("checked","checked");o.attr("checked","")}});i(e,c);a(d).addClass("highlightRow");
a(d).after(e);e.find(".accessTable").tablesorter({widgets:["zebra"]});d.data("accessRow",e)}function l(c,d){var b=a('<tr class="accessRowHeader"><td colspan="6">'+f+"</td></tr>");b.find("select").each(function(){var e=a(this);switch(this.name){case "template_type":e.val(d.type);break;case "cache":e.val(d.cache);break;case "allow_php":e.val(d.allow_php);break;case "php_parse_location":e.val(d.php_parsing);break}e.attr("name",this.name+"_"+d.id)});b.find(".template_name").val(d.name);d.name==="index"&&
b.find(".template_name").attr({readonly:"readonly"});b.find(".refresh").val(d.refresh);b.find(".hits").val(d.hits);b.data("ajax_ids",{id:d.id,group_id:d.group_id});c.data("prefsRow",b);a(c).addClass("highlightRow");a(c).after(b)}var g,j,m;f=a("#prefRowTemplate").html();h=a("#accessRowTemplate").html();if(!f||!h){g=a("#templateAccess, #templatePreferences");j=a("input:hidden[name=template_id]").val();m=a("input:hidden[name=group_id]").val();a("#templatePreferences").data("ajax_ids",{id:j,group_id:m});
i(a("#templateAccess"));g.find("input:text").unbind("blur.manager_updated").bind("blur.manager_updated",template_edit_ajax);g.find("input:radio").unbind("click.manager_updated").bind("click.manager_updated",template_edit_ajax);g.find("select").unbind("change.manager_updated").bind("change.manager_updated",template_edit_ajax)}else{a("#prefRowTemplate, #accessRowTemplate").remove();EE.manager={showPrefsRow:function(c,d){var b=a(d).parent().parent();if(!hideRow(b,"prefsRow")){l(b,c);bind_prefs_events()}return false},
showAccessRow:function(c,d,b){b=a(b).parent().parent();if(!hideRow(b,"accessRow")){k(c,b,d);bind_prefs_events();b.trigger("applyWidgets")}return false}}}});a(".last_edit").css("opacity",0).show();a("#template_details").hover(function(){a(".last_edit").animate({opacity:1},50)},function(){a(".last_edit").animate({opacity:0},50)});a(document).ready(function(){if(EE.manager&&EE.manager.warnings){a(".warning_details").hide();a(".toggle_warning_details").click(function(){a(".warning_details").hide();a("#wd_"+
this.id.substr(3)).show();return false});var i=a("#template_data"),k,l;l=function(g,j,m){var c,d="";if(m&&m.length>1)d='<select name="fr_options" id="fr_options"></select>';c='<div style="padding: 5px;"><label>Find:</label> <input name="fr_find" id="fr_find" type="text" value="" /> <label>Replace:</label> <input type="text" name="fr_replace" id="fr_replace" value=""/> '+d+"</div>";c+='<div style="padding: 5px;"><button class="submit" id="fr_find_btn">Find Next</button> <button class="submit" id="fr_replace_btn">Replace</button> <button class="submit" id="fr_replace_all_btn">Replace All</button> <label><input name="fr_replace_closing_tags" id="fr_replace_closing_tags" type="checkbox" /> Include Closing Tags</label></div>';
a.ee_notice(c,{type:"custom",open:true,close_on_click:false});a("#fr_find").val(g);a("#fr_replace").val(j);a("#fr_replace_closing_tags").attr("checked","");if(d!==""){a("#fr_options").append(a(m));a("#fr_options").click(function(){a("#fr_find").val(a(this).val());a("#fr_find_btn").click()})}g&&a("#fr_find_btn").click()};a("#fr_find_btn").live("click",function(){var g=a("#fr_find").val();k=i.selectNext(g).scrollToCursor()});a("#fr_replace_btn").live("click",function(){var g=a("#fr_find").val(),j=a("#fr_replace").val();
k.getSelectedText()===g&&k.replaceWith(j)});a("#fr_replace_all_btn").live("click",function(){var g=a("#fr_find").val(),j=a("#fr_replace").val();if(jQuery.trim(g)!==""){i.val(i.val().split(g).join(j));if(a("#fr_replace_closing_tags").attr("checked")){if(g[0]==="{"&&g.substr(0,2)!=="{/")g="{/"+g.substr(1);if(j[0]==="{"&&j.substr(0,2)!=="{/")j="{/"+j.substr(1);jQuery.trim(g)!==""&&i.val(i.val().split(g).join(j))}}});a(".find_and_replace").click(function(){var g=this.id.substr(8),j="{exp:"+g,m="{exp:"+
EE.manager.warnings[g].suggestion,c=EE.manager.warnings[g].full_tags,d=Array(new Option(j,j)),b;if(c&&c.length>1)for(b=0;b<c.length;b++){g="{"+c[b]+"}";d.push(new Option(g,g))}if(m==="{exp:")m="";l(j,m,d);return false})}});a("#template_keywords_reset").click(function(){a("#template_keywords").val("");a(".search form").submit()})})(jQuery);
