/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

EE.publish=EE.publish||{};
EE.publish.category_editor=function(){var a=[],b=$("<div />"),e=$('<div id="cat_modal_container" />').appendTo(b),f={},j={},i=EE.BASE+"&C=admin_content&M=category_editor&group_id=",k,h,d;b.dialog({autoOpen:!1,height:450,width:600,modal:!0});$(".edit_categories_link").each(function(){var b=this.href.substr(this.href.lastIndexOf("=")+1);$(this).data("gid",b);a.push(b)});for(d=0;d<a.length;d++)f[a[d]]=$("#cat_group_container_"+[a[d]]),f[a[d]].data("gid",a[d]),j[a[d]]=$("#cat_group_container_"+[a[d]]).find(".cat_action_buttons").remove();
k=function(a){f[a].text("loading...").load(i+a+"&timestamp="+ +new Date+" .pageContents table",function(){h.call(f[a],f[a].html(),!1)})};h=function(a,f){var g=$(this),c=g.data("gid"),a=$.trim(a);g.hasClass("edit_categories_link")&&(g=$("#cat_group_container_"+c));if(a[0]!=="<"&&f)return k(c);g.closest(".cat_group_container").find("#refresh_categories").show();var m=$(a),l;if(m.find("form").length){e.html(m);m=e.find("input[type=submit]");l=e.find("form");$category_name=l.find("#cat_name");$category_url_title=
l.find("#cat_url_title");$category_name.keyup(function(){$category_name.ee_url_title($category_url_title)});var d=function(c){var a=c||$(this),c=a.serialize(),a=a.attr("action");$.ajax({url:a,type:"POST",data:c,dataType:"html",beforeSend:function(){g.html(EE.lang.loading)},success:function(c){c=$.trim(c);b.dialog("close");c[0]=="<"&&(c=$(c).find(".pageContents table"),c.find("form").length==0&&g.html(c));h.call(g,c,!0)},error:function(c){b.dialog("close");h.call(g,c.error,!0)}});return!1};l.submit(d);
var i={};i[m.remove().attr("value")]=function(){d(l)};b.dialog("open");b.dialog("option","buttons",i);b.one("dialogclose",function(){k(c)})}else j[c].clone().appendTo(g).show();return!1};d=function(){$(this).hide();var a=$(this).data("gid"),b=".pageContents";if($(this).hasClass("edit_cat_order_trigger")||$(this).hasClass("edit_categories_link"))b+=" table";a||(a=$(this).closest(".cat_group_container").data("gid"));f[a].text(EE.lang.loading);$.ajax({url:this.href+"&timestamp="+ +new Date+b,success:function(g){var c=
"",g=$.trim(g);g[0]=="<"&&(g=$(g).find(b),c=$("<div />").append(g).html(),g.find("form").length==0&&f[a].html(c));h.call(f[a],c,!0)},error:function(b){b=eval("("+b.responseText+")");f[a].html(b.error);h.call(f[a],b.error,!0)}});return!1};$(".edit_categories_link").click(d);$(".cat_group_container a:not(.cats_done)").live("click",d);$(".cats_done").live("click",function(){var a=$(this).closest(".cat_group_container"),b=a.data("gid");$(".edit_categories_link").each(function(){$(this).data("gid")==b&&
$(this).show()});a.text("loading...").load(EE.BASE+"&C=content_publish&M=category_actions&group_id="+a.data("gid")+"&timestamp="+ +new Date,function(b){a.html($(b).html())});return!1})};var selected_tab="";function get_selected_tab(){return selected_tab}
function tab_focus(a){$(".menu_"+a).parent().is(":visible")||$("a.delete_tab[href=#"+a+"]").trigger("click");$(".tab_menu li").removeClass("current");$(".menu_"+a).parent().addClass("current");$(".main_tab").hide();$("#"+a).show();$(".main_tab").css("z-index","");$("#"+a).css("z-index","5");selected_tab=a;$(".main_tab").sortable("refreshPositions")}EE.tab_focus=tab_focus;
function setup_tabs(){var a="";$(".main_tab").sortable({connectWith:".main_tab",appendTo:"#holder",helper:"clone",forceHelperSize:!0,handle:".handle",start:function(a,e){e.item.css("width",$(this).parent().css("width"))},stop:function(a,e){e.item.css("width","100%")}});$(".tab_menu li a").droppable({accept:".field_selector, .publish_field",tolerance:"pointer",forceHelperSize:!0,deactivate:function(){clearTimeout(a);$(".tab_menu li").removeClass("highlight_tab")},drop:function(a,e){field_id=e.draggable.attr("id").substring(11);
tab_id=$(this).attr("title").substring(5);setTimeout(function(){$("#hold_field_"+field_id).prependTo("#"+tab_id);$("#hold_field_"+field_id).hide().slideDown()},0);tab_focus(tab_id);return!1},over:function(){tab_id=$(this).attr("title").substring(5);$(this).parent().addClass("highlight_tab");a=setTimeout(function(){tab_focus(tab_id);return!1},500)},out:function(){a!=""&&clearTimeout(a);$(this).parent().removeClass("highlight_tab")}});$("#holder .main_tab").droppable({accept:".field_selector",tolerance:"pointer",
drop:function(a,e){field_id=e.draggable.attr("id")=="hide_title"||e.draggable.attr("id")=="hide_url_title"?e.draggable.attr("id").substring(5):e.draggable.attr("id").substring(11);tab_id=$(this).attr("id");$("#hold_field_"+field_id).prependTo("#"+tab_id);$("#hold_field_"+field_id).hide().slideDown()}});$(".tab_menu li.content_tab a, #publish_tab_list a.menu_focus").unbind(".publish_tabs").bind("mousedown.publish_tabs",function(a){tab_id=$(this).attr("title").substring(5);tab_focus(tab_id);a.preventDefault()}).bind("click.publish_tabs",
function(){return!1})}setup_tabs();Number.prototype.is_integer=String.prototype.is_integer=function(){var a=parseInt(this,10);if(isNaN(a))return!1;return this==a&&this.toString()==a.toString()};EE.publish.get_percentage_width=function(a){if(a.attr("data-width")&&a.attr("data-width").slice(0,-1).is_integer())return parseInt(a.attr("data-width"),10);return Math.round(a.width()/a.parent().width()*10)*10};
EE.publish.save_layout=function(){var a=0,b={},e={},f=0,j=!1,i=$("#tab_menu_tabs li.current").attr("id");$(".main_tab").show();$("#tab_menu_tabs a:not(.add_tab_link)").each(function(){if($(this).parent("li").attr("id")&&$(this).parent("li").attr("id").substring(0,5)=="menu_"){var d=$(this).parent("li").attr("id").substring(5),h=$(this).parent("li").attr("id").substring(5),g=$(this).parent("li").attr("title");f=0;visible=!0;$(this).parent("li").is(":visible")?(lay_name=d,b[lay_name]={},b[lay_name]._tab_label=
g):(j=!0,visible=!1);$("#"+h).find(".publish_field").each(function(){var c=$(this),a=this.id.replace(/hold_field_/,""),c=EE.publish.get_percentage_width(c),d=$("#sub_hold_field_"+a+" .markItUp ul li:eq(2)");c>100&&(c=100);d=d.html()!=="undefined"&&d.css("display")!=="none"?!0:!1;c={visible:$(this).css("display")==="none"||visible===!1?!1:!0,collapse:$("#sub_hold_field_"+a).css("display")==="none"?!0:!1,htmlbuttons:d,width:c+"%"};visible===!0?(c.index=f,b[lay_name][a]=c,f+=1):e[a]=c});visible===!0&&
a++}});if(j==!0){var k,h,d=0;for(darn in b){h=darn;for(k in b[h])b[h][k].index>d&&(d=b[h][k].index);break}$.each(e,function(){this.index=++d});jQuery.extend(b[h],e)}EE.tab_focus(i.replace(/menu_/,""));a===0?$.ee_notice(EE.publish.lang.tab_count_zero,{type:"error"}):$("#layout_groups_holder input:checked").length===0?$.ee_notice(EE.publish.lang.no_member_groups,{type:"error"}):$.ajax({type:"POST",dataType:"json",url:EE.BASE+"&C=content_publish&M=save_layout",data:"XID="+EE.XID+"&json_tab_layout="+
JSON.stringify(b)+"&"+$("#layout_groups_holder input").serialize()+"&channel_id="+EE.publish.channel_id,success:function(a){a.messageType==="success"?$.ee_notice(a.message,{type:"success"}):a.messageType==="failure"&&$.ee_notice(a.message,{type:"error"})}})};
EE.publish.remove_layout=function(){if($("#layout_groups_holder input:checked").length===0)return $.ee_notice(EE.publish.lang.no_member_groups,{type:"error"});$.ajax({type:"POST",url:EE.BASE+"&C=content_publish&M=save_layout",data:"XID="+EE.XID+"&json_tab_layout={}&"+$("#layout_groups_holder input").serialize()+"&channel_id="+EE.publish.channel_id+"&field_group="+EE.publish.field_group,success:function(){$.ee_notice(EE.publish.lang.layout_removed+' <a href="javascript:location=location">'+EE.publish.lang.refresh_layout+
"</a>",{duration:0,type:"success"});return!0}});return!1};EE.publish.change_preview_link=function(){$select=$("#layout_preview select");$link=$("#layout_group_preview");base=$link.attr("href").split("layout_preview")[0];$link.attr("href",base+"layout_preview="+$select.val());$.ajax({url:EE.BASE+"&C=content_publish&M=preview_layout",type:"POST",dataType:"json",data:{XID:EE.XID,member_group:$select.find("option:selected").text()}})};
EE.date_obj_time=function(){var a=new Date,b=a.getHours(),a=a.getMinutes(),e="";a<10&&(a="0"+a);EE.date.format=="us"&&(e=b<12?" AM":" PM",b!=0&&(b=(b+11)%12+1));return" '"+b+":"+a+e+"'"}();file_manager_context="";
function disable_fields(a){var b=$(".main_tab input, .main_tab textarea, .main_tab select, #submit_button"),e=$("#submit_button"),f=$("#holder").find("a");a?(disabled_fields=b.filter(":disabled"),b.attr("disabled",!0),e.addClass("disabled_field"),f.addClass("admin_mode"),$("#holder div.markItUp, #holder p.spellcheck").each(function(){$(this).before('<div class="cover" style="position:absolute;width:100%;height:50px;z-index:9999;"></div>').css({})})):(b.removeAttr("disabled"),e.removeClass("disabled_field"),
f.removeClass("admin_mode"),$(".cover").remove(),disabled_fields.attr("disabled",!0))}
$(document).ready(function(){function a(c){if(c)return c=c.toString(),c=c.replace(/\(\!\(([\s\S]*?)\)\!\)/g,function(c,a){var b=a.split("|!|");return altKey===!0?b[1]!==void 0?b[1]:b[0]:b[1]===void 0?"":b[0]}),c=c.replace(/\[\!\[([\s\S]*?)\]\!\]/g,function(c,a){var b=a.split(":!:");if(n===!0)return!1;value=prompt(b[0],b[1]?b[1]:"");value===null&&(n=!0);return value});return""}function b(c,a){var b=$("input[name="+a+"]").closest(".publish_field");c.is_image==!1?b.find(".file_set").show().find(".filename").html('<img src="'+
EE.PATH_CP_GBL_IMG+'default.png" alt="'+EE.PATH_CP_GBL_IMG+'default.png" /><br />'+c.file_name):b.find(".file_set").show().find(".filename").html('<img src="'+c.thumb+'" /><br />'+c.file_name);$("input[name="+a+"_hidden]").val(c.file_name);$("select[name="+a+"_directory]").val(c.directory)}var e,f;$("#layout_group_submit").click(function(){EE.publish.save_layout();return!1});$("#layout_group_remove").click(function(){EE.publish.remove_layout();return!1});$("#layout_preview select").change(function(){EE.publish.change_preview_link()});
$("a.reveal_formatting_buttons").click(function(){$(this).parent().parent().children(".close_container").slideDown();$(this).hide();return!1});$("#write_mode_header .reveal_formatting_buttons").hide();$("a.glossary_link").click(function(){$(this).parent().siblings(".glossary_content").slideToggle("fast");$(this).parent().siblings(".smileyContent .spellcheck_content").hide();return!1});EE.publish.smileys===!0&&($("a.smiley_link").toggle(function(){$(this).parent().siblings(".smileyContent").slideDown("fast",
function(){$(this).css("display","")})},function(){$(this).parent().siblings(".smileyContent").slideUp("fast")}),$(this).parent().siblings(".glossary_content, .spellcheck_content").hide(),$(".glossary_content a").click(function(){var a=$(this).closest(".publish_field"),b=a.attr("id").replace("hold_field_","field_id_");a.find("#"+b).insertAtCursor($(this).attr("title"));return!1}));if(EE.publish.autosave){var j=!1;f=function(){j||(j=!0,setTimeout(e,1E3*EE.publish.autosave.interval))};e=function(){var a;
$("#tools:visible").length===1?f():(a=$("#publishForm").serialize(),$.ajax({type:"POST",dataType:"json",url:EE.BASE+"&C=content_publish&M=autosave",data:a,success:function(a){a.error?console.log(a.error):a.success?(a.autosave_entry_id&&$("input[name=autosave_entry_id]").val(a.autosave_entry_id),$("#autosave_notice").text(a.success)):console.log("Autosave Failed");j=!1}}))};var i=$("textarea, input").not(":password,:checkbox,:radio,:submit,:button,:hidden"),k=$("select, :checkbox, :radio, :file");
i.bind("keypress change",f);k.bind("change",f)}if(EE.publish.pages){var i=$("#pages__pages_uri"),h=EE.publish.pages.pagesUri;i.val()||i.val(h);i.focus(function(){this.value===h&&$(this).val("")}).blur(function(){this.value===""&&$(this).val(h)})}$.ee_filebrowser();var d="";EE.publish.show_write_mode===!0&&$("#write_mode_textarea").markItUp(myWritemodeSettings);EE.publish.markitup.fields!==void 0&&$.each(EE.publish.markitup.fields,function(a){$("#"+a).markItUp(mySettings)});write_mode_height=$(window).height()-
117;$("#write_mode_writer").css("height",write_mode_height+"px");$("#write_mode_writer textarea").css("height",write_mode_height-67-17+"px");var o=$(".write_mode_trigger").overlay({mask:{color:"#262626",loadSpeed:200,opacity:0.85},onBeforeLoad:function(){var a=this.getTrigger()[0],b=$("#write_mode_textarea");d=a.id.match(/^id_\d+$/)?"field_"+a.id:a.id.replace(/id_/,"");b.val($("#"+d).val());b.focus()},onClose:function(){var a="#"+d.replace(/field_/,""),a=$(".write_mode_trigger").index(a);$("#"+d).val($("#write_mode_textarea").val());
o.eq(a).overlay().close()},top:"center",closeOnClick:!1}),n=!1;$.ee_filebrowser.add_trigger(".btn_img a, .file_manipulate",function(c){var b,d="",e="",f="",g="";textareaId=$(this).closest("#markItUpWrite_mode_textarea").length?"write_mode_textarea":$(this).closest(".publish_field").attr("id").replace("hold_field_","field_id_");textareaId!=void 0&&(b=$("#"+textareaId),b.focus());c.is_image?(e=EE.upload_directories[c.directory].properties,f=EE.upload_directories[c.directory].pre_format,g=EE.upload_directories[c.directory].post_format,
d=EE.filebrowser.image_tag.replace(/src="(.*)\[!\[Link:!:http:\/\/\]!\](.*)"/,'src="$1{filedir_'+c.directory+"}"+c.name+'$2"'),dimensions="",typeof c.file_hw_original!="undefined"&&c.file_hw_original!=""&&(dimensions=c.file_hw_original.split(" "),dimensions='height="'+dimensions[0]+'" width="'+dimensions[1]+'"'),d=d.replace(/\/?>$/,dimensions+" "+e+" />"),d=f+d+g):(e=EE.upload_directories[c.directory].file_properties,f=EE.upload_directories[c.directory].file_pre_format,f+='<a href="{filedir_'+c.directory+
"}"+c.name+'" '+e+" >",g="</a>",g+=EE.upload_directories[c.directory].file_post_format);b.is("textarea")?(b.is(".markItUpEditor")||(b.markItUp(myNobuttonSettings),b.closest(".markItUpContainer").find(".markItUpHeader").hide(),b.focus()),c.is_image?$.markItUp({replaceWith:d}):$.markItUp({key:"L",name:"Link",openWith:f,closeWith:g,placeHolder:c.name})):b.val(function(c,b){b+=f+d+g;return a(b)})});$("input[type=file]","#publishForm").each(function(){var a=$(this).closest(".publish_field"),d=a.find(".choose_file");
$.ee_filebrowser.add_trigger(d,$(this).attr("name"),b);a.find(".remove_file").click(function(){a.find("input[type=hidden]").val("");a.find(".file_set").hide();return!1})});$(".hide_field span").click(function(){var a=$(this).parent().parent().attr("id").substr(11),b=$("#hold_field_"+a),a=$("#sub_hold_field_"+a);a.css("display")=="block"?(a.slideUp(),b.find(".ui-resizable-handle").hide(),b.find(".field_collapse").attr("src",EE.THEME_URL+"images/field_collapse.png")):(a.slideDown(),b.find(".ui-resizable-handle").show(),
b.find(".field_collapse").attr("src",EE.THEME_URL+"images/field_expand.png"));return!1});$(".close_upload_bar").toggle(function(){$(this).parent().children(":not(.close_upload_bar)").hide();$(this).children("img").attr("src",EE.THEME_URL+"publish_plus.png")},function(){$(this).parent().children().show();$(this).children("img").attr("src",EE.THEME_URL+"publish_minus.gif")});$(".ping_toggle_all").toggle(function(){$("input.ping_toggle").each(function(){this.checked=!1})},function(){$("input.ping_toggle").each(function(){this.checked=
!0})});EE.user.can_edit_html_buttons&&($(".markItUp ul").append('<li class="btn_plus"><a title="'+EE.lang.add_new_html_button+'" href="'+EE.BASE+"&C=myaccount&M=html_buttons&id="+EE.user_id+'">+</a></li>'),$(".btn_plus a").click(function(){return confirm(EE.lang.confirm_exit,"")}));$(".markItUpHeader ul").prepend('<li class="close_formatting_buttons"><a href="#"><img width="10" height="10" src="'+EE.THEME_URL+'images/publish_minus.gif" alt="Close Formatting Buttons"/></a></li>');$(".close_formatting_buttons a").toggle(function(){$(this).parent().parent().children(":not(.close_formatting_buttons)").hide();
$(this).parent().parent().css("height","13px");$(this).children("img").attr("src",EE.THEME_URL+"images/publish_plus.png")},function(){$(this).parent().parent().children().show();$(this).parent().parent().css("height","auto");$(this).children("img").attr("src",EE.THEME_URL+"images/publish_minus.gif")});$(".tab_menu li:first").addClass("current");EE.publish.title_focus==!0&&$("#title").focus();EE.publish.which=="new"&&$("#title").bind("keyup blur",function(){$("#title").ee_url_title($("#url_title"))});
EE.publish.versioning_enabled=="n"?$("#revision_button").hide():$("#versioning_enabled").click(function(){$(this).attr("checked")?$("#revision_button").show():$("#revision_button").hide()});EE.publish.category_editor();if(EE.publish.hidden_fields){EE._hidden_fields=[];var g=$("input");$.each(EE.publish.hidden_fields,function(a){EE._hidden_fields.push(g.filter("[name="+a+"]")[0])});$(EE._hidden_fields).after('<p class="hidden_blurb">This module field only shows in certain circumstances. This is a placeholder to let you define it in your layout.</p>')}});
