title: "🚀 Feature request"
body:
  - type: textarea
    attributes:
      label: Suggest an idea for ExpressionEngine
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen. Add any considered drawbacks.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Teachability, Documentation, Adoption, Migration Strategy**
        If you can, explain how users will be able to use this and possibly write out a version the docs. Some of the best features are born from writing documentation first. 

        - [ ] I am capable and would like to work on implementation of this feature if it is considered.