<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'ExpressionEngine\\Dependency\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'ExpressionEngine\\Dependency\\PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src/PhpOption'),
    'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => array($vendorDir . '/league/mime-type-detection/src'),
    'ExpressionEngine\\Dependency\\League\\Flysystem\\Cached\\' => array($vendorDir . '/league/flysystem-cached-adapter/src'),
    'ExpressionEngine\\Dependency\\League\\Flysystem\\' => array($vendorDir . '/league/flysystem/src'),
    'ExpressionEngine\\Dependency\\Dotenv\\' => array($vendorDir . '/vlucas/phpdotenv/src'),
);
