<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit91ca97ee53bbfe809ac9afdb2ed93cde
{
    public static $files = array (
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 51,
            'ExpressionEngine\\Dependency\\Psr\\Cache\\' => 38,
            'ExpressionEngine\\Dependency\\PhpOption\\' => 38,
            'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => 53,
            'ExpressionEngine\\Dependency\\League\\Flysystem\\Cached\\' => 52,
            'ExpressionEngine\\Dependency\\League\\Flysystem\\' => 45,
            'ExpressionEngine\\Dependency\\Dotenv\\' => 35,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'ExpressionEngine\\Dependency\\Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'ExpressionEngine\\Dependency\\PhpOption\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption',
        ),
        'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/mime-type-detection/src',
        ),
        'ExpressionEngine\\Dependency\\League\\Flysystem\\Cached\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem-cached-adapter/src',
        ),
        'ExpressionEngine\\Dependency\\League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
        'ExpressionEngine\\Dependency\\Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit91ca97ee53bbfe809ac9afdb2ed93cde::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit91ca97ee53bbfe809ac9afdb2ed93cde::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit91ca97ee53bbfe809ac9afdb2ed93cde::$classMap;

        }, null, ClassLoader::class);
    }
}
