/*!
 * jQuery JavaScript Library v1.7.2
 * http://jquery.com/
 *
 * Copyright 2011, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2011, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
 * Date: Wed Mar 21 12:46:34 2012 -0700
 */

(function(s,j){function Ta(a,b,c){if(c===j&&1===a.nodeType)if(c="data-"+b.replace(Zb,"-$1").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:d.isNumeric(c)?+c:$b.test(c)?d.parseJSON(c):c}catch(e){}d.data(a,b,c)}else c=j;return c}function xa(a){for(var b in a)if(!("data"===b&&d.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;return!0}function Ua(a,b,c){var e=b+"defer",f=b+"queue",g=b+"mark",i=d._data(a,e);i&&(("queue"===c||!d._data(a,f))&&("mark"===
c||!d._data(a,g)))&&setTimeout(function(){!d._data(a,f)&&!d._data(a,g)&&(d.removeData(a,e,!0),i.fire())},0)}function E(){return!1}function ca(){return!0}function Va(a,b,c){b=b||0;if(d.isFunction(b))return d.grep(a,function(a,e){return!!b.call(a,e,a)===c});if(b.nodeType)return d.grep(a,function(a){return a===b===c});if("string"===typeof b){var e=d.grep(a,function(a){return 1===a.nodeType});if(ac.test(b))return d.filter(b,e,!c);b=d.filter(b,e)}return d.grep(a,function(a){return 0<=d.inArray(a,b)===
c})}function Wa(a){var b=Xa.split("|"),a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Ya(a,b){if(1===b.nodeType&&d.hasData(a)){var c,e,f;e=d._data(a);var g=d._data(b,e),i=e.events;if(i)for(c in delete g.handle,g.events={},i){e=0;for(f=i[c].length;e<f;e++)d.event.add(b,c,i[c][e])}g.data&&(g.data=d.extend({},g.data))}}function Za(a,b){var c;1===b.nodeType&&(b.clearAttributes&&b.clearAttributes(),b.mergeAttributes&&b.mergeAttributes(a),c=b.nodeName.toLowerCase(),
"object"===c?b.outerHTML=a.outerHTML:"input"===c&&("checkbox"===a.type||"radio"===a.type)?(a.checked&&(b.defaultChecked=b.checked=a.checked),b.value!==a.value&&(b.value=a.value)):"option"===c?b.selected=a.defaultSelected:"input"===c||"textarea"===c?b.defaultValue=a.defaultValue:"script"===c&&b.text!==a.text&&(b.text=a.text),b.removeAttribute(d.expando),b.removeAttribute("_submit_attached"),b.removeAttribute("_change_attached"))}function da(a){return"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName("*"):
"undefined"!==typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function $a(a){if("checkbox"===a.type||"radio"===a.type)a.defaultChecked=a.checked}function ab(a){var b=(a.nodeName||"").toLowerCase();"input"===b?$a(a):"script"!==b&&"undefined"!==typeof a.getElementsByTagName&&d.grep(a.getElementsByTagName("input"),$a)}function bb(a,b,c){var e="width"===b?a.offsetWidth:a.offsetHeight,f="width"===b?1:0;if(0<e){if("border"!==c)for(;4>f;f+=2)c||(e-=parseFloat(d.css(a,"padding"+J[f]))||0),e="margin"===
c?e+(parseFloat(d.css(a,c+J[f]))||0):e-(parseFloat(d.css(a,"border"+J[f]+"Width"))||0);return e+"px"}e=K(a,b);if(0>e||null==e)e=a.style[b];if(ya.test(e))return e;e=parseFloat(e)||0;if(c)for(;4>f;f+=2)e+=parseFloat(d.css(a,"padding"+J[f]))||0,"padding"!==c&&(e+=parseFloat(d.css(a,"border"+J[f]+"Width"))||0),"margin"===c&&(e+=parseFloat(d.css(a,c+J[f]))||0);return e+"px"}function cb(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");if(d.isFunction(c))for(var e=b.toLowerCase().split(db),f=0,g=
e.length,i,h;f<g;f++)i=e[f],(h=/^\+/.test(i))&&(i=i.substr(1)||"*"),i=a[i]=a[i]||[],i[h?"unshift":"push"](c)}}function ea(a,b,c,e,d,g){d=d||b.dataTypes[0];g=g||{};g[d]=!0;for(var d=a[d],i=0,h=d?d.length:0,k=a===za,n;i<h&&(k||!n);i++)n=d[i](b,c,e),"string"===typeof n&&(!k||g[n]?n=j:(b.dataTypes.unshift(n),n=ea(a,b,c,e,n,g)));if((k||!n)&&!g["*"])n=ea(a,b,c,e,"*",g);return n}function eb(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)b[c]!==j&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e)}
function Aa(a,b,c,e){if(d.isArray(b))d.each(b,function(b,d){c||bc.test(a)?e(a,d):Aa(a+"["+("object"===typeof d?b:"")+"]",d,c,e)});else if(!c&&"object"===d.type(b))for(var f in b)Aa(a+"["+f+"]",b[f],c,e);else e(a,b)}function fb(){try{return new s.XMLHttpRequest}catch(a){}}function gb(){setTimeout(cc,0);return fa=d.now()}function cc(){fa=j}function F(a,b){var c={};d.each(ga.concat.apply([],ga.slice(0,b)),function(){c[this]=a});return c}function hb(a){if(!Ba[a]){var b=m.body,c=d("<"+a+">").appendTo(b),
e=c.css("display");c.remove();if("none"===e||""===e){x||(x=m.createElement("iframe"),x.frameBorder=x.width=x.height=0);b.appendChild(x);if(!M||!x.createElement)M=(x.contentWindow||x.contentDocument).document,M.write((d.support.boxModel?"<!doctype html>":"")+"<html><body>"),M.close();c=M.createElement(a);M.body.appendChild(c);e=d.css(c,"display");b.removeChild(x)}Ba[a]=e}return Ba[a]}function ib(a){return d.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var m=s.document,dc=s.location,
d,jb=function(){if(!l.isReady){try{m.documentElement.doScroll("left")}catch(a){setTimeout(jb,1);return}l.ready()}},l=function(a,b){return new l.fn.init(a,b,kb)},ec=s.jQuery,fc=s.$,kb,gc=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,lb=/\S/,mb=/^\s+/,nb=/\s+$/,hc=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,ic=/^[\],:{}\s]*$/,jc=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,kc=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,lc=/(?:^|:|,)(?:\s*\[)+/g,mc=/(webkit)[ \/]([\w.]+)/,nc=/(opera)(?:.*version)?[ \/]([\w.]+)/,
oc=/(msie) ([\w.]+)/,pc=/(mozilla)(?:.*? rv:([\w.]+))?/,qc=/-([a-z]|[0-9])/ig,rc=/^-ms-/,sc=function(a,b){return(b+"").toUpperCase()},tc=s.navigator.userAgent,ha,ia,R,uc=Object.prototype.toString,Ca=Object.prototype.hasOwnProperty,Da=Array.prototype.push,Z=Array.prototype.slice,ob=String.prototype.trim,pb=Array.prototype.indexOf,qb={};l.fn=l.prototype={constructor:l,init:function(a,b,c){var e;if(!a)return this;if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if("body"===a&&!b&&m.body)return this.context=
m,this[0]=m.body,this.selector=a,this.length=1,this;if("string"===typeof a){if((e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:gc.exec(a))&&(e[1]||!b)){if(e[1])return c=(b=b instanceof l?b[0]:b)?b.ownerDocument||b:m,(a=hc.exec(a))?l.isPlainObject(b)?(a=[m.createElement(a[1])],l.fn.attr.call(a,b,!0)):a=[c.createElement(a[1])]:(a=l.buildFragment([e[1]],[c]),a=(a.cacheable?l.clone(a.fragment):a.fragment).childNodes),l.merge(this,a);if((b=m.getElementById(e[2]))&&b.parentNode){if(b.id!==
e[2])return c.find(a);this.length=1;this[0]=b}this.context=m;this.selector=a;return this}return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a)}if(l.isFunction(a))return c.ready(a);a.selector!==j&&(this.selector=a.selector,this.context=a.context);return l.makeArray(a,this)},selector:"",jquery:"1.7.2",length:0,size:function(){return this.length},toArray:function(){return Z.call(this,0)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a,b,c){var e=
this.constructor();l.isArray(a)?Da.apply(e,a):l.merge(e,a);e.prevObject=this;e.context=this.context;"find"===b?e.selector=this.selector+(this.selector?" ":"")+c:b&&(e.selector=this.selector+"."+b+"("+c+")");return e},each:function(a,b){return l.each(this,a,b)},ready:function(a){l.bindReady();ia.add(a);return this},eq:function(a){a=+a;return-1===a?this.slice(a):this.slice(a,a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(Z.apply(this,
arguments),"slice",Z.call(arguments).join(","))},map:function(a){return this.pushStack(l.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Da,sort:[].sort,splice:[].splice};l.fn.init.prototype=l.fn;l.extend=l.fn.extend=function(){var a,b,c,e,d,g=arguments[0]||{},i=1,h=arguments.length,k=!1;"boolean"===typeof g&&(k=g,g=arguments[1]||{},i=2);"object"!==typeof g&&!l.isFunction(g)&&(g={});h===i&&(g=this,--i);for(;i<h;i++)if(null!=(a=arguments[i]))for(b in a)c=
g[b],e=a[b],g!==e&&(k&&e&&(l.isPlainObject(e)||(d=l.isArray(e)))?(d?(d=!1,c=c&&l.isArray(c)?c:[]):c=c&&l.isPlainObject(c)?c:{},g[b]=l.extend(k,c,e)):e!==j&&(g[b]=e));return g};l.extend({noConflict:function(a){s.$===l&&(s.$=fc);a&&s.jQuery===l&&(s.jQuery=ec);return l},isReady:!1,readyWait:1,holdReady:function(a){a?l.readyWait++:l.ready(!0)},ready:function(a){if(!0===a&&!--l.readyWait||!0!==a&&!l.isReady){if(!m.body)return setTimeout(l.ready,1);l.isReady=!0;!0!==a&&0<--l.readyWait||(ia.fireWith(m,[l]),
l.fn.trigger&&l(m).trigger("ready").off("ready"))}},bindReady:function(){if(!ia){ia=l.Callbacks("once memory");if("complete"===m.readyState)return setTimeout(l.ready,1);if(m.addEventListener)m.addEventListener("DOMContentLoaded",R,!1),s.addEventListener("load",l.ready,!1);else if(m.attachEvent){m.attachEvent("onreadystatechange",R);s.attachEvent("onload",l.ready);var a=!1;try{a=null==s.frameElement}catch(b){}m.documentElement.doScroll&&a&&jb()}}},isFunction:function(a){return"function"===l.type(a)},
isArray:Array.isArray||function(a){return"array"===l.type(a)},isWindow:function(a){return null!=a&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?String(a):qb[uc.call(a)]||"object"},isPlainObject:function(a){if(!a||"object"!==l.type(a)||a.nodeType||l.isWindow(a))return!1;try{if(a.constructor&&!Ca.call(a,"constructor")&&!Ca.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return c===j||Ca.call(a,c)},
isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseJSON:function(a){if("string"!==typeof a||!a)return null;a=l.trim(a);if(s.JSON&&s.JSON.parse)return s.JSON.parse(a);if(ic.test(a.replace(jc,"@").replace(kc,"]").replace(lc,"")))return(new Function("return "+a))();l.error("Invalid JSON: "+a)},parseXML:function(a){if("string"!==typeof a||!a)return null;var b,c;try{s.DOMParser?(c=new DOMParser,b=c.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),
b.async="false",b.loadXML(a))}catch(e){b=j}(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)&&l.error("Invalid XML: "+a);return b},noop:function(){},globalEval:function(a){a&&lb.test(a)&&(s.execScript||function(a){s.eval.call(s,a)})(a)},camelCase:function(a){return a.replace(rc,"ms-").replace(qc,sc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,c){var e,d=0,g=a.length,i=g===j||l.isFunction(a);if(c)if(i)for(e in a){if(!1===
b.apply(a[e],c))break}else for(;d<g&&!1!==b.apply(a[d++],c););else if(i)for(e in a){if(!1===b.call(a[e],e,a[e]))break}else for(;d<g&&!1!==b.call(a[d],d,a[d++]););return a},trim:ob?function(a){return null==a?"":ob.call(a)}:function(a){return null==a?"":a.toString().replace(mb,"").replace(nb,"")},makeArray:function(a,b){var c=b||[];if(null!=a){var e=l.type(a);null==a.length||"string"===e||"function"===e||"regexp"===e||l.isWindow(a)?Da.call(c,a):l.merge(c,a)}return c},inArray:function(a,b,c){var e;if(b){if(pb)return pb.call(b,
a,c);e=b.length;for(c=c?0>c?Math.max(0,e+c):c:0;c<e;c++)if(c in b&&b[c]===a)return c}return-1},merge:function(a,b){var c=a.length,e=0;if("number"===typeof b.length)for(var d=b.length;e<d;e++)a[c++]=b[e];else for(;b[e]!==j;)a[c++]=b[e++];a.length=c;return a},grep:function(a,b,c){for(var e=[],d,c=!!c,g=0,i=a.length;g<i;g++)d=!!b(a[g],g),c!==d&&e.push(a[g]);return e},map:function(a,b,c){var e,d,g=[],i=0,h=a.length;if(a instanceof l||h!==j&&"number"===typeof h&&(0<h&&a[0]&&a[h-1]||0===h||l.isArray(a)))for(;i<
h;i++)e=b(a[i],i,c),null!=e&&(g[g.length]=e);else for(d in a)e=b(a[d],d,c),null!=e&&(g[g.length]=e);return g.concat.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b)var c=a[b],b=a,a=c;if(!l.isFunction(a))return j;var e=Z.call(arguments,2),c=function(){return a.apply(b,e.concat(Z.call(arguments)))};c.guid=a.guid=a.guid||c.guid||l.guid++;return c},access:function(a,b,c,e,d,g,i){var h,k=null==c,n=0,t=a.length;if(c&&"object"===typeof c){for(n in c)l.access(a,b,n,c[n],1,g,e);d=1}else if(e!==
j){h=i===j&&l.isFunction(e);k&&(h?(h=b,b=function(a,b,c){return h.call(l(a),c)}):(b.call(a,e),b=null));if(b)for(;n<t;n++)b(a[n],c,h?e.call(a[n],n,b(a[n],c)):e,i);d=1}return d?a:k?b.call(a):t?b(a[0],c):g},now:function(){return(new Date).getTime()},uaMatch:function(a){a=a.toLowerCase();a=mc.exec(a)||nc.exec(a)||oc.exec(a)||0>a.indexOf("compatible")&&pc.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},sub:function(){function a(b,e){return new a.fn.init(b,e)}l.extend(!0,a,this);a.superclass=this;
a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=function(c,e){e&&(e instanceof l&&!(e instanceof a))&&(e=a(e));return l.fn.init.call(this,c,e,b)};a.fn.init.prototype=a.fn;var b=a(m);return a},browser:{}});l.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){qb["[object "+b+"]"]=b.toLowerCase()});ha=l.uaMatch(tc);ha.browser&&(l.browser[ha.browser]=!0,l.browser.version=ha.version);l.browser.webkit&&(l.browser.safari=!0);lb.test("\u00a0")&&(mb=
/^[\s\xA0]+/,nb=/[\s\xA0]+$/);kb=l(m);m.addEventListener?R=function(){m.removeEventListener("DOMContentLoaded",R,!1);l.ready()}:m.attachEvent&&(R=function(){"complete"===m.readyState&&(m.detachEvent("onreadystatechange",R),l.ready())});d=l;var sb={};d.Callbacks=function(a){var b;if(a){if(!(b=sb[a])){b=a;var c=sb[b]={},e,f;b=b.split(/\s+/);e=0;for(f=b.length;e<f;e++)c[b[e]]=!0;b=c}}else b={};var a=b,g=[],i=[],h,k,n,t,N,S,m=function(b){var c,e,f,h;c=0;for(e=b.length;c<e;c++)f=b[c],h=d.type(f),"array"===
h?m(f):"function"===h&&(!a.unique||!p.has(f))&&g.push(f)},l=function(b,c){c=c||[];h=!a.memory||[b,c];n=k=!0;S=t||0;t=0;for(N=g.length;g&&S<N;S++)if(!1===g[S].apply(b,c)&&a.stopOnFalse){h=!0;break}n=!1;g&&(a.once?!0===h?p.disable():g=[]:i&&i.length&&(h=i.shift(),p.fireWith(h[0],h[1])))},p={add:function(){if(g){var a=g.length;m(arguments);n?N=g.length:h&&!0!==h&&(t=a,l(h[0],h[1]))}return this},remove:function(){if(g)for(var b=arguments,c=0,e=b.length;c<e;c++)for(var d=0;d<g.length&&!(b[c]===g[d]&&(n&&
d<=N&&(N--,d<=S&&S--),g.splice(d--,1),a.unique));d++);return this},has:function(a){if(g)for(var b=0,c=g.length;b<c;b++)if(a===g[b])return!0;return!1},empty:function(){g=[];return this},disable:function(){g=i=h=j;return this},disabled:function(){return!g},lock:function(){i=j;(!h||!0===h)&&p.disable();return this},locked:function(){return!i},fireWith:function(b,c){i&&(n?a.once||i.push([b,c]):(!a.once||!h)&&l(b,c));return this},fire:function(){p.fireWith(this,arguments);return this},fired:function(){return!!k}};
return p};var Ea=[].slice;d.extend({Deferred:function(a){var b=d.Callbacks("once memory"),c=d.Callbacks("once memory"),e=d.Callbacks("memory"),f="pending",g={resolve:b,reject:c,notify:e},i={done:b.add,fail:c.add,progress:e.add,state:function(){return f},isResolved:b.fired,isRejected:c.fired,then:function(a,b,c){h.done(a).fail(b).progress(c);return this},always:function(){h.done.apply(h,arguments).fail.apply(h,arguments);return this},pipe:function(a,b,c){return d.Deferred(function(e){d.each({done:[a,
"resolve"],fail:[b,"reject"],progress:[c,"notify"]},function(a,b){var c=b[0],f=b[1],g;if(d.isFunction(c))h[a](function(){if((g=c.apply(this,arguments))&&d.isFunction(g.promise))g.promise().then(e.resolve,e.reject,e.notify);else e[f+"With"](this===h?e:this,[g])});else h[a](e[f])})}).promise()},promise:function(a){if(null==a)a=i;else for(var b in i)a[b]=i[b];return a}},h=i.promise({}),k;for(k in g)h[k]=g[k].fire,h[k+"With"]=g[k].fireWith;h.done(function(){f="resolved"},c.disable,e.lock).fail(function(){f=
"rejected"},b.disable,e.lock);a&&a.call(h,h);return h},when:function(a){function b(a){return function(b){e[a]=1<arguments.length?Ea.call(arguments,0):b;--h||k.resolveWith(k,e)}}function c(a){return function(b){i[a]=1<arguments.length?Ea.call(arguments,0):b;k.notifyWith(n,i)}}var e=Ea.call(arguments,0),f=0,g=e.length,i=Array(g),h=g,k=1>=g&&a&&d.isFunction(a.promise)?a:d.Deferred(),n=k.promise();if(1<g){for(;f<g;f++)e[f]&&e[f].promise&&d.isFunction(e[f].promise)?e[f].promise().then(b(f),k.reject,c(f)):
--h;h||k.resolveWith(k,e)}else k!==a&&k.resolveWith(k,g?[a]:[]);return n}});var vc=d,Fa;var u,Ga,T,ja,ka,w,G,$,la,Ha,U,q=m.createElement("div");q.setAttribute("className","t");q.innerHTML="   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";Ga=q.getElementsByTagName("*");T=q.getElementsByTagName("a")[0];if(!Ga||!Ga.length||!T)Fa={};else{ja=m.createElement("select");ka=ja.appendChild(m.createElement("option"));w=q.getElementsByTagName("input")[0];
u={leadingWhitespace:3===q.firstChild.nodeType,tbody:!q.getElementsByTagName("tbody").length,htmlSerialize:!!q.getElementsByTagName("link").length,style:/top/.test(T.getAttribute("style")),hrefNormalized:"/a"===T.getAttribute("href"),opacity:/^0.55/.test(T.style.opacity),cssFloat:!!T.style.cssFloat,checkOn:"on"===w.value,optSelected:ka.selected,getSetAttribute:"t"!==q.className,enctype:!!m.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==m.createElement("nav").cloneNode(!0).outerHTML,submitBubbles:!0,
changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0,pixelMargin:!0};d.boxModel=u.boxModel="CSS1Compat"===m.compatMode;w.checked=!0;u.noCloneChecked=w.cloneNode(!0).checked;ja.disabled=!0;u.optDisabled=!ka.disabled;try{delete q.test}catch(md){u.deleteExpando=!1}!q.addEventListener&&(q.attachEvent&&q.fireEvent)&&(q.attachEvent("onclick",function(){u.noCloneEvent=!1}),q.cloneNode(!0).fireEvent("onclick"));w=m.createElement("input");
w.value="t";w.setAttribute("type","radio");u.radioValue="t"===w.value;w.setAttribute("checked","checked");w.setAttribute("name","t");q.appendChild(w);G=m.createDocumentFragment();G.appendChild(q.lastChild);u.checkClone=G.cloneNode(!0).cloneNode(!0).lastChild.checked;u.appendChecked=w.checked;G.removeChild(w);G.appendChild(q);if(q.attachEvent)for(Ha in{submit:1,change:1,focusin:1})la="on"+Ha,U=la in q,U||(q.setAttribute(la,"return;"),U="function"===typeof q[la]),u[Ha+"Bubbles"]=U;G.removeChild(q);
G=ja=ka=q=w=null;d(function(){var a,b,c,e,f=m.getElementsByTagName("body")[0];f&&(a=m.createElement("div"),a.style.cssText="padding:0;margin:0;border:0;visibility:hidden;width:0;height:0;position:static;top:0;margin-top:1px",f.insertBefore(a,f.firstChild),q=m.createElement("div"),a.appendChild(q),q.innerHTML="<table><tr><td style='padding:0;margin:0;border:0;display:none'></td><td>t</td></tr></table>",$=q.getElementsByTagName("td"),U=0===$[0].offsetHeight,$[0].style.display="",$[1].style.display=
"none",u.reliableHiddenOffsets=U&&0===$[0].offsetHeight,s.getComputedStyle&&(q.innerHTML="",b=m.createElement("div"),b.style.width="0",b.style.marginRight="0",q.style.width="2px",q.appendChild(b),u.reliableMarginRight=0===(parseInt((s.getComputedStyle(b,null)||{marginRight:0}).marginRight,10)||0)),"undefined"!==typeof q.style.zoom&&(q.innerHTML="",q.style.width=q.style.padding="1px",q.style.border=0,q.style.overflow="hidden",q.style.display="inline",q.style.zoom=1,u.inlineBlockNeedsLayout=3===q.offsetWidth,
q.style.display="block",q.style.overflow="visible",q.innerHTML="<div style='width:5px;'></div>",u.shrinkWrapBlocks=3!==q.offsetWidth),q.style.cssText="position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:0;visibility:hidden;",q.innerHTML="<div style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;display:block;'><div style='padding:0;margin:0;border:0;display:block;overflow:hidden;'></div></div><table style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>",
b=q.firstChild,c=b.firstChild,e=b.nextSibling.firstChild.firstChild,e={doesNotAddBorder:5!==c.offsetTop,doesAddBorderForTableAndCells:5===e.offsetTop},c.style.position="fixed",c.style.top="20px",e.fixedPosition=20===c.offsetTop||15===c.offsetTop,c.style.position=c.style.top="",b.style.overflow="hidden",b.style.position="relative",e.subtractsBorderForOverflowNotVisible=-5===c.offsetTop,e.doesNotIncludeMarginInBodyOffset=1!==f.offsetTop,s.getComputedStyle&&(q.style.marginTop="1%",u.pixelMargin="1%"!==
(s.getComputedStyle(q,null)||{marginTop:0}).marginTop),"undefined"!==typeof a.style.zoom&&(a.style.zoom=1),f.removeChild(a),q=null,d.extend(u,e))});Fa=u}vc.support=Fa;var $b=/^(?:\{.*\}|\[.*\])$/,Zb=/([A-Z])/g;d.extend({cache:{},uuid:0,expando:"jQuery"+(d.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?d.cache[a[d.expando]]:a[d.expando];return!!a&&!xa(a)},data:function(a,b,c,e){if(d.acceptData(a)){var f;
f=d.expando;var g="string"===typeof b,i=a.nodeType,h=i?d.cache:a,k=i?a[f]:a[f]&&f,n="events"===b;if(k&&h[k]&&(n||e||h[k].data)||!(g&&c===j)){k||(i?a[f]=k=++d.uuid:k=f);h[k]||(h[k]={},i||(h[k].toJSON=d.noop));if("object"===typeof b||"function"===typeof b)e?h[k]=d.extend(h[k],b):h[k].data=d.extend(h[k].data,b);f=a=h[k];e||(a.data||(a.data={}),a=a.data);c!==j&&(a[d.camelCase(b)]=c);if(n&&!a[b])return f.events;g?(c=a[b],null==c&&(c=a[d.camelCase(b)])):c=a;return c}}},removeData:function(a,b,c){if(d.acceptData(a)){var e,
f,g,i=d.expando,h=a.nodeType,k=h?d.cache:a,n=h?a[i]:i;if(k[n]){if(b&&(e=c?k[n]:k[n].data)){d.isArray(b)||(b in e?b=[b]:(b=d.camelCase(b),b=b in e?[b]:b.split(" ")));f=0;for(g=b.length;f<g;f++)delete e[b[f]];if(!(c?xa:d.isEmptyObject)(e))return}if(!c&&(delete k[n].data,!xa(k[n])))return;d.support.deleteExpando||!k.setInterval?delete k[n]:k[n]=null;h&&(d.support.deleteExpando?delete a[i]:a.removeAttribute?a.removeAttribute(i):a[i]=null)}}},_data:function(a,b,c){return d.data(a,b,c,!0)},acceptData:function(a){if(a.nodeName){var b=
d.noData[a.nodeName.toLowerCase()];if(b)return!(!0===b||a.getAttribute("classid")!==b)}return!0}});d.fn.extend({data:function(a,b){var c,e,f,g,i,h=this[0],k=0,n=null;if(a===j){if(this.length&&(n=d.data(h),1===h.nodeType&&!d._data(h,"parsedAttrs"))){f=h.attributes;for(i=f.length;k<i;k++)g=f[k].name,0===g.indexOf("data-")&&(g=d.camelCase(g.substring(5)),Ta(h,g,n[g]));d._data(h,"parsedAttrs",!0)}return n}if("object"===typeof a)return this.each(function(){d.data(this,a)});c=a.split(".",2);c[1]=c[1]?"."+
c[1]:"";e=c[1]+"!";return d.access(this,function(b){if(b===j)return n=this.triggerHandler("getData"+e,[c[0]]),n===j&&h&&(n=d.data(h,a),n=Ta(h,a,n)),n===j&&c[1]?this.data(c[0]):n;c[1]=b;this.each(function(){var f=d(this);f.triggerHandler("setData"+e,c);d.data(this,a,b);f.triggerHandler("changeData"+e,c)})},null,b,1<arguments.length,null,!1)},removeData:function(a){return this.each(function(){d.removeData(this,a)})}});d.extend({_mark:function(a,b){a&&(b=(b||"fx")+"mark",d._data(a,b,(d._data(a,b)||0)+
1))},_unmark:function(a,b,c){!0!==a&&(c=b,b=a,a=!1);if(b){var c=c||"fx",e=c+"mark";(a=a?0:(d._data(b,e)||1)-1)?d._data(b,e,a):(d.removeData(b,e,!0),Ua(b,c,"mark"))}},queue:function(a,b,c){var e;if(a)return b=(b||"fx")+"queue",e=d._data(a,b),c&&(!e||d.isArray(c)?e=d._data(a,b,d.makeArray(c)):e.push(c)),e||[]},dequeue:function(a,b){var b=b||"fx",c=d.queue(a,b),e=c.shift(),f={};"inprogress"===e&&(e=c.shift());e&&("fx"===b&&c.unshift("inprogress"),d._data(a,b+".run",f),e.call(a,function(){d.dequeue(a,
b)},f));c.length||(d.removeData(a,b+"queue "+b+".run",!0),Ua(a,b,"queue"))}});d.fn.extend({queue:function(a,b){var c=2;"string"!==typeof a&&(b=a,a="fx",c--);return arguments.length<c?d.queue(this[0],a):b===j?this:this.each(function(){var c=d.queue(this,a,b);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},delay:function(a,b){a=d.fx?d.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,e){var d=setTimeout(b,a);e.stop=function(){clearTimeout(d)}})},
clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){function c(){--i||e.resolveWith(f,[f])}"string"!==typeof a&&(b=a,a=j);for(var a=a||"fx",e=d.Deferred(),f=this,g=f.length,i=1,h=a+"defer",k=a+"queue",n=a+"mark",t;g--;)if(t=d.data(f[g],h,j,!0)||(d.data(f[g],k,j,!0)||d.data(f[g],n,j,!0))&&d.data(f[g],h,d.Callbacks("once memory"),!0))i++,t.add(c);c();return e.promise(b)}});var tb=/[\n\t\r]/g,ma=/\s+/,wc=/\r/g,xc=/^(?:button|input)$/i,yc=/^(?:button|input|object|select|textarea)$/i,
zc=/^a(?:rea)?$/i,ub=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,vb=d.support.getSetAttribute,z,wb,xb;d.fn.extend({attr:function(a,b){return d.access(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})},prop:function(a,b){return d.access(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){a=d.propFix[a]||a;return this.each(function(){try{this[a]=j,delete this[a]}catch(b){}})},
addClass:function(a){var b,c,e,f,g,i,h;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,this.className))});if(a&&"string"===typeof a){b=a.split(ma);c=0;for(e=this.length;c<e;c++)if(f=this[c],1===f.nodeType)if(!f.className&&1===b.length)f.className=a;else{g=" "+f.className+" ";i=0;for(h=b.length;i<h;i++)~g.indexOf(" "+b[i]+" ")||(g+=b[i]+" ");f.className=d.trim(g)}}return this},removeClass:function(a){var b,c,e,f,g,i,h;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,
b,this.className))});if(a&&"string"===typeof a||a===j){b=(a||"").split(ma);c=0;for(e=this.length;c<e;c++)if(f=this[c],1===f.nodeType&&f.className)if(a){g=(" "+f.className+" ").replace(tb," ");i=0;for(h=b.length;i<h;i++)g=g.replace(" "+b[i]+" "," ");f.className=d.trim(g)}else f.className=""}return this},toggleClass:function(a,b){var c=typeof a,e="boolean"===typeof b;return d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,this.className,b),b)}):this.each(function(){if("string"===
c)for(var f,g=0,i=d(this),h=b,k=a.split(ma);f=k[g++];)h=e?h:!i.hasClass(f),i[h?"addClass":"removeClass"](f);else if("undefined"===c||"boolean"===c)this.className&&d._data(this,"__className__",this.className),this.className=this.className||!1===a?"":d._data(this,"__className__")||""})},hasClass:function(a){for(var a=" "+a+" ",b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&-1<(" "+this[b].className+" ").replace(tb," ").indexOf(a))return!0;return!1},val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=
d.isFunction(a),this.each(function(c){var f=d(this);if(1===this.nodeType&&(c=e?a.call(this,c,f.val()):a,null==c?c="":"number"===typeof c?c+="":d.isArray(c)&&(c=d.map(c,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],!b||!("set"in b)||b.set(this,c,"value")===j))this.value=c});if(f){if((b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()])&&"get"in b&&(c=b.get(f,"value"))!==j)return c;c=f.value;return"string"===typeof c?c.replace(wc,""):null==
c?"":c}}});d.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,c,e=a.selectedIndex,f=[],g=a.options,i="select-one"===a.type;if(0>e)return null;a=i?e:0;for(c=i?e+1:g.length;a<c;a++)if(b=g[a],b.selected&&(d.support.optDisabled?!b.disabled:null===b.getAttribute("disabled"))&&(!b.parentNode.disabled||!d.nodeName(b.parentNode,"optgroup"))){b=d(b).val();if(i)return b;f.push(b)}return i&&!f.length&&g.length?d(g[e]).val():
f},set:function(a,b){var c=d.makeArray(b);d(a).find("option").each(function(){this.selected=0<=d.inArray(d(this).val(),c)});c.length||(a.selectedIndex=-1);return c}}},attrFn:{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0},attr:function(a,b,c,e){var f,g,i=a.nodeType;if(a&&!(3===i||8===i||2===i)){if(e&&b in d.attrFn)return d(a)[b](c);if("undefined"===typeof a.getAttribute)return d.prop(a,b,c);if(e=1!==i||!d.isXMLDoc(a))b=b.toLowerCase(),g=d.attrHooks[b]||(ub.test(b)?wb:z);if(c!==
j)if(null===c)d.removeAttr(a,b);else{if(g&&"set"in g&&e&&(f=g.set(a,c,b))!==j)return f;a.setAttribute(b,""+c);return c}else{if(g&&"get"in g&&e&&null!==(f=g.get(a,b)))return f;f=a.getAttribute(b);return null===f?j:f}}},removeAttr:function(a,b){var c,e,f,g,i,h=0;if(b&&1===a.nodeType){e=b.toLowerCase().split(ma);for(g=e.length;h<g;h++)if(f=e[h])c=d.propFix[f]||f,(i=ub.test(f))||d.attr(a,f,""),a.removeAttribute(vb?f:c),i&&c in a&&(a[c]=!1)}},attrHooks:{type:{set:function(a,b){if(xc.test(a.nodeName)&&
a.parentNode)d.error("type property can't be changed");else if(!d.support.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}},value:{get:function(a,b){return z&&d.nodeName(a,"button")?z.get(a,b):b in a?a.value:null},set:function(a,b,c){if(z&&d.nodeName(a,"button"))return z.set(a,b,c);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",
rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,c){var e,f,g;g=a.nodeType;if(a&&!(3===g||8===g||2===g)){if(g=1!==g||!d.isXMLDoc(a))b=d.propFix[b]||b,f=d.propHooks[b];return c!==j?f&&"set"in f&&(e=f.set(a,c,b))!==j?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):yc.test(a.nodeName)||zc.test(a.nodeName)&&
a.href?0:j}}}});d.attrHooks.tabindex=d.propHooks.tabIndex;wb={get:function(a,b){var c,e=d.prop(a,b);return!0===e||"boolean"!==typeof e&&(c=a.getAttributeNode(b))&&!1!==c.nodeValue?b.toLowerCase():j},set:function(a,b,c){!1===b?d.removeAttr(a,c):(b=d.propFix[c]||c,b in a&&(a[b]=!0),a.setAttribute(c,c.toLowerCase()));return c}};vb||(xb={name:!0,id:!0,coords:!0},z=d.valHooks.button={get:function(a,b){var c;return(c=a.getAttributeNode(b))&&(xb[b]?""!==c.nodeValue:c.specified)?c.nodeValue:j},set:function(a,
b,c){var e=a.getAttributeNode(c);e||(e=m.createAttribute(c),a.setAttributeNode(e));return e.nodeValue=b+""}},d.attrHooks.tabindex.set=z.set,d.each(["width","height"],function(a,b){d.attrHooks[b]=d.extend(d.attrHooks[b],{set:function(a,e){if(""===e)return a.setAttribute(b,"auto"),e}})}),d.attrHooks.contenteditable={get:z.get,set:function(a,b,c){""===b&&(b="false");z.set(a,b,c)}});d.support.hrefNormalized||d.each(["href","src","width","height"],function(a,b){d.attrHooks[b]=d.extend(d.attrHooks[b],{get:function(a){a=
a.getAttribute(b,2);return null===a?j:a}})});d.support.style||(d.attrHooks.style={get:function(a){return a.style.cssText.toLowerCase()||j},set:function(a,b){return a.style.cssText=""+b}});d.support.optSelected||(d.propHooks.selected=d.extend(d.propHooks.selected,{get:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex;return null}}));d.support.enctype||(d.propFix.enctype="encoding");d.support.checkOn||d.each(["radio","checkbox"],function(){d.valHooks[this]={get:function(a){return null===
a.getAttribute("value")?"on":a.value}}});d.each(["radio","checkbox"],function(){d.valHooks[this]=d.extend(d.valHooks[this],{set:function(a,b){if(d.isArray(b))return a.checked=0<=d.inArray(d(a).val(),b)}})});var Ia=/^(?:textarea|input|select)$/i,yb=/^([^\.]*)?(?:\.(.+))?$/,Ac=/(?:^|\s)hover(\.\S+)?\b/,Bc=/^key/,Cc=/^(?:mouse|contextmenu)|click/,zb=/^(?:focusinfocus|focusoutblur)$/,Dc=/^(\w*)(?:#([\w\-]+))?(?:\.([\w\-]+))?$/,Ec=function(a){if(a=Dc.exec(a))a[1]=(a[1]||"").toLowerCase(),a[3]=a[3]&&RegExp("(?:^|\\s)"+
a[3]+"(?:\\s|$)");return a},Ab=function(a){return d.event.special.hover?a:a.replace(Ac,"mouseenter$1 mouseleave$1")};d.event={add:function(a,b,c,e,f){var g,i,h,k,n,t,m,l,p;if(!(3===a.nodeType||8===a.nodeType||!b||!c||!(g=d._data(a)))){c.handler&&(m=c,c=m.handler,f=m.selector);c.guid||(c.guid=d.guid++);h=g.events;h||(g.events=h={});i=g.handle;i||(g.handle=i=function(a){return"undefined"!==typeof d&&(!a||d.event.triggered!==a.type)?d.event.dispatch.apply(i.elem,arguments):j},i.elem=a);b=d.trim(Ab(b)).split(" ");
for(g=0;g<b.length;g++){k=yb.exec(b[g])||[];n=k[1];t=(k[2]||"").split(".").sort();p=d.event.special[n]||{};n=(f?p.delegateType:p.bindType)||n;p=d.event.special[n]||{};k=d.extend({type:n,origType:k[1],data:e,handler:c,guid:c.guid,selector:f,quick:f&&Ec(f),namespace:t.join(".")},m);l=h[n];if(!l&&(l=h[n]=[],l.delegateCount=0,!p.setup||!1===p.setup.call(a,e,t,i)))a.addEventListener?a.addEventListener(n,i,!1):a.attachEvent&&a.attachEvent("on"+n,i);p.add&&(p.add.call(a,k),k.handler.guid||(k.handler.guid=
c.guid));f?l.splice(l.delegateCount++,0,k):l.push(k);d.event.global[n]=!0}a=null}},global:{},remove:function(a,b,c,e,f){var g=d.hasData(a)&&d._data(a),i,h,k,n,t,l,m,j,p,q;if(g&&(m=g.events)){b=d.trim(Ab(b||"")).split(" ");for(i=0;i<b.length;i++)if(h=yb.exec(b[i])||[],k=n=h[1],h=h[2],k){j=d.event.special[k]||{};k=(e?j.delegateType:j.bindType)||k;p=m[k]||[];t=p.length;h=h?RegExp("(^|\\.)"+h.split(".").sort().join("\\.(?:.*\\.)?")+"(\\.|$)"):null;for(l=0;l<p.length;l++)if(q=p[l],(f||n===q.origType)&&
(!c||c.guid===q.guid)&&(!h||h.test(q.namespace))&&(!e||e===q.selector||"**"===e&&q.selector))p.splice(l--,1),q.selector&&p.delegateCount--,j.remove&&j.remove.call(a,q);0===p.length&&t!==p.length&&((!j.teardown||!1===j.teardown.call(a,h))&&d.removeEvent(a,k,g.handle),delete m[k])}else for(k in m)d.event.remove(a,k+b[i],c,e,!0);if(d.isEmptyObject(m)){if(b=g.handle)b.elem=null;d.removeData(a,["events","handle"],!0)}}},customEvent:{getData:!0,setData:!0,changeData:!0},trigger:function(a,b,c,e){if(!c||
!(3===c.nodeType||8===c.nodeType)){var f=a.type||a,g=[],i,h,k,n,t;if(!zb.test(f+d.event.triggered)&&(0<=f.indexOf("!")&&(f=f.slice(0,-1),i=!0),0<=f.indexOf(".")&&(g=f.split("."),f=g.shift(),g.sort()),c&&!d.event.customEvent[f]||d.event.global[f]))if(a="object"===typeof a?a[d.expando]?a:new d.Event(f,a):new d.Event(f),a.type=f,a.isTrigger=!0,a.exclusive=i,a.namespace=g.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+g.join("\\.(?:.*\\.)?")+"(\\.|$)"):null,i=0>f.indexOf(":")?"on"+f:"",c){if(a.result=
j,a.target||(a.target=c),b=null!=b?d.makeArray(b):[],b.unshift(a),k=d.event.special[f]||{},!(k.trigger&&!1===k.trigger.apply(c,b))){t=[[c,k.bindType||f]];if(!e&&!k.noBubble&&!d.isWindow(c)){n=k.delegateType||f;g=zb.test(n+f)?c:c.parentNode;for(h=null;g;g=g.parentNode)t.push([g,n]),h=g;h&&h===c.ownerDocument&&t.push([h.defaultView||h.parentWindow||s,n])}for(h=0;h<t.length&&!a.isPropagationStopped();h++)g=t[h][0],a.type=t[h][1],(n=(d._data(g,"events")||{})[a.type]&&d._data(g,"handle"))&&n.apply(g,b),
(n=i&&g[i])&&(d.acceptData(g)&&!1===n.apply(g,b))&&a.preventDefault();a.type=f;if(!e&&!a.isDefaultPrevented()&&(!k._default||!1===k._default.apply(c.ownerDocument,b))&&!("click"===f&&d.nodeName(c,"a"))&&d.acceptData(c))if(i&&c[f]&&("focus"!==f&&"blur"!==f||0!==a.target.offsetWidth)&&!d.isWindow(c))(h=c[i])&&(c[i]=null),d.event.triggered=f,c[f](),d.event.triggered=j,h&&(c[i]=h);return a.result}}else for(h in c=d.cache,c)c[h].events&&c[h].events[f]&&d.event.trigger(a,b,c[h].handle.elem,!0)}},dispatch:function(a){var a=
d.event.fix(a||s.event),b=(d._data(this,"events")||{})[a.type]||[],c=b.delegateCount,e=[].slice.call(arguments,0),f=!a.exclusive&&!a.namespace,g=d.event.special[a.type]||{},i=[],h,k,n,t,l,m,p;e[0]=a;a.delegateTarget=this;if(!(g.preDispatch&&!1===g.preDispatch.call(this,a))){if(c&&!(a.button&&"click"===a.type)){n=d(this);n.context=this.ownerDocument||this;for(k=a.target;k!=this;k=k.parentNode||this)if(!0!==k.disabled){l={};m=[];n[0]=k;for(h=0;h<c;h++){t=b[h];p=t.selector;if(l[p]===j){var q=l,r=p,D;
if(t.quick){D=t.quick;var u=k.attributes||{};D=(!D[1]||k.nodeName.toLowerCase()===D[1])&&(!D[2]||(u.id||{}).value===D[2])&&(!D[3]||D[3].test((u["class"]||{}).value))}else D=n.is(p);q[r]=D}l[p]&&m.push(t)}m.length&&i.push({elem:k,matches:m})}}b.length>c&&i.push({elem:this,matches:b.slice(c)});for(h=0;h<i.length&&!a.isPropagationStopped();h++){c=i[h];a.currentTarget=c.elem;for(b=0;b<c.matches.length&&!a.isImmediatePropagationStopped();b++)if(t=c.matches[b],f||!a.namespace&&!t.namespace||a.namespace_re&&
a.namespace_re.test(t.namespace))a.data=t.data,a.handleObj=t,t=((d.event.special[t.origType]||{}).handle||t.handler).apply(c.elem,e),t!==j&&(a.result=t,!1===t&&(a.preventDefault(),a.stopPropagation()))}g.postDispatch&&g.postDispatch.call(this,a);return a.result}},props:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],
filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,e,d=b.button,g=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||m,e=c.documentElement,c=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||c&&c.scrollLeft||0)-(e&&e.clientLeft||c&&c.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||c&&
c.scrollTop||0)-(e&&e.clientTop||c&&c.clientTop||0));!a.relatedTarget&&g&&(a.relatedTarget=g===a.target?b.toElement:g);!a.which&&d!==j&&(a.which=d&1?1:d&2?3:d&4?2:0);return a}},fix:function(a){if(a[d.expando])return a;var b,c,e=a,f=d.event.fixHooks[a.type]||{},g=f.props?this.props.concat(f.props):this.props,a=d.Event(e);for(b=g.length;b;)c=g[--b],a[c]=e[c];a.target||(a.target=e.srcElement||m);3===a.target.nodeType&&(a.target=a.target.parentNode);a.metaKey===j&&(a.metaKey=a.ctrlKey);return f.filter?
f.filter(a,e):a},special:{ready:{setup:d.bindReady},load:{noBubble:!0},focus:{delegateType:"focusin"},blur:{delegateType:"focusout"},beforeunload:{setup:function(a,b,c){d.isWindow(this)&&(this.onbeforeunload=c)},teardown:function(a,b){this.onbeforeunload===b&&(this.onbeforeunload=null)}}},simulate:function(a,b,c,e){a=d.extend(new d.Event,c,{type:a,isSimulated:!0,originalEvent:{}});e?d.event.trigger(a,null,b):d.event.dispatch.call(b,a);a.isDefaultPrevented()&&c.preventDefault()}};d.event.handle=d.event.dispatch;
d.removeEvent=m.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?ca:E):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||d.now();this[d.expando]=!0};d.Event.prototype=
{preventDefault:function(){this.isDefaultPrevented=ca;var a=this.originalEvent;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){this.isPropagationStopped=ca;var a=this.originalEvent;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=ca;this.stopPropagation()},isDefaultPrevented:E,isPropagationStopped:E,isImmediatePropagationStopped:E};d.each({mouseenter:"mouseover",mouseleave:"mouseout"},
function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e=a.relatedTarget,f=a.handleObj,g;if(!e||e!==this&&!d.contains(this,e))a.type=f.origType,g=f.handler.apply(this,arguments),a.type=b;return g}}});d.support.submitBubbles||(d.event.special.submit={setup:function(){if(d.nodeName(this,"form"))return!1;d.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=d.nodeName(a,"input")||d.nodeName(a,"button")?a.form:j)&&!a._submit_attached)d.event.add(a,
"submit._submit",function(a){a._submit_bubble=!0}),a._submit_attached=!0})},postDispatch:function(a){a._submit_bubble&&(delete a._submit_bubble,this.parentNode&&!a.isTrigger&&d.event.simulate("submit",this.parentNode,a,!0))},teardown:function(){if(d.nodeName(this,"form"))return!1;d.event.remove(this,"._submit")}});d.support.changeBubbles||(d.event.special.change={setup:function(){if(Ia.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)d.event.add(this,"propertychange._change",function(a){"checked"===
a.originalEvent.propertyName&&(this._just_changed=!0)}),d.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1,d.event.simulate("change",this,a,!0))});return!1}d.event.add(this,"beforeactivate._change",function(a){a=a.target;Ia.test(a.nodeName)&&!a._change_attached&&(d.event.add(a,"change._change",function(a){this.parentNode&&(!a.isSimulated&&!a.isTrigger)&&d.event.simulate("change",this.parentNode,a,!0)}),a._change_attached=!0)})},handle:function(a){var b=
a.target;if(this!==b||a.isSimulated||a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){d.event.remove(this,"._change");return Ia.test(this.nodeName)}});d.support.focusinBubbles||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=0,e=function(a){d.event.simulate(b,a.target,d.event.fix(a),!0)};d.event.special[b]={setup:function(){0===c++&&m.addEventListener(a,e,!0)},teardown:function(){0===--c&&m.removeEventListener(a,
e,!0)}}});d.fn.extend({on:function(a,b,c,e,f){var g,i;if("object"===typeof a){"string"!==typeof b&&(c=c||b,b=j);for(i in a)this.on(i,b,c,a[i],f);return this}null==c&&null==e?(e=b,c=b=j):null==e&&("string"===typeof b?(e=c,c=j):(e=c,c=b,b=j));if(!1===e)e=E;else if(!e)return this;1===f&&(g=e,e=function(a){d().off(a);return g.apply(this,arguments)},e.guid=g.guid||(g.guid=d.guid++));return this.each(function(){d.event.add(this,a,e,c,b)})},one:function(a,b,c,e){return this.on(a,b,c,e,1)},off:function(a,
b,c){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=j;!1===c&&(c=E);return this.each(function(){d.event.remove(this,a,c,b)})},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,c){d(this.context).on(a,this.selector,b,
c);return this},die:function(a,b){d(this.context).off(a,this.selector||"**",b);return this},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1==arguments.length?this.off(a,"**"):this.off(b,a,c)},trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return d.event.trigger(a,b,this[0],!0)},toggle:function(a){var b=arguments,c=a.guid||d.guid++,e=0,f=function(c){var f=(d._data(this,"lastToggle"+a.guid)||
0)%e;d._data(this,"lastToggle"+a.guid,f+1);c.preventDefault();return b[f].apply(this,arguments)||!1};for(f.guid=c;e<b.length;)b[e++].guid=c;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){d.fn[b]=function(a,e){null==e&&(e=a,a=null);
return 0<arguments.length?this.on(b,null,a,e):this.trigger(b)};d.attrFn&&(d.attrFn[b]=!0);Bc.test(b)&&(d.event.fixHooks[b]=d.event.keyHooks);Cc.test(b)&&(d.event.fixHooks[b]=d.event.mouseHooks)});var Bb=function(a,b,c,e,d,g){for(var d=0,i=e.length;d<i;d++){var h=e[d];if(h){for(var k=!1,h=h[a];h;){if(h[V]===c){k=e[h.sizset];break}1===h.nodeType&&!g&&(h[V]=c,h.sizset=d);if(h.nodeName.toLowerCase()===b){k=h;break}h=h[a]}e[d]=k}}},Cb=function(a,b,c,e,d,g){for(var d=0,i=e.length;d<i;d++){var h=e[d];if(h){for(var k=
!1,h=h[a];h;){if(h[V]===c){k=e[h.sizset];break}if(1===h.nodeType)if(g||(h[V]=c,h.sizset=d),"string"!==typeof b){if(h===b){k=!0;break}}else if(0<p.filter(b,[h]).length){k=h;break}h=h[a]}e[d]=k}}},Ja=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,V="sizcache"+(Math.random()+"").replace(".",""),Ka=0,Db=Object.prototype.toString,na=!1,Eb=!0,W=/\\/g,Fc=/\r\n/g,oa=/\W/;[0,0].sort(function(){Eb=!1;return 0});var p=function(a,
b,c,e){var c=c||[],d=b=b||m;if(1!==b.nodeType&&9!==b.nodeType)return[];if(!a||"string"!==typeof a)return c;var g,i,h,k,n,t=!0,l=p.isXML(b),j=[],q=a;do if(Ja.exec(""),g=Ja.exec(q))if(q=g[3],j.push(g[1]),g[2]){k=g[3];break}while(g);if(1<j.length&&Fb.exec(a))if(2===j.length&&r.relative[j[0]])i=Gb(j[0]+j[1],b,e);else for(i=r.relative[j[0]]?[b]:p(j.shift(),b);j.length;)a=j.shift(),r.relative[a]&&(a+=j.shift()),i=Gb(a,i,e);else if(!e&&(1<j.length&&9===b.nodeType&&!l&&r.match.ID.test(j[0])&&!r.match.ID.test(j[j.length-
1]))&&(g=p.find(j.shift(),b,l),b=g.expr?p.filter(g.expr,g.set)[0]:g.set[0]),b){g=e?{expr:j.pop(),set:y(e)}:p.find(j.pop(),1===j.length&&("~"===j[0]||"+"===j[0])&&b.parentNode?b.parentNode:b,l);i=g.expr?p.filter(g.expr,g.set):g.set;for(0<j.length?h=y(i):t=!1;j.length;)g=n=j.pop(),r.relative[n]?g=j.pop():n="",null==g&&(g=b),r.relative[n](h,g,l)}else h=[];h||(h=i);h||p.error(n||a);if("[object Array]"===Db.call(h))if(t)if(b&&1===b.nodeType)for(a=0;null!=h[a];a++)h[a]&&(!0===h[a]||1===h[a].nodeType&&p.contains(b,
h[a]))&&c.push(i[a]);else for(a=0;null!=h[a];a++)h[a]&&1===h[a].nodeType&&c.push(i[a]);else c.push.apply(c,h);else y(h,c);k&&(p(k,d,c,e),p.uniqueSort(c));return c};p.uniqueSort=function(a){if(pa&&(na=Eb,a.sort(pa),na))for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1);return a};p.matches=function(a,b){return p(a,null,null,b)};p.matchesSelector=function(a,b){return 0<p(b,null,null,[a]).length};p.find=function(a,b,c){var d,f,g,i,h,k;if(!a)return[];f=0;for(g=r.order.length;f<g;f++)if(h=r.order[f],
i=r.leftMatch[h].exec(a))if(k=i[1],i.splice(1,1),"\\"!==k.substr(k.length-1)&&(i[1]=(i[1]||"").replace(W,""),d=r.find[h](i,b,c),null!=d)){a=a.replace(r.match[h],"");break}d||(d="undefined"!==typeof b.getElementsByTagName?b.getElementsByTagName("*"):[]);return{set:d,expr:a}};p.filter=function(a,b,c,d){for(var f,g,i,h,k,n,l,m,q=a,s=[],u=b,w=b&&b[0]&&p.isXML(b[0]);a&&b.length;){for(i in r.filter)if(null!=(f=r.leftMatch[i].exec(a))&&f[2])if(n=r.filter[i],k=f[1],g=!1,f.splice(1,1),"\\"!==k.substr(k.length-
1)){u===s&&(s=[]);if(r.preFilter[i])if(f=r.preFilter[i](f,u,c,s,d,w)){if(!0===f)continue}else g=h=!0;if(f)for(l=0;null!=(k=u[l]);l++)k&&(h=n(k,f,l,u),m=d^h,c&&null!=h?m?g=!0:u[l]=!1:m&&(s.push(k),g=!0));if(h!==j){c||(u=s);a=a.replace(r.match[i],"");if(!g)return[];break}}if(a===q)if(null==g)p.error(a);else break;q=a}return u};p.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};var La=p.getText=function(a){var b,c;b=a.nodeType;var d="";if(b)if(1===b||9===b||11===b){if("string"===
typeof a.textContent)return a.textContent;if("string"===typeof a.innerText)return a.innerText.replace(Fc,"");for(a=a.firstChild;a;a=a.nextSibling)d+=La(a)}else{if(3===b||4===b)return a.nodeValue}else for(b=0;c=a[b];b++)8!==c.nodeType&&(d+=La(c));return d},r=p.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")},type:function(a){return a.getAttribute("type")}},relative:{"+":function(a,b){var c=
"string"===typeof b,d=c&&!oa.test(b),c=c&&!d;d&&(b=b.toLowerCase());for(var d=0,f=a.length,g;d<f;d++)if(g=a[d]){for(;(g=g.previousSibling)&&1!==g.nodeType;);a[d]=c||g&&g.nodeName.toLowerCase()===b?g||!1:g===b}c&&p.filter(b,a,!0)},">":function(a,b){var c,d="string"===typeof b,f=0,g=a.length;if(d&&!oa.test(b))for(b=b.toLowerCase();f<g;f++){if(c=a[f])c=c.parentNode,a[f]=c.nodeName.toLowerCase()===b?c:!1}else{for(;f<g;f++)(c=a[f])&&(a[f]=d?c.parentNode:c.parentNode===b);d&&p.filter(b,a,!0)}},"":function(a,
b,c){var d,f=Ka++,g=Cb;"string"===typeof b&&!oa.test(b)&&(d=b=b.toLowerCase(),g=Bb);g("parentNode",b,f,a,d,c)},"~":function(a,b,c){var d,f=Ka++,g=Cb;"string"===typeof b&&!oa.test(b)&&(d=b=b.toLowerCase(),g=Bb);g("previousSibling",b,f,a,d,c)}},find:{ID:function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,b){if("undefined"!==typeof b.getElementsByName){for(var c=[],d=b.getElementsByName(a[1]),f=0,g=d.length;f<g;f++)d[f].getAttribute("name")===
a[1]&&c.push(d[f]);return 0===c.length?null:c}},TAG:function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,d,f,g){a=" "+a[1].replace(W,"")+" ";if(g)return a;for(var g=0,i;null!=(i=b[g]);g++)i&&(f^(i.className&&0<=(" "+i.className+" ").replace(/[\t\n\r]/g," ").indexOf(a))?c||d.push(i):c&&(b[g]=!1));return!1},ID:function(a){return a[1].replace(W,"")},TAG:function(a){return a[1].replace(W,"").toLowerCase()},CHILD:function(a){if("nth"===
a[1]){a[2]||p.error(a[0]);a[2]=a[2].replace(/^\+|\s*/g,"");var b=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===a[2]&&"2n"||"odd"===a[2]&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}else a[2]&&p.error(a[0]);a[0]=Ka++;return a},ATTR:function(a,b,c,d,f,g){b=a[1]=a[1].replace(W,"");!g&&r.attrMap[b]&&(a[1]=r.attrMap[b]);a[4]=(a[4]||a[5]||"").replace(W,"");"~="===a[2]&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(a,b,c,d,f){if("not"===a[1])if(1<(Ja.exec(a[3])||"").length||
/^\w/.test(a[3]))a[3]=p(a[3],null,null,b);else return a=p.filter(a[3],b,c,1^f),c||d.push.apply(d,a),!1;else if(r.match.POS.test(a[0])||r.match.CHILD.test(a[0]))return!0;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return!1===a.disabled&&"hidden"!==a.type},disabled:function(a){return!0===a.disabled},checked:function(a){return!0===a.checked},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!!a.firstChild},
empty:function(a){return!a.firstChild},has:function(a,b,c){return!!p(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){var b=a.getAttribute("type"),c=a.type;return"input"===a.nodeName.toLowerCase()&&"text"===c&&(b===c||null===b)},radio:function(a){return"input"===a.nodeName.toLowerCase()&&"radio"===a.type},checkbox:function(a){return"input"===a.nodeName.toLowerCase()&&"checkbox"===a.type},file:function(a){return"input"===a.nodeName.toLowerCase()&&"file"===a.type},
password:function(a){return"input"===a.nodeName.toLowerCase()&&"password"===a.type},submit:function(a){var b=a.nodeName.toLowerCase();return("input"===b||"button"===b)&&"submit"===a.type},image:function(a){return"input"===a.nodeName.toLowerCase()&&"image"===a.type},reset:function(a){var b=a.nodeName.toLowerCase();return("input"===b||"button"===b)&&"reset"===a.type},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)},
focus:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b){return 0===b},last:function(a,b,c,d){return b===d.length-1},even:function(a,b){return 0===b%2},odd:function(a,b){return 1===b%2},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-0===b}},filter:{PSEUDO:function(a,b,c,d){var f=b[1],g=r.filters[f];if(g)return g(a,c,b,d);if("contains"===f)return 0<=(a.textContent||a.innerText||
La([a])||"").indexOf(b[3]);if("not"===f){b=b[3];c=0;for(d=b.length;c<d;c++)if(b[c]===a)return!1;return!0}p.error(f)},CHILD:function(a,b){var c,d,f,g,i,h;c=b[1];h=a;switch(c){case "only":case "first":for(;h=h.previousSibling;)if(1===h.nodeType)return!1;if("first"===c)return!0;h=a;case "last":for(;h=h.nextSibling;)if(1===h.nodeType)return!1;return!0;case "nth":c=b[2];d=b[3];if(1===c&&0===d)return!0;f=b[0];if((g=a.parentNode)&&(g[V]!==f||!a.nodeIndex)){i=0;for(h=g.firstChild;h;h=h.nextSibling)1===h.nodeType&&
(h.nodeIndex=++i);g[V]=f}h=a.nodeIndex-d;return 0===c?0===h:0===h%c&&0<=h/c}},ID:function(a,b){return 1===a.nodeType&&a.getAttribute("id")===b},TAG:function(a,b){return"*"===b&&1===a.nodeType||!!a.nodeName&&a.nodeName.toLowerCase()===b},CLASS:function(a,b){return-1<(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)},ATTR:function(a,b){var c=b[1],c=p.attr?p.attr(a,c):r.attrHandle[c]?r.attrHandle[c](a):null!=a[c]?a[c]:a.getAttribute(c),d=c+"",f=b[2],g=b[4];return null==c?"!="===f:!f&&p.attr?
null!=c:"="===f?d===g:"*="===f?0<=d.indexOf(g):"~="===f?0<=(" "+d+" ").indexOf(g):!g?d&&!1!==c:"!="===f?d!==g:"^="===f?0===d.indexOf(g):"$="===f?d.substr(d.length-g.length)===g:"|="===f?d===g||d.substr(0,g.length+1)===g+"-":!1},POS:function(a,b,c,d){var f=r.setFilters[b[2]];if(f)return f(a,c,b,d)}}},Fb=r.match.POS,Gc=function(a,b){return"\\"+(b-0+1)},aa;for(aa in r.match)r.match[aa]=RegExp(r.match[aa].source+/(?![^\[]*\])(?![^\(]*\))/.source),r.leftMatch[aa]=RegExp(/(^(?:.|\r|\n)*?)/.source+r.match[aa].source.replace(/\\(\d+)/g,
Gc));r.match.globalPOS=Fb;var y=function(a,b){a=Array.prototype.slice.call(a,0);return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(m.documentElement.childNodes,0)[0].nodeType}catch(nd){y=function(a,b){var c=0,d=b||[];if("[object Array]"===Db.call(a))Array.prototype.push.apply(d,a);else if("number"===typeof a.length)for(var f=a.length;c<f;c++)d.push(a[c]);else for(;a[c];c++)d.push(a[c]);return d}}var pa,ba;m.documentElement.compareDocumentPosition?pa=function(a,b){return a===b?(na=!0,
0):!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1}:(pa=function(a,b){if(a===b)return na=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,d,f=[],g=[];c=a.parentNode;d=b.parentNode;var i=c;if(c===d)return ba(a,b);if(c){if(!d)return 1}else return-1;for(;i;)f.unshift(i),i=i.parentNode;for(i=d;i;)g.unshift(i),i=i.parentNode;c=f.length;d=g.length;for(i=0;i<c&&i<d;i++)if(f[i]!==g[i])return ba(f[i],g[i]);
return i===c?ba(a,g[i],-1):ba(f[i],b,1)},ba=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});var qa=m.createElement("div"),Hb="script"+(new Date).getTime(),ra=m.documentElement;qa.innerHTML="<a name='"+Hb+"'/>";ra.insertBefore(qa,ra.firstChild);m.getElementById(Hb)&&(r.find.ID=function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(b=b.getElementById(a[1]))?b.id===a[1]||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").nodeValue===
a[1]?[b]:j:[]},r.filter.ID=function(a,b){var c="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id");return 1===a.nodeType&&c&&c.nodeValue===b});ra.removeChild(qa);var ra=qa=null,H=m.createElement("div");H.appendChild(m.createComment(""));0<H.getElementsByTagName("*").length&&(r.find.TAG=function(a,b){var c=b.getElementsByTagName(a[1]);if("*"===a[1]){for(var d=[],f=0;c[f];f++)1===c[f].nodeType&&d.push(c[f]);c=d}return c});H.innerHTML="<a href='#'></a>";H.firstChild&&("undefined"!==typeof H.firstChild.getAttribute&&
"#"!==H.firstChild.getAttribute("href"))&&(r.attrHandle.href=function(a){return a.getAttribute("href",2)});H=null;if(m.querySelectorAll){var Ma=p,sa=m.createElement("div");sa.innerHTML="<p class='TEST'></p>";if(!(sa.querySelectorAll&&0===sa.querySelectorAll(".TEST").length)){var p=function(a,b,c,d){b=b||m;if(!d&&!p.isXML(b)){var f=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(a);if(f&&(1===b.nodeType||9===b.nodeType)){if(f[1])return y(b.getElementsByTagName(a),c);if(f[2]&&r.find.CLASS&&b.getElementsByClassName)return y(b.getElementsByClassName(f[2]),
c)}if(9===b.nodeType){if("body"===a&&b.body)return y([b.body],c);if(f&&f[3]){var g=b.getElementById(f[3]);if(g&&g.parentNode){if(g.id===f[3])return y([g],c)}else return y([],c)}try{return y(b.querySelectorAll(a),c)}catch(i){}}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var f=b,h=(g=b.getAttribute("id"))||"__sizzle__",k=b.parentNode,n=/^\s*[+~]/.test(a);g?h=h.replace(/'/g,"\\$&"):b.setAttribute("id",h);n&&k&&(b=b.parentNode);try{if(!n||k)return y(b.querySelectorAll("[id='"+h+"'] "+
a),c)}catch(j){}finally{g||f.removeAttribute("id")}}}return Ma(a,b,c,d)},Na;for(Na in Ma)p[Na]=Ma[Na];sa=null}}var ta=m.documentElement,ua=ta.matchesSelector||ta.mozMatchesSelector||ta.webkitMatchesSelector||ta.msMatchesSelector;if(ua){var Hc=!ua.call(m.createElement("div"),"div"),Ib=!1;try{ua.call(m.documentElement,"[test!='']:sizzle")}catch(od){Ib=!0}p.matchesSelector=function(a,b){b=b.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!p.isXML(a))try{if(Ib||!r.match.PSEUDO.test(b)&&!/!=/.test(b)){var c=
ua.call(a,b);if(c||!Hc||a.document&&11!==a.document.nodeType)return c}}catch(d){}return 0<p(b,null,null,[a]).length}}var X=m.createElement("div");X.innerHTML="<div class='test e'></div><div class='test'></div>";X.getElementsByClassName&&0!==X.getElementsByClassName("e").length&&(X.lastChild.className="e",1!==X.getElementsByClassName("e").length&&(r.order.splice(1,0,"CLASS"),r.find.CLASS=function(a,b,c){if("undefined"!==typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a[1])},X=null));
p.contains=m.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:m.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};p.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1};var Gb=function(a,b,c){for(var d,f=[],g="",b=b.nodeType?[b]:b;d=r.match.PSEUDO.exec(a);)g+=d[0],a=a.replace(r.match.PSEUDO,"");a=r.relative[a]?a+"*":a;d=0;for(var i=b.length;d<i;d++)p(a,b[d],
f,c);return p.filter(g,f)};p.attr=d.attr;p.selectors.attrMap={};d.find=p;d.expr=p.selectors;d.expr[":"]=d.expr.filters;d.unique=p.uniqueSort;d.text=p.getText;d.isXMLDoc=p.isXML;d.contains=p.contains;var Ic=/Until$/,Jc=/^(?:parents|prevUntil|prevAll)/,Kc=/,/,ac=/^.[^:#\[\.,]*$/,Lc=Array.prototype.slice,Jb=d.expr.match.globalPOS,Mc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({find:function(a){var b=this,c,e;if("string"!==typeof a)return d(a).filter(function(){c=0;for(e=b.length;c<e;c++)if(d.contains(b[c],
this))return!0});var f=this.pushStack("","find",a),g,i,h;c=0;for(e=this.length;c<e;c++)if(g=f.length,d.find(a,this[c],f),0<c)for(i=g;i<f.length;i++)for(h=0;h<g;h++)if(f[h]===f[i]){f.splice(i--,1);break}return f},has:function(a){var b=d(a);return this.filter(function(){for(var a=0,e=b.length;a<e;a++)if(d.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(Va(this,a,!1),"not",a)},filter:function(a){return this.pushStack(Va(this,a,!0),"filter",a)},is:function(a){return!!a&&("string"===
typeof a?Jb.test(a)?0<=d(a,this.context).index(this[0]):0<d.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){var c=[],e,f,g=this[0];if(d.isArray(a)){for(f=1;g&&g.ownerDocument&&g!==b;){for(e=0;e<a.length;e++)d(g).is(a[e])&&c.push({selector:a[e],elem:g,level:f});g=g.parentNode;f++}return c}var i=Jb.test(a)||"string"!==typeof a?d(a,b||this.context):0;e=0;for(f=this.length;e<f;e++)for(g=this[e];g;)if(i?-1<i.index(g):d.find.matchesSelector(g,a)){c.push(g);break}else if(g=g.parentNode,
!g||!g.ownerDocument||g===b||11===g.nodeType)break;c=1<c.length?d.unique(c):c;return this.pushStack(c,"closest",a)},index:function(a){return!a?this[0]&&this[0].parentNode?this.prevAll().length:-1:"string"===typeof a?d.inArray(this[0],d(a)):d.inArray(a.jquery?a[0]:a,this)},add:function(a,b){var c="string"===typeof a?d(a,b):d.makeArray(a&&a.nodeType?[a]:a),e=d.merge(this.get(),c);return this.pushStack(!c[0]||!c[0].parentNode||11===c[0].parentNode.nodeType||!e[0]||!e[0].parentNode||11===e[0].parentNode.nodeType?
e:d.unique(e))},andSelf:function(){return this.add(this.prevObject)}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return d.dir(a,"parentNode")},parentsUntil:function(a,b,c){return d.dir(a,"parentNode",c)},next:function(a){return d.nth(a,2,"nextSibling")},prev:function(a){return d.nth(a,2,"previousSibling")},nextAll:function(a){return d.dir(a,"nextSibling")},prevAll:function(a){return d.dir(a,"previousSibling")},nextUntil:function(a,b,c){return d.dir(a,
"nextSibling",c)},prevUntil:function(a,b,c){return d.dir(a,"previousSibling",c)},siblings:function(a){return d.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return d.sibling(a.firstChild)},contents:function(a){return d.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:d.makeArray(a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);Ic.test(a)||(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));f=1<this.length&&!Mc[a]?d.unique(f):f;if((1<this.length||
Kc.test(e))&&Jc.test(a))f=f.reverse();return this.pushStack(f,a,Lc.call(arguments).join(","))}});d.extend({filter:function(a,b,c){c&&(a=":not("+a+")");return 1===b.length?d.find.matchesSelector(b[0],a)?[b[0]]:[]:d.find.matches(a,b)},dir:function(a,b,c){for(var e=[],a=a[b];a&&9!==a.nodeType&&(c===j||1!==a.nodeType||!d(a).is(c));)1===a.nodeType&&e.push(a),a=a[b];return e},nth:function(a,b,c){for(var b=b||1,d=0;a&&!(1===a.nodeType&&++d===b);a=a[c]);return a},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===
a.nodeType&&a!==b&&c.push(a);return c}});var Xa="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",Nc=/ jQuery\d+="(?:\d+|null)"/g,Oa=/^\s+/,Kb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Lb=/<([\w:]+)/,Oc=/<tbody/i,Pc=/<|&#?\w+;/,Qc=/<(?:script|style)/i,Rc=/<(?:script|object|embed|option|style)/i,Mb=RegExp("<(?:"+Xa+")[\\s/>]","i"),Nb=/checked\s*(?:[^=]|=\s*.checked.)/i,
Ob=/\/(java|ecma)script/i,Sc=/^\s*<!(?:\[CDATA\[|\-\-)/,A={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]},Pa=Wa(m);A.optgroup=A.option;A.tbody=A.tfoot=A.colgroup=A.caption=A.thead;A.th=A.td;d.support.htmlSerialize||(A._default=
[1,"div<div>","</div>"]);d.fn.extend({text:function(a){return d.access(this,function(a){return a===j?d.text(this):this.empty().append((this[0]&&this[0].ownerDocument||m).createTextNode(a))},null,a,arguments.length)},wrapAll:function(a){if(d.isFunction(a))return this.each(function(b){d(this).wrapAll(a.call(this,b))});if(this[0]){var b=d(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;
return a}).append(this)}return this},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
!0,function(a){1===this.nodeType&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this)});if(arguments.length){var a=d.clean(arguments);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
!1,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,d.clean(arguments));return a}},remove:function(a,b){for(var c=0,e;null!=(e=this[c]);c++)if(!a||d.filter(a,[e]).length)!b&&1===e.nodeType&&(d.cleanData(e.getElementsByTagName("*")),d.cleanData([e])),e.parentNode&&e.parentNode.removeChild(e);return this},empty:function(){for(var a=0,b;null!=(b=this[a]);a++)for(1===b.nodeType&&d.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,b)})},html:function(a){return d.access(this,function(a){var c=this[0]||{},e=0,f=this.length;if(a===j)return 1===c.nodeType?c.innerHTML.replace(Nc,""):null;if("string"===typeof a&&!Qc.test(a)&&(d.support.leadingWhitespace||!Oa.test(a))&&!A[(Lb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Kb,"<$1></$2>");try{for(;e<f;e++)c=this[e]||{},1===c.nodeType&&(d.cleanData(c.getElementsByTagName("*")),
c.innerHTML=a);c=0}catch(g){}}c&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(d.isFunction(a))return this.each(function(b){var c=d(this),e=c.html();c.replaceWith(a.call(this,b,e))});"string"!==typeof a&&(a=d(a).detach());return this.each(function(){var b=this.nextSibling,c=this.parentNode;d(this).remove();b?d(b).before(a):d(c).append(a)})}return this.length?this.pushStack(d(d.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,
!0)},domManip:function(a,b,c){var e,f,g,i=a[0],h=[];if(!d.support.checkClone&&3===arguments.length&&"string"===typeof i&&Nb.test(i))return this.each(function(){d(this).domManip(a,b,c,!0)});if(d.isFunction(i))return this.each(function(e){var f=d(this);a[0]=i.call(this,e,b?f.html():j);f.domManip(a,b,c)});if(this[0]){e=i&&i.parentNode;e=d.support.parentNode&&e&&11===e.nodeType&&e.childNodes.length===this.length?{fragment:e}:d.buildFragment(a,this,h);g=e.fragment;if(f=1===g.childNodes.length?g=g.firstChild:
g.firstChild){b=b&&d.nodeName(f,"tr");f=0;for(var k=this.length,n=k-1;f<k;f++)c.call(b?d.nodeName(this[f],"table")?this[f].getElementsByTagName("tbody")[0]||this[f].appendChild(this[f].ownerDocument.createElement("tbody")):this[f]:this[f],e.cacheable||1<k&&f<n?d.clone(g,!0,!0):g)}h.length&&d.each(h,function(a,b){b.src?d.ajax({type:"GET",global:!1,url:b.src,async:!1,dataType:"script"}):d.globalEval((b.text||b.textContent||b.innerHTML||"").replace(Sc,"/*$0*/"));b.parentNode&&b.parentNode.removeChild(b)})}return this}});
d.buildFragment=function(a,b,c){var e,f,g,i,h=a[0];b&&b[0]&&(i=b[0].ownerDocument||b[0]);i.createDocumentFragment||(i=m);if(1===a.length&&"string"===typeof h&&512>h.length&&i===m&&"<"===h.charAt(0)&&!Rc.test(h)&&(d.support.checkClone||!Nb.test(h))&&(d.support.html5Clone||!Mb.test(h)))f=!0,(g=d.fragments[h])&&1!==g&&(e=g);e||(e=i.createDocumentFragment(),d.clean(a,i,e,c));f&&(d.fragments[h]=g?e:1);return{fragment:e,cacheable:f}};d.fragments={};d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",
insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(c){var e=[],c=d(c),f=1===this.length&&this[0].parentNode;if(f&&11===f.nodeType&&1===f.childNodes.length&&1===c.length)return c[b](this[0]),this;for(var f=0,g=c.length;f<g;f++){var i=(0<f?this.clone(!0):this).get();d(c[f])[b](i);e=e.concat(i)}return this.pushStack(e,a,c.selector)}});d.extend({clone:function(a,b,c){var e,f,g;d.support.html5Clone||d.isXMLDoc(a)||!Mb.test("<"+a.nodeName+">")?e=a.cloneNode(!0):(e=m.createElement("div"),
Pa.appendChild(e),e.innerHTML=a.outerHTML,e=e.firstChild);var i=e;if((!d.support.noCloneEvent||!d.support.noCloneChecked)&&(1===a.nodeType||11===a.nodeType)&&!d.isXMLDoc(a)){Za(a,i);e=da(a);f=da(i);for(g=0;e[g];++g)f[g]&&Za(e[g],f[g])}if(b&&(Ya(a,i),c)){e=da(a);f=da(i);for(g=0;e[g];++g)Ya(e[g],f[g])}return i},clean:function(a,b,c,e){var f,g=[],b=b||m;"undefined"===typeof b.createElement&&(b=b.ownerDocument||b[0]&&b[0].ownerDocument||m);for(var i=0,h;null!=(h=a[i]);i++)if("number"===typeof h&&(h+=
""),h){if("string"===typeof h)if(Pc.test(h)){h=h.replace(Kb,"<$1></$2>");f=(Lb.exec(h)||["",""])[1].toLowerCase();var k=A[f]||A._default,n=k[0],j=b.createElement("div"),l=Pa.childNodes;b===m?Pa.appendChild(j):Wa(b).appendChild(j);for(j.innerHTML=k[1]+h+k[2];n--;)j=j.lastChild;if(!d.support.tbody){n=Oc.test(h);k="table"===f&&!n?j.firstChild&&j.firstChild.childNodes:"<table>"===k[1]&&!n?j.childNodes:[];for(f=k.length-1;0<=f;--f)d.nodeName(k[f],"tbody")&&!k[f].childNodes.length&&k[f].parentNode.removeChild(k[f])}!d.support.leadingWhitespace&&
Oa.test(h)&&j.insertBefore(b.createTextNode(Oa.exec(h)[0]),j.firstChild);h=j.childNodes;j&&(j.parentNode.removeChild(j),0<l.length&&(j=l[l.length-1])&&j.parentNode&&j.parentNode.removeChild(j))}else h=b.createTextNode(h);var p;if(!d.support.appendChecked)if(h[0]&&"number"===typeof(p=h.length))for(f=0;f<p;f++)ab(h[f]);else ab(h);h.nodeType?g.push(h):g=d.merge(g,h)}if(c){a=function(a){return!a.type||Ob.test(a.type)};for(i=0;g[i];i++)b=g[i],e&&d.nodeName(b,"script")&&(!b.type||Ob.test(b.type))?e.push(b.parentNode?
b.parentNode.removeChild(b):b):(1===b.nodeType&&(h=d.grep(b.getElementsByTagName("script"),a),g.splice.apply(g,[i+1,0].concat(h))),c.appendChild(b))}return g},cleanData:function(a){for(var b,c,e=d.cache,f=d.event.special,g=d.support.deleteExpando,i=0,h;null!=(h=a[i]);i++)if(!h.nodeName||!d.noData[h.nodeName.toLowerCase()])if(c=h[d.expando]){if((b=e[c])&&b.events){for(var k in b.events)f[k]?d.event.remove(h,k):d.removeEvent(h,k,b.handle);b.handle&&(b.handle.elem=null)}g?delete h[d.expando]:h.removeAttribute&&
h.removeAttribute(d.expando);delete e[c]}}});var Qa=/alpha\([^)]*\)/i,Tc=/opacity=([^)]*)/,Uc=/([A-Z]|^ms)/g,Vc=/^[\-+]?(?:\d*\.)?\d+$/i,ya=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,Wc=/^([\-+])=([\-+.\de]+)/,Xc=/^margin/,Yc={position:"absolute",visibility:"hidden",display:"block"},J=["Top","Right","Bottom","Left"],K,Pb,Qb;d.fn.css=function(a,b){return d.access(this,function(a,b,f){return f!==j?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)};d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=
K(a,"opacity");return""===c?"1":c}return a.style.opacity}}},cssNumber:{fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":d.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,c,e){if(a&&!(3===a.nodeType||8===a.nodeType||!a.style)){var f,g=d.camelCase(b),i=a.style,h=d.cssHooks[g],b=d.cssProps[g]||g;if(c!==j){e=typeof c;if("string"===e&&(f=Wc.exec(c)))c=+(f[1]+1)*+f[2]+parseFloat(d.css(a,b)),e="number";if(!(null==c||"number"===e&&
isNaN(c)))if("number"===e&&!d.cssNumber[g]&&(c+="px"),!h||!("set"in h)||(c=h.set(a,c))!==j)try{i[b]=c}catch(k){}}else return h&&"get"in h&&(f=h.get(a,!1,e))!==j?f:i[b]}},css:function(a,b,c){var e,f,b=d.camelCase(b);f=d.cssHooks[b];b=d.cssProps[b]||b;"cssFloat"===b&&(b="float");if(f&&"get"in f&&(e=f.get(a,!0,c))!==j)return e;if(K)return K(a,b)},swap:function(a,b,c){var d={},f;for(f in b)d[f]=a.style[f],a.style[f]=b[f];c=c.call(a);for(f in b)a.style[f]=d[f];return c}});d.curCSS=d.css;m.defaultView&&
m.defaultView.getComputedStyle&&(Pb=function(a,b){var c,e,f,g=a.style,b=b.replace(Uc,"-$1").toLowerCase();if((e=a.ownerDocument.defaultView)&&(f=e.getComputedStyle(a,null)))c=f.getPropertyValue(b),""===c&&!d.contains(a.ownerDocument.documentElement,a)&&(c=d.style(a,b));!d.support.pixelMargin&&(f&&Xc.test(b)&&ya.test(c))&&(e=g.width,g.width=c,c=f.width,g.width=e);return c});m.documentElement.currentStyle&&(Qb=function(a,b){var c,d,f=a.currentStyle&&a.currentStyle[b],g=a.style;if(null==f&&g&&(c=g[b]))f=
c;if(ya.test(f)){c=g.left;if(d=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;g.left="fontSize"===b?"1em":f;f=g.pixelLeft+"px";g.left=c;d&&(a.runtimeStyle.left=d)}return""===f?"auto":f});K=Pb||Qb;d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){if(e)return 0!==a.offsetWidth?bb(a,b,f):d.swap(a,Yc,function(){return bb(a,b,f)})},set:function(a,b){return Vc.test(b)?b+"px":b}}});d.support.opacity||(d.cssHooks.opacity={get:function(a,b){return Tc.test((b&&
a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var c=a.style,e=a.currentStyle,f=d.isNumeric(b)?"alpha(opacity="+100*b+")":"",g=e&&e.filter||c.filter||"";c.zoom=1;if(1<=b&&""===d.trim(g.replace(Qa,""))&&(c.removeAttribute("filter"),e&&!e.filter))return;c.filter=Qa.test(g)?g.replace(Qa,f):g+" "+f}});d(function(){d.support.reliableMarginRight||(d.cssHooks.marginRight={get:function(a,b){return d.swap(a,{display:"inline-block"},function(){return b?
K(a,"margin-right"):a.style.marginRight})}})});d.expr&&d.expr.filters&&(d.expr.filters.hidden=function(a){var b=a.offsetHeight;return 0===a.offsetWidth&&0===b||!d.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||d.css(a,"display"))},d.expr.filters.visible=function(a){return!d.expr.filters.hidden(a)});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){for(var d="string"===typeof c?c.split(" "):[c],f={},c=0;4>c;c++)f[a+J[c]+b]=d[c]||d[c-
2]||d[0];return f}}});var Zc=/%20/g,bc=/\[\]$/,Rb=/\r?\n/g,$c=/#.*$/,ad=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,bd=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,cd=/^(?:GET|HEAD)$/,dd=/^\/\//,Sb=/\?/,ed=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,fd=/^(?:select|textarea)/i,db=/\s+/,gd=/([?&])_=[^&]*/,Tb=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,Ub=d.fn.load,za={},Vb={},L,I,Wb=["*/"]+["*"];try{L=dc.href}catch(pd){L=m.createElement("a"),
L.href="",L=L.href}I=Tb.exec(L.toLowerCase())||[];d.fn.extend({load:function(a,b,c){if("string"!==typeof a&&Ub)return Ub.apply(this,arguments);if(!this.length)return this;var e=a.indexOf(" ");if(0<=e)var f=a.slice(e,a.length),a=a.slice(0,e);e="GET";b&&(d.isFunction(b)?(c=b,b=j):"object"===typeof b&&(b=d.param(b,d.ajaxSettings.traditional),e="POST"));var g=this;d.ajax({url:a,type:e,dataType:"html",data:b,complete:function(a,b,e){e=a.responseText;a.isResolved()&&(a.done(function(a){e=a}),g.html(f?d("<div>").append(e.replace(ed,
"")).find(f):e));c&&g.each(c,[e,b,a])}});return this},serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?d.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||fd.test(this.nodeName)||bd.test(this.type))}).map(function(a,b){var c=d(this).val();return null==c?null:d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Rb,"\r\n")}}):{name:b.name,value:c.replace(Rb,
"\r\n")}}).get()}});d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){d.isFunction(e)&&(g=g||f,f=e,e=j);return d.ajax({type:b,url:a,data:e,success:f,dataType:g})}});d.extend({getScript:function(a,b){return d.get(a,j,b,"script")},getJSON:function(a,b,c){return d.get(a,b,c,"json")},ajaxSetup:function(a,b){b?eb(a,d.ajaxSettings):(b=a,a=d.ajaxSettings);eb(a,
b);return a},ajaxSettings:{url:L,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(I[1]),global:!0,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",processData:!0,async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":Wb},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":s.String,"text html":!0,"text json":d.parseJSON,
"text xml":d.parseXML},flatOptions:{context:!0,url:!0}},ajaxPrefilter:cb(za),ajaxTransport:cb(Vb),ajax:function(a,b){function c(a,b,c,l){if(2!==w){w=2;s&&clearTimeout(s);r=j;p=l||"";v.readyState=0<a?4:0;var m,t,q,l=b;if(c){var u=e,N=v,y=u.contents,x=u.dataTypes,rb=u.responseFields,C,B,z,D;for(B in rb)B in c&&(N[rb[B]]=c[B]);for(;"*"===x[0];)x.shift(),C===j&&(C=u.mimeType||N.getResponseHeader("content-type"));if(C)for(B in y)if(y[B]&&y[B].test(C)){x.unshift(B);break}if(x[0]in c)z=x[0];else{for(B in c){if(!x[0]||
u.converters[B+" "+x[0]]){z=B;break}D||(D=B)}z=z||D}z?(z!==x[0]&&x.unshift(z),c=c[z]):c=void 0}else c=j;if(200<=a&&300>a||304===a){if(e.ifModified){if(C=v.getResponseHeader("Last-Modified"))d.lastModified[n]=C;if(C=v.getResponseHeader("Etag"))d.etag[n]=C}if(304===a)l="notmodified",m=!0;else try{C=e;C.dataFilter&&(c=C.dataFilter(c,C.dataType));var J=C.dataTypes;B={};var G,H,L=J.length,I,O=J[0],E,K,P,Q,F;for(G=1;G<L;G++){if(1===G)for(H in C.converters)"string"===typeof H&&(B[H.toLowerCase()]=C.converters[H]);
E=O;O=J[G];if("*"===O)O=E;else if("*"!==E&&E!==O){K=E+" "+O;P=B[K]||B["* "+O];if(!P)for(Q in F=j,B)if(I=Q.split(" "),I[0]===E||"*"===I[0])if(F=B[I[1]+" "+O]){Q=B[Q];!0===Q?P=F:!0===F&&(P=Q);break}!P&&!F&&d.error("No conversion from "+K.replace(" "," to "));!0!==P&&(c=P?P(c):F(Q(c)))}}t=c;l="success";m=!0}catch(M){l="parsererror",q=M}}else if(q=l,!l||a)l="error",0>a&&(a=0);v.status=a;v.statusText=""+(b||l);m?i.resolveWith(f,[t,l,v]):i.rejectWith(f,[v,l,q]);v.statusCode(k);k=j;A&&g.trigger("ajax"+(m?
"Success":"Error"),[v,e,m?t:q]);h.fireWith(f,[v,l]);A&&(g.trigger("ajaxComplete",[v,e]),--d.active||d.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=j);var b=b||{},e=d.ajaxSetup({},b),f=e.context||e,g=f!==e&&(f.nodeType||f instanceof d)?d(f):d.event,i=d.Deferred(),h=d.Callbacks("once memory"),k=e.statusCode||{},n,l={},m={},p,q,r,s,u,w=0,A,y,v={readyState:0,setRequestHeader:function(a,b){if(!w){var c=a.toLowerCase(),a=m[c]=m[c]||a;l[a]=b}return this},getAllResponseHeaders:function(){return 2===
w?p:null},getResponseHeader:function(a){var b;if(2===w){if(!q)for(q={};b=ad.exec(p);)q[b[1].toLowerCase()]=b[2];b=q[a.toLowerCase()]}return b===j?null:b},overrideMimeType:function(a){w||(e.mimeType=a);return this},abort:function(a){a=a||"abort";r&&r.abort(a);c(0,a);return this}};i.promise(v);v.success=v.done;v.error=v.fail;v.complete=h.add;v.statusCode=function(a){if(a){var b;if(2>w)for(b in a)k[b]=[k[b],a[b]];else b=a[v.status],v.then(b,b)}return this};e.url=((a||e.url)+"").replace($c,"").replace(dd,
I[1]+"//");e.dataTypes=d.trim(e.dataType||"*").toLowerCase().split(db);null==e.crossDomain&&(u=Tb.exec(e.url.toLowerCase()),e.crossDomain=!(!u||!(u[1]!=I[1]||u[2]!=I[2]||(u[3]||("http:"===u[1]?80:443))!=(I[3]||("http:"===I[1]?80:443)))));e.data&&(e.processData&&"string"!==typeof e.data)&&(e.data=d.param(e.data,e.traditional));ea(za,e,b,v);if(2===w)return!1;A=e.global;e.type=e.type.toUpperCase();e.hasContent=!cd.test(e.type);A&&0===d.active++&&d.event.trigger("ajaxStart");if(!e.hasContent&&(e.data&&
(e.url+=(Sb.test(e.url)?"&":"?")+e.data,delete e.data),n=e.url,!1===e.cache)){u=d.now();var x=e.url.replace(gd,"$1_="+u);e.url=x+(x===e.url?(Sb.test(e.url)?"&":"?")+"_="+u:"")}(e.data&&e.hasContent&&!1!==e.contentType||b.contentType)&&v.setRequestHeader("Content-Type",e.contentType);e.ifModified&&(n=n||e.url,d.lastModified[n]&&v.setRequestHeader("If-Modified-Since",d.lastModified[n]),d.etag[n]&&v.setRequestHeader("If-None-Match",d.etag[n]));v.setRequestHeader("Accept",e.dataTypes[0]&&e.accepts[e.dataTypes[0]]?
e.accepts[e.dataTypes[0]]+("*"!==e.dataTypes[0]?", "+Wb+"; q=0.01":""):e.accepts["*"]);for(y in e.headers)v.setRequestHeader(y,e.headers[y]);if(e.beforeSend&&(!1===e.beforeSend.call(f,v,e)||2===w))return v.abort(),!1;for(y in{success:1,error:1,complete:1})v[y](e[y]);if(r=ea(Vb,e,b,v)){v.readyState=1;A&&g.trigger("ajaxSend",[v,e]);e.async&&0<e.timeout&&(s=setTimeout(function(){v.abort("timeout")},e.timeout));try{w=1,r.send(l,c)}catch(z){if(2>w)c(-1,z);else throw z;}}else c(-1,"No Transport");return v},
param:function(a,b){var c=[],e=function(a,b){b=d.isFunction(b)?b():b;c[c.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};b===j&&(b=d.ajaxSettings.traditional);if(d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){e(this.name,this.value)});else for(var f in a)Aa(f,a[f],b,e);return c.join("&").replace(Zc,"+")}});d.extend({active:0,lastModified:{},etag:{}});var hd=d.now(),va=/(\=)\?(&|$)|\?\?/i;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){return d.expando+"_"+hd++}});
d.ajaxPrefilter("json jsonp",function(a,b,c){b="string"===typeof a.data&&/^application\/x\-www\-form\-urlencoded/.test(a.contentType);if("jsonp"===a.dataTypes[0]||!1!==a.jsonp&&(va.test(a.url)||b&&va.test(a.data))){var e,f=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,g=s[f],i=a.url,h=a.data,k="$1"+f+"$2";!1!==a.jsonp&&(i=i.replace(va,k),a.url===i&&(b&&(h=h.replace(va,k)),a.data===h&&(i+=(/\?/.test(i)?"&":"?")+a.jsonp+"="+f)));a.url=i;a.data=h;s[f]=function(a){e=
[a]};c.always(function(){s[f]=g;if(e&&d.isFunction(g))s[f](e[0])});a.converters["script json"]=function(){e||d.error(f+" was not called");return e[0]};a.dataTypes[0]="json";return"script"}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){d.globalEval(a);return a}}});d.ajaxPrefilter("script",function(a){a.cache===j&&(a.cache=!1);a.crossDomain&&(a.type=
"GET",a.global=!1)});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c=m.head||m.getElementsByTagName("head")[0]||m.documentElement;return{send:function(d,f){b=m.createElement("script");b.async="async";a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(a,d){if(d||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,c&&b.parentNode&&c.removeChild(b),b=j,d||f(200,"success")};c.insertBefore(b,c.firstChild)},abort:function(){if(b)b.onload(0,
1)}}}});var Ra=s.ActiveXObject?function(){for(var a in Y)Y[a](0,1)}:!1,id=0,Y;d.ajaxSettings.xhr=s.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&fb()))a:{try{a=new s.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:fb;var Sa=d.ajaxSettings.xhr();d.extend(d.support,{ajax:!!Sa,cors:!!Sa&&"withCredentials"in Sa});d.support.ajax&&d.ajaxTransport(function(a){if(!a.crossDomain||d.support.cors){var b;return{send:function(c,e){var f=a.xhr(),g,i;a.username?f.open(a.type,a.url,
a.async,a.username,a.password):f.open(a.type,a.url,a.async);if(a.xhrFields)for(i in a.xhrFields)f[i]=a.xhrFields[i];a.mimeType&&f.overrideMimeType&&f.overrideMimeType(a.mimeType);!a.crossDomain&&!c["X-Requested-With"]&&(c["X-Requested-With"]="XMLHttpRequest");try{for(i in c)f.setRequestHeader(i,c[i])}catch(h){}f.send(a.hasContent&&a.data||null);b=function(c,h){var i,l,m,p,q;try{if(b&&(h||4===f.readyState))if(b=j,g&&(f.onreadystatechange=d.noop,Ra&&delete Y[g]),h)4!==f.readyState&&f.abort();else{i=
f.status;m=f.getAllResponseHeaders();p={};if((q=f.responseXML)&&q.documentElement)p.xml=q;try{p.text=f.responseText}catch(r){}try{l=f.statusText}catch(s){l=""}!i&&a.isLocal&&!a.crossDomain?i=p.text?200:404:1223===i&&(i=204)}}catch(u){h||e(-1,u)}p&&e(i,l,p,m)};!a.async||4===f.readyState?b():(g=++id,Ra&&(Y||(Y={},d(s).unload(Ra)),Y[g]=b),f.onreadystatechange=b)},abort:function(){b&&b(0,1)}}}});var Ba={},x,M,jd=/^(?:toggle|show|hide)$/,kd=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,wa,ga=[["height","marginTop",
"marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]],fa;d.fn.extend({show:function(a,b,c){if(a||0===a)return this.animate(F("show",3),a,b,c);for(var c=0,e=this.length;c<e;c++)a=this[c],a.style&&(b=a.style.display,!d._data(a,"olddisplay")&&"none"===b&&(b=a.style.display=""),(""===b&&"none"===d.css(a,"display")||!d.contains(a.ownerDocument.documentElement,a))&&d._data(a,"olddisplay",hb(a.nodeName)));for(c=0;c<e;c++)if(a=this[c],
a.style&&(b=a.style.display,""===b||"none"===b))a.style.display=d._data(a,"olddisplay")||"";return this},hide:function(a,b,c){if(a||0===a)return this.animate(F("hide",3),a,b,c);for(var c=0,e=this.length;c<e;c++)a=this[c],a.style&&(b=d.css(a,"display"),"none"!==b&&!d._data(a,"olddisplay")&&d._data(a,"olddisplay",b));for(c=0;c<e;c++)this[c].style&&(this[c].style.display="none");return this},_toggle:d.fn.toggle,toggle:function(a,b,c){var e="boolean"===typeof a;d.isFunction(a)&&d.isFunction(b)?this._toggle.apply(this,
arguments):null==a||e?this.each(function(){var b=e?a:d(this).is(":hidden");d(this)[b?"show":"hide"]()}):this.animate(F("toggle",3),a,b,c);return this},fadeTo:function(a,b,c,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){function f(){!1===g.queue&&d._mark(this);var b=d.extend({},g),c=1===this.nodeType,e=c&&d(this).is(":hidden"),f,j,l,m,p;b.animatedProperties={};for(l in a)if(f=d.camelCase(l),l!==f&&(a[f]=a[l],delete a[l]),(j=d.cssHooks[f])&&
"expand"in j)for(l in m=j.expand(a[f]),delete a[f],m)l in a||(a[l]=m[l]);for(f in a){j=a[f];d.isArray(j)?(b.animatedProperties[f]=j[1],j=a[f]=j[0]):b.animatedProperties[f]=b.specialEasing&&b.specialEasing[f]||b.easing||"swing";if("hide"===j&&e||"show"===j&&!e)return b.complete.call(this);if(c&&("height"===f||"width"===f))b.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY],"inline"===d.css(this,"display")&&"none"===d.css(this,"float")&&(!d.support.inlineBlockNeedsLayout||"inline"===
hb(this.nodeName)?this.style.display="inline-block":this.style.zoom=1)}null!=b.overflow&&(this.style.overflow="hidden");for(l in a)if(c=new d.fx(this,b,l),j=a[l],jd.test(j))if(f=d._data(this,"toggle"+l)||("toggle"===j?e?"show":"hide":0))d._data(this,"toggle"+l,"show"===f?"hide":"show"),c[f]();else c[j]();else f=kd.exec(j),m=c.cur(),f?(j=parseFloat(f[2]),p=f[3]||(d.cssNumber[l]?"":"px"),"px"!==p&&(d.style(this,l,(j||1)+p),m*=(j||1)/c.cur(),d.style(this,l,m+p)),f[1]&&(j=("-="===f[1]?-1:1)*j+m),c.custom(m,
j,p)):c.custom(m,j,"");return!0}var g=d.speed(b,c,e);if(d.isEmptyObject(a))return this.each(g.complete,[!1]);a=d.extend({},a);return!1===g.queue?this.each(f):this.queue(g.queue,f)},stop:function(a,b,c){"string"!==typeof a&&(c=b,b=a,a=j);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b,f=!1,g=d.timers,i=d._data(this);c||d._unmark(!0,this);if(null==a)for(b in i){if(i[b]&&i[b].stop&&b.indexOf(".run")===b.length-4){var h=i[b];d.removeData(this,b,!0);h.stop(c)}}else if(i[b=a+".run"]&&
i[b].stop)i=i[b],d.removeData(this,b,!0),i.stop(c);for(b=g.length;b--;)if(g[b].elem===this&&(null==a||g[b].queue===a)){if(c)g[b](!0);else g[b].saveState();f=!0;g.splice(b,1)}(!c||!f)&&d.dequeue(this,a)})}});d.each({slideDown:F("show",1),slideUp:F("hide",1),slideToggle:F("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.extend({speed:function(a,b,c){var e=a&&"object"===typeof a?d.extend({},
a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};e.duration=d.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(a){d.isFunction(e.old)&&e.old.call(this);e.queue?d.dequeue(this,e.queue):!1!==a&&d._unmark(this)};return e},easing:{linear:function(a){return a},swing:function(a){return-Math.cos(a*Math.PI)/2+0.5}},
timers:[],fx:function(a,b,c){this.options=b;this.elem=a;this.prop=c;b.orig=b.orig||{}}});d.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(d.fx.step[this.prop]||d.fx.step._default)(this)},cur:function(){if(null!=this.elem[this.prop]&&(!this.elem.style||null==this.elem.style[this.prop]))return this.elem[this.prop];var a,b=d.css(this.elem,this.prop);return isNaN(a=parseFloat(b))?!b||"auto"===b?0:b:a},custom:function(a,b,c){function e(a){return f.step(a)}
var f=this,g=d.fx;this.startTime=fa||gb();this.end=b;this.now=this.start=a;this.pos=this.state=0;this.unit=c||this.unit||(d.cssNumber[this.prop]?"":"px");e.queue=this.options.queue;e.elem=this.elem;e.saveState=function(){d._data(f.elem,"fxshow"+f.prop)===j&&(f.options.hide?d._data(f.elem,"fxshow"+f.prop,f.start):f.options.show&&d._data(f.elem,"fxshow"+f.prop,f.end))};e()&&(d.timers.push(e)&&!wa)&&(wa=setInterval(g.tick,g.interval))},show:function(){var a=d._data(this.elem,"fxshow"+this.prop);this.options.orig[this.prop]=
a||d.style(this.elem,this.prop);this.options.show=!0;a!==j?this.custom(this.cur(),a):this.custom("width"===this.prop||"height"===this.prop?1:0,this.cur());d(this.elem).show()},hide:function(){this.options.orig[this.prop]=d._data(this.elem,"fxshow"+this.prop)||d.style(this.elem,this.prop);this.options.hide=!0;this.custom(this.cur(),0)},step:function(a){var b,c=fa||gb(),e=!0,f=this.elem,g=this.options;if(a||c>=g.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();g.animatedProperties[this.prop]=
!0;for(b in g.animatedProperties)!0!==g.animatedProperties[b]&&(e=!1);if(e){null!=g.overflow&&!d.support.shrinkWrapBlocks&&d.each(["","X","Y"],function(a,b){f.style["overflow"+b]=g.overflow[a]});g.hide&&d(f).hide();if(g.hide||g.show)for(b in g.animatedProperties)d.style(f,b,g.orig[b]),d.removeData(f,"fxshow"+b,!0),d.removeData(f,"toggle"+b,!0);if(a=g.complete)g.complete=!1,a.call(f)}return!1}Infinity==g.duration?this.now=c:(a=c-this.startTime,this.state=a/g.duration,this.pos=d.easing[g.animatedProperties[this.prop]](this.state,
a,0,1,g.duration),this.now=this.start+(this.end-this.start)*this.pos);this.update();return!0}};d.extend(d.fx,{tick:function(){for(var a,b=d.timers,c=0;c<b.length;c++)a=b[c],!a()&&b[c]===a&&b.splice(c--,1);b.length||d.fx.stop()},interval:13,stop:function(){clearInterval(wa);wa=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){d.style(a.elem,"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}}});
d.each(ga.concat.apply([],ga),function(a,b){b.indexOf("margin")&&(d.fx.step[b]=function(a){d.style(a.elem,b,Math.max(0,a.now)+a.unit)})});d.expr&&d.expr.filters&&(d.expr.filters.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length});var Xb,ld=/^t(?:able|d|h)$/i,Yb=/^(?:body|html)$/i;Xb="getBoundingClientRect"in m.documentElement?function(a,b,c,e){try{e=a.getBoundingClientRect()}catch(f){}if(!e||!d.contains(c,a))return e?{top:e.top,left:e.left}:{top:0,left:0};a=b.body;
b=ib(b);return{top:e.top+(b.pageYOffset||d.support.boxModel&&c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0),left:e.left+(b.pageXOffset||d.support.boxModel&&c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0)}}:function(a,b,c){var e,f=a.offsetParent,g=b.body;e=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var i=a.offsetTop,h=a.offsetLeft;(a=a.parentNode)&&(a!==g&&a!==c)&&!(d.support.fixedPosition&&"fixed"===e.position);){e=b?b.getComputedStyle(a,null):a.currentStyle;
i-=a.scrollTop;h-=a.scrollLeft;if(a===f){i+=a.offsetTop;h+=a.offsetLeft;if(d.support.doesNotAddBorder&&(!d.support.doesAddBorderForTableAndCells||!ld.test(a.nodeName)))i+=parseFloat(e.borderTopWidth)||0,h+=parseFloat(e.borderLeftWidth)||0;f=a.offsetParent}d.support.subtractsBorderForOverflowNotVisible&&"visible"!==e.overflow&&(i+=parseFloat(e.borderTopWidth)||0,h+=parseFloat(e.borderLeftWidth)||0)}if("relative"===e.position||"static"===e.position)i+=g.offsetTop,h+=g.offsetLeft;d.support.fixedPosition&&
"fixed"===e.position&&(i+=Math.max(c.scrollTop,g.scrollTop),h+=Math.max(c.scrollLeft,g.scrollLeft));return{top:i,left:h}};d.fn.offset=function(a){if(arguments.length)return a===j?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b=this[0],c=b&&b.ownerDocument;return!c?null:b===c.body?d.offset.bodyOffset(b):Xb(b,c,c.documentElement)};d.offset={bodyOffset:function(a){var b=a.offsetTop,c=a.offsetLeft;d.support.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(d.css(a,"marginTop"))||0,c+=parseFloat(d.css(a,
"marginLeft"))||0);return{top:b,left:c}},setOffset:function(a,b,c){var e=d.css(a,"position");"static"===e&&(a.style.position="relative");var f=d(a),g=f.offset(),i=d.css(a,"top"),h=d.css(a,"left"),k={},j={};("absolute"===e||"fixed"===e)&&-1<d.inArray("auto",[i,h])?(j=f.position(),e=j.top,h=j.left):(e=parseFloat(i)||0,h=parseFloat(h)||0);d.isFunction(b)&&(b=b.call(a,c,g));null!=b.top&&(k.top=b.top-g.top+e);null!=b.left&&(k.left=b.left-g.left+h);"using"in b?b.using.call(a,k):f.css(k)}};d.fn.extend({position:function(){if(!this[0])return null;
var a=this[0],b=this.offsetParent(),c=this.offset(),e=Yb.test(b[0].nodeName)?{top:0,left:0}:b.offset();c.top-=parseFloat(d.css(a,"marginTop"))||0;c.left-=parseFloat(d.css(a,"marginLeft"))||0;e.top+=parseFloat(d.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(d.css(b[0],"borderLeftWidth"))||0;return{top:c.top-e.top,left:c.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||m.body;a&&!Yb.test(a.nodeName)&&"static"===d.css(a,"position");)a=a.offsetParent;return a})}});
d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c=/Y/.test(b);d.fn[a]=function(e){return d.access(this,function(a,e,i){var h=ib(a);if(i===j)return h?b in h?h[b]:d.support.boxModel&&h.document.documentElement[e]||h.document.body[e]:a[e];h?h.scrollTo(!c?i:d(h).scrollLeft(),c?i:d(h).scrollTop()):a[e]=i},a,e,arguments.length,null)}});d.each({Height:"height",Width:"width"},function(a,b){var c="client"+a,e="scroll"+a,f="offset"+a;d.fn["inner"+a]=function(){var a=this[0];return a?
a.style?parseFloat(d.css(a,b,"padding")):this[b]():null};d.fn["outer"+a]=function(a){var c=this[0];return c?c.style?parseFloat(d.css(c,b,a?"margin":"border")):this[b]():null};d.fn[b]=function(a){return d.access(this,function(a,b,g){if(d.isWindow(a))return b=a.document,a=b.documentElement[c],d.support.boxModel&&a||b.body&&b.body[c]||a;if(9===a.nodeType)return b=a.documentElement,b[c]>=b[e]?b[c]:Math.max(a.body[e],b[e],a.body[f],b[f]);if(g===j)return a=d.css(a,b),b=parseFloat(a),d.isNumeric(b)?b:a;
d(a).css(b,g)},b,a,arguments.length,null)}});s.jQuery=s.$=d;"function"===typeof define&&(define.amd&&define.amd.jQuery)&&define("jquery",[],function(){return d})})(window);
