/*!
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */

(function(a){function v(){var b=[];a("#dir_choice option").each(function(){b.push(a(this).val())});a.ee_filebrowser.endpoint_request("directory_contents",{directory:b},function(){})}function l(b,c){b=b;if(isNaN(c))c=0;if(isNaN(b))n[b.id]=b;else{EE.dirs=n;b=n[b]}if(!(!b in h)){h[b.id]=b.files;o[b.id]=b.url;var d=m=="list"?p:q,g=b.files.length;a.each(b.files,function(w,i){i.img_id=w+"";i.directory=b.id+"";i.is_image=!(i.mime_type.indexOf("image")<0);if(i.is_image)i.thumb=b.url+"/_thumbs/thumb_"+i.file_name});
var e=a("#tableView").detach(),j=a("#viewSelectors").detach();e.find("tbody").empty();a("#file_chooser_body").empty().append(e);a("#file_chooser_footer").empty().append(j);e=Math.ceil(g/d);j=[];for(var f=0;f<e;f++)j[f]=f+1;c*=d;g={directory:b.id,pages_from:c+1,pages_to:c+d>g?g:c+d,pages_total:g,pages_current:Math.floor(c/d)+1,pages:j};e=b.files.slice(c,c+d);if(m!="list"){j=[];f=e.length;for(var r=0;r<d&&f;){f--;if(e[f].has_thumb){j.push(e[f]);r++}}a("#tableView").hide();a.tmpl("thumb",j).appendTo("#file_chooser_body");
a("a.file_chooser_thumbnail:nth-child(7n+2)").addClass("first");a("a.file_chooser_thumbnail:nth-child(7n+1)").addClass("last")}else{a("#tableView").show();a.tmpl("fileRow",e).appendTo("#tableView tbody")}a.tmpl("pagination",g).appendTo("#file_chooser_footer")}}function s(b){h[b]==""&&a.ee_filebrowser.endpoint_request("directory_contents",{directory:b},l)}function x(){k.dialog({width:730,height:495,resizable:false,position:["center","center"],modal:true,draggable:true,title:EE.filebrowser.window_title,
autoOpen:false,zIndex:99999,open:function(){var b=a("#dir_choice").val();s(b)}});m="list";a("input[name=view_type]").click(function(){m=this.value;l(a("#dir_choice").val(),0)});a("#dir_choice").change(function(){s(this.value);l(this.value,0)});a.template("fileRow",a("<tbody />").append(a("#rowTmpl").remove().attr("id","")));a.template("noFilesRow",a("#noFilesRowTmpl").remove());a.template("pagination",a("#paginationTmpl").remove());a.template("thumb",a("#thumbTmpl").remove());a("#upload_form",k).submit(a.ee_filebrowser.upload_start)}
var t=0,h,o,k,p,q,u,n={},m;a.ee_filebrowser=function(){p=10;q=21;a.ee_filebrowser.endpoint_request("setup",function(b){h={};o={};k=a(b.manager).appendTo(document.body);for(var c in b.directories){t||(t=c);h[c]=""}x();v()})};a.ee_filebrowser.endpoint_request=function(b,c,d){if(!d&&a.isFunction(c)){d=c;c={}}c=a.extend(c,{action:b});a.getJSON(EE.BASE+"&"+EE.filebrowser.endpoint_url+"&"+a.param(c),d)};a.ee_filebrowser.add_trigger=function(b,c,d){if(!d&&a.isFunction(c)){d=c;c="userfile"}a(b).click(function(){var g=
this;a("#upload_file",k).attr("name",c);k.dialog("open");u=function(e){d.call(g,e,c)};return false})};a.ee_filebrowser.change_dim=function(b,c){if(a("#cloned #constrain:checked").length!=0)if(c.attr("id")=="resize_width"){var d=b.height/b.width;a("#resize_height").val(Math.floor(d*c.val()))}else{d=b.width/b.height;a("#resize_width").val(Math.floor(d*c.val()))}};a.ee_filebrowser.submit_image_edit=function(b,c){a.ajax({type:"POST",url:EE.BASE+"&"+EE.filebrowser.endpoint_url+"&action=edit_image",data:a("#image_edit_form").serialize(),
success:function(d){b.file_name=d;b.dimensions='width="'+b.width+'" height="'+b.height+'" ';a.ee_filebrowser.clean_up(b,c)},error:function(d){if(a.ee_notice)a.ee_notice(d.responseText,{type:"error"});else{d.responseText=d.responseText.replace(/<p>/,"");alert(d.responseText.replace(/<\/p>/,""))}}})};a.ee_filebrowser.placeImage=function(b,c){console.log(h[b][c]);a.ee_filebrowser.clean_up(h[b][c],"");return false};a.ee_filebrowser.clean_up=function(b,c){a("#page_0 .items").html(c);k.dialog("close");
u(b)};a.ee_filebrowser=a.extend(a.ee_filebrowser,{upload_start:function(){a("input[name=upload_dir]").val(a("#dir_choice").val())},upload_success:function(b){a.ee_filebrowser.clean_up(b,"")},upload_error:function(b){a("#progress",k).hide();if(a.ee_notice)a.ee_notice(b.error,{type:"error"});else{b.error=b.error.replace(/<p>/,"");alert(b.error.replace(/<\/p>/,""))}console.log(b)}});a.ee_filebrowser.setPage=l})(jQuery);
