/*
 * FancyBox - jQuery Plugin
 * Simple and fancy lightbox alternative
 *
 * Examples and documentation at: http://fancybox.net
 * 
 * Copyright (c) 2008 - 2010 Janis Skarnelis
 *
 * Version: 1.3.1 (05/03/2010)
 * Requires: jQuery v1.3+
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */

(function(b){var m,s,w,f,C,k,z,A,B,q=0,d={},r=[],p=0,c={},g=[],D=null,n=new Image,F=/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i,R=/[^\.]\.(swf)\s*$/i,G,H=1,l,i,h=!1,x=b.extend(b("<div/>")[0],{prop:0}),t=0,O=!b.support.opacity&&!window.XMLHttpRequest,I=function(){s.hide();n.onerror=n.onload=null;D&&D.abort();m.empty()},P=function(){b.fancybox('<p id="fancybox_error">The requested content cannot be loaded.<br />Please try again later.</p>',{scrolling:"no",padding:20,transitionIn:"none",transitionOut:"none"})},
J=function(){return[b(window).width(),b(window).height(),b(document).scrollLeft(),b(document).scrollTop()]},S=function(a){if(a&&a.length)switch(c.titlePosition){case "inside":return a;case "over":return'<span id="fancybox-title-over">'+a+"</span>";default:return'<span id="fancybox-title-wrap"><span id="fancybox-title-left"></span><span id="fancybox-title-main">'+a+'</span><span id="fancybox-title-right"></span></span>'}return!1},K=function(){k.css("overflow","auto"==c.scrolling?"image"==c.type||"iframe"==
c.type||"swf"==c.type?"hidden":"auto":"yes"==c.scrolling?"auto":"visible");b.support.opacity||(k.get(0).style.removeAttribute("filter"),f.get(0).style.removeAttribute("filter"));b("#fancybox-title").show();if(c.hideOnContentClick)k.one("click",b.fancybox.close);if(c.hideOnOverlayClick)w.one("click",b.fancybox.close);c.showCloseButton&&z.show();b(document).unbind("keydown.fb").bind("keydown.fb",function(a){27==a.keyCode&&c.enableEscapeButton?(a.preventDefault(),b.fancybox.close()):37==a.keyCode?(a.preventDefault(),
b.fancybox.prev()):39==a.keyCode&&(a.preventDefault(),b.fancybox.next())});b.fn.mousewheel&&(f.unbind("mousewheel.fb"),1<g.length&&f.bind("mousewheel.fb",function(a,c){a.preventDefault();h||0===c||(0<c?b.fancybox.prev():b.fancybox.next())}));c.showNavArrows&&((c.cyclic&&1<g.length||0!==p)&&A.show(),(c.cyclic&&1<g.length||p!=g.length-1)&&B.show());b(window).bind("resize.fb",b.fancybox.center);c.centerOnScroll?b(window).bind("scroll.fb",b.fancybox.center):b(window).unbind("scroll.fb");if(b.isFunction(c.onComplete))c.onComplete(g,
p,c);h=!1;var a,e;g.length-1>p&&(a=g[p+1].href,"undefined"!==typeof a&&a.match(F)&&(e=new Image,e.src=a));0<p&&(a=g[p-1].href,"undefined"!==typeof a&&a.match(F)&&(e=new Image,e.src=a))},M=function(a){var b=Math.round(l.width+(i.width-l.width)*a),d=Math.round(l.height+(i.height-l.height)*a),h=Math.round(l.top+(i.top-l.top)*a),g=Math.round(l.left+(i.left-l.left)*a);f.css({width:b+"px",height:d+"px",top:h+"px",left:g+"px"});b=Math.max(b-2*c.padding,0);d=Math.max(d-(2*c.padding+t*a),0);k.css({width:b+
"px",height:d+"px"});"undefined"!==typeof i.opacity&&f.css("opacity",0.5>a?0.5:a)},Q=function(){var a=d.orig?b(d.orig):!1,e={};a&&a.length?(e=a.offset(),e.top+=parseFloat(a.css("paddingTop"))||0,e.left+=parseFloat(a.css("paddingLeft"))||0,e.top+=parseFloat(a.css("border-top-width"))||0,e.left+=parseFloat(a.css("border-left-width"))||0,e.width=a.width(),e.height=a.height(),e={width:e.width+2*c.padding,height:e.height+2*c.padding,top:e.top-c.padding-20,left:e.left-c.padding-20}):(a=J(),e={width:1,height:1,
top:a[3]+0.5*a[1],left:a[2]+0.5*a[0]});return e},N=function(){s.hide();if(f.is(":visible")&&b.isFunction(c.onCleanup)&&!1===c.onCleanup(g,p,c))b.event.trigger("fancybox-cancel"),h=!1;else{g=r;p=q;c=d;k.get(0).scrollTop=0;k.get(0).scrollLeft=0;if(c.overlayShow){if(O)b("select:not(#fancybox-tmp select)").filter(function(){return"hidden"!==this.style.visibility}).css({visibility:"hidden"}).one("fancybox-cleanup",function(){this.style.visibility="inherit"});w.css({"background-color":c.overlayColor,opacity:c.overlayOpacity}).unbind().show()}var a=
J(),e={},j=c.margin,y=c.autoScale,L=2*(20+j),n=2*(20+j),u=2*c.padding;-1<c.width.toString().indexOf("%")?(e.width=a[0]*parseFloat(c.width)/100-40,y=!1):e.width=c.width+u;-1<c.height.toString().indexOf("%")?(e.height=a[1]*parseFloat(c.height)/100-40,y=!1):e.height=c.height+u;if(y&&(e.width>a[0]-L||e.height>a[1]-n))"image"==d.type||"swf"==d.type?(n+=u,y=Math.min(Math.min(a[0]-(L+u),c.width)/c.width,Math.min(a[1]-n,c.height)/c.height),e.width=Math.round(y*(e.width-u))+u,e.height=Math.round(y*(e.height-
u))+u):(e.width=Math.min(e.width,a[0]-L),e.height=Math.min(e.height,a[1]-n));e.top=a[3]+0.5*(a[1]-(e.height+40));e.left=a[2]+0.5*(a[0]-(e.width+40));!1===c.autoScale&&(e.top=Math.max(a[3]+j,e.top),e.left=Math.max(a[2]+j,e.left));i=e;a=c.title;e=i.width-2*c.padding;j="fancybox-title-"+c.titlePosition;b("#fancybox-title").remove();t=0;if(!1!==c.titleShow&&(a=b.isFunction(c.titleFormat)?c.titleFormat(a,g,p,c):S(a))&&""!==a){b('<div id="fancybox-title" class="'+j+'" />').css({width:e,paddingLeft:c.padding,
paddingRight:c.padding}).html(a).appendTo("body");switch(c.titlePosition){case "inside":t=b("#fancybox-title").outerHeight(!0)-c.padding;i.height+=t;break;case "over":b("#fancybox-title").css("bottom",c.padding);break;default:b("#fancybox-title").css("bottom",-1*b("#fancybox-title").outerHeight(!0))}b("#fancybox-title").appendTo(C).hide()}if(f.is(":visible")){b(z.add(A).add(B)).hide();var a=f.position(),v;l={top:a.top,left:a.left,width:f.width(),height:f.height()};v=l.width==i.width&&l.height==i.height;
k.fadeOut(c.changeFade,function(){var a=function(){k.html(m.contents()).fadeIn(c.changeFade,K)};b.event.trigger("fancybox-change");k.empty().css("overflow","hidden");v?(k.css({top:c.padding,left:c.padding,width:Math.max(i.width-2*c.padding,1),height:Math.max(i.height-2*c.padding-t,1)}),a()):(k.css({top:c.padding,left:c.padding,width:Math.max(l.width-2*c.padding,1),height:Math.max(l.height-2*c.padding,1)}),x.prop=0,b(x).animate({prop:1},{duration:c.changeSpeed,easing:c.easingChange,step:M,complete:a}))})}else f.css("opacity",
1),"elastic"==c.transitionIn?(l=Q(),k.css({top:c.padding,left:c.padding,width:Math.max(l.width-2*c.padding,1),height:Math.max(l.height-2*c.padding,1)}).html(m.contents()),f.css(l).show(),c.opacity&&(i.opacity=0),x.prop=0,b(x).animate({prop:1},{duration:c.speedIn,easing:c.easingIn,step:M,complete:K})):(k.css({top:c.padding,left:c.padding,width:Math.max(i.width-2*c.padding,1),height:Math.max(i.height-2*c.padding-t,1)}).html(m.contents()),f.css(i).fadeIn("none"==c.transitionIn?0:c.speedIn,K))}},E=function(){m.width(d.width);
m.height(d.height);"auto"==d.width&&(d.width=m.width());"auto"==d.height&&(d.height=m.height());N()},v=function(){I();var a=r[q],c,j,f,g,i;d=b.extend({},b.fn.fancybox.defaults,"undefined"==typeof b(a).data("fancybox")?d:b(a).data("fancybox"));f=a.title||b(a).title||d.title||"";a.nodeName&&!d.orig&&(d.orig=b(a).children("img:first").length?b(a).children("img:first"):b(a));""===f&&d.orig&&(f=d.orig.attr("alt"));c=a.nodeName&&/^(?:javascript|#)/i.test(a.href)?d.href||null:d.href||a.href||null;d.type?
(j=d.type,c||(c=d.content)):d.content?j="html":c?c.match(F)?j="image":c.match(R)?j="swf":b(a).hasClass("iframe")?j="iframe":c.match(/#/)?(a=c.substr(c.indexOf("#")),j=0<b(a).length?"inline":"ajax"):j="ajax":j="inline";d.type=j;d.href=c;d.title=f;d.autoDimensions&&("iframe"!==d.type&&"swf"!==d.type)&&(d.width="auto",d.height="auto");d.modal&&(d.overlayShow=!0,d.hideOnOverlayClick=!1,d.hideOnContentClick=!1,d.enableEscapeButton=!1,d.showCloseButton=!1);if(b.isFunction(d.onStart)&&!1===d.onStart(r,q,
d))h=!1;else switch(m.css("padding",20+d.padding+d.margin),b(".fancybox-inline-tmp").unbind("fancybox-cancel").bind("fancybox-change",function(){b(this).replaceWith(k.children())}),j){case "html":m.html(d.content);E();break;case "inline":b('<div class="fancybox-inline-tmp" />').hide().insertBefore(b(a)).bind("fancybox-cleanup",function(){b(this).replaceWith(k.children())}).bind("fancybox-cancel",function(){b(this).replaceWith(m.children())});b(a).appendTo(m);E();break;case "image":h=!1;b.fancybox.showActivity();
n=new Image;n.onerror=function(){P()};n.onload=function(){n.onerror=null;n.onload=null;h=!0;d.width=n.width;d.height=n.height;b("<img />").attr({id:"fancybox-img",src:n.src,alt:d.title}).appendTo(m);N()};n.src=c;break;case "swf":g='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+d.width+'" height="'+d.height+'"><param name="movie" value="'+c+'"></param>';i="";b.each(d.swf,function(a,b){g+='<param name="'+a+'" value="'+b+'"></param>';i+=" "+a+'="'+b+'"'});g+='<embed src="'+c+
'" type="application/x-shockwave-flash" width="'+d.width+'" height="'+d.height+'"'+i+"></embed></object>";m.html(g);E();break;case "ajax":a=c.split("#",2);j=d.ajax.data||{};1<a.length&&(c=a[0],"string"==typeof j?j+="&selector="+a[1]:j.selector=a[1]);h=!1;b.fancybox.showActivity();D=b.ajax(b.extend(d.ajax,{url:c,data:j,error:P,success:function(a){200==D.status&&(m.html(a),E())}}));break;case "iframe":b('<iframe id="fancybox-frame" name="fancybox-frame'+(new Date).getTime()+'" frameborder="0" hspace="0" scrolling="'+
d.scrolling+'" src="'+d.href+'"></iframe>').appendTo(m),N()}},T=function(){s.is(":visible")?(b("div",s).css("top",-40*H+"px"),H=(H+1)%12):clearInterval(G)};b.fn.fancybox=function(a){b(this).data("fancybox",b.extend({},a,b.metadata?b(this).metadata():{})).unbind("click.fb").bind("click.fb",function(a){a.preventDefault();if(!h)return h=!0,b(this).blur(),r=[],q=0,a=b(this).attr("rel")||"",!a||""==a||"nofollow"===a?r.push(this):(r=b("a[rel="+a+"], area[rel="+a+"]"),q=r.index(this)),v(),!1});return this};
b.fancybox=function(a,c){if(!h){h=!0;var d="undefined"!==typeof c?c:{};r=[];q=d.index||0;if(b.isArray(a)){for(var f=0,g=a.length;f<g;f++)"object"==typeof a[f]?b(a[f]).data("fancybox",b.extend({},d,a[f])):a[f]=b({}).data("fancybox",b.extend({content:a[f]},d));r=jQuery.merge(r,a)}else"object"==typeof a?b(a).data("fancybox",b.extend({},d,a)):a=b({}).data("fancybox",b.extend({content:a},d)),r.push(a);if(q>r.length||0>q)q=0;v()}};b.fancybox.showActivity=function(){clearInterval(G);s.show();G=setInterval(T,
66)};b.fancybox.hideActivity=function(){s.hide()};b.fancybox.next=function(){return b.fancybox.pos(p+1)};b.fancybox.prev=function(){return b.fancybox.pos(p-1)};b.fancybox.pos=function(a){h||(a=parseInt(a,10),-1<a&&g.length>a&&(q=a,v()),c.cyclic&&(1<g.length&&0>a)&&(q=g.length-1,v()),c.cyclic&&(1<g.length&&a>=g.length)&&(q=0,v()))};b.fancybox.cancel=function(){if(!h){h=!0;b.event.trigger("fancybox-cancel");I();if(d&&b.isFunction(d.onCancel))d.onCancel(r,q,d);h=!1}};b.fancybox.close=function(){function a(){w.fadeOut("fast");
f.hide();b.event.trigger("fancybox-cleanup");k.empty();if(b.isFunction(c.onClosed))c.onClosed(g,p,c);g=d=[];p=q=0;c=d={};h=!1}if(!h&&!f.is(":hidden"))if(h=!0,c&&b.isFunction(c.onCleanup)&&!1===c.onCleanup(g,p,c))h=!1;else if(I(),b(z.add(A).add(B)).hide(),b("#fancybox-title").remove(),f.add(k).add(w).unbind(),b(window).unbind("resize.fb scroll.fb"),b(document).unbind("keydown.fb"),k.css("overflow","hidden"),"elastic"==c.transitionOut){l=Q();var e=f.position();i={top:e.top,left:e.left,width:f.width(),
height:f.height()};c.opacity&&(i.opacity=1);x.prop=1;b(x).animate({prop:0},{duration:c.speedOut,easing:c.easingOut,step:M,complete:a})}else f.fadeOut("none"==c.transitionOut?0:c.speedOut,a)};b.fancybox.resize=function(){var a,d;!h&&!f.is(":hidden")&&(h=!0,a=k.wrapInner("<div style='overflow:auto'></div>").children(),d=a.height(),f.css({height:d+2*c.padding+t}),k.css({height:d}),a.replaceWith(a.children()),b.fancybox.center())};b.fancybox.center=function(){h=!0;var a=J(),b=c.margin,d={};d.top=a[3]+
0.5*(a[1]-(f.height()-t+40));d.left=a[2]+0.5*(a[0]-(f.width()+40));d.top=Math.max(a[3]+b,d.top);d.left=Math.max(a[2]+b,d.left);f.css(d);h=!1};b.fn.fancybox.defaults={padding:10,margin:20,opacity:!1,modal:!1,cyclic:!1,scrolling:"auto",width:560,height:340,autoScale:!0,autoDimensions:!0,centerOnScroll:!1,ajax:{},swf:{wmode:"transparent"},hideOnOverlayClick:!0,hideOnContentClick:!1,overlayShow:!0,overlayOpacity:0.3,overlayColor:"#666",titleShow:!0,titlePosition:"outside",titleFormat:null,transitionIn:"fade",
transitionOut:"fade",speedIn:300,speedOut:300,changeSpeed:300,changeFade:"fast",easingIn:"swing",easingOut:"swing",showCloseButton:!0,showNavArrows:!0,enableEscapeButton:!0,onStart:null,onCancel:null,onComplete:null,onCleanup:null,onClosed:null};b(document).ready(function(){b("#fancybox-wrap").length||(b("body").append(m=b('<div id="fancybox-tmp"></div>'),s=b('<div id="fancybox-loading"><div></div></div>'),w=b('<div id="fancybox-overlay"></div>'),f=b('<div id="fancybox-wrap"></div>')),b.support.opacity||
(f.addClass("fancybox-ie"),s.addClass("fancybox-ie")),C=b('<div id="fancybox-outer"></div>').append('<div class="fancy-bg" id="fancy-bg-n"></div><div class="fancy-bg" id="fancy-bg-ne"></div><div class="fancy-bg" id="fancy-bg-e"></div><div class="fancy-bg" id="fancy-bg-se"></div><div class="fancy-bg" id="fancy-bg-s"></div><div class="fancy-bg" id="fancy-bg-sw"></div><div class="fancy-bg" id="fancy-bg-w"></div><div class="fancy-bg" id="fancy-bg-nw"></div>').appendTo(f),C.append(k=b('<div id="fancybox-inner"></div>'),
z=b('<a id="fancybox-close"></a>'),A=b('<a href="javascript:;" id="fancybox-left"><span class="fancy-ico" id="fancybox-left-ico"></span></a>'),B=b('<a href="javascript:;" id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a>')),z.click(b.fancybox.close),s.click(b.fancybox.cancel),A.click(function(a){a.preventDefault();b.fancybox.prev()}),B.click(function(a){a.preventDefault();b.fancybox.next()}),O&&(w.get(0).style.setExpression("height","document.body.scrollHeight > document.body.offsetHeight ? document.body.scrollHeight : document.body.offsetHeight + 'px'"),
s.get(0).style.setExpression("top","(-20 + (document.documentElement.clientHeight ? document.documentElement.clientHeight/2 : document.body.clientHeight/2 ) + ( ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop )) + 'px'"),C.prepend('<iframe id="fancybox-hide-sel-frame" src="javascript:\'\';" scrolling="no" frameborder="0" ></iframe>')))})})(jQuery);
