/**
 * jquery.Jcrop.js v0.9.8
 * jQuery Image Cropping Plugin
 * @author Kelly Hallman <khallman@gmail.com>
 * Copyright (c) 2008-2009 Kelly Hallman - released under MIT License {{{
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:

 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.

 * }}}
 */

(function(j){j.Jcrop=function(q,y){function e(a){return""+parseInt(a)+"px"}function O(a){a=j(a).offset();return[a.left,a.top]}function C(a){return[a.pageX-M[0],a.pageY-M[1]]}function ea(a,k){return function(g){if(b.aspectRatio)switch(a){case "e":g[1]=k.y+1;break;case "w":g[1]=k.y+1;break;case "n":g[0]=k.x+1;break;case "s":g[0]=k.x+1}else switch(a){case "e":g[1]=k.y2;break;case "w":g[1]=k.y2;break;case "n":g[0]=k.x2;break;case "s":g[0]=k.x2}r.setCurrent(g);p.update()}}function fa(a){var b=a;P.watchKeys();
return function(a){r.moveOffset([a[0]-b[0],a[1]-b[1]]);b=a;p.update()}}function V(a){switch(a){case "n":return"sw";case "s":return"nw";case "e":return"nw";case "w":return"ne";case "ne":return"sw";case "nw":return"se";case "se":return"nw";case "sw":return"ne"}}function W(a){return function(k){if(b.disabled||"move"==a&&!b.allowMove)return!1;G=!0;var g=C(k);M=O(u);B.setCursor("move"==a?a:a+"-resize");if("move"==a)B.activateHandlers(fa(g),Q);else{var g=r.getFixed(),z=V(a),c=r.getCorner(V(z));r.setPressed(r.getCorner(z));
r.setCurrent(c);B.activateHandlers(ea(a,g),Q)}k.stopPropagation();k.preventDefault();return!1}}function R(a){return{x:parseInt(a.x*v),y:parseInt(a.y*A),x2:parseInt(a.x2*v),y2:parseInt(a.y2*A),w:parseInt(a.w*v),h:parseInt(a.h*A)}}function Q(){var a=r.getFixed();a.w>b.minSelect[0]&&a.h>b.minSelect[1]?(p.enableHandles(),p.done()):p.release();B.setCursor(b.allowSelect?"crosshair":"default")}function ga(a){r.setCurrent(a);p.update()}function X(){var a=j("<div></div>").addClass(b.baseClass+"-tracker");
j.browser.msie&&a.css({opacity:0,backgroundColor:"white"});return a}function Y(a){Z([a[0]/v,a[1]/A,a[2]/v,a[3]/A])}function Z(a){r.setPressed([a[0],a[1]]);r.setCurrent([a[2],a[3]]);p.update()}function $(a){"object"!=typeof a&&(a={});b=j.extend(b,a);if("function"!==typeof b.onChange)b.onChange=function(){};if("function"!==typeof b.onSelect)b.onSelect=function(){}}function S(a){b.allowResize?a?p.enableOnly():p.enableHandles():p.disableHandles();B.setCursor(b.allowSelect?"crosshair":"default");p.setCursor(b.allowMove?
"move":"default");T.css("backgroundColor",b.bgColor);"setSelect"in b&&(Y(y.setSelect),p.done(),delete b.setSelect);"trueSize"in b&&(v=b.trueSize[0]/s,A=b.trueSize[1]/o);H=b.maxSize[0]||0;I=b.maxSize[1]||0;J=b.minSize[0]||0;K=b.minSize[1]||0;"outerImage"in b&&(u.attr("src",b.outerImage),delete b.outerImage);p.refresh()}"object"!==typeof q&&(q=j(q)[0]);"object"!==typeof y&&(y={});if(!("trackDocument"in y)&&(y.trackDocument=j.browser.msie?!1:!0,j.browser.msie&&"8"==j.browser.version.split(".")[0]))y.trackDocument=
!0;if(!("keySupport"in y))y.keySupport=j.browser.msie?!1:!0;var b={trackDocument:!1,baseClass:"jcrop",addClass:null,bgColor:"black",bgOpacity:0.6,borderOpacity:0.4,handleOpacity:0.5,handlePad:5,handleSize:9,handleOffset:5,edgeMargin:14,aspectRatio:0,keySupport:!0,cornerHandles:!0,sideHandles:!0,drawBorders:!0,dragEdges:!0,boxWidth:0,boxHeight:0,boundary:8,animationDelay:20,swingSpeed:3,allowSelect:!0,allowMove:!0,allowResize:!0,minSelect:[0,0],maxSize:[0,0],minSize:[0,0],onChange:function(){},onSelect:function(){}};
$(y);var D=j(q),u=D.clone().removeAttr("id").css({position:"absolute"});u.width(D.width());u.height(D.height());D.after(u).hide();(function(a,b,g){var z=a.width(),c=a.height();z>b&&0<b&&(z=b,c=b/a.width()*a.height());c>g&&0<g&&(c=g,z=g/a.height()*a.width());v=a.width()/z;A=a.height()/c;a.width(z).height(c)})(u,b.boxWidth,b.boxHeight);var s=u.width(),o=u.height(),T=j("<div />").width(s).height(o).addClass(b.baseClass+"-holder").css({position:"relative",backgroundColor:b.bgColor}).insertAfter(D).append(u);
b.addClass&&T.addClass(b.addClass);var aa=j("<img />").attr("src",u.attr("src")).css("position","absolute").width(s).height(o),U=j("<div />").width("100%").height("100%").css({zIndex:310,position:"absolute",overflow:"hidden"}).append(aa),F=j("<div />").width("100%").height("100%").css("zIndex",320),N=j("<div />").css({position:"absolute",zIndex:300}).insertBefore(u).append(U,F),E=b.boundary,L=X().width(s+2*E).height(o+2*E).css({position:"absolute",top:e(-E),left:e(-E),zIndex:290}).mousedown(function(a){if(b.disabled||
!b.allowSelect)return!1;G=!0;M=O(u);p.disableHandles();"crosshair"!=ba&&(B.setCursor("crosshair"),ba="crosshair");var k=C(a);r.setPressed(k);B.activateHandlers(ga,Q);P.watchKeys();p.update();a.stopPropagation();a.preventDefault();return!1}),H,I,J,K,v,A,M=O(u),G,ba,ca,ha,r=function(){function a(){if(!b.aspectRatio){var a=m-c,x=l-d;H&&Math.abs(a)>H&&(m=0<a?c+H:c-H);I&&Math.abs(x)>I&&(l=0<x?d+I:d-I);K&&Math.abs(x)<K&&(l=0<x?d+K:d-K);J&&Math.abs(a)<J&&(m=0<a?c+J:c-J);0>c&&(m-=c,c-=c);0>d&&(l-=d,d-=d);
0>m&&(c-=m,m-=m);0>l&&(d-=l,l-=l);m>s&&(a=m-s,c-=a,m-=a);l>o&&(a=l-o,d-=a,l-=a);c>s&&(a=c-o,l-=a,d-=a);d>o&&(a=d-o,l-=a,d-=a);return z(g(c,d,m,l))}var a=b.aspectRatio,x=b.minSize[0]/v,k=b.maxSize[0]/v,e=m-c,j=l-d,n=Math.abs(e),f=Math.abs(j);0==k&&(k=10*s);n/f<a?(n=l,w=f*a,f=0>e?c-w:w+c,0>f?(f=0,h=Math.abs((f-c)/a),n=0>j?d-h:h+d):f>s&&(f=s,h=Math.abs((f-c)/a),n=0>j?d-h:h+d)):(f=m,h=n/a,n=0>j?d-h:d+h,0>n?(n=0,w=Math.abs((n-d)*a),f=0>e?c-w:w+c):n>o&&(n=o,w=Math.abs(n-d)*a,f=0>e?c-w:w+c));f>c?(f-c<x?
f=c+x:f-c>k&&(f=c+k),n=n>d?d+(f-c)/a:d-(f-c)/a):f<c&&(c-f<x?f=c-x:c-f>k&&(f=c-k),n=n>d?d+(c-f)/a:d-(c-f)/a);0>f?(c-=f,f=0):f>s&&(c-=f-s,f=s);0>n?(d-=n,n=0):n>o&&(d-=n-o,n=o);return last=z(g(c,d,f,n))}function k(a){0>a[0]&&(a[0]=0);0>a[1]&&(a[1]=0);a[0]>s&&(a[0]=s);a[1]>o&&(a[1]=o);return[a[0],a[1]]}function g(a,c,b,d){var k=a,e=b,f=c,g=d;b<a&&(k=b,e=a);d<c&&(f=d,g=c);return[Math.round(k),Math.round(f),Math.round(e),Math.round(g)]}function z(a){return{x:a[0],y:a[1],x2:a[2],y2:a[3],w:a[2]-a[0],h:a[3]-
a[1]}}var c=0,d=0,m=0,l=0,e,j;return{flipCoords:g,setPressed:function(a){a=k(a);m=c=a[0];l=d=a[1]},setCurrent:function(a){a=k(a);e=a[0]-m;j=a[1]-l;m=a[0];l=a[1]},getOffset:function(){return[e,j]},moveOffset:function(a){var b=a[0],a=a[1];0>c+b&&(b-=b+c);0>d+a&&(a-=a+d);o<l+a&&(a+=o-(l+a));s<m+b&&(b+=s-(m+b));c+=b;m+=b;d+=a;l+=a},getCorner:function(b){var c=a();switch(b){case "ne":return[c.x2,c.y];case "nw":return[c.x,c.y];case "se":return[c.x2,c.y2];case "sw":return[c.x,c.y2]}},getFixed:a}}(),p=function(){function a(a){a=
j("<div />").css({position:"absolute",opacity:b.borderOpacity}).addClass(b.baseClass+"-"+a);U.append(a);return a}function k(a,c){var b=j("<div />").mousedown(W(a)).css({cursor:a+"-resize",position:"absolute",zIndex:c});F.append(b);return b}function g(a){var c=b.handleSize,d=f,g=c;switch(a){case "n":case "s":c="100%";break;case "e":case "w":g="100%"}return k(a,da++).width(c).height(g).css({top:e(-d+1),left:e(-d+1)})}function z(a){for(i in a)t[a[i]]=k(a[i],da++).css({top:e(-f+1),left:e(-f+1),opacity:b.handleOpacity}).addClass(b.baseClass+
"-handle")}function c(a){var c=Math.round(a.h/2-f),b=Math.round(a.w/2-f);west=-f+1;var d=a.w-f,a=a.h-f;"e"in t&&t.e.css({top:e(c),left:e(d)})&&t.w.css({top:e(c)})&&t.s.css({top:e(a),left:e(b)})&&t.n.css({left:e(b)});"ne"in t&&t.ne.css({left:e(d)})&&t.se.css({top:e(a),left:e(d)})&&t.sw.css({top:e(a)});"b"in t&&t.b.css({top:e(a)})&&t.r.css({left:e(d)})}function d(){var a=r.getFixed();r.setPressed([a.x,a.y]);r.setCurrent([a.x2,a.y2]);m()}function m(){if(x)return l()}function l(){var a=r.getFixed(),d=
a.h;N.width(a.w).height(d);var d=a.x,f=a.y;aa.css({top:e(-f),left:e(-d)});N.css({top:e(f),left:e(d)});b.drawBorders&&v.right.css({left:e(a.w-1)})&&v.bottom.css({top:e(a.h-1)});n&&c(a);x||(N.show(),u.css("opacity",b.bgOpacity),x=!0);b.onChange(R(a))}function p(){n=!0;if(b.allowResize)return c(r.getFixed()),F.show(),!0}function o(){n=!1;F.hide()}function s(a){(ca=a)?o():p()}var x,da=370,v={},t={},n=!1,f=b.handleOffset;b.drawBorders&&(v={top:a("hline").css("top",j.browser.msie?e(-1):e(0)),bottom:a("hline"),
left:a("vline"),right:a("vline")});if(b.dragEdges)t.t=g("n"),t.b=g("s"),t.r=g("e"),t.l=g("w");b.sideHandles&&z(["n","s","e","w"]);b.cornerHandles&&z(["sw","nw","ne","se"]);var q=X().mousedown(W("move")).css({cursor:"move",position:"absolute",zIndex:360});U.append(q);o();return{updateVisible:m,update:l,release:function(){o();N.hide();u.css("opacity",1);x=!1},refresh:d,setCursor:function(a){q.css("cursor",a)},enableHandles:p,enableOnly:function(){n=!0},showHandles:function(){n&&(c(r.getFixed()),F.show())},
disableHandles:o,animMode:s,done:function(){s(!1);d()}}}(),B=function(){function a(a){g(C(a))}function k(d){d.preventDefault();d.stopPropagation();G&&(G=!1,e(C(d)),b.onSelect(R(r.getFixed())),L.css({zIndex:290}),c&&j(document).unbind("mousemove",a).unbind("mouseup",k),g=function(){},e=function(){});return!1}var g=function(){},e=function(){},c=b.trackDocument;c||L.mousemove(a).mouseup(k).mouseout(k);u.before(L);return{activateHandlers:function(b,m){G=!0;g=b;e=m;L.css({zIndex:450});c&&j(document).mousemove(a).mouseup(k);
return!1},setCursor:function(a){L.css("cursor",a)}}}(),P=function(){function a(a,c,d){b.allowMove&&(r.moveOffset([c,d]),p.updateVisible());a.preventDefault();a.stopPropagation()}var e=j('<input type="radio" />').css({position:"absolute",left:"-30px"}).keypress(function(b){if(b.ctrlKey)return!0;var c=(ha=b.shiftKey?!0:!1)?10:1;switch(b.keyCode){case 37:a(b,-c,0);break;case 39:a(b,c,0);break;case 38:a(b,0,-c);break;case 40:a(b,0,c);break;case 27:p.release();break;case 9:return!0}return nothing(b)}).blur(function(){e.hide()}),
g=j("<div />").css({position:"absolute",overflow:"hidden"}).append(e);b.keySupport&&g.insertBefore(u);return{watchKeys:function(){b.keySupport&&(e.show(),e.focus())}}}();F.hide();S(!0);E={animateTo:function(a){var e=a[2]/v,g=a[3]/A;if(!ca){var a=r.flipCoords(a[0]/v,a[1]/A,e,g),j=r.getFixed(),c=initcr=[j.x,j.y,j.x2,j.y2],d=b.animationDelay,m=c[0],l=c[1],e=c[2],g=c[3],o=a[0]-initcr[0],s=a[1]-initcr[1],u=a[2]-initcr[2],x=a[3]-initcr[3],q=0,y=b.swingSpeed;p.animMode(!0);var t=function(){return function(){q+=
(100-q)/y;c[0]=m+q/100*o;c[1]=l+q/100*s;c[2]=e+q/100*u;c[3]=g+q/100*x;100>q?window.setTimeout(t,d):p.done();99.8<=q&&(q=100);Z(c)}}();window.setTimeout(t,d)}},setSelect:Y,setOptions:function(a){$(a);S()},tellSelect:function(){return R(r.getFixed())},tellScaled:function(){return r.getFixed()},disable:function(){b.disabled=!0;p.disableHandles();p.setCursor("default");B.setCursor("default")},enable:function(){b.disabled=!1;S()},cancel:function(){p.done();B.activateHandlers(null,null)},focus:P.watchKeys,
getBounds:function(){return[s*v,o*A]},getWidgetSize:function(){return[s,o]},release:p.release,destroy:function(){T.remove();D.show()}};D.data("Jcrop",E);return E};j.fn.Jcrop=function(q){function y(e){var y=q.useImg||e.src,C=new Image;C.onload=function(){j.Jcrop(e,q)};C.src=y}"object"!==typeof q&&(q={});this.each(function(){if(j(this).data("Jcrop")){if("api"==q)return j(this).data("Jcrop");j(this).data("Jcrop").setOptions(q)}else y(this)});return this}})(jQuery);
