/**
 * jscolor, JavaScript Color Picker
 *
 * @version 1.3.1
 * @license GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 * @author  Jan Odvarko, http://odvarko.cz
 * @created 2008-06-15
 * @updated 2010-01-23
 * @link    http://jscolor.com
 */

/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2010-01-23
 @link    http://jscolor.com
*/
var jscolor={dir:EE.PATH_CP_GBL_IMG,bindClass:"color",binding:!0,preloading:!0,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var c=jscolor.detectDir();jscolor.dir=!1!==c?c:"jscolor/"}return jscolor.dir},detectDir:function(){for(var c=location.href,d=document.getElementsByTagName("base"),b=0;b<d.length;b+=1)d[b].href&&(c=d[b].href);d=document.getElementsByTagName("script");
for(b=0;b<d.length;b+=1)if(d[b].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(d[b].src))return c=(new jscolor.URI(d[b].src)).toAbsolute(c),c.path=c.path.replace(/[^\/]+$/,""),c.query=null,c.fragment=null,c.toString();return!1},bind:function(){for(var c=RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),d=document.getElementsByTagName("input"),b=0;b<d.length;b+=1){var l;if(!d[b].color&&d[b].className&&(l=d[b].className.match(c))){if(l[3])try{eval("prop="+l[3])}catch(w){}d[b].color=new jscolor.color(d[b],
{})}}},preload:function(){for(var c in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(c)&&jscolor.loadImage(c)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},requireImage:function(c){jscolor.imgRequire[c]=!0},loadImage:function(c){jscolor.imgLoaded[c]||(jscolor.imgLoaded[c]=new Image,jscolor.imgLoaded[c].src=jscolor.getDir()+c)},fetchElement:function(c){return"string"===typeof c?document.getElementById(c):c},addEvent:function(c,d,b){c.addEventListener?
c.addEventListener(d,b,!1):c.attachEvent&&c.attachEvent("on"+d,b)},fireEvent:function(c,d){if(c)if(document.createEventObject){var b=document.createEventObject();c.fireEvent("on"+d,b)}else if(document.createEvent)b=document.createEvent("HTMLEvents"),b.initEvent(d,!0,!0),c.dispatchEvent(b);else if(c["on"+d])c["on"+d]()},getElementPos:function(c){var d=c,b=0,l=0;if(d.offsetParent){do b+=d.offsetLeft,l+=d.offsetTop;while(d=d.offsetParent)}for(;(c=c.parentNode)&&"BODY"!==c.nodeName.toUpperCase();)b-=
c.scrollLeft,l-=c.scrollTop;return[b,l]},getElementSize:function(c){return[c.offsetWidth,c.offsetHeight]},getMousePos:function(c){c||(c=window.event);if("number"===typeof c.pageX)return[c.pageX,c.pageY];if("number"===typeof c.clientX)return[c.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c.clientY+document.body.scrollTop+document.documentElement.scrollTop]},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&
(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:
document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(c){function d(b){for(var c="";b;)if("../"===b.substr(0,3)||"./"===b.substr(0,2))b=b.replace(/^\.+/,"").substr(1);else if("/./"===b.substr(0,3)||"/."===b)b="/"+b.substr(3);else if("/../"===b.substr(0,4)||"/.."===b)b="/"+b.substr(4),c=c.replace(/\/?[^\/]*$/,"");else if("."===b||".."===b)b="";else var d=
b.match(/^\/?[^\/]*/)[0],b=b.substr(d.length),c=c+d;return c}this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(b){b=b.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=b[3]?b[2]:null;this.authority=b[5]?b[6]:null;this.path=b[7];this.query=b[9]?b[10]:null;this.fragment=b[12]?b[13]:null;return this};this.toString=function(){var b="";null!==this.scheme&&(b=b+this.scheme+":");null!==this.authority&&(b=
b+"//"+this.authority);null!==this.path&&(b+=this.path);null!==this.query&&(b=b+"?"+this.query);null!==this.fragment&&(b=b+"#"+this.fragment);return b};this.toAbsolute=function(b){var b=new jscolor.URI(b),c=new jscolor.URI;if(null===b.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===b.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(c.scheme=this.scheme,c.authority=this.authority,c.path=d(this.path),c.query=this.query):(null!==this.authority?(c.authority=this.authority,
c.path=d(this.path),c.query=this.query):(""===this.path?(c.path=b.path,c.query=null!==this.query?this.query:b.query):("/"===this.path.substr(0,1)?c.path=d(this.path):(c.path=null!==b.authority&&""===b.path?"/"+this.path:b.path.replace(/[^\/]+$/,"")+this.path,c.path=d(c.path)),c.query=this.query),c.authority=b.authority),c.scheme=b.scheme);c.fragment=this.fragment;return c};c&&this.parse(c)},color:function(c,d){function b(a,c,b){if(null===a)return[b,b,b];var e=Math.floor(a),d=b*(1-c),a=b*(1-c*(e%2?
a-e:1-(a-e)));switch(e){case 6:case 0:return[b,a,d];case 1:return[a,b,d];case 2:return[d,b,a];case 3:return[d,a,b];case 4:return[a,d,b];case 5:return[b,d,a]}}function l(){switch(p){case 0:var a=1;break;case 1:a=2}var c=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),a=Math.round((1-e.hsv[a])*(jscolor.images.pad[1]-1));jscolor.picker.padM.style.backgroundPosition=e.pickerFace+e.pickerInset+c-Math.floor(jscolor.images.cross[0]/2)+"px "+(e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.cross[1]/
2))+"px";c=jscolor.picker.sld.childNodes;switch(p){case 0:for(var d=b(e.hsv[0],e.hsv[1],1),a=0;a<c.length;a+=1)c[a].style.backgroundColor="rgb("+100*d[0]*(1-a/c.length)+"%,"+100*d[1]*(1-a/c.length)+"%,"+100*d[2]*(1-a/c.length)+"%)";break;case 1:var h,k=[e.hsv[2],0,0],a=Math.floor(e.hsv[0]),g=a%2?e.hsv[0]-a:1-(e.hsv[0]-a);switch(a){case 6:case 0:d=[0,1,2];break;case 1:d=[1,0,2];break;case 2:d=[2,0,1];break;case 3:d=[2,1,0];break;case 4:d=[1,2,0];break;case 5:d=[0,2,1]}for(a=0;a<c.length;a+=1)h=1-1/
(c.length-1)*a,k[1]=k[0]*(1-h*g),k[2]=k[0]*(1-h),c[a].style.backgroundColor="rgb("+100*k[d[0]]+"%,"+100*k[d[1]]+"%,"+100*k[d[2]]+"%)"}}function w(){switch(p){case 0:var a=2;break;case 1:a=1}a=Math.round((1-e.hsv[a])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.arrow[1]/2))+"px"}function s(){return jscolor.picker&&jscolor.picker.owner===e}function C(){h!==c&&e.importColor()}function A(a){var c=jscolor.getMousePos(a),
a=c[0]-t[0],c=c[1]-t[1];switch(p){case 0:e.fromHSV(a*(6/(jscolor.images.pad[0]-1)),1-c/(jscolor.images.pad[1]-1),null,x);break;case 1:e.fromHSV(a*(6/(jscolor.images.pad[0]-1)),null,1-c/(jscolor.images.pad[1]-1),x)}}function B(a){a=jscolor.getMousePos(a)[1]-t[1];switch(p){case 0:e.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),y);break;case 1:e.fromHSV(null,1-a/(jscolor.images.sld[1]-1),null,y)}}this.adjust=this.required=!0;this.hash=!1;this.caps=!0;this.styleElement=this.valueElement=c;this.hsv=
[0,0,1];this.rgb=[1,1,1];this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerFace=10;this.pickerFaceColor="#f4f6f6";this.pickerBorder=1;this.pickerBorderColor="#d0d7df";this.pickerInset=1;this.pickerInsetColor="#d0d7df";this.pickerZIndex=1E4;for(var q in d)d.hasOwnProperty(q)&&(this[q]=d[q]);this.hidePicker=function(){s()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!s()){var a=
jscolor.getElementPos(c),b=jscolor.getElementSize(c),d=jscolor.getViewPos(),i=jscolor.getViewSize(),k=[2*this.pickerBorder+4*this.pickerInset+2*this.pickerFace+jscolor.images.pad[0]+2*jscolor.images.arrow[0]+jscolor.images.sld[0],2*this.pickerBorder+2*this.pickerInset+2*this.pickerFace+jscolor.images.pad[1]],g,f,m;switch(this.pickerPosition.toLowerCase()){case "left":g=1;f=0;m=-1;break;case "right":g=1;f=0;m=1;break;case "top":g=0;f=1;m=-1;break;default:g=0,m=f=1}var j=(b[f]+k[f])/2,a=[-d[g]+a[g]+
k[g]>i[g]?-d[g]+a[g]+b[g]/2>i[g]/2&&0<=a[g]+b[g]-k[g]?a[g]+b[g]-k[g]:a[g]:a[g],-d[f]+a[f]+b[f]+k[f]-j+j*m>i[f]?-d[f]+a[f]+b[f]/2>i[f]/2&&0<=a[f]+b[f]-j-j*m?a[f]+b[f]-j-j*m:a[f]+b[f]-j+j*m:0<=a[f]+b[f]-j+j*m?a[f]+b[f]-j+j*m:a[f]+b[f]-j-j*m];g=a[g];f=a[f];if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),
sldM:document.createElement("div")};for(a=0;a<jscolor.images.sld[1];a+=4)b=document.createElement("div"),b.style.height="4px",b.style.fontSize="1px",b.style.lineHeight="0",jscolor.picker.sld.appendChild(b);jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);
jscolor.picker.boxB.appendChild(jscolor.picker.box)}a=jscolor.picker;t=[g+e.pickerBorder+e.pickerFace+e.pickerInset,f+e.pickerBorder+e.pickerFace+e.pickerInset];a.box.onmouseup=a.box.onmouseout=function(){c.focus()};a.box.onmousedown=function(){r=!0};a.box.onmousemove=function(a){u&&A(a);v&&B(a)};a.padM.onmouseup=a.padM.onmouseout=function(){u&&(u=!1,jscolor.fireEvent(h,"change"))};a.padM.onmousedown=function(a){u=!0;A(a)};a.sldM.onmouseup=a.sldM.onmouseout=function(){v&&(v=!1,jscolor.fireEvent(h,
"change"))};a.sldM.onmousedown=function(a){v=!0;B(a)};a.box.style.width=4*e.pickerInset+2*e.pickerFace+jscolor.images.pad[0]+2*jscolor.images.arrow[0]+jscolor.images.sld[0]+"px";a.box.style.height=2*e.pickerInset+2*e.pickerFace+jscolor.images.pad[1]+"px";a.boxB.style.position="absolute";a.boxB.style.clear="both";a.boxB.style.left=g+"px";a.boxB.style.top=f+"px";a.boxB.style.zIndex=e.pickerZIndex;a.boxB.style.border=e.pickerBorder+"px solid";a.boxB.style.borderColor=e.pickerBorderColor;a.boxB.style.background=
e.pickerFaceColor;a.pad.style.width=jscolor.images.pad[0]+"px";a.pad.style.height=jscolor.images.pad[1]+"px";a.padB.style.position="absolute";a.padB.style.left=e.pickerFace+"px";a.padB.style.top=e.pickerFace+"px";a.padB.style.border=e.pickerInset+"px solid";a.padB.style.borderColor=e.pickerInsetColor;a.padM.style.position="absolute";a.padM.style.left="0";a.padM.style.top="0";a.padM.style.width=e.pickerFace+2*e.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";a.padM.style.height=a.box.style.height;
a.padM.style.cursor="crosshair";a.sld.style.overflow="hidden";a.sld.style.width=jscolor.images.sld[0]+"px";a.sld.style.height=jscolor.images.sld[1]+"px";a.sldB.style.position="absolute";a.sldB.style.right=e.pickerFace+"px";a.sldB.style.top=e.pickerFace+"px";a.sldB.style.border=e.pickerInset+"px solid";a.sldB.style.borderColor=e.pickerInsetColor;a.sldM.style.position="absolute";a.sldM.style.right="0";a.sldM.style.top="0";a.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+e.pickerFace+
2*e.pickerInset+"px";a.sldM.style.height=a.box.style.height;try{a.sldM.style.cursor="pointer"}catch(q){a.sldM.style.cursor="hand"}switch(p){case 0:var n="hs.png";break;case 1:n="hv.png"}a.padM.style.background="url('"+jscolor.getDir()+"cross.gif') no-repeat";a.sldM.style.background="url('"+jscolor.getDir()+"arrow.gif') no-repeat";a.pad.style.background="url('"+jscolor.getDir()+n+"') 0 0 no-repeat";l();w();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(a.boxB)}};this.importColor=
function(){h?this.adjust?!this.required&&/^\s*$/.test(h.value)?(h.value="",i.style.backgroundColor=i.jscStyle.backgroundColor,i.style.color=i.jscStyle.color,this.exportColor(n|z)):this.fromString(h.value)||this.exportColor():this.fromString(h.value,n)||(i.style.backgroundColor=i.jscStyle.backgroundColor,i.style.color=i.jscStyle.color,this.exportColor(n|z)):this.exportColor()};this.exportColor=function(a){if(!(a&n)&&h){var b=this.toString();this.caps&&(b=b.toUpperCase());this.hash&&(b="#"+b);h.value=
b}!(a&z)&&i&&(i.style.backgroundColor="#"+this.toString(),i.style.color=0.5>0.213*this.rgb[0]+0.715*this.rgb[1]+0.072*this.rgb[2]?"#FFF":"#000");!(a&y)&&s()&&l();!(a&x)&&s()&&w()};this.fromHSV=function(a,c,d,e){0>a&&(a=0)||6<a&&(a=6);0>c&&(c=0)||1<c&&(c=1);0>d&&(d=0)||1<d&&(d=1);this.rgb=b(null===a?this.hsv[0]:this.hsv[0]=a,null===c?this.hsv[1]:this.hsv[1]=c,null===d?this.hsv[2]:this.hsv[2]=d);this.exportColor(e)};this.fromRGB=function(a,b,c,d){0>a&&(a=0)||1<a&&(a=1);0>b&&(b=0)||1<b&&(b=1);0>c&&(c=
0)||1<c&&(c=1);var a=null===a?this.rgb[0]:this.rgb[0]=a,b=null===b?this.rgb[1]:this.rgb[1]=b,e=null===c?this.rgb[2]:this.rgb[2]=c,g=Math.min(Math.min(a,b),e),c=Math.max(Math.max(a,b),e),f=c-g;0===f?a=[null,0,c]:(a=a===g?3+(e-b)/f:b===g?5+(a-e)/f:1+(b-a)/f,a=[6===a?0:a,f/c,c]);null!==a[0]&&(this.hsv[0]=a[0]);0!==a[2]&&(this.hsv[1]=a[1]);this.hsv[2]=a[2];this.exportColor(d)};this.fromString=function(a,b){var c=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return c?(6===c[1].length?this.fromRGB(parseInt(c[1].substr(0,
2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var e=this,p="hvs"===this.pickerMode.toLowerCase()?
1:0,r=!1,h=jscolor.fetchElement(this.valueElement),i=jscolor.fetchElement(this.styleElement),u=!1,v=!1,t,n=1,z=2,y=4,x=8;jscolor.addEvent(c,"focus",function(){e.pickerOnfocus&&e.showPicker()});jscolor.addEvent(c,"blur",function(){r?r=!1:window.setTimeout(function(){r||(h===c&&e.importColor(),e.pickerOnfocus&&e.hidePicker());r=!1},0)});h&&(q=function(){e.fromString(h.value,n)},jscolor.addEvent(h,"keyup",q),jscolor.addEvent(h,"input",q),jscolor.addEvent(h,"blur",C),h.setAttribute("autocomplete","off"));
i&&(i.jscStyle={backgroundColor:i.style.backgroundColor,color:i.style.color});switch(p){case 0:jscolor.requireImage("hs.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};jscolor.install();
