/*!
 * 
 * TableSorter 2.0 - Client-side table sorting with ease!
 * Version 2.0.3
 * @requires jQuery v1.2.3
 * 
 * Copyright (c) 2007 Christian Bach
 * Examples and docs at: http://tablesorter.com
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 * 
 */

(function(b){b.extend({tablesorter:new function(){function a(c,a){p(c+","+((new Date).getTime()-a.getTime())+"ms")}function p(c){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(c):alert(c)}function k(c,a){if(c.config.debug)var d="";var j=c.tBodies[0].rows;if(c.tBodies[0].rows[0])for(var f=[],j=j[0].cells,m=j.length,e=0;e<m;e++){var g=!1;b.metadata&&b(a[e]).metadata()&&b(a[e]).metadata().sorter?g=s(b(a[e]).metadata().sorter):c.config.headers[e]&&c.config.headers[e].sorter&&
(g=s(c.config.headers[e].sorter));if(!g)a:{for(var g=c,n=j[e],l=r.length,q=1;q<l;q++)if(r[q].is(b.trim(y(g.config,n)),g,n)){g=r[q];break a}g=r[0]}c.config.debug&&(d+="column:"+e+" parser:"+g.id+"\n");f.push(g)}c.config.debug&&p(d);return f}function s(c){for(var a=r.length,b=0;b<a;b++)if(r[b].id.toLowerCase()==c.toLowerCase())return r[b];return!1}function t(c){if(c.config.debug)var h=new Date;for(var d=c.tBodies[0]&&c.tBodies[0].rows.length||0,j=c.tBodies[0].rows[0]&&c.tBodies[0].rows[0].cells.length||
0,f=c.config.parsers,m={row:[],normalized:[]},e=0;e<d;++e){var g=c.tBodies[0].rows[e],n=[];m.row.push(b(g));for(var l=0;l<j;++l)n.push(f[l].format(y(c.config,g.cells[l]),c,g.cells[l]));n.push(e);m.normalized.push(n)}c.config.debug&&a("Building cache for "+d+" rows:",h);return m}function y(c,a){if(!a)return"";var d="";return d="simple"==c.textExtraction?a.childNodes[0]&&a.childNodes[0].hasChildNodes()?a.childNodes[0].innerHTML:a.innerHTML:"function"==typeof c.textExtraction?c.textExtraction(a):b(a).text()}
function v(c,h){if(c.config.debug)var d=new Date;for(var j=h.row,f=h.normalized,m=f.length,e=f[0].length-1,g=b(c.tBodies[0]),n=[],l=0;l<m;l++)if(n.push(j[f[l][e]]),!c.config.appender)for(var q=j[f[l][e]],D=q.length,w=0;w<D;w++)g[0].appendChild(q[w]);c.config.appender&&c.config.appender(c,n);n=null;c.config.debug&&a("Rebuilt table:",d);x(c);setTimeout(function(){b(c).trigger("sortEnd")},0)}function x(a){for(var b=a.config.widgets,d=b.length,j=0;j<d;j++)z(b[j]).format(a)}function z(a){for(var b=u.length,
d=0;d<b;d++)if(u[d].id.toLowerCase()==a.toLowerCase())return u[d]}function A(a,h,d,j){h.removeClass(j[0]).removeClass(j[1]);var f=[];h.each(function(){this.sortDisabled||(f[this.column]=b(this))});a=d.length;for(h=0;h<a;h++)f[d[h][0]].addClass(j[d[h][1]])}function B(a,b,d){d.normalized.sort(function(b){for(var f=[],h=[],e=b.length,g,n,l,q=0;q<e;q++)l=b[q][0],n=b[q][1],f[q]=l,h[q]="text"==a.config.parsers[l].type?0==n?E:F:0==n?G:H;g=d.normalized[0].length-1;return function(a,c){for(var b,d=0;d<e;d++)if(b=
f[d],b=h[d](a[b],c[b]))return b;return a[g]-c[g]}}(b));return d}function E(a,b){return a<b?-1:a>b?1:0}function F(a,b){return b<a?-1:b>a?1:0}function G(a,b){return a-b}function H(a,b){return b-a}var r=[],u=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],
headerList:[],dateFormat:"us",decimal:".",debug:!1};this.benchmark=a;this.construct=function(c){return this.each(function(){if(this.tHead&&this.tBodies){var h,d,j,f;this.config={};f=b.extend(this.config,b.tablesorter.defaults,c);h=b(this);var m=this;if(m.config.debug)var e=new Date;for(var g=0;g<m.tHead.rows.length;g++);$tableHeaders=b("thead th",m);$tableHeaders.each(function(a){this.count=0;this.column=a;var c=m.config.sortInitialOrder;this.order=i="Number"!=typeof c?"desc"==c.toLowerCase()?1:0:
1==c?c:0;if(b.metadata&&!1===b(this).metadata().sorter||m.config.headers[a]&&!1===m.config.headers[a].sorter)this.sortDisabled=!0;this.sortDisabled||b(this).addClass(m.config.cssHeader);m.config.headerList[a]=this});m.config.debug&&(a("Built headers:",e),p($tableHeaders));d=$tableHeaders;this.config.parsers=k(this,d);j=t(this);var n=[f.cssDesc,f.cssAsc];if(this.config.widthFixed){var l=b("<colgroup>");b("tr:first td",this.tBodies[0]).each(function(){l.append(b("<col>").css("width",b(this).width()))});
b(this).prepend(l)}d.click(function(a){h.trigger("sortStart");var c=h[0].tBodies[0]&&h[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&0<c){b(this);c=this.column;this.order=this.count++%2;if(a[f.sortMultiSortKey]){a:{for(var a=f.sortList,e=a.length,g=0;g<e;g++)if(a[g][0]==c){a=!0;break a}a=!1}if(a)for(a=0;a<f.sortList.length;a++)e=f.sortList[a],g=f.headerList[e[0]],e[0]==c&&(g.count=e[1],g.count++,e[1]=g.count%2);else f.sortList.push([c,this.order])}else{f.sortList=[];if(null!=f.sortForce){e=
f.sortForce;for(a=0;a<e.length;a++)e[a][0]!=c&&f.sortList.push(e[a])}f.sortList.push([c,this.order])}setTimeout(function(){A(h[0],d,f.sortList,n);v(h[0],B(h[0],f.sortList,j))},1);return!1}}).mousedown(function(){if(f.cancelSelection)return this.onselectstart=function(){return!1},!1});h.bind("update",function(){this.config.parsers=k(this,d);j=t(this)}).bind("sorton",function(a,c){b(this).trigger("sortStart");f.sortList=c;for(var e=f.sortList,g=this.config,h=e.length,l=0;l<h;l++){var m=e[l],p=g.headerList[m[0]];
p.count=m[1];p.count++}A(this,d,e,n);v(this,B(this,e,j))}).bind("appendCache",function(){v(this,j)}).bind("applyWidgetId",function(a,c){z(c).format(this)}).bind("applyWidgets",function(){x(this)});b.metadata&&(b(this).metadata()&&b(this).metadata().sortlist)&&(f.sortList=b(this).metadata().sortlist);0<f.sortList.length&&h.trigger("sorton",[f.sortList]);x(this)}})};this.addParser=function(a){for(var b=r.length,d=!0,j=0;j<b;j++)r[j].id.toLowerCase()==a.id.toLowerCase()&&(d=!1);d&&r.push(a)};this.addWidget=
function(a){u.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a,h){var d="\\"+h.decimal;return RegExp("/(^[+]?0("+d+"0+)?$)|(^([-+]?[1-9][0-9]*)$)|(^([-+]?((0?|[1-9][0-9]*)"+d+"(0*[1-9][0-9]*)))$)|(^[-+]?[1-9]+[0-9]*"+d+"0+$)/").test(b.trim(a))};this.clearTableBody=function(a){b.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):a.tBodies[0].innerHTML=
""}}});b.fn.extend({tablesorter:b.tablesorter.construct});var k=b.tablesorter;k.addParser({id:"text",is:function(){return!0},format:function(a){return b.trim(a.toLowerCase())},type:"text"});k.addParser({id:"digit",is:function(a,p){return b.tablesorter.isDigit(a,p.config)},format:function(a){return b.tablesorter.formatFloat(a)},type:"numeric"});k.addParser({id:"currency",is:function(a){return/^[\u00a3$\u20ac?.]/.test(a)},format:function(a){return b.tablesorter.formatFloat(a.replace(RegExp(/[^0-9.]/g),
""))},type:"numeric"});k.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(a)},format:function(a){for(var a=a.split("."),p="",k=a.length,s=0;s<k;s++)var t=a[s],p=2==t.length?p+("0"+t):p+t;return b.tablesorter.formatFloat(p)},type:"numeric"});k.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});k.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},
format:function(a){return b.tablesorter.formatFloat(""!=a?(new Date(a.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});k.addParser({id:"percent",is:function(a){return/\%$/.test(b.trim(a))},format:function(a){return b.tablesorter.formatFloat(a.replace(RegExp(/%/g),""))},type:"numeric"});k.addParser({id:"usLongDate",is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(a){return b.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});k.addParser({id:"shortDate",is:function(a){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(a)},format:function(a,p){var k=p.config,a=a.replace(/\-/g,"/");if("us"==k.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==k.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==k.dateFormat||"dd-mm-yy"==k.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return b.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});k.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(a){return b.tablesorter.formatFloat((new Date("2000/01/01 "+a)).getTime())},type:"numeric"});k.addParser({id:"metadata",is:function(){return!1},format:function(a,k,C){a=k.config;a=!a.parserMetadataName?"sortValue":a.parserMetadataName;return b(C).metadata()[a]},type:"numeric"});k.addWidget({id:"zebra",format:function(a){if(a.config.debug)var k=new Date;
b("tr:visible",a.tBodies[0]).filter(":even").removeClass(a.config.widgetZebra.css[1]).addClass(a.config.widgetZebra.css[0]).end().filter(":odd").removeClass(a.config.widgetZebra.css[0]).addClass(a.config.widgetZebra.css[1]);a.config.debug&&b.tablesorter.benchmark("Applying Zebra widget",k)}})})(jQuery);
