/*!
 * 
 * TableSorter 2.0 - Client-side table sorting with ease!
 * Version 2.0.3
 * @requires jQuery v1.2.3
 * 
 * Copyright (c) 2007 Christian Bach
 * Examples and docs at: http://tablesorter.com
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 * 
 */

(function(b){b.extend({tablesorter:new function(){function a(c,a){h(c+","+((new Date).getTime()-a.getTime())+"ms")}function h(c){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(c):alert(c)}function e(c,a){if(c.config.debug)var d="";var q=c.tBodies[0].rows;if(c.tBodies[0].rows[0])for(var f=[],q=q[0].cells,C=q.length,l=0;l<C;l++){var m=!1;b.metadata&&b(a[l]).metadata()&&b(a[l]).metadata().sorter?m=r(b(a[l]).metadata().sorter):c.config.headers[l]&&c.config.headers[l].sorter&&
(m=r(c.config.headers[l].sorter));if(!m)a:{for(var m=c,k=q[l],p=n.length,s=1;s<p;s++)if(n[s].is(b.trim(y(m.config,k)),m,k)){m=n[s];break a}m=n[0]}c.config.debug&&(d+="column:"+l+" parser:"+m.id+"\n");f.push(m)}c.config.debug&&h(d);return f}function r(c){for(var a=n.length,d=0;d<a;d++)if(n[d].id.toLowerCase()==c.toLowerCase())return n[d];return!1}function t(c){if(c.config.debug)var g=new Date;for(var d=c.tBodies[0]&&c.tBodies[0].rows.length||0,q=c.tBodies[0].rows[0]&&c.tBodies[0].rows[0].cells.length||
0,f=c.config.parsers,h={row:[],normalized:[]},l=0;l<d;++l){var m=c.tBodies[0].rows[l],k=[];h.row.push(b(m));for(var p=0;p<q;++p)k.push(f[p].format(y(c.config,m.cells[p]),c,m.cells[p]));k.push(l);h.normalized.push(k)}c.config.debug&&a("Building cache for "+d+" rows:",g);return h}function y(c,a){if(!a)return"";var d="";return d="simple"==c.textExtraction?a.childNodes[0]&&a.childNodes[0].hasChildNodes()?a.childNodes[0].innerHTML:a.innerHTML:"function"==typeof c.textExtraction?c.textExtraction(a):b(a).text()}
function w(c,g){if(c.config.debug)var d=new Date;for(var q=g.row,f=g.normalized,h=f.length,l=f[0].length-1,m=b(c.tBodies[0]),k=[],p=0;p<h;p++)if(k.push(q[f[p][l]]),!c.config.appender)for(var s=q[f[p][l]],e=s.length,n=0;n<e;n++)m[0].appendChild(s[n]);c.config.appender&&c.config.appender(c,k);k=null;c.config.debug&&a("Rebuilt table:",d);x(c);setTimeout(function(){b(c).trigger("sortEnd")},0)}function D(c){if(c.config.debug)var g=new Date;for(var d=0;d<c.tHead.rows.length;d++);$tableHeaders=b("thead th",
c);$tableHeaders.each(function(a){this.count=0;this.column=a;var d=c.config.sortInitialOrder;this.order=i="Number"!=typeof d?"desc"==d.toLowerCase()?1:0:1==d?d:0;d=b.metadata&&!1===b(this).metadata().sorter?!0:!1;d||(d=c.config.headers[a]&&!1===c.config.headers[a].sorter?!0:!1);d&&(this.sortDisabled=!0);this.sortDisabled||b(this).addClass(c.config.cssHeader);c.config.headerList[a]=this});c.config.debug&&(a("Built headers:",g),h($tableHeaders));return $tableHeaders}function x(c){for(var a=c.config.widgets,
d=a.length,b=0;b<d;b++)z(a[b]).format(c)}function z(c){for(var a=v.length,d=0;d<a;d++)if(v[d].id.toLowerCase()==c.toLowerCase())return v[d]}function E(c,a){for(var d=a.length,b=0;b<d;b++)if(a[b][0]==c)return!0;return!1}function A(a,g,d,q){g.removeClass(q[0]).removeClass(q[1]);var f=[];g.each(function(a){this.sortDisabled||(f[this.column]=b(this))});a=d.length;for(g=0;g<a;g++)f[d[g][0]].addClass(q[d[g][1]])}function F(a,g){if(a.config.widthFixed){var d=b("<colgroup>");b("tr:first td",a.tBodies[0]).each(function(){d.append(b("<col>").css("width",
b(this).width()))});b(a).prepend(d)}}function B(a,b,d){d.normalized.sort(function(b){for(var g=[],h=[],l=b.length,m,k,p,e=0;e<l;e++)p=b[e][0],k=b[e][1],g[e]=p,h[e]="text"==a.config.parsers[p].type?0==k?G:H:0==k?I:J;m=d.normalized[0].length-1;return function(a,c){for(var b,d=0;d<l;d++)if(b=g[d],b=h[d](a[b],c[b]))return b;return a[m]-c[m]}}(b));return d}function G(a,b){return a<b?-1:a>b?1:0}function H(a,b){return b<a?-1:b>a?1:0}function I(a,b){return a-b}function J(a,b){return b-a}var n=[],v=[];this.defaults=
{cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:".",debug:!1};this.benchmark=a;this.construct=function(a){return this.each(function(){if(this.tHead&&this.tBodies){var g,d,h,f;this.config={};f=b.extend(this.config,b.tablesorter.defaults,
a);g=b(this);d=D(this);this.config.parsers=e(this,d);h=t(this);var n=[f.cssDesc,f.cssAsc];F(this);d.click(function(a){g.trigger("sortStart");var c=g[0].tBodies[0]&&g[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&0<c){b(this);c=this.column;this.order=this.count++%2;if(a[f.sortMultiSortKey])if(E(c,f.sortList))for(a=0;a<f.sortList.length;a++){var k=f.sortList[a],e=f.headerList[k[0]];k[0]==c&&(e.count=k[1],e.count++,k[1]=e.count%2)}else f.sortList.push([c,this.order]);else{f.sortList=[];if(null!=
f.sortForce)for(k=f.sortForce,a=0;a<k.length;a++)k[a][0]!=c&&f.sortList.push(k[a]);f.sortList.push([c,this.order])}setTimeout(function(){A(g[0],d,f.sortList,n);w(g[0],B(g[0],f.sortList,h))},1);return!1}}).mousedown(function(){if(f.cancelSelection)return this.onselectstart=function(){return!1},!1});g.bind("update",function(){this.config.parsers=e(this,d);h=t(this)}).bind("sorton",function(a,c){b(this).trigger("sortStart");f.sortList=c;for(var g=f.sortList,e=this.config,s=g.length,u=0;u<s;u++){var r=
g[u],t=e.headerList[r[0]];t.count=r[1];t.count++}A(this,d,g,n);w(this,B(this,g,h))}).bind("appendCache",function(){w(this,h)}).bind("applyWidgetId",function(a,c){z(c).format(this)}).bind("applyWidgets",function(){x(this)});b.metadata&&b(this).metadata()&&b(this).metadata().sortlist&&(f.sortList=b(this).metadata().sortlist);0<f.sortList.length&&g.trigger("sorton",[f.sortList]);x(this)}})};this.addParser=function(a){for(var b=n.length,d=!0,h=0;h<b;h++)n[h].id.toLowerCase()==a.id.toLowerCase()&&(d=!1);
d&&n.push(a)};this.addWidget=function(a){v.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a,h){var d="\\"+h.decimal;return RegExp("/(^[+]?0("+d+"0+)?$)|(^([-+]?[1-9][0-9]*)$)|(^([-+]?((0?|[1-9][0-9]*)"+d+"(0*[1-9][0-9]*)))$)|(^[-+]?[1-9]+[0-9]*"+d+"0+$)/").test(b.trim(a))};this.clearTableBody=function(a){b.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});b.fn.extend({tablesorter:b.tablesorter.construct});var e=b.tablesorter;e.addParser({id:"text",is:function(a){return!0},format:function(a){return b.trim(a.toLowerCase())},type:"text"});e.addParser({id:"digit",is:function(a,h){return b.tablesorter.isDigit(a,h.config)},format:function(a){return b.tablesorter.formatFloat(a)},type:"numeric"});e.addParser({id:"currency",is:function(a){return/^[\u00a3$\u20ac?.]/.test(a)},format:function(a){return b.tablesorter.formatFloat(a.replace(RegExp(/[^0-9.]/g),
""))},type:"numeric"});e.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(a)},format:function(a){a=a.split(".");for(var h="",e=a.length,r=0;r<e;r++)var t=a[r],h=2==t.length?h+("0"+t):h+t;return b.tablesorter.formatFloat(h)},type:"numeric"});e.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});e.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},
format:function(a){return b.tablesorter.formatFloat(""!=a?(new Date(a.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});e.addParser({id:"percent",is:function(a){return/\%$/.test(b.trim(a))},format:function(a){return b.tablesorter.formatFloat(a.replace(RegExp(/%/g),""))},type:"numeric"});e.addParser({id:"usLongDate",is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(a){return b.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});e.addParser({id:"shortDate",is:function(a){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(a)},format:function(a,h){var e=h.config;a=a.replace(/\-/g,"/");if("us"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==e.dateFormat||"dd-mm-yy"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return b.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});e.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(a){return b.tablesorter.formatFloat((new Date("2000/01/01 "+a)).getTime())},type:"numeric"});e.addParser({id:"metadata",is:function(a){return!1},format:function(a,e,u){a=e.config;a=a.parserMetadataName?a.parserMetadataName:"sortValue";return b(u).metadata()[a]},type:"numeric"});e.addWidget({id:"zebra",format:function(a){if(a.config.debug)var e=new Date;
b("tr:visible",a.tBodies[0]).filter(":even").removeClass(a.config.widgetZebra.css[1]).addClass(a.config.widgetZebra.css[0]).end().filter(":odd").removeClass(a.config.widgetZebra.css[0]).addClass(a.config.widgetZebra.css[1]);a.config.debug&&b.tablesorter.benchmark("Applying Zebra widget",e)}})})(jQuery);
