/*  WysiHat - WYSIWYG JavaScript framework, version 0.2.1
 *  (c) 2008-2010 Joshua Peek
 *  JQ-WysiHat - jQuery port of WysiHat to run on jQuery
 *  (c) 2010 Scott Williams & Aaron Gustafson
 *  EL-WysiHat - Extensive rewrite of JQ-WysiHat for ExpressionEngine
 *  (c) 2012 EllisLab, Inc.
 *
 *  WysiHat is freely distributable under the terms of an MIT-style license.
 *--------------------------------------------------------------------------*/

(function(j,e,t){var g=window.WysiHat={name:"WysiHat",addButton:function(a,c){this._buttons[a]=c},attach:function(a,c){return new g.Editor(e(a),c)},inherit:function(a,c){function f(){var c;this.parent={};for(c in a)a.hasOwnProperty(c)&&(this.parent[c]=e.proxy(a[c],this))}var w,b;f.prototype=a;b=new f;for(w in c)b[w]=c[w];return b},_buttons:[]};g.Editor=function(a,c){this.$field=a.hide();this.$editor=this.create();a.before(this.$editor);this.createWrapper();this.Element=g.Element;this.Commands=g.Commands;
this.Formatting=g.Formatting;this.init(c)};g.Editor.prototype={_emptyChar:String.fromCharCode(8203),_empty:function(){return"<p>"+this._emptyChar+"</p>"},create:function(){return e("<div/>",{"class":g.name+"-editor",data:{wysihat:this,field:this.$field},role:"application",contentEditable:"true",height:this.$field.height(),dir:this.$field.attr("dir"),html:g.Formatting.getBrowserMarkupFrom(this.$field)})},createWrapper:function(){var a=this;this.$field.add(this.$editor).wrapAll(e("<div/>",{"class":g.name+
"-container",mouseup:function(){a.$field.is(":visible")?a.$editor.height(a.$field.outerHeight()):a.$editor.is(":visible")&&a.$field.height(a.$editor.outerHeight())}}))},init:function(a){var c=this.$editor,f=this;this.Undo=new g.Undo;this.Selection=new g.Selection(c);this.Event=new g.Event(this);this.Toolbar=new g.Toolbar(c,a.buttons);this.$field.change(e.proxy(this,"updateEditor"));c.closest("form").submit(function(){f.$field.is(":visible")||f.updateField()})},updateField:function(){this.$field.val(g.Formatting.getApplicationMarkupFrom(this.$editor))},
updateEditor:function(){this.$editor.html(g.Formatting.getBrowserMarkupFrom(this.$field));this.selectEmptyParagraph()},selectEmptyParagraph:function(){var a=this.$editor,c=a.html(),f=window.getSelection();if(""==c||"<br>"==c||"<br/>"==c||"<p></p>"==c||"<p>\x00</p>"==c)a.html(this._empty()),c=j.createRange(),f.removeAllRanges(),c.selectNodeContents(a.find("p").get(0)),e.browser.mozilla&&a.find("p").eq(0).html(""),f.addRange(c)}};g.Editor.constructor=g.Editor;var m=function(a){for(var c=arguments.length,
f=!1;!1==f&&1<c--;)f=a.is(arguments[c].join(","));return f},u=["blockquote","details","fieldset","figure","td"],l="article aside header footer nav section".split(" "),b="blockquote details dl ol table ul".split(" "),d="dd dt li summary td th".split(" "),i="address caption dd div dt figcaption figure h1 h2 h3 h4 h5 h6 hgroup hr p pre summary small".split(" "),x="audio canvas embed iframe img object param source track video".split(" "),y="a abbr b br cite code del dfn em i ins kbd mark span q samp s strong sub sup time u var wbr".split(" "),
k="b code del em i ins kbd span s strong u font".split(" "),p="address blockquote div dd dt h1 h2 h3 h4 h5 h6 p pre".split(" "),q="button datalist fieldset form input keygen label legend optgroup option output select textarea".split(" ");g.Element={isRoot:function(a){return m(a,u)},isSection:function(a){return m(a,l)},isContainer:function(a){return m(a,b)},isSubContainer:function(a){return m(a,d)},isBlock:function(a){return m(a,u,l,b,d,i)},isHTML4Block:function(a){return m(a,p)},isContentElement:function(a){return m(a,
d,i)},isMediaElement:function(a){return m(a,x)},isPhraseElement:function(a){return m(a,y)},isFormatter:function(a){return m(a,k)},isFormComponent:function(a){return m(a,q)},getRoots:function(){return u},getSections:function(){return l},getContainers:function(){return b},getSubContainers:function(){return d},getBlocks:function(){return u.concat(l,b,d,i)},getHTML4Blocks:function(){return p},getContentElements:function(){return d.concat(i)},getMediaElements:function(){return x},getPhraseElements:function(){return y},
getFormatters:function(){return k},getFormComponents:function(){return q}};e(j).ready(function(){var a=e(j),c,f;if("onselectionchange"in j&&"selection"in j)a.on("selectionchange",function(){var a=j.selection.createRange().parentElement();e(a).trigger("WysiHat-selection:change")});else f=function(){var a=j.activeElement,f=a.tagName.toLowerCase();if("textarea"==f||"input"==f)c=null;else{a=window.getSelection();if(1>a.rangeCount||(a=a.getRangeAt(0))&&a.equalRange(c))return;c=a;for(a=a.commonAncestorContainer;a.nodeType==
Node.TEXT_NODE;)a=a.parentNode}e(a).trigger("WysiHat-selection:change")},a.mouseup(f),a.keyup(f)});var n=g,s=e('<div id="paster" contentEditable="true"/>').css({width:"100%",height:10,position:"absolute",left:-9999});n.Paster={getHandler:function(a){return function(c,f){var b=a.Commands.getRanges(),h=b[0].startContainer,d=0;s.html("").css("top",e(j).scrollTop());s.appendTo(j.body);s.focus();setTimeout(function C(){if(!s.html()&&(d+=50,200>d)){setTimeout(C,50);return}var c=e(h).closest(g.Element.getBlocks().join(",")),
i=a.$editor.html();c.length?a.Formatting.cleanupPaste(s,c.get(0).tagName):a.Formatting.cleanupPaste(s);a.$editor.focus();a.Commands.restoreRanges(b);""==i||"<br>"==i||"<br/>"==i||"<p></p>"==i||"<p>\x00</p>"==i||i==a._empty()?a.$editor.html(s.html()):a.Commands.insertHTML(s.html());s=s.remove();f()},50);return!1}}};for(var z,v={3:"enter",8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",27:"esc",32:"space",37:"left",38:"up",39:"right",40:"down",46:"delete",91:"mod",92:"mod",93:"mod",59:";",
186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"\\",221:"]",222:"'",63232:"up",63233:"down",63234:"left",63235:"right",63272:"delete"},n=0;10>n;n++)v[n+48]=String(n);for(n=65;90>=n;n++)v[n]=String.fromCharCode(n);n=/AppleWebKit/.test(navigator.userAgent)&&/Mobile\/\w+/.test(navigator.userAgent)||/Mac/.test(navigator.platform)?"cmd":"ctrl";z={cut:n+"-x",copy:n+"-c",paste:n+"-v",undo:n+"-z",redo:n+"-shift-z",bold:n+"-b",italics:n+"-i",underline:n+"-u"};g.Event=function(a){this.Editor=
a;this.$editor=a.$editor;this.eventHandlers=[];this.pasteStart=this.textStart=null;this.textDeleting=!1;this.Undo=a.Undo;this.Selection=a.Selection;this._hijack_events();this.add("paste",g.Paster.getHandler(a))};g.Event.prototype={add:function(a,c){this.eventHandlers[a]=c},has:function(a){return a in this.eventHandlers},run:function(a,c,f){!1!==this.eventHandlers[a](c,f)&&f()},fire:function(a){var c=this,f,b;this._saveTextState(a);if("undo"==a||"redo"==a){if(this.Undo["undo"==a?"hasUndo":"hasRedo"]())b=
this.Undo[a](this.$editor.html()),this.$editor.html(b[0]),this.Selection.set(b[1])}else{if(!this.has(a))return!0;f=this.getState();b=function(){this.hasRun||(this.hasRun=!0,c.textChange(f),c._saveTextState(a),c.$editor.focus())};this.run(a,f,e.proxy(b,b))}},textChange:function(a,c){c=c||this.getState();this.Editor.selectEmptyParagraph();this.Undo.push(a.html,c.html,a.selection,c.selection)},isKeyCombo:function(a,c){var f="",b="",b=-1<a.indexOf("-");if(c.altGraphKey)return!1;c.metaKey&&(f+="cmd-");
c.altKey&&(f+="alt-");c.ctrlKey&&(f+="ctrl-");c.shiftKey&&(f+="shift-");if(!b&&1<a.length)return f.replace(/-$/,"")==a;b=v[c.keyCode];return!b?!1:a.toLowerCase()==(f+b).toLowerCase()},isEvent:function(a,c){var f=c.type;if(f==a)return!0;if("key"!=f.substr(0,3))return!1;f=z[a];return!f?!1:this.isKeyCombo(f,c)},getState:function(){return{html:this.$editor.html(),selection:this.Selection.get()}},_saveTextState:function(a){"redo"!=a&&this.textStart&&(this.textChange(this.textStart),this.textStart=null)},
_hijack_events:function(){var a={"selectionchange focusin mousedown":e.proxy(this._rangeEvent,this),"keydown keyup keypress":e.proxy(this._keyEvent,this),"cut undo redo paste input contextmenu":e.proxy(this._menuEvent,this)};this.$editor.on(a)},_keyComboEvent:function(a){var c=["undo","redo","paste"],f;if("keydown"==a.type)for(;f=c.shift();)if(this.isEvent(f,a)){if("paste"==f){this.fire(f);break}a.preventDefault();this.fire(f);return!1}return!0},_keyEvent:function(a){if("keypress"==a.type)return!0;
if(a.ctrlKey||a.altKey||a.metaKey)return this._keyComboEvent(a);if("keydown"==a.type)"backspace"==v[a.keyCode]?!1==this.textDeleting&&(this.textDeleting=!0,this._saveTextState("backspace")):!0==this.textDeleting&&(this.textDeleting=!1,this._saveTextState("keypress")),null==this.textStart&&(this.textStart=this.getState());else if("keyup"==a.type)switch(v[a.keyCode]){case "up":case "down":case "left":case "right":this._saveTextState("keyup")}},_rangeEvent:function(a){this._saveTextState(a.type)},_menuEvent:function(a){for(var c=
["undo","redo","paste"],f;f=c.shift();)this.isEvent(f,a)&&("paste"!=f&&a.preventDefault(),this.fire(f))}};g.Event.constructor=g.Event;g.Undo=function(){this.max_depth=75;this.saved=[];this.index=0};g.Undo.prototype={push:function(a,c,f,b){var h=[],d=this;if(h=e.isArray(a)?e.map(a,function(a,f){return d._diff(a,c[f])}):this._diff(a,c))this.index<this.saved.length&&(this.saved=this.saved.slice(0,this.index),this.index=this.saved.length),this.saved.length>this.max_depth&&(this.saved=this.saved.slice(this.saved.length-
this.max_depth),this.index=this.saved.length),this.index++,this.saved.push({changes:h,selection:[f,b]})},undo:function(a){this.index--;for(var c=this.saved[this.index],f=c.changes,b=f.length,h=0;h<b;h++)change=f[h],a=a.substring(0,change[0])+change[1]+a.substring(change[0]+change[2].length);return[a,c.selection[0]]},redo:function(a){for(var c=this.saved[this.index],f=c.changes,b=f.length-1;0<=b;b--)change=f[b],a=a.substring(0,change[0])+change[2]+a.substring(change[0]+change[1].length);this.index++;
return[a,c.selection[1]]},hasUndo:function(){return 0!=this.index},hasRedo:function(){return this.index!=this.saved.length},_diff:function(a,c){var f=a.length,b=c.length,h=0,e=0;if(a==c)return null;for(;h<f&&h<b&&a[h]==c[h];)h++;for(;e<f&&e<b&&a[f-e-1]==c[b-e-1];)e++;h==Math.min(f,b)&&(h=0);e==Math.min(f,b)&&(e=0);if(h||e)a=a.substring(h,f-e+1),c=c.substring(h,b-e+1),f=a.length,b=c.length;return f!==b&&(e=f<b?c.indexOf(a):a.indexOf(c),-1<e)?f<b?[[h,"",c.substr(0,e)],[h+f,"",c.substr(e+f)]]:[[h,a.substr(0,
e),""],[h+e+b,a.substr(e+b),""]]:[[h,a,c]]}};g.Undo.constructor=g.Undo;g.Selection=function(a){this.$editor=a;this.top=this.$editor.get(0)};g.Selection.prototype={_replace:RegExp("[\r\n]","g"),get:function(a){var c=window.getSelection(),f=j.createRange();if(a===t){if(!c.rangeCount)return[0,0];a=c.getRangeAt(0)}c=a.toString().replace(this._replace,"").length;f.setStart(this.top,0);f.setEnd(a.startContainer,a.startOffset);a=f.toString().replace(this._replace,"").length;return[a,a+c]},set:function(a,
c){e.isArray(a)&&(c=a[1],a=a[0]);var f=window.getSelection(),b=j.createRange(),h;h=this._getOffsetNode(this.top,a,!0);b.setStart.apply(b,h);c===t||c==a?b.collapse(!0):(h=this._getOffsetNode(this.top,c,!1),b.setEnd.apply(b,h));f.removeAllRanges();f.addRange(b)},toString:function(a){var c=window.getSelection();a===t&&(a=c.getRangeAt(0));return a.toString()},_getOffsetNode:function(a,c,f){function b(a){if(a.nodeType==Node.TEXT_NODE||a.nodeType==Node.CDATA_SECTION_NODE)0<c&&(h=a,c-=a.nodeValue.replace(/\n/g,
"").length);else for(var f=0,e=a.childNodes.length;0<c&&f<e;++f)b(a.childNodes[f])}var h=a,d=0,d=this.$editor.get(0).lastChild,i=g.Element.getBlocks();b(a);if(0==c){if(h.nodeType!=Node.TEXT_NODE){for(;null!==h.firstChild;)h=h.firstChild;return[h,0]}if(f){for(a=0;null===h.nextSibling&&h.parentNode!==d;)a++,h=h.parentNode;-1<e.inArray(h.nodeName.toLowerCase(),i)&&null!==h.nextSibling&&(h=h.nextSibling);for(;a&&h.firstChild&&"br"!=h.firstChild.nodeName.toLowerCase();)a--,h=h.firstChild}}d=h.nodeValue?
h.nodeValue.length:0;return[h,d+c]}};g.Selection.constructor=g.Selection;var n=g,r={is:{},make:{}},A={bold:"bold",italic:"italic",underline:"underline",strikethrough:"strikethrough",orderedList:"insertOrderedList",unorderedList:"insertUnorderedList"};e.each("bold underline italic strikethrough fontname fontsize forecolor createLink insertImage insertOrderedList insertUnorderedList".split(" "),function(a,c){r.make[c]=function(a){r.execCommand(c,!1,a)}});e.each({bold:"b, strong",italic:"i, em",link:"a[href]",
underline:"u, ins",indented:"blockquote",strikethrough:"s, del",orderedList:"ol",unorderedList:"ul"},function(a,c){r.is[a]=a in A?function(){return r.selectionIsWithin(c)||j.queryCommandState(A[a])}:function(){return r.selectionIsWithin(c)}});e.each({linked:"link",underlined:"underline",struckthrough:"strikethrough",ol:"orderedList",ul:"unorderedList"},function(a,c){r.is[a]=function(){return r.is[c]()}});e.each({italicize:"italic",font:"fontname",color:"forecolor",link:"createLink",ol:"insertOrderedList",
ul:"insertUnorderedList",orderedList:"insertOrderedList",unorderedList:"insertUnorderedList",align:"alignment"},function(a,c){r.make[a]=e.proxy(r.make,c)});r.noSpans=function(){try{return j.execCommand("styleWithCSS",0,!1),function(){j.execCommand("styleWithCSS",0,!1)}}catch(a){try{return j.execCommand("useCSS",0,!0),function(){j.execCommand("useCSS",0,!0)}}catch(c){try{return j.execCommand("styleWithCSS",!1,!1),function(){j.execCommand("styleWithCSS",!1,!1)}}catch(f){return e.noop}}}}();n.Commands=
r;e.extend(g.Commands,{_blockElements:g.Element.getContentElements().join(",").replace(",div,",",div:not(."+g.name+"-editor),"),styleSelectors:{fontname:"fontFamily",fontsize:"fontSize",forecolor:"color",hilitecolor:"backgroundColor",backcolor:"backgroundColor"},validCommands:"backColor bold createLink fontName fontSize foreColor hiliteColor italic removeFormat strikethrough subscript superscript underline unlink delete formatBlock forwardDelete indent insertHorizontalRule insertHTML insertImage insertLineBreak insertOrderedList insertParagraph insertText insertUnorderedList justifyCenter justifyFull justifyLeft justifyRight outdent copy cut paste selectAll styleWithCSS useCSS".split(" "),
execCommand:function(a,c,f){this.noSpans();try{j.execCommand(a,c,f)}catch(b){return null}},isMakeCommand:function(a){return a in this.make},isValidExecCommand:function(a){return-1<e.inArray(a,this.validCommands)},queryCommandState:function(a){if(a in this.is)return this.is[a]();try{return j.queryCommandState(a)}catch(c){return null}},selectionIsWithin:function(a){var c=g.Element.getPhraseElements(),f=!1,b=a.split(","),h=b.length,d=window.getSelection(),i=d.anchorNode,d=d.focusNode;i&&(i.nodeType&&
3==i.nodeType&&""==i.nodeValue)&&(i=i.nextSibling);if(!i)return!1;if(e.browser.mozilla){for(;h--;)if(-1!=e.inArray(b[h],c)){f=!0;break}if(f&&(1==i.nodeType&&-1==e.inArray(i.nodeName.toLowerCase(),c))&&(h=i.firstChild))""==h.nodeValue&&(h=h.nextSibling),1==h.nodeType&&(i=h)}for(;i&&d&&1!=i.nodeType&&1!=d.nodeType;)1!=i.nodeType&&(i=i.parentNode),1!=d.nodeType&&(d=d.parentNode);return!(!e(i).closest(a).length&&!e(d).closest(a).length)},getSelectedStyles:function(){var a=window.getSelection(),a=e(a.getNode()),
c={},f;for(f in this.styleSelectors)c[f]=a.css(this.styleSelectors[f]);return c},replaceElement:function(a,c){if(!a.hasClass(g.name+"-editor")){for(var f=a.get(0),b=e("<"+c+"/>").html(f.innerHTML),f=f.attributes,h=f.length||0;h--;)b.attr(f[h].name,f[h].value);a.replaceWith(b);return b}},deleteElement:function(a){a=e(a);a.replaceWith(a.html())},stripFormattingElements:function(){function a(f,h){var d=e(h);d.children().each(a);b(d)&&c.deleteElement(d)}for(var c=this,f=window.getSelection(),b=g.Element.isFormatter,
h=f.rangeCount,d=[],i;h--;)i=f.getRangeAt(h),d.push(i),this.getRangeElements(i,this._blockElements).each(a);this.restoreRanges(d)},manipulateSelection:function(){for(var a=window.getSelection(),c=a.rangeCount,f=[],b=arguments,e=b[0],d;c--;)d=a.getRangeAt(c),f.push(d),b[0]=d,e.apply(this,b);this.restoreRanges(f)},getRangeElements:function(a,c){var b=e(a.startContainer).closest(c),d=e(a.endContainer).closest(c),h=e("nullset");b.parents(".WysiHat-editor").length&&d.parents(".WysiHat-editor").length&&
(h=b,b.filter(d).length||(h=b.nextAll().filter(d).length?b.nextUntil(d).andSelf().add(d):b.prevUntil(d).andSelf().add(d)));return h},getRanges:function(){for(var a=window.getSelection(),c=a.rangeCount,b=[],d;c--;)d=a.getRangeAt(c),b.push(d);return b},restoreRanges:function(a){var c=window.getSelection(),b=a.length;for(c.removeAllRanges();b--;)c.addRange(a[b])},changeContentBlock:function(a){for(var c=window.getSelection(),b=this,d=e(b),h=c.rangeCount,i=[],g;h--;)g=c.getRangeAt(h),i.push(g),this.getRangeElements(g,
this._blockElements).each(function(){b.replaceElement(e(this),a)}).data("WysiHat-replaced",!0);d.children(a).removeData("WysiHat-replaced");this.restoreRanges(i)},unformatContentBlock:function(){this.changeContentBlock("p")},unlinkSelection:function(){this.manipulateSelection(function(a){this.getRangeElements(a,"[href]").each(this.clearElement)})},wrapHTML:function(){var a=window.getSelection(),c=a.getRangeAt(0),b=a.getNode(),d=arguments.length;c.collapsed&&(c=j.createRange(),c.selectNodeContents(b),
a.removeAllRanges(),a.addRange(c));for(c=a.getRangeAt(0);d--;)a=e("<"+arguments[d]+"/>"),c.surroundContents(a.get(0))},toggleHTML:function(a){var c=a.$editor,a=a.$element,b=c.data("field"),d=a.siblings(),e=a.data("text");c.is(":visible")?(a.find("b").text(a.data("toggle-text")),d.hide(),c.hide(),b.show()):(a.find("b").text(e),d.show(),b.hide(),c.show())},insertHTML:function(a){if(e.browser.msie){var c=j.selection.createRange();c.pasteHTML(a);c.collapse(!1);c.select()}else this.execCommand("insertHTML",
!1,a)},quoteSelection:function(){var a=e("<blockquote/>");this.manipulateSelection(function(a,b){var d=b.clone(),h=this.getRangeElements(a,this._blockElements),i=h.length-1,j=e();h.each(function(a){var c=e(this),b=!1;g.Element.isSubContainer(c)&&(b=!0);!a&&b&&a==i?(b=e("<p/>").html(c.html()),c.html("").append(b),j=j.add(b)):j=b?j.add(c.closest(g.Element.getContainers().join(","))):j.add(c);a==i&&j.wrapAll(d)})},a)},unquoteSelection:function(){this.manipulateSelection(function(a){this.getRangeElements(a,
"blockquote > *").each(function(){var a=this,b=e(a),d=b.closest("blockquote"),h=d.clone().html(""),d=d.children(),i=d.length-1,j=e();b.unwrap("blockquote");0<i&&d.each(function(b){this!=a&&(j=j.add(this));if(b==i||this==a)j.wrapAll(h.clone()),j=e()});d=b.parent();g.Element.isSubContainer(d)&&1==d.children().length&&d.html(b.html())})})}});e.extend(g.Commands.make,{blockquote:function(){g.Commands.is.indented()?g.Commands.unquoteSelection():g.Commands.quoteSelection()},alignment:function(a){g.Commands.execCommand("justify"+
a)},backgroundColor:function(a){g.Commands.execCommand(e.browser.mozilla?"hilitecolor":"backcolor",!1,a)}});var B={is:function(a){return g.Commands.is[a]()},make:function(a,c){return g.Commands.make[a](c)},toggle:function(a,c){return g.Commands.make[a](c)}};e.extend(g.Editor.prototype,B);g.Formatting={_bottomUp:function(a,c,b){a=a.find(c);a=e.makeArray(a).reverse();e.each(a,b)},cleanup:function(a){var c=g.Commands.replaceElement,b=g.Commands.deleteElement;a.contents().filter(function(){return this.nodeType==
Node.COMMENT_NODE}).remove();this._bottomUp(a,"span",function(){var a=e(this),b=a.css("font-weight"),b="bold"==b||500<b,f="italic"==a.css("font-style");a.hasClass("Apple-style-span")&&a.removeClass("Apple-style-span");a.removeAttr("style");f&&b?(a.wrap("<b>"),c(a,"i")):b?c(a,"b"):f&&c(a,"i")});a.children("div").each(function(){this.attributes.length||c(e(this),"p")}).end().find("strong").each(function(){c(e(this),"b")}).end().find("em").each(function(){c(e(this),"i")}).end().find("strike").each(function(){c(e(this),
"del")}).end().find("u").each(function(){c(e(this),"ins")}).end().find("p:empty,script,noscript,style").remove();a.find("b > b, i > i").each(function(){b(this)})},cleanupPaste:function(a,b){this.cleanup(a);this._bottomUp(a,"*",function(){var a=this.nodeName.toLowerCase(),b=j.createElement(a);switch(a){case "a":b.href=this.href;b.title=this.title;break;case "img":b.src=this.src,b.alt=this.alt}b.innerHTML=this.innerHTML;e(this).replaceWith(b)});a.find("br").replaceWith("\n");a.html(function(a,b){b=
e.trim(b);b=b.replace(/<\/p>\s*<p>/g,"\n\n").replace(/^(<p>)+/,"").replace(/(<\/p>)+$/,"").replace(/<\!--[^>]*--\>/g,"");if(-1==b.indexOf("\n"))return b;b=b.replace(/\n/,"<p>").replace(/\n/g,"\n</p><p>");return e.trim(b)+"</p>"});a.find("span").children(g.Element.getBlocks()).unwrap();a.find(":empty").remove();"p"!=b.toLowerCase()&&a.find(b).replaceWith(function(a,b){return b});var f,d=[];for(a.find("p ~ p").each(function(){var a=e(this),b=a.prev();f?e.trim(b.html())||(f.after("\n"),f=d.pop()):f=
b;f.html(function(b,c){var f=e.trim(a.html());(c=e.trim(c))&&f&&(c+="<br>");return c+f});d.push(a)});f=d.pop();)f.remove();a.before("\n").find("br").replaceWith("<br>\n")},reBlocks:RegExp("(<(?:ul|ol)>|</(?:"+g.Element.getBlocks().join("|")+")>)[\r\n]*","g"),format:function(a){a.html(function(a,b){return b.replace("<p>&nbsp;</p>","").replace(/<br\/?><\/p>/,"</p>").replace(this.reBlocks,"$1\n").replace(/\n+/,"\n").replace(/<p>\n+<\/p>/,"")})},getBrowserMarkupFrom:function(a){var a=e("<div>"+a.val().replace(/\n/,
"")+"</div>"),b;this.cleanup(a);b=a.html();(""==b||"<br>"==b||"<br/>"==b)&&a.html("<p>&#x200b;</p>");return a.html()},getApplicationMarkupFrom:function(a){var a=a.clone(),b,a=e("<div/>").html(a.html());b=a.html();(""==b||"<br>"==b||"<br/>"==b)&&a.html("<p>&#x200b;</p>");this.cleanup(a);this.format(a);a.find("*").html(function(a,b){return b.replace("\n","<br>\n").replace(/(<br>)+/g,"<br>").replace(/(\t| +)/g," ")});return a.html().replace(/<\/?[A-Z]+/g,function(a){return a.toLowerCase()})}};var D=
{init:function(a,b){this.name=a;this.$editor=b;this.$field=b.data("field");return this},setElement:function(a){this.$element=e(a);return this},getHandler:function(){if(this.handler)return e.proxy(this,"handler");var a=this;return g.Commands.isMakeCommand(this.name)?function(){return g.Commands.make[a.name]()}:g.Commands.isValidExecCommand(this.name)?function(){return g.Commands.execCommand(a.name)}:e.noop},getStateHandler:function(){if(this.query)return e.proxy(this,"query");if(g.Commands.isValidExecCommand(this.name)){var a=
this;return function(b){return b.data("wysihat").Commands.queryCommandState(a.name)}}return e.noop},setOn:function(){this.$element.addClass("selected").attr("aria-pressed","true").find("b").text(this["toggle-text"]?this["toggle-text"]:this.label);return this},setOff:function(){this.$element.removeClass("selected").attr("aria-pressed","false").find("b").text(this.label);return this}};g.Toolbar=function(a,b){this.suspendQueries=!1;this.$editor=a;this.$toolbar=e('<div class="'+g.name+'-editor-toolbar" role="presentation"></div>');
a.before(this.$toolbar);var f=b.length,d;for(d=0;d<f;d++)this.addButton(b[d])};g.Toolbar.prototype={addButton:function(a){var b=this.$editor.data("wysihat"),d=g.inherit(D,g._buttons[a]).init(a,b.$editor);e.extend(d,B);d.Editor=b;d.Event=b.Event;d.Commands=b.Commands;d.Selection=b.Selection;d.setElement(this.createButtonElement(d));d.Event.add(a,d.getHandler());this.observeButtonClick(d);this.observeStateChanges(d)},createButtonElement:function(a){var b;if(a.type&&"select"==a.type){var d=a.options,
i=d.length,h=0;for(b=e('<select class="button"/>');h<i;h++)b.append('<option value="'+d[h][0]+'">'+d[h][1]+"</option>");b.appendTo(this.$toolbar).wrap('<div class="button select-container"/>')}else b=e('<button aria-pressed="false" tabindex="-1"></button>'),b.append("<b>"+a.label+"</b>").addClass("button "+a.name).hover(function(){this.title=e(this).find("b").text()},function(){e(this).removeAttr("title")}).appendTo(this.$toolbar);a.cssClass&&b.addClass(a.cssClass);a.title&&b.attr("title",a.title);
b.data("text",a.label);a["toggle-text"]&&b.data("toggle-text",a["toggle-text"]);return b},observeButtonClick:function(a){var b=this;a.$element.on(a.type&&"select"==a.type?"change":"click",function(){b.suspendQueries=!0;var d=a.$editor;d.is(":focus")||d.focus();a.Event.fire(a.name);return b.suspendQueries=!1})},observeStateChanges:function(a){var b=this,d=a.getStateHandler(),e;b.$editor.on("WysiHat-selection:change",function(){if(!b.suspendQueries){var i=d(a.$editor,a.$element);i!=e&&(e=i,b.updateButtonState(a,
i))}})},updateButtonState:function(a,b){b?a.setOn():a.setOff()}};g.Toolbar.constructor=g.Toolbar})(document,jQuery);jQuery.fn.wysihat=function(j){var e=this.data("wysihat");return e?-1!=jQuery.inArray(j,["Event","Selection","Toolbar","Undo"])?e[j]:e:this.each(function(){e=WysiHat.attach(this,j);$(this).data("wysihat",e)})};
(function(j,e){"undefined"==typeof Node&&(window.Node=new function(){return{ATTRIBUTE_NODE:2,CDATA_SECTION_NODE:4,COMMENT_NODE:8,DOCUMENT_FRAGMENT_NODE:11,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,ELEMENT_NODE:1,ENTITY_NODE:6,ENTITY_REFERENCE_NODE:5,NOTATION_NODE:12,PROCESSING_INSTRUCTION_NODE:7,TEXT_NODE:3}});if(j.getSelection)window.Selection={},window.Selection.prototype=window.getSelection().__proto__;else{var t=function(){this.startContainer;this.startOffset;this.endContainer;this.endOffset;this.collapsed},
g=function(){this._reset();this._selection=j.selection},m=function(b,d){this.node=b;this.offset=d};t.prototype={setStart:function(b,d){this.startContainer=b;this.startOffset=d;b==this.endContainer&&d==this.endOffset&&(this.collapsed=!0)},setEnd:function(b,d){this.endContainer=b;this.endOffset=d;b==this.startContainer&&d==this.startOffset&&(this.collapsed=!0)},collapse:function(b){b?(this.endContainer=this.startContainer,this.endOffset=this.startOffset):(this.startContainer=this.endContainer,this.startOffset=
this.endOffset)},getNode:function(){var b=j.selection.createRange();return l.getParentElement(b)},selectNode:function(b){this.setStart(b.parentNode,l.getNodeIndex(b));this.setEnd(b.parentNode,l.getNodeIndex(b)+1)},insertNode:function(b){l.insertNode(b,this.startContainer,this.startOffset)},selectNodeContents:function(b){var d=l.isCharacterDataNode(b)?b.length:b.childNodes.length;this.setStart(b,0);this.setEnd(b,d)},surroundContents:function(){},cloneRange:function(){var b=new t;b.setStart(this.startContainer,
this.startOffset);b.setEnd(this.endContainer,this.endOffset);return b},toString:function(){var b=l.rangeToTextRange(this);return b?b.text:""}};j.createRange=function(){return new t};g.prototype={_reset:function(){this.rangeCount=0;this.focusOffset=this.focusNode=this.anchorOffset=this.anchorNode=null;this._ranges=[]},addRange:function(b){var d=l.rangeToTextRange(b);d?(d.select(),this.rangeCount=1,this._ranges=[b],this.isCollapsed=b.collapsed,this._updateNodeRefs(b)):this.removeAllRanges()},removeAllRanges:function(){this.rangeCount&&
this._selection.empty();this._reset()},getRangeAt:function(b){return 0!==b?null:this._ranges[b]},toString:function(){return this.rangeCount?this._ranges[0].toString():""},_refresh:function(){var b=this._selection.createRange(),d=l.getParentElement(b),e;0==b.compareEndPoints("StartToEnd",b)?b=e=l.getBoundary(b,d,!0,!0):(e=l.getBoundary(b,d,!0,!1),b=l.getBoundary(b,d,!1,!1));d=new t;d.setStart(e.node,e.offset);d.setEnd(b.node,b.offset);this.rangeCount=1;this._ranges=[d];this.isCollapsed=d.collapsed;
this._updateNodeRefs(d);return this},_updateNodeRefs:function(b){this.anchorNode=b.startContainer;this.anchorOffset=b.startOffset;this.focusNode=b.endContainer;this.focusOffset=b.endOffset}};var u=new g;window.getSelection=function(){return u._refresh()};var l={isCharacterDataNode:function(b){b=b.nodeType;return 3==b||4==b||8==b},getNodeIndex:function(b){for(var d=0;b=b.previousSibling;)d++;return d},isAncestorOf:function(b,d,e){for(d=e?d:d.parentNode;d;){if(d===b)return!0;d=d.parentNode}return!1},
getCommonAncestor:function(b,d){var i=[],g;for(g=b;g;g=g.parentNode)i.push(g);for(g=d;g;g=g.parentNode)if(-1<e.inArray(g,i))return g;return null},insertNode:function(b,d,g){var j=11==b.nodeType?b.firstChild:b;this.isCharacterDataNode(d)?g==d.length?e(b).insertAfter(d):d.parentNode.insertBefore(b,0==g?d:this.splitDataNode(d,g)):g>=d.childNodes.length?d.appendChild(b):d.insertBefore(b,d.childNodes[g]);return j},splitDataNode:function(b,d){var g=b.cloneNode(!1);g.deleteData(0,d);b.deleteData(d,b.length-
d);e(g).insertAfter(b);return g},rangeToTextRange:function(b){var d;d=this.createBoundaryTextRange(new m(b.startContainer,b.startOffset),!0);if(b.collapsed)return d;b=this.createBoundaryTextRange(new m(b.endContainer,b.endOffset),!1);if(!d||!b)return!1;textRange=j.body.createTextRange();textRange.setEndPoint("StartToStart",d);textRange.setEndPoint("EndToEnd",b);return textRange},getParentElement:function(b){var d=b.parentElement(),e,g;g=b.duplicate();g.collapse(!0);e=g.parentElement();g=b.duplicate();
g.collapse(!1);b=g.parentElement();e=e==b?e:this.getCommonAncestor(e,b);return e==d?e:this.getCommonAncestor(d,e)},createBoundaryTextRange:function(b,d){var g=b.offset,m=j.body.createTextRange(),l=this.isCharacterDataNode(b.node),k,p,q;l?(k=b.node,p=k.parentNode):(k=b.node.childNodes,k=g<k.length?k[g]:null,p=b.node);q=j.createElement("span");q.innerHTML="&#feff;";k?p.insertBefore(q,k):p.appendChild(q);if(!e.contains(j.body,q))return p.removeChild(q),null;m.moveToElementText(q);m.collapse(!d);p.removeChild(q);
if(l)m[d?"moveStart":"moveEnd"]("character",g);return m},getBoundary:function(b,d,e,g){var l=b.duplicate(),k;l.collapse(e);k=l.parentElement();this.isAncestorOf(d,k,!0)||(k=d);if(!k.canHaveHTML)return new m(k.parentNode,this.getNodeIndex(k));var d=j.createElement("span"),p=e?"StartToStart":"StartToEnd",q;do k.insertBefore(d,d.previousSibling),l.moveToElementText(d);while(0<(q=l.compareEndPoints(p,b))&&d.previousSibling);p=d.nextSibling;if(-1==q&&p&&this.isCharacterDataNode(p)){l.setEndPoint(e?"EndToStart":
"EndToEnd",b);if(/[\r\n]/.test(p.data)){k=l.duplicate();e=k.text.replace(/\r\n/g,"\r").length;for(e=k.moveStart("character",e);-1==k.compareEndPoints("StartToEnd",k);)e++,k.moveStart("character",1)}else e=l.text.length;k=new m(p,e)}else p=(g||!e)&&d.previousSibling,k=(e=(g||e)&&d.nextSibling)&&this.isCharacterDataNode(e)?new m(e,0):p&&this.isCharacterDataNode(p)?new m(p,p.length):new m(k,this.getNodeIndex(d));d.parentNode.removeChild(d);return k}};window.Range=t;window.Selection=g}e.extend(Range.prototype,
{equalRange:function(b){return!b||!b.compareBoundaryPoints?!1:this.collapsed&&b.collapsed?0==this.compareBoundaryPoints(this.START_TO_START,b):0==this.compareBoundaryPoints(this.START_TO_START,b)&&1==this.compareBoundaryPoints(this.START_TO_END,b)&&0==this.compareBoundaryPoints(this.END_TO_END,b)&&-1==this.compareBoundaryPoints(this.END_TO_START,b)}});e.extend(window.Selection.prototype,{getNode:function(){return 0<this.rangeCount?this.getRangeAt(0).getNode():null}})})(document,jQuery);
