<?php

require_once SYSPATH.'ee/EllisLab/ExpressionEngine/Boot/boot.common.php';
require_once APPPATH.'helpers/string_helper.php';
require_once APPPATH.'helpers/security_helper.php';
require_once APPPATH.'libraries/Functions.php';
require_once APPPATH.'libraries/Typography.php';
require_once APPPATH.'libraries/typography/Markdown/Michelf/MarkdownExtra.inc.php';

if ( ! defined('PATH_ADDONS'))
{
	define('PATH_ADDONS', APPPATH.'modules/');
}

if ( ! defined('REQ'))
{
	define('REQ', FALSE);
}


class LiteAllTest extends \PHPUnit_Framework_TestCase {

		private $typography;

	public function tearDown()
	{
		unset($this->typography);
	}


	public function setUp()
	{
		$this->typography = new EE_Typography();
	}

	private function getContentForMarkup($name)
	{
		$path = realpath(__DIR__.'/../../../../support/typography/' . $name);
		return file_get_contents($path);
	}

	/**
	 * There are number of preferences we can pass to the parse_type
	 * method that we need to test:
	 *
	 *  - text_format (xhtml, markdown, br, none, lite)
	 *  - html_format (safe, all, none)
	 *  - auto_links (y, n)
	 *  - allow_img_url (n, y)
	 */

	/**
	 * @dataProvider dataProvider
	 */
    public function testParseType($description, $in, $out)
    {
        $prefs = array(
            'text_format' => 'lite',
            'html_format' => 'all',
            'auto_links' => 'n',
            'allow_img_url' => 'y',
        );

        $parsed = $this->typography->parse_type($in, $prefs);
        $this->assertEquals($out, $parsed, '[Lite/All] ' . $description);
    }

	public function dataProvider()
	{
		$data = array(
			array('Empty string', '', ''),
		);

		$data = array_merge(
			$this->whitespaceData(),
			$this->punctuationData(),
			$this->HTMLWithClosingTagsData(),
			$this->HTMLWithoutClosingTagsData(),
			$this->HTMLWithContentData(),
			$this->HTMLAttributesData(),
			$this->HTMLWithAttributesData(),
			$this->BBCodeData(),
			$this->unprocessedMarkdownData(),
			$data
		);

		return $data;
	}

	protected function whitespaceData()
	{
		return array(
			array('Single spaces', 'a b', 'a b'),
			array('Double spaces', 'a  b', 'a  b'),
			array('Double spaces after a sentence', 'Word.  Word', 'Word.&nbsp; Word'),
			array('A tab converts to a space', "a\tb", "a\tb"),
			array('Tabs convert to spaces', "a\t\tb", "a\t\tb"),
			array('A return is not converted', "a\nb", "a\nb"),
			array('Multiple returns are not converted', "a\n\nb", "a\n\nb"),
		);
	}

	protected function punctuationData()
	{
		return array(
			array('Backtick', '`', '`'),
			array('Tilde', '~', '~'),
			array('Exclamation point', '!', '!'),
			array('At sign', '@', '@'),
			array('Pound/hash sign', '#', '#'),
			array('Dollar sign', '$', '$'),
			array('Percent sign', '%', '%'),
			array('Circumflex', '^', '^'),
			array('Ampersand', '&', '&amp;'),
			array('Asterisk', '*', '*'),
			array('Parentheses', '()', '()'),
			array('Underscore', '_', '_'),
			array('Hyphen', '-', '-'),
			array('Equals sign', '=', '='),
			array('Plus sign', '+', '+'),
			array('Brackets', '[]', '[]'),
			array('Braces', '{}', '&#123;&#125;'),
			array('Backslash', '\\', '\\'),
			array('Pipe', '|', '|'),
			array('Semicolon', ';', ';'),
			array('Colon', ':', ':'),
			array('Single quote', "'", '&#8217;'),
			array('Double quote', '"', '&#8221;'),
			array('Comma', ',', ','),
			array('Period', '.', '.'),
			array('Angle brackets', '<>', '<>'),
			array('Forward slash', '/', '/'),
			array('Question mark', '?', '?'),
			array('Em dash', '--', '&#8212;'),
			array('Ellipses', 'you know...', 'you know&#8230;'),
			array('Apostrophy', "It's its", 'It&#8217;s its'),
			array('US quote no whitespace', '"Hello"', '&#8220;Hello&#8221;'),
			array('UK quote no whitespace', "'Hello'", '&#8216;Hello&#8217;'),
			array('Simple nested US quote', '"I said, \'Hello\'"', '&#8220;I said, &#8216;Hello&#8217;&#8221;'),
			array('Simple nested UK quote', "'I said, \"Hello\"'", "&#8216;I said, &#8220;Hello&#8221;&#8217;"),
			array('US quote surrounded by whitespace', 'Foo "Bar" Baz', 'Foo &#8220;Bar&#8221; Baz'),
			array('UK quote surrounded by whitespace', "Foo 'Bar' Baz", 'Foo &#8216;Bar&#8217; Baz'),
		);
	}

	protected function HTMLWithClosingTagsData()
	{
		return array(
			array('<!-- -->', '<!-- -->', '<!&#8212;&#8212;>'),
			array('<a></a>', '<a></a>', '<a></a>'),
			array('<abbr></abbr>', '<abbr></abbr>', '<abbr></abbr>'),
			array('<acronym></acronym>', '<acronym></acronym>', '<acronym></acronym>'),
			array('<address></address>', '<address></address>', '<address></address>'),
			array('<applet></applet>', '<applet></applet>', '<applet></applet>'),
			array('<area></area>', '<area></area>', '<area></area>'),
			array('<article></article>', '<article></article>', '<article></article>'),
			array('<aside></aside>', '<aside></aside>', '<aside></aside>'),
			array('<audio></audio>', '<audio></audio>', '<audio></audio>'),
			array('<b></b>', '<b></b>', '<b></b>'),
			array('<base></base>', '<base></base>', '<base></base>'),
			array('<basefont></basefont>', '<basefont></basefont>', '<basefont></basefont>'),
			array('<bdi></bdi>', '<bdi></bdi>', '<bdi></bdi>'),
			array('<bdo></bdo>', '<bdo></bdo>', '<bdo></bdo>'),
			array('<big></big>', '<big></big>', '<big></big>'),
			array('<blockquote></blockquote>', '<blockquote></blockquote>', '<blockquote></blockquote>'),
			array('<body></body>', '<body></body>', '<body></body>'),
			array('<button></button>', '<button></button>', '<button></button>'),
			array('<canvas></canvas>', '<canvas></canvas>', '<canvas></canvas>'),
			array('<caption></caption>', '<caption></caption>', '<caption></caption>'),
			array('<center></center>', '<center></center>', '<center></center>'),
			array('<cite></cite>', '<cite></cite>', '<cite></cite>'),
			array('<code></code>', '<code></code>', '<code></code>'),
			array('<col></col>', '<col></col>', '<col></col>'),
			array('<colgroup></colgroup>', '<colgroup></colgroup>', '<colgroup></colgroup>'),
			array('<datalist></datalist>', '<datalist></datalist>', '<datalist></datalist>'),
			array('<dd></dd>', '<dd></dd>', '<dd></dd>'),
			array('<del></del>', '<del></del>', '<del></del>'),
			array('<details></details>', '<details></details>', '<details></details>'),
			array('<dfn></dfn>', '<dfn></dfn>', '<dfn></dfn>'),
			array('<dialog></dialog>', '<dialog></dialog>', '<dialog></dialog>'),
			array('<dir></dir>', '<dir></dir>', '<dir></dir>'),
			array('<div></div>', '<div></div>', '<div></div>'),
			array('<dl></dl>', '<dl></dl>', '<dl></dl>'),
			array('<dt></dt>', '<dt></dt>', '<dt></dt>'),
			array('<em></em>', '<em></em>', '<em></em>'),
			array('<embed></embed>', '<embed></embed>', '<embed></embed>'),
			array('<fieldset></fieldset>', '<fieldset></fieldset>', '<fieldset></fieldset>'),
			array('<figcaption></figcaption>', '<figcaption></figcaption>', '<figcaption></figcaption>'),
			array('<figure></figure>', '<figure></figure>', '<figure></figure>'),
			array('<font></font>', '<font></font>', '<font></font>'),
			array('<footer></footer>', '<footer></footer>', '<footer></footer>'),
			array('<form></form>', '<form></form>', '<form></form>'),
			array('<frame></frame>', '<frame></frame>', '<frame></frame>'),
			array('<frameset></frameset>', '<frameset></frameset>', '<frameset></frameset>'),
			array('<h1></h1>', '<h1></h1>', '<h1></h1>'),
			array('<h2></h2>', '<h2></h2>', '<h2></h2>'),
			array('<h3></h3>', '<h3></h3>', '<h3></h3>'),
			array('<h4></h4>', '<h4></h4>', '<h4></h4>'),
			array('<h5></h5>', '<h5></h5>', '<h5></h5>'),
			array('<h6></h6>', '<h6></h6>', '<h6></h6>'),
			array('<head></head>', '<head></head>', '<head></head>'),
			array('<header></header>', '<header></header>', '<header></header>'),
			array('<html></html>', '<html></html>', '<html></html>'),
			array('<i></i>', '<i></i>', '<i></i>'),
			array('<iframe></iframe>', '<iframe></iframe>', '<iframe></iframe>'),
			array('<ins></ins>', '<ins></ins>', '<ins></ins>'),
			array('<kbd></kbd>', '<kbd></kbd>', '<kbd></kbd>'),
			array('<keygen></keygen>', '<keygen></keygen>', '<keygen></keygen>'),
			array('<label></label>', '<label></label>', '<label></label>'),
			array('<legend></legend>', '<legend></legend>', '<legend></legend>'),
			array('<li></li>', '<li></li>', '<li></li>'),
			array('<link></link>', '<link></link>', '<link></link>'),
			array('<main></main>', '<main></main>', '<main></main>'),
			array('<map></map>', '<map></map>', '<map></map>'),
			array('<mark></mark>', '<mark></mark>', '<mark></mark>'),
			array('<menu></menu>', '<menu></menu>', '<menu></menu>'),
			array('<menuitem></menuitem>', '<menuitem></menuitem>', '<menuitem></menuitem>'),
			array('<meta></meta>', '<meta></meta>', '<meta></meta>'),
			array('<meter></meter>', '<meter></meter>', '<meter></meter>'),
			array('<nav></nav>', '<nav></nav>', '<nav></nav>'),
			array('<noframes></noframes>', '<noframes></noframes>', '<noframes></noframes>'),
			array('<noscript></noscript>', '<noscript></noscript>', '<noscript></noscript>'),
			array('<object></object>', '<object></object>', '<object></object>'),
			array('<ol></ol>', '<ol></ol>', '<ol></ol>'),
			array('<optgroup></optgroup>', '<optgroup></optgroup>', '<optgroup></optgroup>'),
			array('<option></option>', '<option></option>', '<option></option>'),
			array('<output></output>', '<output></output>', '<output></output>'),
			array('<p></p>', '<p></p>', '<p></p>'),
			array('<param></param>', '<param></param>', '<param></param>'),
			array('<picture></picture>', '<picture></picture>', '<picture></picture>'),
			array('<pre></pre>', '<pre></pre>', '<pre></pre>'),
			array('<progress></progress>', '<progress></progress>', '<progress></progress>'),
			array('<q></q>', '<q></q>', '<q></q>'),
			array('<rp></rp>', '<rp></rp>', '<rp></rp>'),
			array('<rt></rt>', '<rt></rt>', '<rt></rt>'),
			array('<ruby></ruby>', '<ruby></ruby>', '<ruby></ruby>'),
			array('<s></s>', '<s></s>', '<s></s>'),
			array('<samp></samp>', '<samp></samp>', '<samp></samp>'),
			array('<script></script>', '<script></script>', '<script></script>'),
			array('<section></section>', '<section></section>', '<section></section>'),
			array('<select></select>', '<select></select>', '<select></select>'),
			array('<small></small>', '<small></small>', '<small></small>'),
			array('<source></source>', '<source></source>', '<source></source>'),
			array('<span></span>', '<span></span>', '<span></span>'),
			array('<strike></strike>', '<strike></strike>', '<strike></strike>'),
			array('<strong></strong>', '<strong></strong>', '<strong></strong>'),
			array('<style></style>', '<style></style>', '<style></style>'),
			array('<sub></sub>', '<sub></sub>', '<sub></sub>'),
			array('<summary></summary>', '<summary></summary>', '<summary></summary>'),
			array('<sup></sup>', '<sup></sup>', '<sup></sup>'),
			array('<table></table>', '<table></table>', '<table></table>'),
			array('<tbody></tbody>', '<tbody></tbody>', '<tbody></tbody>'),
			array('<td></td>', '<td></td>', '<td></td>'),
			array('<textarea></textarea>', '<textarea></textarea>', '<textarea></textarea>'),
			array('<tfoot></tfoot>', '<tfoot></tfoot>', '<tfoot></tfoot>'),
			array('<th></th>', '<th></th>', '<th></th>'),
			array('<thead></thead>', '<thead></thead>', '<thead></thead>'),
			array('<time></time>', '<time></time>', '<time></time>'),
			array('<title></title>', '<title></title>', '<title></title>'),
			array('<tr></tr>', '<tr></tr>', '<tr></tr>'),
			array('<track></track>', '<track></track>', '<track></track>'),
			array('<tt></tt>', '<tt></tt>', '<tt></tt>'),
			array('<u></u>', '<u></u>', '<u></u>'),
			array('<ul></ul>', '<ul></ul>', '<ul></ul>'),
			array('<var></var>', '<var></var>', '<var></var>'),
			array('<video></video>', '<video></video>', '<video></video>'),
			array('<wbr></wbr>', '<wbr></wbr>', '<wbr></wbr>'),
		);
	}

	protected function HTMLWithoutClosingTagsData()
	{
		return array(
			array('<!--', '<!--', '<!&#8212;'),
			array('<a>', '<a>', '<a>'),
			array('<abbr>', '<abbr>', '<abbr>'),
			array('<acronym>', '<acronym>', '<acronym>'),
			array('<address>', '<address>', '<address>'),
			array('<applet>', '<applet>', '<applet>'),
			array('<area>', '<area>', '<area>'),
			array('<article>', '<article>', '<article>'),
			array('<aside>', '<aside>', '<aside>'),
			array('<audio>', '<audio>', '<audio>'),
			array('<b>', '<b>', '<b>'),
			array('<base>', '<base>', '<base>'),
			array('<basefont>', '<basefont>', '<basefont>'),
			array('<bdi>', '<bdi>', '<bdi>'),
			array('<bdo>', '<bdo>', '<bdo>'),
			array('<big>', '<big>', '<big>'),
			array('<blockquote>', '<blockquote>', '<blockquote>'),
			array('<body>', '<body>', '<body>'),
			array('<br>', '<br>', '<br>'),
			array('<button>', '<button>', '<button>'),
			array('<canvas>', '<canvas>', '<canvas>'),
			array('<caption>', '<caption>', '<caption>'),
			array('<center>', '<center>', '<center>'),
			array('<cite>', '<cite>', '<cite>'),
			array('<code>', '<code>', '<code>'),
			array('<col>', '<col>', '<col>'),
			array('<colgroup>', '<colgroup>', '<colgroup>'),
			array('<datalist>', '<datalist>', '<datalist>'),
			array('<dd>', '<dd>', '<dd>'),
			array('<del>', '<del>', '<del>'),
			array('<details>', '<details>', '<details>'),
			array('<dfn>', '<dfn>', '<dfn>'),
			array('<dialog>', '<dialog>', '<dialog>'),
			array('<dir>', '<dir>', '<dir>'),
			array('<div>', '<div>', '<div>'),
			array('<dl>', '<dl>', '<dl>'),
			array('<dt>', '<dt>', '<dt>'),
			array('<em>', '<em>', '<em>'),
			array('<embed>', '<embed>', '<embed>'),
			array('<fieldset>', '<fieldset>', '<fieldset>'),
			array('<figcaption>', '<figcaption>', '<figcaption>'),
			array('<figure>', '<figure>', '<figure>'),
			array('<font>', '<font>', '<font>'),
			array('<footer>', '<footer>', '<footer>'),
			array('<form>', '<form>', '<form>'),
			array('<frame>', '<frame>', '<frame>'),
			array('<frameset>', '<frameset>', '<frameset>'),
			array('<h1>', '<h1>', '<h1>'),
			array('<h2>', '<h2>', '<h2>'),
			array('<h3>', '<h3>', '<h3>'),
			array('<h4>', '<h4>', '<h4>'),
			array('<h5>', '<h5>', '<h5>'),
			array('<h6>', '<h6>', '<h6>'),
			array('<head>', '<head>', '<head>'),
			array('<header>', '<header>', '<header>'),
			array('<hr>', '<hr>', '<hr>'),
			array('<html>', '<html>', '<html>'),
			array('<i>', '<i>', '<i>'),
			array('<iframe>', '<iframe>', '<iframe>'),
			array('<img>', '<img>', '<img>'),
			array('<input>', '<input>', '<input>'),
			array('<ins>', '<ins>', '<ins>'),
			array('<kbd>', '<kbd>', '<kbd>'),
			array('<keygen>', '<keygen>', '<keygen>'),
			array('<label>', '<label>', '<label>'),
			array('<legend>', '<legend>', '<legend>'),
			array('<li>', '<li>', '<li>'),
			array('<link>', '<link>', '<link>'),
			array('<main>', '<main>', '<main>'),
			array('<map>', '<map>', '<map>'),
			array('<mark>', '<mark>', '<mark>'),
			array('<menu>', '<menu>', '<menu>'),
			array('<menuitem>', '<menuitem>', '<menuitem>'),
			array('<meta>', '<meta>', '<meta>'),
			array('<meter>', '<meter>', '<meter>'),
			array('<nav>', '<nav>', '<nav>'),
			array('<noframes>', '<noframes>', '<noframes>'),
			array('<noscript>', '<noscript>', '<noscript>'),
			array('<object>', '<object>', '<object>'),
			array('<ol>', '<ol>', '<ol>'),
			array('<optgroup>', '<optgroup>', '<optgroup>'),
			array('<option>', '<option>', '<option>'),
			array('<output>', '<output>', '<output>'),
			array('<p>', '<p>', '<p>'),
			array('<param>', '<param>', '<param>'),
			array('<picture>', '<picture>', '<picture>'),
			array('<pre>', '<pre>', '<pre>'),
			array('<progress>', '<progress>', '<progress>'),
			array('<q>', '<q>', '<q>'),
			array('<rp>', '<rp>', '<rp>'),
			array('<rt>', '<rt>', '<rt>'),
			array('<ruby>', '<ruby>', '<ruby>'),
			array('<s>', '<s>', '<s>'),
			array('<samp>', '<samp>', '<samp>'),
			array('<script>', '<script>', '<script>'),
			array('<section>', '<section>', '<section>'),
			array('<select>', '<select>', '<select>'),
			array('<small>', '<small>', '<small>'),
			array('<source>', '<source>', '<source>'),
			array('<span>', '<span>', '<span>'),
			array('<strike>', '<strike>', '<strike>'),
			array('<strong>', '<strong>', '<strong>'),
			array('<style>', '<style>', '<style>'),
			array('<sub>', '<sub>', '<sub>'),
			array('<summary>', '<summary>', '<summary>'),
			array('<sup>', '<sup>', '<sup>'),
			array('<table>', '<table>', '<table>'),
			array('<tbody>', '<tbody>', '<tbody>'),
			array('<td>', '<td>', '<td>'),
			array('<textarea>', '<textarea>', '<textarea>'),
			array('<tfoot>', '<tfoot>', '<tfoot>'),
			array('<th>', '<th>', '<th>'),
			array('<thead>', '<thead>', '<thead>'),
			array('<time>', '<time>', '<time>'),
			array('<title>', '<title>', '<title>'),
			array('<tr>', '<tr>', '<tr>'),
			array('<track>', '<track>', '<track>'),
			array('<tt>', '<tt>', '<tt>'),
			array('<u>', '<u>', '<u>'),
			array('<ul>', '<ul>', '<ul>'),
			array('<var>', '<var>', '<var>'),
			array('<video>', '<video>', '<video>'),
			array('<wbr>', '<wbr>', '<wbr>'),
		);
	}

	protected function HTMLWithContentData()
	{
		return array(
			array('<!-- foobar -->', '<!-- foobar -->', '<!&#8212;foobar&#8212;>'),
			array('<a>foobar</a>', '<a>foobar</a>', '<a>foobar</a>'),
			array('<abbr>foobar</abbr>', '<abbr>foobar</abbr>', '<abbr>foobar</abbr>'),
			array('<acronym>foobar</acronym>', '<acronym>foobar</acronym>', '<acronym>foobar</acronym>'),
			array('<address>foobar</address>', '<address>foobar</address>', '<address>foobar</address>'),
			array('<applet>foobar</applet>', '<applet>foobar</applet>', '<applet>foobar</applet>'),
			array('<area>foobar</area>', '<area>foobar</area>', '<area>foobar</area>'),
			array('<article>foobar</article>', '<article>foobar</article>', '<article>foobar</article>'),
			array('<aside>foobar</aside>', '<aside>foobar</aside>', '<aside>foobar</aside>'),
			array('<audio>foobar</audio>', '<audio>foobar</audio>', '<audio>foobar</audio>'),
			array('<b>foobar</b>', '<b>foobar</b>', '<b>foobar</b>'),
			array('<base>foobar</base>', '<base>foobar</base>', '<base>foobar</base>'),
			array('<basefont>foobar</basefont>', '<basefont>foobar</basefont>', '<basefont>foobar</basefont>'),
			array('<bdi>foobar</bdi>', '<bdi>foobar</bdi>', '<bdi>foobar</bdi>'),
			array('<bdo>foobar</bdo>', '<bdo>foobar</bdo>', '<bdo>foobar</bdo>'),
			array('<big>foobar</big>', '<big>foobar</big>', '<big>foobar</big>'),
			array('<blockquote>foobar</blockquote>', '<blockquote>foobar</blockquote>', '<blockquote>foobar</blockquote>'),
			array('<body>foobar</body>', '<body>foobar</body>', '<body>foobar</body>'),
			array('<button>foobar</button>', '<button>foobar</button>', '<button>foobar</button>'),
			array('<canvas>foobar</canvas>', '<canvas>foobar</canvas>', '<canvas>foobar</canvas>'),
			array('<caption>foobar</caption>', '<caption>foobar</caption>', '<caption>foobar</caption>'),
			array('<center>foobar</center>', '<center>foobar</center>', '<center>foobar</center>'),
			array('<cite>foobar</cite>', '<cite>foobar</cite>', '<cite>foobar</cite>'),
			array('<code>foobar</code>', '<code>foobar</code>', '<code>foobar</code>'),
			array('<col>foobar</col>', '<col>foobar</col>', '<col>foobar</col>'),
			array('<colgroup>foobar</colgroup>', '<colgroup>foobar</colgroup>', '<colgroup>foobar</colgroup>'),
			array('<datalist>foobar</datalist>', '<datalist>foobar</datalist>', '<datalist>foobar</datalist>'),
			array('<dd>foobar</dd>', '<dd>foobar</dd>', '<dd>foobar</dd>'),
			array('<del>foobar</del>', '<del>foobar</del>', '<del>foobar</del>'),
			array('<details>foobar</details>', '<details>foobar</details>', '<details>foobar</details>'),
			array('<dfn>foobar</dfn>', '<dfn>foobar</dfn>', '<dfn>foobar</dfn>'),
			array('<dialog>foobar</dialog>', '<dialog>foobar</dialog>', '<dialog>foobar</dialog>'),
			array('<dir>foobar</dir>', '<dir>foobar</dir>', '<dir>foobar</dir>'),
			array('<div>foobar</div>', '<div>foobar</div>', '<div>foobar</div>'),
			array('<dl>foobar</dl>', '<dl>foobar</dl>', '<dl>foobar</dl>'),
			array('<dt>foobar</dt>', '<dt>foobar</dt>', '<dt>foobar</dt>'),
			array('<em>foobar</em>', '<em>foobar</em>', '<em>foobar</em>'),
			array('<embed>foobar</embed>', '<embed>foobar</embed>', '<embed>foobar</embed>'),
			array('<fieldset>foobar</fieldset>', '<fieldset>foobar</fieldset>', '<fieldset>foobar</fieldset>'),
			array('<figcaption>foobar</figcaption>', '<figcaption>foobar</figcaption>', '<figcaption>foobar</figcaption>'),
			array('<figure>foobar</figure>', '<figure>foobar</figure>', '<figure>foobar</figure>'),
			array('<font>foobar</font>', '<font>foobar</font>', '<font>foobar</font>'),
			array('<footer>foobar</footer>', '<footer>foobar</footer>', '<footer>foobar</footer>'),
			array('<form>foobar</form>', '<form>foobar</form>', '<form>foobar</form>'),
			array('<frame>foobar</frame>', '<frame>foobar</frame>', '<frame>foobar</frame>'),
			array('<frameset>foobar</frameset>', '<frameset>foobar</frameset>', '<frameset>foobar</frameset>'),
			array('<h1>foobar</h1>', '<h1>foobar</h1>', '<h1>foobar</h1>'),
			array('<h2>foobar</h2>', '<h2>foobar</h2>', '<h2>foobar</h2>'),
			array('<h3>foobar</h3>', '<h3>foobar</h3>', '<h3>foobar</h3>'),
			array('<h4>foobar</h4>', '<h4>foobar</h4>', '<h4>foobar</h4>'),
			array('<h5>foobar</h5>', '<h5>foobar</h5>', '<h5>foobar</h5>'),
			array('<h6>foobar</h6>', '<h6>foobar</h6>', '<h6>foobar</h6>'),
			array('<head>foobar</head>', '<head>foobar</head>', '<head>foobar</head>'),
			array('<header>foobar</header>', '<header>foobar</header>', '<header>foobar</header>'),
			array('<html>foobar</html>', '<html>foobar</html>', '<html>foobar</html>'),
			array('<i>foobar</i>', '<i>foobar</i>', '<i>foobar</i>'),
			array('<iframe>foobar</iframe>', '<iframe>foobar</iframe>', '<iframe>foobar</iframe>'),
			array('<ins>foobar</ins>', '<ins>foobar</ins>', '<ins>foobar</ins>'),
			array('<kbd>foobar</kbd>', '<kbd>foobar</kbd>', '<kbd>foobar</kbd>'),
			array('<keygen>foobar</keygen>', '<keygen>foobar</keygen>', '<keygen>foobar</keygen>'),
			array('<label>foobar</label>', '<label>foobar</label>', '<label>foobar</label>'),
			array('<legend>foobar</legend>', '<legend>foobar</legend>', '<legend>foobar</legend>'),
			array('<li>foobar</li>', '<li>foobar</li>', '<li>foobar</li>'),
			array('<link>foobar</link>', '<link>foobar</link>', '<link>foobar</link>'),
			array('<main>foobar</main>', '<main>foobar</main>', '<main>foobar</main>'),
			array('<map>foobar</map>', '<map>foobar</map>', '<map>foobar</map>'),
			array('<mark>foobar</mark>', '<mark>foobar</mark>', '<mark>foobar</mark>'),
			array('<menu>foobar</menu>', '<menu>foobar</menu>', '<menu>foobar</menu>'),
			array('<menuitem>foobar</menuitem>', '<menuitem>foobar</menuitem>', '<menuitem>foobar</menuitem>'),
			array('<meta>foobar</meta>', '<meta>foobar</meta>', '<meta>foobar</meta>'),
			array('<meter>foobar</meter>', '<meter>foobar</meter>', '<meter>foobar</meter>'),
			array('<nav>foobar</nav>', '<nav>foobar</nav>', '<nav>foobar</nav>'),
			array('<noframes>foobar</noframes>', '<noframes>foobar</noframes>', '<noframes>foobar</noframes>'),
			array('<noscript>foobar</noscript>', '<noscript>foobar</noscript>', '<noscript>foobar</noscript>'),
			array('<object>foobar</object>', '<object>foobar</object>', '<object>foobar</object>'),
			array('<ol>foobar</ol>', '<ol>foobar</ol>', '<ol>foobar</ol>'),
			array('<optgroup>foobar</optgroup>', '<optgroup>foobar</optgroup>', '<optgroup>foobar</optgroup>'),
			array('<option>foobar</option>', '<option>foobar</option>', '<option>foobar</option>'),
			array('<output>foobar</output>', '<output>foobar</output>', '<output>foobar</output>'),
			array('<p>foobar</p>', '<p>foobar</p>', '<p>foobar</p>'),
			array('<param>foobar</param>', '<param>foobar</param>', '<param>foobar</param>'),
			array('<picture>foobar</picture>', '<picture>foobar</picture>', '<picture>foobar</picture>'),
			array('<pre>foobar</pre>', '<pre>foobar</pre>', '<pre>foobar</pre>'),
			array('<progress>foobar</progress>', '<progress>foobar</progress>', '<progress>foobar</progress>'),
			array('<q>foobar</q>', '<q>foobar</q>', '<q>foobar</q>'),
			array('<rp>foobar</rp>', '<rp>foobar</rp>', '<rp>foobar</rp>'),
			array('<rt>foobar</rt>', '<rt>foobar</rt>', '<rt>foobar</rt>'),
			array('<ruby>foobar</ruby>', '<ruby>foobar</ruby>', '<ruby>foobar</ruby>'),
			array('<s>foobar</s>', '<s>foobar</s>', '<s>foobar</s>'),
			array('<samp>foobar</samp>', '<samp>foobar</samp>', '<samp>foobar</samp>'),
			array('<script>foobar</script>', '<script>foobar</script>', '<script>foobar</script>'),
			array('<section>foobar</section>', '<section>foobar</section>', '<section>foobar</section>'),
			array('<select>foobar</select>', '<select>foobar</select>', '<select>foobar</select>'),
			array('<small>foobar</small>', '<small>foobar</small>', '<small>foobar</small>'),
			array('<source>foobar</source>', '<source>foobar</source>', '<source>foobar</source>'),
			array('<span>foobar</span>', '<span>foobar</span>', '<span>foobar</span>'),
			array('<strike>foobar</strike>', '<strike>foobar</strike>', '<strike>foobar</strike>'),
			array('<strong>foobar</strong>', '<strong>foobar</strong>', '<strong>foobar</strong>'),
			array('<style>foobar</style>', '<style>foobar</style>', '<style>foobar</style>'),
			array('<sub>foobar</sub>', '<sub>foobar</sub>', '<sub>foobar</sub>'),
			array('<summary>foobar</summary>', '<summary>foobar</summary>', '<summary>foobar</summary>'),
			array('<sup>foobar</sup>', '<sup>foobar</sup>', '<sup>foobar</sup>'),
			array('<table>foobar</table>', '<table>foobar</table>', '<table>foobar</table>'),
			array('<tbody>foobar</tbody>', '<tbody>foobar</tbody>', '<tbody>foobar</tbody>'),
			array('<td>foobar</td>', '<td>foobar</td>', '<td>foobar</td>'),
			array('<textarea>foobar</textarea>', '<textarea>foobar</textarea>', '<textarea>foobar</textarea>'),
			array('<tfoot>foobar</tfoot>', '<tfoot>foobar</tfoot>', '<tfoot>foobar</tfoot>'),
			array('<th>foobar</th>', '<th>foobar</th>', '<th>foobar</th>'),
			array('<thead>foobar</thead>', '<thead>foobar</thead>', '<thead>foobar</thead>'),
			array('<time>foobar</time>', '<time>foobar</time>', '<time>foobar</time>'),
			array('<title>foobar</title>', '<title>foobar</title>', '<title>foobar</title>'),
			array('<tr>foobar</tr>', '<tr>foobar</tr>', '<tr>foobar</tr>'),
			array('<track>foobar</track>', '<track>foobar</track>', '<track>foobar</track>'),
			array('<tt>foobar</tt>', '<tt>foobar</tt>', '<tt>foobar</tt>'),
			array('<u>foobar</u>', '<u>foobar</u>', '<u>foobar</u>'),
			array('<ul>foobar</ul>', '<ul>foobar</ul>', '<ul>foobar</ul>'),
			array('<var>foobar</var>', '<var>foobar</var>', '<var>foobar</var>'),
			array('<video>foobar</video>', '<video>foobar</video>', '<video>foobar</video>'),
			array('<wbr>foobar</wbr>', '<wbr>foobar</wbr>', '<wbr>foobar</wbr>'),
		);
	}

	protected function HTMLAttributesData()
	{
		return array(
			array('async', '<div async>', '<div async>'),
			array('autofocus', '<div autofocus>', '<div autofocus>'),
			array('autoplay', '<div autoplay>', '<div autoplay>'),
			array('challenge', '<div challenge>', '<div challenge>'),
			array('checked', '<div checked>', '<div checked>'),
			array('controls', '<div controls>', '<div controls>'),
			array('default', '<div default>', '<div default>'),
			array('defer', '<div defer>', '<div defer>'),
			array('disabled', '<div disabled>', '<div disabled>'),
			array('hidden', '<div hidden>', '<div hidden>'),
			array('ismap', '<div ismap>', '<div ismap>'),
			array('loop', '<div loop>', '<div loop>'),
			array('multiple', '<div multiple>', '<div multiple>'),
			array('muted', '<div muted>', '<div muted>'),
			array('novalidate', '<div novalidate>', '<div novalidate>'),
			array('readonly', '<div readonly>', '<div readonly>'),
			array('required', '<div required>', '<div required>'),
			array('reversed', '<div reversed>', '<div reversed>'),
			array('sandbox', '<div sandbox>', '<div sandbox>'),
			array('scoped', '<div scoped>', '<div scoped>'),
			array('selected', '<div selected>', '<div selected>'),

			array('accept', '<div accept="foo">', '<div accept=&#8220;foo&#8221;>'),
			array('accept-charset', '<div accept-charset="foo">', '<div accept-charset=&#8220;foo&#8221;>'),
			array('accesskey', '<div accesskey="foo">', '<div accesskey=&#8220;foo&#8221;>'),
			array('action', '<div action="foo">', '<div action=&#8220;foo&#8221;>'),
			array('align', '<div align="foo">', '<div align=&#8220;foo&#8221;>'),
			array('alt', '<div alt="foo">', '<div alt=&#8220;foo&#8221;>'),
			array('autocomplete', '<div autocomplete="foo">', '<div autocomplete=&#8220;foo&#8221;>'),
			array('bgcolor', '<div bgcolor="foo">', '<div bgcolor=&#8220;foo&#8221;>'),
			array('border', '<div border="foo">', '<div border=&#8220;foo&#8221;>'),
			array('charset', '<div charset="foo">', '<div charset=&#8220;foo&#8221;>'),
			array('cite', '<div cite="foo">', '<div cite=&#8220;foo&#8221;>'),
			array('class', '<div class="foo">', '<div class=&#8220;foo&#8221;>'),
			array('color', '<div color="foo">', '<div color=&#8220;foo&#8221;>'),
			array('cols', '<div cols="foo">', '<div cols=&#8220;foo&#8221;>'),
			array('colspan', '<div colspan="foo">', '<div colspan=&#8220;foo&#8221;>'),
			array('content', '<div content="foo">', '<div content=&#8220;foo&#8221;>'),
			array('contenteditable', '<div contenteditable="foo">', '<div contenteditable=&#8220;foo&#8221;>'),
			array('contextmenu', '<div contextmenu="foo">', '<div contextmenu=&#8220;foo&#8221;>'),
			array('coords', '<div coords="foo">', '<div coords=&#8220;foo&#8221;>'),
			array('data', '<div data="foo">', '<div data=&#8220;foo&#8221;>'),
			array('data', '<div data="foo">', '<div data=&#8220;foo&#8221;>'),
			array('datetime', '<div datetime="foo">', '<div datetime=&#8220;foo&#8221;>'),
			array('dir', '<div dir="foo">', '<div dir=&#8220;foo&#8221;>'),
			array('dirname', '<div dirname="foo">', '<div dirname=&#8220;foo&#8221;>'),
			array('download', '<div download="foo">', '<div download=&#8220;foo&#8221;>'),
			array('draggable', '<div draggable="foo">', '<div draggable=&#8220;foo&#8221;>'),
			array('dropzone', '<div dropzone="foo">', '<div dropzone=&#8220;foo&#8221;>'),
			array('enctype', '<div enctype="foo">', '<div enctype=&#8220;foo&#8221;>'),
			array('for', '<div for="foo">', '<div for=&#8220;foo&#8221;>'),
			array('form', '<div form="foo">', '<div form=&#8220;foo&#8221;>'),
			array('formaction', '<div formaction="foo">', '<div formaction=&#8220;foo&#8221;>'),
			array('headers', '<div headers="foo">', '<div headers=&#8220;foo&#8221;>'),
			array('height', '<div height="foo">', '<div height=&#8220;foo&#8221;>'),
			array('high', '<div high="foo">', '<div high=&#8220;foo&#8221;>'),
			array('href', '<div href="foo">', '<div href=&#8220;foo&#8221;>'),
			array('hreflang', '<div hreflang="foo">', '<div hreflang=&#8220;foo&#8221;>'),
			array('http', '<div http="foo">', '<div http=&#8220;foo&#8221;>'),
			array('id', '<div id="foo">', '<div id=&#8220;foo&#8221;>'),
			array('keytype', '<div keytype="foo">', '<div keytype=&#8220;foo&#8221;>'),
			array('kind', '<div kind="foo">', '<div kind=&#8220;foo&#8221;>'),
			array('label', '<div label="foo">', '<div label=&#8220;foo&#8221;>'),
			array('lang', '<div lang="foo">', '<div lang=&#8220;foo&#8221;>'),
			array('list', '<div list="foo">', '<div list=&#8220;foo&#8221;>'),
			array('low', '<div low="foo">', '<div low=&#8220;foo&#8221;>'),
			array('max', '<div max="foo">', '<div max=&#8220;foo&#8221;>'),
			array('maxlength', '<div maxlength="foo">', '<div maxlength=&#8220;foo&#8221;>'),
			array('media', '<div media="foo">', '<div media=&#8220;foo&#8221;>'),
			array('method', '<div method="foo">', '<div method=&#8220;foo&#8221;>'),
			array('min', '<div min="foo">', '<div min=&#8220;foo&#8221;>'),
			array('name', '<div name="foo">', '<div name=&#8220;foo&#8221;>'),
			array('onabort', '<div onabort="foo">', '<div onabort=&#8220;foo&#8221;>'),
			array('onafterprint', '<div onafterprint="foo">', '<div onafterprint=&#8220;foo&#8221;>'),
			array('onbeforeprint', '<div onbeforeprint="foo">', '<div onbeforeprint=&#8220;foo&#8221;>'),
			array('onbeforeunload', '<div onbeforeunload="foo">', '<div onbeforeunload=&#8220;foo&#8221;>'),
			array('onblur', '<div onblur="foo">', '<div onblur=&#8220;foo&#8221;>'),
			array('oncanplay', '<div oncanplay="foo">', '<div oncanplay=&#8220;foo&#8221;>'),
			array('oncanplaythrough', '<div oncanplaythrough="foo">', '<div oncanplaythrough=&#8220;foo&#8221;>'),
			array('onchange', '<div onchange="foo">', '<div onchange=&#8220;foo&#8221;>'),
			array('onclick', '<div onclick="foo">', '<div onclick=&#8220;foo&#8221;>'),
			array('oncontextmenu', '<div oncontextmenu="foo">', '<div oncontextmenu=&#8220;foo&#8221;>'),
			array('oncopy', '<div oncopy="foo">', '<div oncopy=&#8220;foo&#8221;>'),
			array('oncuechange', '<div oncuechange="foo">', '<div oncuechange=&#8220;foo&#8221;>'),
			array('oncut', '<div oncut="foo">', '<div oncut=&#8220;foo&#8221;>'),
			array('ondblclick', '<div ondblclick="foo">', '<div ondblclick=&#8220;foo&#8221;>'),
			array('ondrag', '<div ondrag="foo">', '<div ondrag=&#8220;foo&#8221;>'),
			array('ondragend', '<div ondragend="foo">', '<div ondragend=&#8220;foo&#8221;>'),
			array('ondragenter', '<div ondragenter="foo">', '<div ondragenter=&#8220;foo&#8221;>'),
			array('ondragleave', '<div ondragleave="foo">', '<div ondragleave=&#8220;foo&#8221;>'),
			array('ondragover', '<div ondragover="foo">', '<div ondragover=&#8220;foo&#8221;>'),
			array('ondragstart', '<div ondragstart="foo">', '<div ondragstart=&#8220;foo&#8221;>'),
			array('ondrop', '<div ondrop="foo">', '<div ondrop=&#8220;foo&#8221;>'),
			array('ondurationchange', '<div ondurationchange="foo">', '<div ondurationchange=&#8220;foo&#8221;>'),
			array('onemptied', '<div onemptied="foo">', '<div onemptied=&#8220;foo&#8221;>'),
			array('onended', '<div onended="foo">', '<div onended=&#8220;foo&#8221;>'),
			array('onerror', '<div onerror="foo">', '<div onerror=&#8220;foo&#8221;>'),
			array('onfocus', '<div onfocus="foo">', '<div onfocus=&#8220;foo&#8221;>'),
			array('onhashchange', '<div onhashchange="foo">', '<div onhashchange=&#8220;foo&#8221;>'),
			array('oninput', '<div oninput="foo">', '<div oninput=&#8220;foo&#8221;>'),
			array('oninvalid', '<div oninvalid="foo">', '<div oninvalid=&#8220;foo&#8221;>'),
			array('onkeydown', '<div onkeydown="foo">', '<div onkeydown=&#8220;foo&#8221;>'),
			array('onkeypress', '<div onkeypress="foo">', '<div onkeypress=&#8220;foo&#8221;>'),
			array('onkeyup', '<div onkeyup="foo">', '<div onkeyup=&#8220;foo&#8221;>'),
			array('onload', '<div onload="foo">', '<div onload=&#8220;foo&#8221;>'),
			array('onloadeddata', '<div onloadeddata="foo">', '<div onloadeddata=&#8220;foo&#8221;>'),
			array('onloadedmetadata', '<div onloadedmetadata="foo">', '<div onloadedmetadata=&#8220;foo&#8221;>'),
			array('onloadstart', '<div onloadstart="foo">', '<div onloadstart=&#8220;foo&#8221;>'),
			array('onmousedown', '<div onmousedown="foo">', '<div onmousedown=&#8220;foo&#8221;>'),
			array('onmousemove', '<div onmousemove="foo">', '<div onmousemove=&#8220;foo&#8221;>'),
			array('onmouseout', '<div onmouseout="foo">', '<div onmouseout=&#8220;foo&#8221;>'),
			array('onmouseover', '<div onmouseover="foo">', '<div onmouseover=&#8220;foo&#8221;>'),
			array('onmouseup', '<div onmouseup="foo">', '<div onmouseup=&#8220;foo&#8221;>'),
			array('onmousewheel', '<div onmousewheel="foo">', '<div onmousewheel=&#8220;foo&#8221;>'),
			array('onoffline', '<div onoffline="foo">', '<div onoffline=&#8220;foo&#8221;>'),
			array('ononline', '<div ononline="foo">', '<div ononline=&#8220;foo&#8221;>'),
			array('onpagehide', '<div onpagehide="foo">', '<div onpagehide=&#8220;foo&#8221;>'),
			array('onpageshow', '<div onpageshow="foo">', '<div onpageshow=&#8220;foo&#8221;>'),
			array('onpaste', '<div onpaste="foo">', '<div onpaste=&#8220;foo&#8221;>'),
			array('onpause', '<div onpause="foo">', '<div onpause=&#8220;foo&#8221;>'),
			array('onplay', '<div onplay="foo">', '<div onplay=&#8220;foo&#8221;>'),
			array('onplaying', '<div onplaying="foo">', '<div onplaying=&#8220;foo&#8221;>'),
			array('onpopstate', '<div onpopstate="foo">', '<div onpopstate=&#8220;foo&#8221;>'),
			array('onprogress', '<div onprogress="foo">', '<div onprogress=&#8220;foo&#8221;>'),
			array('onratechange', '<div onratechange="foo">', '<div onratechange=&#8220;foo&#8221;>'),
			array('onreset', '<div onreset="foo">', '<div onreset=&#8220;foo&#8221;>'),
			array('onresize', '<div onresize="foo">', '<div onresize=&#8220;foo&#8221;>'),
			array('onscroll', '<div onscroll="foo">', '<div onscroll=&#8220;foo&#8221;>'),
			array('onsearch', '<div onsearch="foo">', '<div onsearch=&#8220;foo&#8221;>'),
			array('onseeked', '<div onseeked="foo">', '<div onseeked=&#8220;foo&#8221;>'),
			array('onseeking', '<div onseeking="foo">', '<div onseeking=&#8220;foo&#8221;>'),
			array('onselect', '<div onselect="foo">', '<div onselect=&#8220;foo&#8221;>'),
			array('onshow', '<div onshow="foo">', '<div onshow=&#8220;foo&#8221;>'),
			array('onstalled', '<div onstalled="foo">', '<div onstalled=&#8220;foo&#8221;>'),
			array('onstorage', '<div onstorage="foo">', '<div onstorage=&#8220;foo&#8221;>'),
			array('onsubmit', '<div onsubmit="foo">', '<div onsubmit=&#8220;foo&#8221;>'),
			array('onsuspend', '<div onsuspend="foo">', '<div onsuspend=&#8220;foo&#8221;>'),
			array('ontimeupdate', '<div ontimeupdate="foo">', '<div ontimeupdate=&#8220;foo&#8221;>'),
			array('ontoggle', '<div ontoggle="foo">', '<div ontoggle=&#8220;foo&#8221;>'),
			array('onunload', '<div onunload="foo">', '<div onunload=&#8220;foo&#8221;>'),
			array('onvolumechange', '<div onvolumechange="foo">', '<div onvolumechange=&#8220;foo&#8221;>'),
			array('onwaiting', '<div onwaiting="foo">', '<div onwaiting=&#8220;foo&#8221;>'),
			array('onwheel', '<div onwheel="foo">', '<div onwheel=&#8220;foo&#8221;>'),
			array('open', '<div open="foo">', '<div open=&#8220;foo&#8221;>'),
			array('optimum', '<div optimum="foo">', '<div optimum=&#8220;foo&#8221;>'),
			array('pattern', '<div pattern="foo">', '<div pattern=&#8220;foo&#8221;>'),
			array('placeholder', '<div placeholder="foo">', '<div placeholder=&#8220;foo&#8221;>'),
			array('poster', '<div poster="foo">', '<div poster=&#8220;foo&#8221;>'),
			array('preload', '<div preload="foo">', '<div preload=&#8220;foo&#8221;>'),
			array('rel', '<div rel="foo">', '<div rel=&#8220;foo&#8221;>'),
			array('rows', '<div rows="foo">', '<div rows=&#8220;foo&#8221;>'),
			array('rowspan', '<div rowspan="foo">', '<div rowspan=&#8220;foo&#8221;>'),
			array('scope', '<div scope="foo">', '<div scope=&#8220;foo&#8221;>'),
			array('shape', '<div shape="foo">', '<div shape=&#8220;foo&#8221;>'),
			array('size', '<div size="foo">', '<div size=&#8220;foo&#8221;>'),
			array('sizes', '<div sizes="foo">', '<div sizes=&#8220;foo&#8221;>'),
			array('span', '<div span="foo">', '<div span=&#8220;foo&#8221;>'),
			array('spellcheck', '<div spellcheck="foo">', '<div spellcheck=&#8220;foo&#8221;>'),
			array('src', '<div src="foo">', '<div src=&#8220;foo&#8221;>'),
			array('srcdoc', '<div srcdoc="foo">', '<div srcdoc=&#8220;foo&#8221;>'),
			array('srclang', '<div srclang="foo">', '<div srclang=&#8220;foo&#8221;>'),
			array('srcset', '<div srcset="foo">', '<div srcset=&#8220;foo&#8221;>'),
			array('start', '<div start="foo">', '<div start=&#8220;foo&#8221;>'),
			array('step', '<div step="foo">', '<div step=&#8220;foo&#8221;>'),
			array('style', '<div style="foo">', '<div style=&#8220;foo&#8221;>'),
			array('tabindex', '<div tabindex="foo">', '<div tabindex=&#8220;foo&#8221;>'),
			array('target', '<div target="foo">', '<div target=&#8220;foo&#8221;>'),
			array('title', '<div title="foo">', '<div title=&#8220;foo&#8221;>'),
			array('translate', '<div translate="foo">', '<div translate=&#8220;foo&#8221;>'),
			array('type', '<div type="foo">', '<div type=&#8220;foo&#8221;>'),
			array('usemap', '<div usemap="foo">', '<div usemap=&#8220;foo&#8221;>'),
			array('value', '<div value="foo">', '<div value=&#8220;foo&#8221;>'),
			array('width', '<div width="foo">', '<div width=&#8220;foo&#8221;>'),
			array('wrap', '<div wrap="foo">', '<div wrap=&#8220;foo&#8221;>'),
		);
	}

	protected function HTMLWithAttributesData()
	{
		$all_attributes = 'async autofocus autoplay challenge checked controls default defer disabled hidden ismap loop multiple muted novalidate readonly required reversed sandbox scoped selected accept="foo" accept-charset="foo" accesskey="foo" action="foo" align="foo" alt="foo" autocomplete="foo" bgcolor="foo" border="foo" charset="foo" cite="foo" class="foo" color="foo" cols="foo" colspan="foo" content="foo" contenteditable="foo" contextmenu="foo" coords="foo" data="foo" data="foo" datetime="foo" dir="foo" dirname="foo" download="foo" draggable="foo" dropzone="foo" enctype="foo" for="foo" form="foo" formaction="foo" headers="foo" height="foo" high="foo" href="foo" hreflang="foo" http="foo" id="foo" keytype="foo" kind="foo" label="foo" lang="foo" list="foo" low="foo" max="foo" maxlength="foo" media="foo" method="foo" min="foo" name="foo" onabort="foo" onafterprint="foo" onbeforeprint="foo" onbeforeunload="foo" onblur="foo" oncanplay="foo" oncanplaythrough="foo" onchange="foo" onclick="foo" oncontextmenu="foo" oncopy="foo" oncuechange="foo" oncut="foo" ondblclick="foo" ondrag="foo" ondragend="foo" ondragenter="foo" ondragleave="foo" ondragover="foo" ondragstart="foo" ondrop="foo" ondurationchange="foo" onemptied="foo" onended="foo" onerror="foo" onfocus="foo" onhashchange="foo" oninput="foo" oninvalid="foo" onkeydown="foo" onkeypress="foo" onkeyup="foo" onload="foo" onloadeddata="foo" onloadedmetadata="foo" onloadstart="foo" onmousedown="foo" onmousemove="foo" onmouseout="foo" onmouseover="foo" onmouseup="foo" onmousewheel="foo" onoffline="foo" ononline="foo" onpagehide="foo" onpageshow="foo" onpaste="foo" onpause="foo" onplay="foo" onplaying="foo" onpopstate="foo" onprogress="foo" onratechange="foo" onreset="foo" onresize="foo" onscroll="foo" onsearch="foo" onseeked="foo" onseeking="foo" onselect="foo" onshow="foo" onstalled="foo" onstorage="foo" onsubmit="foo" onsuspend="foo" ontimeupdate="foo" ontoggle="foo" onunload="foo" onvolumechange="foo" onwaiting="foo" onwheel="foo" open="foo" optimum="foo" pattern="foo" placeholder="foo" poster="foo" preload="foo" rel="foo" rows="foo" rowspan="foo" scope="foo" shape="foo" size="foo" sizes="foo" span="foo" spellcheck="foo" src="foo" srcdoc="foo" srclang="foo" srcset="foo" start="foo" step="foo" style="foo" tabindex="foo" target="foo" title="foo" translate="foo" type="foo" usemap="foo" value="foo" width="foo" wrap="foo"';
		$allowed_attributes = 'async autofocus autoplay challenge checked controls default defer disabled hidden ismap loop multiple muted novalidate readonly required reversed sandbox scoped selected accept=&#8220;foo&#8221; accept-charset=&#8220;foo&#8221; accesskey=&#8220;foo&#8221; action=&#8220;foo&#8221; align=&#8220;foo&#8221; alt=&#8220;foo&#8221; autocomplete=&#8220;foo&#8221; bgcolor=&#8220;foo&#8221; border=&#8220;foo&#8221; charset=&#8220;foo&#8221; cite=&#8220;foo&#8221; class=&#8220;foo&#8221; color=&#8220;foo&#8221; cols=&#8220;foo&#8221; colspan=&#8220;foo&#8221; content=&#8220;foo&#8221; contenteditable=&#8220;foo&#8221; contextmenu=&#8220;foo&#8221; coords=&#8220;foo&#8221; data=&#8220;foo&#8221; data=&#8220;foo&#8221; datetime=&#8220;foo&#8221; dir=&#8220;foo&#8221; dirname=&#8220;foo&#8221; download=&#8220;foo&#8221; draggable=&#8220;foo&#8221; dropzone=&#8220;foo&#8221; enctype=&#8220;foo&#8221; for=&#8220;foo&#8221; form=&#8220;foo&#8221; formaction=&#8220;foo&#8221; headers=&#8220;foo&#8221; height=&#8220;foo&#8221; high=&#8220;foo&#8221; href=&#8220;foo&#8221; hreflang=&#8220;foo&#8221; http=&#8220;foo&#8221; id=&#8220;foo&#8221; keytype=&#8220;foo&#8221; kind=&#8220;foo&#8221; label=&#8220;foo&#8221; lang=&#8220;foo&#8221; list=&#8220;foo&#8221; low=&#8220;foo&#8221; max=&#8220;foo&#8221; maxlength=&#8220;foo&#8221; media=&#8220;foo&#8221; method=&#8220;foo&#8221; min=&#8220;foo&#8221; name=&#8220;foo&#8221; onabort=&#8220;foo&#8221; onafterprint=&#8220;foo&#8221; onbeforeprint=&#8220;foo&#8221; onbeforeunload=&#8220;foo&#8221; onblur=&#8220;foo&#8221; oncanplay=&#8220;foo&#8221; oncanplaythrough=&#8220;foo&#8221; onchange=&#8220;foo&#8221; onclick=&#8220;foo&#8221; oncontextmenu=&#8220;foo&#8221; oncopy=&#8220;foo&#8221; oncuechange=&#8220;foo&#8221; oncut=&#8220;foo&#8221; ondblclick=&#8220;foo&#8221; ondrag=&#8220;foo&#8221; ondragend=&#8220;foo&#8221; ondragenter=&#8220;foo&#8221; ondragleave=&#8220;foo&#8221; ondragover=&#8220;foo&#8221; ondragstart=&#8220;foo&#8221; ondrop=&#8220;foo&#8221; ondurationchange=&#8220;foo&#8221; onemptied=&#8220;foo&#8221; onended=&#8220;foo&#8221; onerror=&#8220;foo&#8221; onfocus=&#8220;foo&#8221; onhashchange=&#8220;foo&#8221; oninput=&#8220;foo&#8221; oninvalid=&#8220;foo&#8221; onkeydown=&#8220;foo&#8221; onkeypress=&#8220;foo&#8221; onkeyup=&#8220;foo&#8221; onload=&#8220;foo&#8221; onloadeddata=&#8220;foo&#8221; onloadedmetadata=&#8220;foo&#8221; onloadstart=&#8220;foo&#8221; onmousedown=&#8220;foo&#8221; onmousemove=&#8220;foo&#8221; onmouseout=&#8220;foo&#8221; onmouseover=&#8220;foo&#8221; onmouseup=&#8220;foo&#8221; onmousewheel=&#8220;foo&#8221; onoffline=&#8220;foo&#8221; ononline=&#8220;foo&#8221; onpagehide=&#8220;foo&#8221; onpageshow=&#8220;foo&#8221; onpaste=&#8220;foo&#8221; onpause=&#8220;foo&#8221; onplay=&#8220;foo&#8221; onplaying=&#8220;foo&#8221; onpopstate=&#8220;foo&#8221; onprogress=&#8220;foo&#8221; onratechange=&#8220;foo&#8221; onreset=&#8220;foo&#8221; onresize=&#8220;foo&#8221; onscroll=&#8220;foo&#8221; onsearch=&#8220;foo&#8221; onseeked=&#8220;foo&#8221; onseeking=&#8220;foo&#8221; onselect=&#8220;foo&#8221; onshow=&#8220;foo&#8221; onstalled=&#8220;foo&#8221; onstorage=&#8220;foo&#8221; onsubmit=&#8220;foo&#8221; onsuspend=&#8220;foo&#8221; ontimeupdate=&#8220;foo&#8221; ontoggle=&#8220;foo&#8221; onunload=&#8220;foo&#8221; onvolumechange=&#8220;foo&#8221; onwaiting=&#8220;foo&#8221; onwheel=&#8220;foo&#8221; open=&#8220;foo&#8221; optimum=&#8220;foo&#8221; pattern=&#8220;foo&#8221; placeholder=&#8220;foo&#8221; poster=&#8220;foo&#8221; preload=&#8220;foo&#8221; rel=&#8220;foo&#8221; rows=&#8220;foo&#8221; rowspan=&#8220;foo&#8221; scope=&#8220;foo&#8221; shape=&#8220;foo&#8221; size=&#8220;foo&#8221; sizes=&#8220;foo&#8221; span=&#8220;foo&#8221; spellcheck=&#8220;foo&#8221; src=&#8220;foo&#8221; srcdoc=&#8220;foo&#8221; srclang=&#8220;foo&#8221; srcset=&#8220;foo&#8221; start=&#8220;foo&#8221; step=&#8220;foo&#8221; style=&#8220;foo&#8221; tabindex=&#8220;foo&#8221; target=&#8220;foo&#8221; title=&#8220;foo&#8221; translate=&#8220;foo&#8221; type=&#8220;foo&#8221; usemap=&#8220;foo&#8221; value=&#8220;foo&#8221; width=&#8220;foo&#8221; wrap=&#8220;foo&#8221;';

		return array(
			array('<a> with attributes', '<a ' . $all_attributes . '></a>', '<a ' . $allowed_attributes . '></a>'),
			array('<abbr> with attributes', '<abbr ' . $all_attributes . '></abbr>', '<abbr ' . $allowed_attributes . '></abbr>'),
			array('<acronym> with attributes', '<acronym ' . $all_attributes . '></acronym>', '<acronym ' . $allowed_attributes . '></acronym>'),
			array('<address> with attributes', '<address ' . $all_attributes . '></address>', '<address ' . $allowed_attributes . '></address>'),
			array('<applet> with attributes', '<applet ' . $all_attributes . '></applet>', '<applet ' . $allowed_attributes . '></applet>'),
			array('<area> with attributes', '<area ' . $all_attributes . '></area>', '<area ' . $allowed_attributes . '></area>'),
			array('<article> with attributes', '<article ' . $all_attributes . '></article>', '<article ' . $allowed_attributes . '></article>'),
			array('<aside> with attributes', '<aside ' . $all_attributes . '></aside>', '<aside ' . $allowed_attributes . '></aside>'),
			array('<audio> with attributes', '<audio ' . $all_attributes . '></audio>', '<audio ' . $allowed_attributes . '></audio>'),
			array('<b> with attributes', '<b ' . $all_attributes . '></b>', '<b ' . $allowed_attributes . '></b>'),
			array('<base> with attributes', '<base ' . $all_attributes . '></base>', '<base ' . $allowed_attributes . '></base>'),
			array('<basefont> with attributes', '<basefont ' . $all_attributes . '></basefont>', '<basefont ' . $allowed_attributes . '></basefont>'),
			array('<bdi> with attributes', '<bdi ' . $all_attributes . '></bdi>', '<bdi ' . $allowed_attributes . '></bdi>'),
			array('<bdo> with attributes', '<bdo ' . $all_attributes . '></bdo>', '<bdo ' . $allowed_attributes . '></bdo>'),
			array('<big> with attributes', '<big ' . $all_attributes . '></big>', '<big ' . $allowed_attributes . '></big>'),
			array('<blockquote> with attributes', '<blockquote ' . $all_attributes . '></blockquote>', '<blockquote ' . $allowed_attributes . '></blockquote>'),
			array('<body> with attributes', '<body ' . $all_attributes . '></body>', '<body ' . $allowed_attributes . '></body>'),
			array('<br> with attributes', '<br ' . $all_attributes . '>', '<br ' . $allowed_attributes . '>'),
			array('<button> with attributes', '<button ' . $all_attributes . '></button>', '<button ' . $allowed_attributes . '></button>'),
			array('<canvas> with attributes', '<canvas ' . $all_attributes . '></canvas>', '<canvas ' . $allowed_attributes . '></canvas>'),
			array('<caption> with attributes', '<caption ' . $all_attributes . '></caption>', '<caption ' . $allowed_attributes . '></caption>'),
			array('<center> with attributes', '<center ' . $all_attributes . '></center>', '<center ' . $allowed_attributes . '></center>'),
			array('<cite> with attributes', '<cite ' . $all_attributes . '></cite>', '<cite ' . $allowed_attributes . '></cite>'),
			array('<code> with attributes', '<code ' . $all_attributes . '></code>', '<code ' . $allowed_attributes .'></code>'),
			array('<col> with attributes', '<col ' . $all_attributes . '></col>', '<col ' . $allowed_attributes . '></col>'),
			array('<colgroup> with attributes', '<colgroup ' . $all_attributes . '></colgroup>', '<colgroup ' . $allowed_attributes . '></colgroup>'),
			array('<datalist> with attributes', '<datalist ' . $all_attributes . '></datalist>', '<datalist ' . $allowed_attributes . '></datalist>'),
			array('<dd> with attributes', '<dd ' . $all_attributes . '></dd>', '<dd ' . $allowed_attributes . '></dd>'),
			array('<del> with attributes', '<del ' . $all_attributes . '></del>', '<del ' . $allowed_attributes . '></del>'),
			array('<details> with attributes', '<details ' . $all_attributes . '></details>', '<details ' . $allowed_attributes . '></details>'),
			array('<dfn> with attributes', '<dfn ' . $all_attributes . '></dfn>', '<dfn ' . $allowed_attributes . '></dfn>'),
			array('<dialog> with attributes', '<dialog ' . $all_attributes . '></dialog>', '<dialog ' . $allowed_attributes . '></dialog>'),
			array('<dir> with attributes', '<dir ' . $all_attributes . '></dir>', '<dir ' . $allowed_attributes . '></dir>'),
			array('<div> with attributes', '<div ' . $all_attributes . '></div>', '<div ' . $allowed_attributes . '></div>'),
			array('<dl> with attributes', '<dl ' . $all_attributes . '></dl>', '<dl ' . $allowed_attributes . '></dl>'),
			array('<dt> with attributes', '<dt ' . $all_attributes . '></dt>', '<dt ' . $allowed_attributes . '></dt>'),
			array('<em> with attributes', '<em ' . $all_attributes . '></em>', '<em ' . $allowed_attributes . '></em>'),
			array('<embed> with attributes', '<embed ' . $all_attributes . '></embed>', '<embed ' . $allowed_attributes . '></embed>'),
			array('<fieldset> with attributes', '<fieldset ' . $all_attributes . '></fieldset>', '<fieldset ' . $allowed_attributes . '></fieldset>'),
			array('<figcaption> with attributes', '<figcaption ' . $all_attributes . '></figcaption>', '<figcaption ' . $allowed_attributes . '></figcaption>'),
			array('<figure> with attributes', '<figure ' . $all_attributes . '></figure>', '<figure ' . $allowed_attributes . '></figure>'),
			array('<font> with attributes', '<font ' . $all_attributes . '></font>', '<font ' . $allowed_attributes . '></font>'),
			array('<footer> with attributes', '<footer ' . $all_attributes . '></footer>', '<footer ' . $allowed_attributes . '></footer>'),
			array('<form> with attributes', '<form ' . $all_attributes . '></form>', '<form ' . $allowed_attributes . '></form>'),
			array('<frame> with attributes', '<frame ' . $all_attributes . '></frame>', '<frame ' . $allowed_attributes . '></frame>'),
			array('<frameset> with attributes', '<frameset ' . $all_attributes . '></frameset>', '<frameset ' . $allowed_attributes . '></frameset>'),
			array('<h1> with attributes', '<h1 ' . $all_attributes . '></h1>', '<h1 ' . $allowed_attributes . '></h1>'),
			array('<h2> with attributes', '<h2 ' . $all_attributes . '></h2>', '<h2 ' . $allowed_attributes . '></h2>'),
			array('<h3> with attributes', '<h3 ' . $all_attributes . '></h3>', '<h3 ' . $allowed_attributes . '></h3>'),
			array('<h4> with attributes', '<h4 ' . $all_attributes . '></h4>', '<h4 ' . $allowed_attributes . '></h4>'),
			array('<h5> with attributes', '<h5 ' . $all_attributes . '></h5>', '<h5 ' . $allowed_attributes . '></h5>'),
			array('<h6> with attributes', '<h6 ' . $all_attributes . '></h6>', '<h6 ' . $allowed_attributes . '></h6>'),
			array('<head> with attributes', '<head ' . $all_attributes . '></head>', '<head ' . $allowed_attributes . '></head>'),
			array('<header> with attributes', '<header ' . $all_attributes . '></header>', '<header ' . $allowed_attributes . '></header>'),
			array('<html> with attributes', '<html ' . $all_attributes . '></html>', '<html ' . $allowed_attributes . '></html>'),
			array('<i> with attributes', '<i ' . $all_attributes . '></i>', '<i ' . $allowed_attributes . '></i>'),
			array('<iframe> with attributes', '<iframe ' . $all_attributes . '></iframe>', '<iframe ' . $allowed_attributes . '></iframe>'),
			array('<img> with attributes', '<img ' . $all_attributes . '>', '<img ' . $allowed_attributes . '>'),
			array('<input> with attributes', '<input ' . $all_attributes . '>', '<input ' . $allowed_attributes . '>'),
			array('<ins> with attributes', '<ins ' . $all_attributes . '></ins>', '<ins ' . $allowed_attributes . '></ins>'),
			array('<kbd> with attributes', '<kbd ' . $all_attributes . '></kbd>', '<kbd ' . $allowed_attributes . '></kbd>'),
			array('<keygen> with attributes', '<keygen ' . $all_attributes . '></keygen>', '<keygen ' . $allowed_attributes . '></keygen>'),
			array('<label> with attributes', '<label ' . $all_attributes . '></label>', '<label ' . $allowed_attributes . '></label>'),
			array('<legend> with attributes', '<legend ' . $all_attributes . '></legend>', '<legend ' . $allowed_attributes . '></legend>'),
			array('<li> with attributes', '<li ' . $all_attributes . '></li>', '<li ' . $allowed_attributes . '></li>'),
			array('<link> with attributes', '<link ' . $all_attributes . '></link>', '<link ' . $allowed_attributes . '></link>'),
			array('<main> with attributes', '<main ' . $all_attributes . '></main>', '<main ' . $allowed_attributes . '></main>'),
			array('<map> with attributes', '<map ' . $all_attributes . '></map>', '<map ' . $allowed_attributes . '></map>'),
			array('<mark> with attributes', '<mark ' . $all_attributes . '></mark>', '<mark ' . $allowed_attributes .'></mark>'),
			array('<menu> with attributes', '<menu ' . $all_attributes . '></menu>', '<menu ' . $allowed_attributes . '></menu>'),
			array('<menuitem> with attributes', '<menuitem ' . $all_attributes . '></menuitem>', '<menuitem ' . $allowed_attributes . '></menuitem>'),
			array('<meta> with attributes', '<meta ' . $all_attributes . '></meta>', '<meta ' . $allowed_attributes . '></meta>'),
			array('<meter> with attributes', '<meter ' . $all_attributes . '></meter>', '<meter ' . $allowed_attributes . '></meter>'),
			array('<nav> with attributes', '<nav ' . $all_attributes . '></nav>', '<nav ' . $allowed_attributes . '></nav>'),
			array('<noframes> with attributes', '<noframes ' . $all_attributes . '></noframes>', '<noframes ' . $allowed_attributes . '></noframes>'),
			array('<noscript> with attributes', '<noscript ' . $all_attributes . '></noscript>', '<noscript ' . $allowed_attributes . '></noscript>'),
			array('<object> with attributes', '<object ' . $all_attributes . '></object>', '<object ' . $allowed_attributes . '></object>'),
			array('<ol> with attributes', '<ol ' . $all_attributes . '></ol>', '<ol ' . $allowed_attributes . '></ol>'),
			array('<optgroup> with attributes', '<optgroup ' . $all_attributes . '></optgroup>', '<optgroup ' . $allowed_attributes . '></optgroup>'),
			array('<option> with attributes', '<option ' . $all_attributes . '></option>', '<option ' . $allowed_attributes . '></option>'),
			array('<output> with attributes', '<output ' . $all_attributes . '></output>', '<output ' . $allowed_attributes . '></output>'),
			array('<p> with attributes', '<p ' . $all_attributes . '></p>', '<p ' . $allowed_attributes . '></p>'),
			array('<param> with attributes', '<param ' . $all_attributes . '></param>', '<param ' . $allowed_attributes . '></param>'),
			array('<picture> with attributes', '<picture ' . $all_attributes . '></picture>', '<picture ' . $allowed_attributes .'></picture>'),
			array('<pre> with attributes', '<pre ' . $all_attributes . '></pre>', '<pre ' . $allowed_attributes .'></pre>'),
			array('<progress> with attributes', '<progress ' . $all_attributes . '></progress>', '<progress ' . $allowed_attributes . '></progress>'),
			array('<q> with attributes', '<q ' . $all_attributes . '></q>', '<q ' . $allowed_attributes . '></q>'),
			array('<rp> with attributes', '<rp ' . $all_attributes . '></rp>', '<rp ' . $allowed_attributes . '></rp>'),
			array('<rt> with attributes', '<rt ' . $all_attributes . '></rt>', '<rt ' . $allowed_attributes . '></rt>'),
			array('<ruby> with attributes', '<ruby ' . $all_attributes . '></ruby>', '<ruby ' . $allowed_attributes . '></ruby>'),
			array('<s> with attributes', '<s ' . $all_attributes . '></s>', '<s ' . $allowed_attributes . '></s>'),
			array('<samp> with attributes', '<samp ' . $all_attributes . '></samp>', '<samp ' . $allowed_attributes . '></samp>'),
			array('<script> with attributes', '<script ' . $all_attributes . '></script>', '<script ' . $allowed_attributes . '></script>'),
			array('<section> with attributes', '<section ' . $all_attributes . '></section>', '<section ' . $allowed_attributes . '></section>'),
			array('<select> with attributes', '<select ' . $all_attributes . '></select>', '<select ' . $allowed_attributes . '></select>'),
			array('<small> with attributes', '<small ' . $all_attributes . '></small>', '<small ' . $allowed_attributes . '></small>'),
			array('<source> with attributes', '<source ' . $all_attributes . '></source>', '<source ' . $allowed_attributes . '></source>'),
			array('<span> with attributes', '<span ' . $all_attributes . '></span>', '<span ' . $allowed_attributes . '></span>'),
			array('<strike> with attributes', '<strike ' . $all_attributes . '></strike>', '<strike ' . $allowed_attributes . '></strike>'),
			array('<strong> with attributes', '<strong ' . $all_attributes . '></strong>', '<strong ' . $allowed_attributes . '></strong>'),
			array('<style> with attributes', '<style ' . $all_attributes . '></style>', '<style ' . $allowed_attributes . '></style>'),
			array('<sub> with attributes', '<sub ' . $all_attributes . '></sub>', '<sub ' . $allowed_attributes . '></sub>'),
			array('<summary> with attributes', '<summary ' . $all_attributes . '></summary>', '<summary ' . $allowed_attributes . '></summary>'),
			array('<sup> with attributes', '<sup ' . $all_attributes . '></sup>', '<sup ' . $allowed_attributes . '></sup>'),
			array('<table> with attributes', '<table ' . $all_attributes . '></table>', '<table ' . $allowed_attributes . '></table>'),
			array('<tbody> with attributes', '<tbody ' . $all_attributes . '></tbody>', '<tbody ' . $allowed_attributes . '></tbody>'),
			array('<td> with attributes', '<td ' . $all_attributes . '></td>', '<td ' . $allowed_attributes . '></td>'),
			array('<textarea> with attributes', '<textarea ' . $all_attributes . '></textarea>', '<textarea ' . $allowed_attributes . '></textarea>'),
			array('<tfoot> with attributes', '<tfoot ' . $all_attributes . '></tfoot>', '<tfoot ' . $allowed_attributes . '></tfoot>'),
			array('<th> with attributes', '<th ' . $all_attributes . '></th>', '<th ' . $allowed_attributes . '></th>'),
			array('<thead> with attributes', '<thead ' . $all_attributes . '></thead>', '<thead ' . $allowed_attributes . '></thead>'),
			array('<time> with attributes', '<time ' . $all_attributes . '></time>', '<time ' . $allowed_attributes . '></time>'),
			array('<title> with attributes', '<title ' . $all_attributes . '></title>', '<title ' . $allowed_attributes . '></title>'),
			array('<tr> with attributes', '<tr ' . $all_attributes . '></tr>', '<tr ' . $allowed_attributes . '></tr>'),
			array('<track> with attributes', '<track ' . $all_attributes . '></track>', '<track ' . $allowed_attributes . '></track>'),
			array('<tt> with attributes', '<tt ' . $all_attributes . '></tt>', '<tt ' . $allowed_attributes . '></tt>'),
			array('<u> with attributes', '<u ' . $all_attributes . '></u>', '<u ' . $allowed_attributes . '></u>'),
			array('<ul> with attributes', '<ul ' . $all_attributes . '></ul>', '<ul ' . $allowed_attributes . '></ul>'),
			array('<var> with attributes', '<var ' . $all_attributes . '></var>', '<var ' . $allowed_attributes . '></var>'),
			array('<video> with attributes', '<video ' . $all_attributes . '></video>', '<video ' . $allowed_attributes . '></video>'),
			array('<wbr> with attributes', '<wbr ' . $all_attributes . '></wbr>', '<wbr ' . $allowed_attributes . '></wbr>'),
		);
	}

	protected function unprocessedMarkdownData()
	{
		$data = array(
			// Automatic Escaping
			array('Ampersands', 'AT&T', "AT&amp;T"),
			array('HTML Entity', '&copy;', "&copy;"),
			array('Angle brackets', '4 < 5 and 3 > 4', "4 < 5 and 3 > 4"),

			// Links
			// array('Link with title attribute', 'This is [an example](http://example.com/ "Title") inline link.', ""),
			array('Link without title attribute', '[This link](http://example.net/) has no title attribute.', '[This link](http://example.net/) has no title attribute.'),
			array('Relative URLs', 'See my [About](/about/) page for details.', 'See my [About](/about/) page for details.'),
			array('Refernce style link', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "This is [an example][id] reference-style link.\n\n[id]: http://example.com/&nbsp; &#8220;Optional Title Here&#8221;\n"),
			array('Refernce style link (with space)', "This is [an example] [id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "This is [an example] [id] reference-style link.\n\n[id]: http://example.com/&nbsp; &#8220;Optional Title Here&#8221;\n"),
			// array('Refernce style link (with single quote)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  'Optional Title Here'", "This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link."),
			array('Refernce style link (with parenthesis)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  (Optional Title Here)", "This is [an example][id] reference-style link.\n\n[id]: http://example.com/&nbsp; (Optional Title Here)"),
			array('Refernce style link (with angle brackets)', "This is [an example][id] reference-style link.\n\n[id]: <http://example.com/>  \"Optional Title Here\"\n", "This is [an example][id] reference-style link.\n\n[id]: <http://example.com/>&nbsp; &#8220;Optional Title Here&#8221;\n"),
			array('Refernce style link (with title on newline)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/\n\t\"Optional Title Here\"\n", "This is [an example][id] reference-style link.\n\n[id]: http://example.com/\n\t&#8220;Optional Title Here&#8221;\n"),
			array('Refernce style implicit link', "Visit [Daring Fireball][] for more information.\n\n[Daring Fireball]: http://daringfireball.net/", "Visit [Daring Fireball][] for more information.\n\n[Daring Fireball]: http://daringfireball.net/"),
			array('Automatic link', '<http://example.com>', '<http://example.com>'),
            // array('Automatic email link', '<address@example.com>', '<a>'),

			// Emphasis
			array('Single asterisks', '*single asterisks*', '*single asterisks*'),
			array('Single underscores', '_single underscores_', '_single underscores_'),
			array('Double asterisks', '**double asterisks**', '**double asterisks**'),
			array('Double underscores', '__double underscores__', '__double underscores__'),
			array('Single asterisks in the middle of a word', 'un*frigging*believable', 'un*frigging*believable'),
			array('Double asterisks in the middle of a word', 'un**frigging**believable', 'un**frigging**believable'),
			array('Literal asterisk', '8 * 7 = 56', '8 * 7 = 56'),
			array('Literal underscore', 'Literal _ underscore', 'Literal _ underscore'),
			array('Escaped asterisk', '\*this text is surrounded by literal asterisks\*', '\*this text is surrounded by literal asterisks\*'),
			array('Escaped underscore', '\_this text is surrounded by literal asterisks\_', '\_this text is surrounded by literal asterisks\_'),

			// Code
			array('Span of code', 'Use the `printf()` function.', 'Use the `printf()` function.'),
			array('Literal backtick', '``There is a literal backtick (`) here.``', '``There is a literal backtick (`) here.``'),
			array('Encoded angle brackets inside code span', "Please don't use any `<blink>` tags.", "Please don&#8217;t use any `<blink>` tags."),
			array('Encoded ampersands inside code span', '`&#8212;` is the decimal-encoded equivalent of `&mdash;`.', '`&#8212;` is the decimal-encoded equivalent of `&mdash;`.'),

			// Images
			array('Image tag', '![Alt text](/path/to/img.jpg)', '![Alt text](/path/to/img.jpg)'),
			// array('Image tag with title', '![Alt text](/path/to/img.jpg "Optional title")', ""),
			array('Reference style image tag', "![Alt text][id]\n\n[id]: url/to/image  \"Optional title attribute\"\n", "![Alt text][id]\n\n[id]: url/to/image  &#8220;Optional title attribute&#8221;\n"),

			// Escapes
			array('Escaped backslash', '\\\\', "\\\\"),
			array('Escaped backtick', '\`', "\`"),
			array('Escaped asterisk', '\*', "\*"),
			array('Escaped underscore', '\_', "\_"),
			array('Escaped curly braces', '\{\}', "\&#123;\&#125;"),
			array('Escaped square brackets', '\[\]', "\[\]"),
			array('Escaped parentheses', '\(\)', "\(\)"),
			array('Escaped hash mark', '\#', "\#"),
			array('Escaped plus sign', '\+', "\+"),
			array('Escaped hyphen', '\-', "\-"),
			array('Escaped dot', '\.', "\."),
			array('Escaped exclamation mark', '\!', "\!"),

			// Horizontal rules
			array('HR by "* * *"', '* * *', '* * *'),
			array('HR by "***"', '***', '***'),
			array('HR by "*****"', '*****', '*****'),
			array('HR by "---"', '---', '&#8212;-'),
			array('HR by "- - -"', '- - -', '- - -'),
			array('HR by "-----"', '-----', '&#8212;&#8212;-'),
			array('HR by "___"', '___', '___'),
			array('HR by "_ _ _"', '_ _ _', '_ _ _'),
			array('HR by "_____"', '_____', '_____'),

			// Headers
			array('# H1', '# This is an H1', '# This is an H1'),
			array('## H2', '## This is an H2', '## This is an H2'),
			array('### H3', '### This is an H3', '### This is an H3'),
			array('#### H4', '#### This is an H4', '#### This is an H4'),
			array('##### H5', '##### This is an H5', '##### This is an H5'),
			array('###### H6', '###### This is an H6', '###### This is an H6'),
			array('# H1 #', '# This is an H1 #', '# This is an H1 #'),
			array('## H2 ##', '## This is an H2 ##', '## This is an H2 ##'),
			array('### H3 ###', '### This is an H3 ###', '### This is an H3 ###'),
			array('#### H4 ####', '#### This is an H4 ####', '#### This is an H4 ####'),
			array('##### H5 #####', '##### This is an H5 #####', '##### This is an H5 #####'),
			array('###### H6 ######', '###### This is an H6 ######', '###### This is an H6 ######'),
			array('H1 by underscore', "This is an H1\n=============", "This is an H1\n============="),
			array('H2 by underscore', "This is an H2\n-------------", "This is an H2&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;-"),

			/* @TODO alter the expectation...
			// Blockquotes
			array('Email style blockquote', $this->getContentForMarkup('email-style-blockquote.in.md'), $this->getContentForMarkup('email-style-blockquote.in.md')),
			array('Lazy style blockquote', $this->getContentForMarkup('lazy-style-blockquote.in.md'), $this->getContentForMarkup('lazy-style-blockquote.in.md')),
			array('Nested blockquotes', $this->getContentForMarkup('nested-blockquotes.in.md'), $this->getContentForMarkup('nested-blockquotes.in.md')),
			array('Markdown inside blockquote', $this->getContentForMarkup('markdown-in-blockquote.in.md'), $this->getContentForMarkup('markdown-in-blockquote.in.md')),

			// Lists
			array('List by asterisk', $this->getContentForMarkup('list-by-asterisk.in.md'), $this->getContentForMarkup('list-by-asterisk.in.md')),
			array('List by plus', $this->getContentForMarkup('list-by-plus.in.md'), $this->getContentForMarkup('list-by-plus.in.md')),
			array('List by hyphen', $this->getContentForMarkup('list-by-hyphen.in.md'), $this->getContentForMarkup('list-by-hyphen.in.md')),
			array('Ordered list', $this->getContentForMarkup('ordered-list.in.md'), $this->getContentForMarkup('ordered-list.in.md')),
			array('Wrapped lists', $this->getContentForMarkup('wrapped-lists.in.md'), $this->getContentForMarkup('wrapped-lists.in.md')),
			array('Lists with paragraph tags', $this->getContentForMarkup('lists-with-paragraph-tags.in.md'), $this->getContentForMarkup('lists-with-paragraph-tags.in.md')),
			array('Lists with paragraphs', $this->getContentForMarkup('lists-with-paragraphs.in.md'), $this->getContentForMarkup('lists-with-paragraphs.in.md')),
			array('Lists with blockquotes', $this->getContentForMarkup('lists-with-blockquotes.in.md'), $this->getContentForMarkup('lists-with-blockquotes.in.md')),
			array('Lists with code blocks', $this->getContentForMarkup('lists-with-code-blocks.in.md'), $this->getContentForMarkup('lists-with-code-blocks.in.md')),
			array('Not a list', '1986\. What a great season.', "1986&#46; What a great season."),

			// Code blocks
			array('Code block by 4 spaces', $this->getContentForMarkup('codeblock-by-4-spaces.in.md'), $this->getContentForMarkup('codeblock-by-4-spaces.in.md')),
			array('Code block by 5 spaces', $this->getContentForMarkup('codeblock-by-5-spaces.in.md'), $this->getContentForMarkup('codeblock-by-5-spaces.in.md')),
			array('Code block by 1 tab', $this->getContentForMarkup('codeblock-by-1-tab.in.md'), $this->getContentForMarkup('codeblock-by-1-tab.in.md')),
			array('Code block by 2 tabs', $this->getContentForMarkup('codeblock-by-2-tabs.in.md'), $this->getContentForMarkup('codeblock-by-2-tabs.in.md')),
			array('Code block with encoded ampersands', $this->getContentForMarkup('codeblock-with-encoded-ampersands.in.md'), $this->getContentForMarkup('codeblock-with-encoded-ampersands.in.md')),
			array('Code block with encoded angle brackets', $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.in.md'), $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.in.md')),
			*/
		);

		return array_merge($data, $this->unprocessedMarkdownExtraData());
	}

	protected function unprocessedMarkdownExtraData()
	{
		return array(
			// array('Markdown inside HTML blocks', $this->getContentForMarkup('markdown-inside-html-blocks.in.md'), $this->getContentForMarkup('markdown-inside-html-blocks.out.md')),

			// Special Attributes
			array('Header: ID', '## Header 2 {#header2}', '## Header 2 &#123;#header2&#125;'),
			array('Header: Class names', '## Header 2 {.main}', '## Header 2 &#123;.main&#125;'),
			array('Header: Custom attributes', '## Le Header 2 {lang=fr}', '## Le Header 2 &#123;lang=fr&#125;'),
			array('Header: Multiple attributes', '## Le Header 2 {.main .shine lang=fr #header2}', '## Le Header 2 &#123;.main .shine lang=fr #header2&#125;'),
			array('Link: ID', '[link](/url){#header2}', '[link](/url)&#123;#header2&#125;'),
			array('Link: Class names', '[link](/url){.main}', '[link](/url)&#123;.main&#125;'),
			array('Link: Custom attributes', '[link](/url){lang=fr}', '[link](/url)&#123;lang=fr&#125;'),
			array('Link: Multiple attributes', '[link](/url){.main .shine lang=fr #header2}', '[link](/url)&#123;.main .shine lang=fr #header2&#125;'),
			array('Reference Link: ID', "[link][linkref]\n\n[linkref]: /url {#header2}", "[link][linkref]\n\n[linkref]: /url &#123;#header2&#125;"),
			array('Reference Link: Class names', "[link][linkref]\n\n[linkref]: /url {.main}", "[link][linkref]\n\n[linkref]: /url &#123;.main&#125;"),
			array('Reference Link: Custom attributes', "[link][linkref]\n\n[linkref]: /url {lang=fr}", "[link][linkref]\n\n[linkref]: /url &#123;lang=fr&#125;"),
			array('Reference Link: Multiple attributes', "[link][linkref]\n\n[linkref]: /url {.main .shine lang=fr #header2}", "[link][linkref]\n\n[linkref]: /url &#123;.main .shine lang=fr #header2&#125;"),
			array('Image: ID', '![link](/url){#header2}', '![link](/url)&#123;#header2&#125;'),
			array('Image: Class names', '![link](/url){.main}', '![link](/url)&#123;.main&#125;'),
			array('Image: Custom attributes', '![link](/url){lang=fr}', '![link](/url)&#123;lang=fr&#125;'),
			array('Image: Multiple attributes', '![link](/url){.main .shine lang=fr #header2}', '![link](/url)&#123;.main .shine lang=fr #header2&#125;'),
			array('Fenced code block: ID', "~~~ {#header2}\ncode block\n~~~\n", "~~~ &#123;#header2&#125;\ncode block\n~~~\n"),
			array('Fenced code block: Class names', "~~~ {.main}\ncode block\n~~~\n", "~~~ &#123;.main&#125;\ncode block\n~~~\n"),
			array('Fenced code block: Custom attributes', "~~~ {lang=fr}\ncode block\n~~~\n", "~~~ &#123;lang=fr&#125;\ncode block\n~~~\n"),
			array('Fenced code block: Multiple attributes', "~~~ {.main .shine lang=fr #header2}\ncode block\n~~~\n", "~~~ &#123;.main .shine lang=fr #header2&#125;\ncode block\n~~~\n"),

			/*
			// Fenced Code Blocks
			array('Fenced code block by 3 tildes', $this->getContentForMarkup('codeblock-by-3-tildes.in.md'), $this->getContentForMarkup('codeblock-by-3-tildes.out.md')),
			array('Fenced code block by 4 tildes', $this->getContentForMarkup('codeblock-by-4-tildes.in.md'), $this->getContentForMarkup('codeblock-by-4-tildes.out.md')),
			array('Fenced code block by 3 backticks', $this->getContentForMarkup('codeblock-by-3-backticks.in.md'), $this->getContentForMarkup('codeblock-by-3-backticks.out.md')),
			array('Fenced code block by 4 backticks', $this->getContentForMarkup('codeblock-by-4-backticks.in.md'), $this->getContentForMarkup('codeblock-by-4-backticks.out.md')),
			array('Fenced code block beginning and ending with blank lines', $this->getContentForMarkup('codeblock-begin-end-blank-lines.in.md'), $this->getContentForMarkup('codeblock-begin-end-blank-lines.out.md')),
			array('Fenced code block after a list', $this->getContentForMarkup('codeblock-after-list.in.md'), $this->getContentForMarkup('codeblock-after-list.out.md')),

			// Tables
			array('Table', $this->getContentForMarkup('table.in.md'), $this->getContentForMarkup('table.out.md')),
			array('Table with leading and tailing pipes', $this->getContentForMarkup('table-with-pipes.in.md'), $this->getContentForMarkup('table-with-pipes.out.md')),
			array('Table with alignment', $this->getContentForMarkup('table-with-alignment.in.md'), $this->getContentForMarkup('table-with-alignment.out.md')),
			array('Table with span-level formatting', $this->getContentForMarkup('table-with-formatting.in.md'), $this->getContentForMarkup('table-with-formatting.out.md')),

			// Definition Lists
			array('Definition list', $this->getContentForMarkup('definition-list.in.md'), $this->getContentForMarkup('definition-list.out.md')),
			array('Definition list wrapped', $this->getContentForMarkup('definition-list-wrapped.in.md'), $this->getContentForMarkup('definition-list-wrapped.out.md')),
			array('Definition list indented', $this->getContentForMarkup('definition-list-indented.in.md'), $this->getContentForMarkup('definition-list-indented.out.md')),
			array('Definition list multiple definitions', $this->getContentForMarkup('definition-list-multiple.in.md'), $this->getContentForMarkup('definition-list-multiple.out.md')),
			array('Definition list with paragraph tags', $this->getContentForMarkup('definition-list-with-paragraph-tags.in.md'), $this->getContentForMarkup('definition-list-with-paragraph-tags.out.md')),
			array('Definition list with multiple paragraphs', $this->getContentForMarkup('definition-list-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('definition-list-with-multiple-paragraphs.out.md')),

			// Footnotes
			array('Footnote first', $this->getContentForMarkup('footnote-first.in.md'), $this->getContentForMarkup('footnote-first.out.md')),
			array('Footnote intermingled', $this->getContentForMarkup('footnote-intermingled.in.md'), $this->getContentForMarkup('footnote-intermingled.out.md')),
			array('Footnote last', $this->getContentForMarkup('footnote-last.in.md'), $this->getContentForMarkup('footnote-last.out.md')),
			array('Footnote with multiple paragraphs', $this->getContentForMarkup('footnote-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('footnote-with-multiple-paragraphs.out.md')),

			// Abbreviations
			array('Abbreviation definition first', "*[HTML]: Hyper Text Markup Language\n\nThe HTML specification", "The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification\n"),
			array('Abbreviation definition middle', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language\n\nis dry", "The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification\n\nis dry\n"),
			array('Abbreviation definition last', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language", "The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification\n"),
			array('Multiword abbreviation', "*[Foo Bar]: Fubar\n\nI saw a Foo Bar once", "I saw a <abbr title=\"Fubar\">Foo Bar</abbr> once\n"),
			array('Empty abbreviateion', "Operation Tigra Genesis is going well.\n\n*[Tigra Genesis]:", "Operation <abbr>Tigra Genesis</abbr> is going well.\n"),
			*/

			array('Single underscores in the middle of a word', 'un_frigging_believable', "un_frigging_believable"),
			array('Double underscores in the middle of a word', 'un__frigging__believable', "un__frigging__believable"),
		);
	}

	protected function BBCodeData()
	{
		return array(
            array('[abbr] tag', '[abbr="Cascading Style Sheets"]CSS[/abbr]', '<abbr title=&#8220;Cascading Style Sheets&#8221;>CSS</abbr>'),
            array('[abbr] tag with property', '[abbr title="Cascading Style Sheets"]CSS[/abbr]', '<abbr title=&#8220;Cascading Style Sheets&#8221;>CSS</abbr>'),
            array('[b] tag', '[b]some bold text[/b]', '<b>some bold text</b>'),
            array('[blockquote] tag', '[blockquote]Some text. blah, blah, blah...[/blockquote]', '<blockquote>Some text. blah, blah, blah&#8230;</blockquote>'),
            // array('[cite] tag', '[cite="some place"]some text[/cite]', ''),
            // array('[code] tag', '[code]Some pre-formatted text...[/code]', '<code>Some pre-formatted text&#8230;</code>'),
            array('[color] tag', '[color=green]Some green text[/color]', '<span style=&#8220;color:green;&#8221;>Some green text</span>'),
            array('[del] tag', 'This is [del]very[/del] exciting.', 'This is <del>very</del> exciting.'),
            array('[em] tag', '[em]some em text[/em]', '<em>some em text</em>'),
            // array('[email] tag', '[email]you@example.com[/email]', "<span data-eeEncEmail_qqaBvHJmAg='1'>.encoded_email</span><script type=\"text/javascript\">/*<![CDATA[*/var out = '',el = document.getElementsByTagName('span'),l = ['>','a','/','<',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121','>','\"',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121',':','o','t','l','i','a','m','\\\"','=','f','e','r','h','a ','<'],i = l.length,j = el.length;while (--i >= 0)out += unescape(l[i].replace(/^\s\s*/, '&#'));while (--j >= 0)if (el[j].getAttribute('data-eeEncEmail_qqaBvHJmAg'))el[j].innerHTML = out;/*]]>*/</script>"),
            // array('[email] tag with value', '[email=you@example.com]click here to email[/email]', ''),
            array('[h2] tag', '[h2]some text[/h2]', '<h2>some text</h2>'),
            array('[h3] tag', '[h3]some text[/h3]', '<h3>some text</h3>'),
            array('[h4] tag', '[h4]some text[/h4]', '<h4>some text</h4>'),
            array('[h5] tag', '[h5]some text[/h5]', '<h5>some text</h5>'),
            array('[h6] tag', '[h6]some text[/h6]', '<h6>some text</h6>'),
            array('[i] tag', '[i]some italic text[/i]', '<i>some italic text</i>'),
            // array('[img] tag', '[img]http://example.com/pic.jpg[/img]', ''),
            array('[ins] tag', '[ins]some text[/ins]', '<ins>some text</ins>'),
            array('[mark] tag', '[mark]some text[/mark]', '<mark>some text</mark>'),
            array('[pre] tag', '[pre]Some pre-formatted text...[/pre]', '<pre>Some pre-formatted text&#8230;</pre>'),
            array('[quote] tag', '[quote]Some text. blah, blah, blah...[/quote]', '<blockquote>Some text. blah, blah, blah&#8230;</blockquote>'),
            array('[size=1] tag', '[size=1]some text[/size]', '<span style=&#8220;font-size:9px;&#8221;>some text</span>'),
            array('[size=2] tag', '[size=2]some text[/size]', '<span style=&#8220;font-size:11px;&#8221;>some text</span>'),
            array('[size=3] tag', '[size=3]some text[/size]', '<span style=&#8220;font-size:14px;&#8221;>some text</span>'),
            array('[size=4] tag', '[size=4]some text[/size]', '<span style=&#8220;font-size:16px;&#8221;>some text</span>'),
            array('[size=5] tag', '[size=5]some text[/size]', '<span style=&#8220;font-size:18px;&#8221;>some text</span>'),
            array('[size=6] tag', '[size=6]some text[/size]', '<span style=&#8220;font-size:20px;&#8221;>some text</span>'),
            array('[span] tag', '[span]some text[/span]', '<span>some text</span>'),
            array('[strike] tag', '[strike]some text[/strike]', '<del>some text</del>'),
            array('[strong] tag', '[strong]some strong text[/strong]', '<strong>some strong text</strong>'),
            array('[style] tag', '[style=class_name]your content[/style]', '<span class=&#8220;class_name&#8221;>your content</span>'),
            array('[sub] tag', '[sub]some text[/sub]', '<sub>some text</sub>'),
            array('[sup] tag', '[sup]some text[/sup]', '<sup>some text</sup>'),
            array('[u] tag', '[u]some underlined text[/u]', '<em>some underlined text</em>'),
            array('[url] tag', '[url]http://example.com/[/url]', '<a href=&#8220;http://example.com/&#8221;>http://example.com/</a>'),
            array('[url] tag with value', '[url=http://example.com/]my site[/url]', '<a href=&#8220;http://example.com/&#8221;>my site</a>'),
            // array('[url] tag with value and property', '[url=http://example.com/ class="link"]my site[/url]', '<a href="http://example.com/" class="link">my site</a>'),
		);
	}

}

// EOF
