<?php

require_once SYSPATH.'ee/EllisLab/ExpressionEngine/Boot/boot.common.php';
require_once APPPATH.'helpers/string_helper.php';
require_once APPPATH.'helpers/security_helper.php';
require_once APPPATH.'libraries/Functions.php';
require_once APPPATH.'libraries/Typography.php';
require_once APPPATH.'libraries/typography/Markdown/Michelf/MarkdownExtra.inc.php';

if ( ! defined('PATH_ADDONS'))
{
	define('PATH_ADDONS', APPPATH.'modules/');
}

if ( ! defined('REQ'))
{
	define('REQ', FALSE);
}


class MarkdownSafeTest extends \PHPUnit_Framework_TestCase {

		private $typography;

	public function tearDown()
	{
		unset($this->typography);
	}


	public function setUp()
	{
		$this->typography = new EE_Typography();
	}

	private function getContentForMarkup($name)
	{
		$path = realpath(__DIR__.'/../../../../support/typography/' . $name);
		return file_get_contents($path);
	}

	/**
	 * There are number of preferences we can pass to the parse_type
	 * method that we need to test:
	 *
	 *  - text_format (xhtml, markdown, br, none, lite)
	 *  - html_format (safe, all, none)
	 *  - auto_links (y, n)
	 *  - allow_img_url (n, y)
	 */

	/**
	 * @dataProvider dataProvider
	 */
    public function testParseType($description, $in, $out)
    {
        $prefs = array(
            'text_format' => 'markdown',
            'html_format' => 'safe',
            'auto_links' => 'n',
            'allow_img_url' => 'y',
        );

        $parsed = $this->typography->parse_type($in, $prefs);
        $this->assertEquals($out, $parsed, '[No Format] ' . $description);
    }

	public function dataProvider()
	{
		$data = array(
			array('Empty string', '', ''),
		);

		$data = array_merge(
			$this->whitespaceData(),
            $this->punctuationData(),
            $this->HTMLWithClosingTagsData(),
            $this->HTMLWithoutClosingTagsData(),
            $this->HTMLWithContentData(),
            $this->HTMLAttributesData(),
            $this->HTMLWithAttributesData(),
            $this->BBCodeData(),
            $this->markdownData(),
			$data
		);

		return $data;
	}

	protected function whitespaceData()
	{
		return array(
			array('Single spaces', 'a b', '<p>a b</p>' . "\n"),
			array('Double spaces', 'a  b', '<p>a  b</p>' . "\n"),
			array('Double spaces after a sentence', 'Word.  Word', '<p>Word.  Word</p>' . "\n"),
			array('A tab converts to a space', "a\tb", "<p>a b</p>\n"),
			array('Tabs convert to spaces', "a\t\tb", "<p>a  b</p>\n"),
			array('A return is a <br>', "a\nb", "<p>a\nb</p>\n"),
			array('Multiple returns are not converted', "a\n\nb", "<p>a</p>\n\n<p>b</p>\n"),
		);
	}

	protected function punctuationData()
	{
		return array(
			array('Backtick', '`', '<p>`</p>' . "\n"),
			array('Tilde', '~', '<p>~</p>' . "\n"),
			array('Exclamation point', '!', '<p>!</p>' . "\n"),
			array('At sign', '@', '<p>@</p>' . "\n"),
			array('Pound/hash sign', '#', '<p>#</p>' . "\n"),
			array('Dollar sign', '$', '<p>$</p>' . "\n"),
			array('Percent sign', '%', '<p>%</p>' . "\n"),
			array('Circumflex', '^', '<p>^</p>' . "\n"),
			array('Ampersand', '&', '<p>&amp;</p>' . "\n"),
			array('Asterisk', '*', '<p>*</p>' . "\n"),
			array('Parentheses', '()', '<p>()</p>' . "\n"),
			array('Underscore', '_', '<p>_</p>' . "\n"),
			array('Hyphen', '-', '<p>-</p>' . "\n"),
			array('Equals sign', '=', '<p>=</p>' . "\n"),
			array('Plus sign', '+', '<p>+</p>' . "\n"),
			array('Brackets', '[]', '<p>[]</p>' . "\n"),
			array('Braces', '{}', '<p>&#123;&#125;</p>' . "\n"),
			array('Backslash', '\\', '<p>\\</p>' . "\n"),
			array('Pipe', '|', '<p>|</p>' . "\n"),
			array('Semicolon', ';', '<p>;</p>' . "\n"),
			array('Colon', ':', '<p>:</p>' . "\n"),
			array('Single quote', "'", "<p>&#8216;</p>\n"),
			array('Double quote', '"', '<p>&#8220;</p>' . "\n"),
			array('Comma', ',', '<p>,</p>' . "\n"),
			array('Period', '.', '<p>.</p>' . "\n"),
			array('Angle brackets', '<>', '<p>&lt;&gt;</p>' . "\n"),
			array('Forward slash', '/', '<p>/</p>' . "\n"),
			array('Question mark', '?', '<p>?</p>' . "\n"),
			array('Em dash', '--', '<p>&#8211;</p>' . "\n"),
			array('Ellipses', 'you know...', '<p>you know&#8230;</p>' . "\n"),
			array('Apostrophy', "It's its", "<p>It&#8217;s its</p>\n"),
			array('US quote no whitespace', '"Hello"', '<p>&#8220;Hello&#8221;</p>' . "\n"),
			array('UK quote no whitespace', "'Hello'", '<p>&#8216;Hello&#8217;</p>' . "\n"),
			array('Simple nested US quote', '"I said, \'Hello\'"', '<p>&#8220;I said, &#8216;Hello&#8217;&#8221;</p>' . "\n"),
			array('Simple nested UK quote', "'I said, \"Hello\"'", '<p>&#8216;I said, &#8220;Hello&#8221;&#8217;</p>' . "\n"),
			array('US quote surrounded by whitespace', 'Foo "Bar" Baz', '<p>Foo &#8220;Bar&#8221; Baz</p>' . "\n"),
			array('UK quote surrounded by whitespace', "Foo 'Bar' Baz", '<p>Foo &#8216;Bar&#8217; Baz</p>' . "\n"),
		);
	}

	protected function HTMLWithClosingTagsData()
	{
		return array(
			array('<!-- -->', '<!-- -->', '<p>&lt;!&#8211; &#8211;&gt;</p>' . "\n"),
			array('<a></a>', '<a></a>', '<p>&lt;a&gt;&lt;/a&gt;</p>' . "\n"),
            // array('<abbr></abbr>', '<abbr></abbr>', '<p>&lt;abbr&gt;&lt;/abbr&gt;</p>' . "\n"),
            // array('<acronym></acronym>', '<acronym></acronym>', '<p>&lt;acronym&gt;&lt;/acronym&gt;</p>' . "\n"),
            // array('<address></address>', '<address></address>', '<p>&lt;address&gt;&lt;/address&gt;</p>' . "\n"),
            // array('<applet></applet>', '<applet></applet>', '<p>&lt;applet&gt;&lt;/applet&gt;</p>' . "\n"),
            // array('<area></area>', '<area></area>', '<p>&lt;area&gt;&lt;/area&gt;</p>' . "\n"),
            // array('<article></article>', '<article></article>', '<p>&lt;article&gt;&lt;/article&gt;</p>' . "\n"),
            // array('<aside></aside>', '<aside></aside>', '<p>&lt;aside&gt;&lt;/aside&gt;</p>' . "\n"),
            // array('<audio></audio>', '<audio></audio>','<p>&lt;audio&gt;&lt;/audio&gt;</p>' . "\n"),
			array('<b></b>', '<b></b>', '<p>&lt;b&gt;&lt;/b&gt;</p>' . "\n"),
			array('<base></base>', '<base></base>', '<p>&lt;base&gt;&lt;/base&gt;</p>' . "\n"),
			array('<basefont></basefont>', '<basefont></basefont>', '<p>&lt;basefont&gt;&lt;/basefont&gt;</p>' . "\n"),
			array('<bdi></bdi>', '<bdi></bdi>', '<p>&lt;bdi&gt;&lt;/bdi&gt;</p>' . "\n"),
			array('<bdo></bdo>', '<bdo></bdo>', '<p>&lt;bdo&gt;&lt;/bdo&gt;</p>' . "\n"),
			array('<big></big>', '<big></big>', '<p>&lt;big&gt;&lt;/big&gt;</p>' . "\n"),
			array('<blockquote></blockquote>', '<blockquote></blockquote>', '<p>&lt;blockquote&gt;&lt;/blockquote&gt;</p>' . "\n"),
			array('<body></body>', '<body></body>', '<p>&lt;body&gt;&lt;/body&gt;</p>' . "\n"),
			array('<button></button>', '<button></button>', '<p>&lt;button&gt;&lt;/button&gt;</p>' . "\n"),
			array('<canvas></canvas>', '<canvas></canvas>', '<p>&lt;canvas&gt;&lt;/canvas&gt;</p>' . "\n"),
			array('<caption></caption>', '<caption></caption>', '<p>&lt;caption&gt;&lt;/caption&gt;</p>' . "\n"),
			array('<center></center>', '<center></center>', '<p>&lt;center&gt;&lt;/center&gt;</p>' . "\n"),
			array('<cite></cite>', '<cite></cite>', '<p>&lt;cite&gt;&lt;/cite&gt;</p>' . "\n"),
			array('<code></code>', '<code></code>', '<p><code></code></p>' . "\n"),
			array('<col></col>', '<col></col>', '<p>&lt;col&gt;&lt;/col&gt;</p>' . "\n"),
			array('<colgroup></colgroup>', '<colgroup></colgroup>', '<p>&lt;colgroup&gt;&lt;/colgroup&gt;</p>' . "\n"),
			array('<datalist></datalist>', '<datalist></datalist>', '<p>&lt;datalist&gt;&lt;/datalist&gt;</p>' . "\n"),
			array('<dd></dd>', '<dd></dd>', '<p>&lt;dd&gt;&lt;/dd&gt;</p>' . "\n"),
			array('<del></del>', '<del></del>', '<p>&lt;del&gt;&lt;/del&gt;</p>' . "\n"),
			array('<details></details>', '<details></details>', '<p>&lt;details&gt;&lt;/details&gt;</p>' . "\n"),
			array('<dfn></dfn>', '<dfn></dfn>', '<p>&lt;dfn&gt;&lt;/dfn&gt;</p>' . "\n"),
			array('<dialog></dialog>', '<dialog></dialog>', '<p>&lt;dialog&gt;&lt;/dialog&gt;</p>' . "\n"),
			array('<dir></dir>', '<dir></dir>', '<p>&lt;dir&gt;&lt;/dir&gt;</p>' . "\n"),
			array('<div></div>', '<div></div>', '<p>&lt;div&gt;&lt;/div&gt;</p>' . "\n"),
			array('<dl></dl>', '<dl></dl>', '<p>&lt;dl&gt;&lt;/dl&gt;</p>' . "\n"),
			array('<dt></dt>', '<dt></dt>', '<p>&lt;dt&gt;&lt;/dt&gt;</p>' . "\n"),
			array('<em></em>', '<em></em>', '<p>&lt;em&gt;&lt;/em&gt;</p>' . "\n"),
			array('<embed></embed>', '<embed></embed>', '<p>&lt;embed&gt;&lt;/embed&gt;</p>' . "\n"),
			array('<fieldset></fieldset>', '<fieldset></fieldset>', '<p>&lt;fieldset&gt;&lt;/fieldset&gt;</p>' . "\n"),
			array('<figcaption></figcaption>', '<figcaption></figcaption>', '<p>&lt;figcaption&gt;&lt;/figcaption&gt;</p>' . "\n"),
			array('<figure></figure>', '<figure></figure>', '<p>&lt;figure&gt;&lt;/figure&gt;</p>' . "\n"),
			array('<font></font>', '<font></font>', '<p>&lt;font&gt;&lt;/font&gt;</p>' . "\n"),
			array('<footer></footer>', '<footer></footer>', '<p>&lt;footer&gt;&lt;/footer&gt;</p>' . "\n"),
			array('<form></form>', '<form></form>', '<p>&lt;form&gt;&lt;/form&gt;</p>' . "\n"),
			array('<frame></frame>', '<frame></frame>', '<p>&lt;frame&gt;&lt;/frame&gt;</p>' . "\n"),
			array('<frameset></frameset>', '<frameset></frameset>', '<p>&lt;frameset&gt;&lt;/frameset&gt;</p>' . "\n"),
			array('<h1></h1>', '<h1></h1>', '<p>&lt;h1&gt;&lt;/h1&gt;</p>' . "\n"),
			array('<h2></h2>', '<h2></h2>', '<p>&lt;h2&gt;&lt;/h2&gt;</p>' . "\n"),
			array('<h3></h3>', '<h3></h3>', '<p>&lt;h3&gt;&lt;/h3&gt;</p>' . "\n"),
			array('<h4></h4>', '<h4></h4>', '<p>&lt;h4&gt;&lt;/h4&gt;</p>' . "\n"),
			array('<h5></h5>', '<h5></h5>', '<p>&lt;h5&gt;&lt;/h5&gt;</p>' . "\n"),
			array('<h6></h6>', '<h6></h6>', '<p>&lt;h6&gt;&lt;/h6&gt;</p>' . "\n"),
			array('<head></head>', '<head></head>', '<p>&lt;head&gt;&lt;/head&gt;</p>' . "\n"),
			array('<header></header>', '<header></header>', '<p>&lt;header&gt;&lt;/header&gt;</p>' . "\n"),
			array('<html></html>', '<html></html>', '<p>&lt;html&gt;&lt;/html&gt;</p>' . "\n"),
			array('<i></i>', '<i></i>', '<p>&lt;i&gt;&lt;/i&gt;</p>' . "\n"),
			array('<iframe></iframe>', '<iframe></iframe>', '<p>&lt;iframe&gt;&lt;/iframe&gt;</p>' . "\n"),
			array('<ins></ins>', '<ins></ins>', '<p>&lt;ins&gt;&lt;/ins&gt;</p>' . "\n"),
			array('<kbd></kbd>', '<kbd></kbd>', '<p>&lt;kbd&gt;&lt;/kbd&gt;</p>' . "\n"),
			array('<keygen></keygen>', '<keygen></keygen>', '<p>&lt;keygen&gt;&lt;/keygen&gt;</p>' . "\n"),
			array('<label></label>', '<label></label>', '<p>&lt;label&gt;&lt;/label&gt;</p>' . "\n"),
			array('<legend></legend>', '<legend></legend>', '<p>&lt;legend&gt;&lt;/legend&gt;</p>' . "\n"),
			array('<li></li>', '<li></li>', '<p>&lt;li&gt;&lt;/li&gt;</p>' . "\n"),
			array('<link></link>', '<link></link>', '<p>&lt;link&gt;&lt;/link&gt;</p>' . "\n"),
			array('<main></main>', '<main></main>', '<p>&lt;main&gt;&lt;/main&gt;</p>' . "\n"),
			array('<map></map>', '<map></map>', '<p>&lt;map&gt;&lt;/map&gt;</p>' . "\n"),
			array('<mark></mark>', '<mark></mark>', '<p><mark></mark></p>' . "\n"),
			array('<menu></menu>', '<menu></menu>', '<p>&lt;menu&gt;&lt;/menu&gt;</p>' . "\n"),
			array('<menuitem></menuitem>', '<menuitem></menuitem>', '<p>&lt;menuitem&gt;&lt;/menuitem&gt;</p>' . "\n"),
			array('<meta></meta>', '<meta></meta>', '<p>&lt;meta&gt;&lt;/meta&gt;</p>' . "\n"),
			array('<meter></meter>', '<meter></meter>', '<p>&lt;meter&gt;&lt;/meter&gt;</p>' . "\n"),
			array('<nav></nav>', '<nav></nav>', '<p>&lt;nav&gt;&lt;/nav&gt;</p>' . "\n"),
			array('<noframes></noframes>', '<noframes></noframes>', '<p>&lt;noframes&gt;&lt;/noframes&gt;</p>' . "\n"),
			array('<noscript></noscript>', '<noscript></noscript>', '<p>&lt;noscript&gt;&lt;/noscript&gt;</p>' . "\n"),
			array('<object></object>', '<object></object>', '<p>&lt;object&gt;&lt;/object&gt;</p>' . "\n"),
			array('<ol></ol>', '<ol></ol>', '<p>&lt;ol&gt;&lt;/ol&gt;</p>' . "\n"),
			array('<optgroup></optgroup>', '<optgroup></optgroup>', '<p>&lt;optgroup&gt;&lt;/optgroup&gt;</p>' . "\n"),
			array('<option></option>', '<option></option>', '<p>&lt;option&gt;&lt;/option&gt;</p>' . "\n"),
			array('<output></output>', '<output></output>', '<p>&lt;output&gt;&lt;/output&gt;</p>' . "\n"),
			array('<p></p>', '<p></p>', '' . "\n"),
            // array('<param></param>', '<param></param>', '<p>&lt;param&gt;&lt;/param&gt;</p>' . "\n"),
            // array('<picture></picture>', '<picture></picture>','<p>&lt;picture&gt;&lt;/picture&gt;</p>' . "\n"),
			array('<pre></pre>', '<pre></pre>', '<p>&lt;pre&gt;&lt;/pre&gt;</p>' . "\n"),
            // array('<progress></progress>', '<progress></progress>', '<p>&lt;progress&gt;&lt;/progress&gt;</p>' . "\n"),
			array('<q></q>', '<q></q>', '<p>&lt;q&gt;&lt;/q&gt;</p>' . "\n"),
			array('<rp></rp>', '<rp></rp>', '<p>&lt;rp&gt;&lt;/rp&gt;</p>' . "\n"),
			array('<rt></rt>', '<rt></rt>', '<p>&lt;rt&gt;&lt;/rt&gt;</p>' . "\n"),
			array('<ruby></ruby>', '<ruby></ruby>', '<p>&lt;ruby&gt;&lt;/ruby&gt;</p>' . "\n"),
			array('<s></s>', '<s></s>', '<p>&lt;s&gt;&lt;/s&gt;</p>' . "\n"),
			array('<samp></samp>', '<samp></samp>', '<p>&lt;samp&gt;&lt;/samp&gt;</p>' . "\n"),
			array('<script></script>', '<script></script>', '<p>[removed][removed]</p>' . "\n"),
			array('<section></section>', '<section></section>', '<p>&lt;section&gt;&lt;/section&gt;</p>' . "\n"),
			array('<select></select>', '<select></select>', '<p>&lt;select&gt;&lt;/select&gt;</p>' . "\n"),
			array('<small></small>', '<small></small>', '<p>&lt;small&gt;&lt;/small&gt;</p>' . "\n"),
			array('<source></source>', '<source></source>', '<p>&lt;source&gt;&lt;/source&gt;</p>' . "\n"),
			array('<span></span>', '<span></span>', '<p><span></span></p>' . "\n"),
			array('<strike></strike>', '<strike></strike>', '<p>&lt;strike&gt;&lt;/strike&gt;</p>' . "\n"),
			array('<strong></strong>', '<strong></strong>', '<p>&lt;strong&gt;&lt;/strong&gt;</p>' . "\n"),
			array('<style></style>', '<style></style>', '<p>&lt;style&gt;&lt;/style&gt;</p>' . "\n"),
			array('<sub></sub>', '<sub></sub>', '<p>&lt;sub&gt;&lt;/sub&gt;</p>' . "\n"),
			array('<summary></summary>', '<summary></summary>', '<p>&lt;summary&gt;&lt;/summary&gt;</p>' . "\n"),
			array('<sup></sup>', '<sup></sup>', '<p>&lt;sup&gt;&lt;/sup&gt;</p>' . "\n"),
			array('<table></table>', '<table></table>', '<p>&lt;table&gt;&lt;/table&gt;</p>' . "\n"),
			array('<tbody></tbody>', '<tbody></tbody>', '<p>&lt;tbody&gt;&lt;/tbody&gt;</p>' . "\n"),
			array('<td></td>', '<td></td>', '<p>&lt;td&gt;&lt;/td&gt;</p>' . "\n"),
			array('<textarea></textarea>', '<textarea></textarea>', '<p>&lt;textarea&gt;&lt;/textarea&gt;</p>' . "\n"),
			array('<tfoot></tfoot>', '<tfoot></tfoot>', '<p>&lt;tfoot&gt;&lt;/tfoot&gt;</p>' . "\n"),
			array('<th></th>', '<th></th>', '<p>&lt;th&gt;&lt;/th&gt;</p>' . "\n"),
			array('<thead></thead>', '<thead></thead>', '<p>&lt;thead&gt;&lt;/thead&gt;</p>' . "\n"),
			array('<time></time>', '<time></time>', '<p>&lt;time&gt;&lt;/time&gt;</p>' . "\n"),
			array('<title></title>', '<title></title>', '<p>&lt;title&gt;&lt;/title&gt;</p>' . "\n"),
			array('<tr></tr>', '<tr></tr>', '<p>&lt;tr&gt;&lt;/tr&gt;</p>' . "\n"),
			array('<track></track>', '<track></track>', '<p>&lt;track&gt;&lt;/track&gt;</p>' . "\n"),
			array('<tt></tt>', '<tt></tt>', '<p>&lt;tt&gt;&lt;/tt&gt;</p>' . "\n"),
			array('<u></u>', '<u></u>', '<p>&lt;u&gt;&lt;/u&gt;</p>' . "\n"),
			array('<ul></ul>', '<ul></ul>', '<p>&lt;ul&gt;&lt;/ul&gt;</p>' . "\n"),
			array('<var></var>', '<var></var>', '<p>&lt;var&gt;&lt;/var&gt;</p>' . "\n"),
			array('<video></video>', '<video></video>', '<p>&lt;video&gt;&lt;/video&gt;</p>' . "\n"),
			array('<wbr></wbr>', '<wbr></wbr>', '<p>&lt;wbr&gt;&lt;/wbr&gt;</p>' . "\n"),
		);
	}

	protected function HTMLWithoutClosingTagsData()
	{
		return array(
			array('<!--', '<!--', '<p>&lt;!&#8211;</p>' . "\n"),
			array('<a>', '<a>', '<p>&lt;a&gt;</p>' . "\n"),
			// array('<abbr>', '<abbr>', '<p>&lt;abbr&gt;</p>' . "\n"),
			// array('<acronym>', '<acronym>', '<p>&lt;acronym&gt;</p>' . "\n"),
			// array('<address>', '<address>', '<p>&lt;address&gt;</p>' . "\n"),
			// array('<applet>', '<applet>', '<p>&lt;applet&gt;</p>' . "\n"),
			// array('<area>', '<area>', '<p>&lt;area&gt;</p>' . "\n"),
			// array('<article>', '<article>', '<p>&lt;article&gt;</p>' . "\n"),
			// array('<aside>', '<aside>', '<p>&lt;aside&gt;</p>' . "\n"),
			// array('<audio>', '<audio>', '<p>&lt;audio&gt;</p>' . "\n"),
			array('<b>', '<b>', '<p>&lt;b&gt;</p>' . "\n"),
			array('<base>', '<base>', '<p>&lt;base&gt;</p>' . "\n"),
			array('<basefont>', '<basefont>', '<p>&lt;basefont&gt;</p>' . "\n"),
			array('<bdi>', '<bdi>', '<p>&lt;bdi&gt;</p>' . "\n"),
			array('<bdo>', '<bdo>', '<p>&lt;bdo&gt;</p>' . "\n"),
			array('<big>', '<big>', '<p>&lt;big&gt;</p>' . "\n"),
			array('<blockquote>', '<blockquote>', '<p>&lt;blockquote&gt;</p>' . "\n"),
			array('<body>', '<body>', '<p>&lt;body&gt;</p>' . "\n"),
            // array('<br>', '<br>', "\n"),
			array('<button>', '<button>', '<p>&lt;button&gt;</p>' . "\n"),
			array('<canvas>', '<canvas>', '<p>&lt;canvas&gt;</p>' . "\n"),
			array('<caption>', '<caption>', '<p>&lt;caption&gt;</p>' . "\n"),
			array('<center>', '<center>', '<p>&lt;center&gt;</p>' . "\n"),
			array('<cite>', '<cite>', '<p>&lt;cite&gt;</p>' . "\n"),
			array('<code>', '<code>', '<p>&lt;code&gt;</p>' . "\n"),
			array('<col>', '<col>', '<p>&lt;col&gt;</p>' . "\n"),
			array('<colgroup>', '<colgroup>', '<p>&lt;colgroup&gt;</p>' . "\n"),
			array('<datalist>', '<datalist>', '<p>&lt;datalist&gt;</p>' . "\n"),
			array('<dd>', '<dd>', '<p>&lt;dd&gt;</p>' . "\n"),
			array('<del>', '<del>', '<p>&lt;del&gt;</p>' . "\n"),
			array('<details>', '<details>', '<p>&lt;details&gt;</p>' . "\n"),
			array('<dfn>', '<dfn>', '<p>&lt;dfn&gt;</p>' . "\n"),
			array('<dialog>', '<dialog>', '<p>&lt;dialog&gt;</p>' . "\n"),
			array('<dir>', '<dir>', '<p>&lt;dir&gt;</p>' . "\n"),
			array('<div>', '<div>', '<p>&lt;div&gt;</p>' . "\n"),
			array('<dl>', '<dl>', '<p>&lt;dl&gt;</p>' . "\n"),
			array('<dt>', '<dt>', '<p>&lt;dt&gt;</p>' . "\n"),
			array('<em>', '<em>', '<p>&lt;em&gt;</p>' . "\n"),
			array('<embed>', '<embed>', '<p>&lt;embed&gt;</p>' . "\n"),
			array('<fieldset>', '<fieldset>', '<p>&lt;fieldset&gt;</p>' . "\n"),
			array('<figcaption>', '<figcaption>', '<p>&lt;figcaption&gt;</p>' . "\n"),
			array('<figure>', '<figure>', '<p>&lt;figure&gt;</p>' . "\n"),
			array('<font>', '<font>', '<p>&lt;font&gt;</p>' . "\n"),
			array('<footer>', '<footer>', '<p>&lt;footer&gt;</p>' . "\n"),
			array('<form>', '<form>', '<p>&lt;form&gt;</p>' . "\n"),
			array('<frame>', '<frame>', '<p>&lt;frame&gt;</p>' . "\n"),
			array('<frameset>', '<frameset>', '<p>&lt;frameset&gt;</p>' . "\n"),
			array('<h1>', '<h1>', '<p>&lt;h1&gt;</p>' . "\n"),
			array('<h2>', '<h2>', '<p>&lt;h2&gt;</p>' . "\n"),
			array('<h3>', '<h3>', '<p>&lt;h3&gt;</p>' . "\n"),
			array('<h4>', '<h4>', '<p>&lt;h4&gt;</p>' . "\n"),
			array('<h5>', '<h5>', '<p>&lt;h5&gt;</p>' . "\n"),
			array('<h6>', '<h6>', '<p>&lt;h6&gt;</p>' . "\n"),
			array('<head>', '<head>', '<p>&lt;head&gt;</p>' . "\n"),
			array('<header>', '<header>', '<p>&lt;header&gt;</p>' . "\n"),
			array('<hr>', '<hr>', '<p>&lt;hr&gt;</p>' . "\n"),
			array('<html>', '<html>', '<p>&lt;html&gt;</p>' . "\n"),
			array('<i>', '<i>', '<p>&lt;i&gt;</p>' . "\n"),
			array('<iframe>', '<iframe>', '<p>&lt;iframe&gt;</p>' . "\n"),
			array('<img>', '<img>', '<p>&lt;img&gt;</p>' . "\n"),
			array('<input>', '<input>', '<p>&lt;input&gt;</p>' . "\n"),
			array('<ins>', '<ins>', '<p>&lt;ins&gt;</p>' . "\n"),
			array('<kbd>', '<kbd>', '<p>&lt;kbd&gt;</p>' . "\n"),
			array('<keygen>', '<keygen>', '<p>&lt;keygen&gt;</p>' . "\n"),
			array('<label>', '<label>', '<p>&lt;label&gt;</p>' . "\n"),
			array('<legend>', '<legend>', '<p>&lt;legend&gt;</p>' . "\n"),
			array('<li>', '<li>', '<p>&lt;li&gt;</p>' . "\n"),
			array('<link>', '<link>', '<p>&lt;link&gt;</p>' . "\n"),
			array('<main>', '<main>', '<p>&lt;main&gt;</p>' . "\n"),
			array('<map>', '<map>', '<p>&lt;map&gt;</p>' . "\n"),
			array('<mark>', '<mark>', '<p>&lt;mark&gt;</p>' . "\n"),
			array('<menu>', '<menu>', '<p>&lt;menu&gt;</p>' . "\n"),
			array('<menuitem>', '<menuitem>', '<p>&lt;menuitem&gt;</p>' . "\n"),
			array('<meta>', '<meta>', '<p>&lt;meta&gt;</p>' . "\n"),
			array('<meter>', '<meter>', '<p>&lt;meter&gt;</p>' . "\n"),
			array('<nav>', '<nav>', '<p>&lt;nav&gt;</p>' . "\n"),
			array('<noframes>', '<noframes>', '<p>&lt;noframes&gt;</p>' . "\n"),
			array('<noscript>', '<noscript>', '<p>&lt;noscript&gt;</p>' . "\n"),
			array('<object>', '<object>', '<p>&lt;object&gt;</p>' . "\n"),
			array('<ol>', '<ol>', '<p>&lt;ol&gt;</p>' . "\n"),
			array('<optgroup>', '<optgroup>', '<p>&lt;optgroup&gt;</p>' . "\n"),
			array('<option>', '<option>', '<p>&lt;option&gt;</p>' . "\n"),
			array('<output>', '<output>', '<p>&lt;output&gt;</p>' . "\n"),
			array('<p>', '<p>', '' . "\n"),
			// array('<param>', '<param>', '<p>&lt;param&gt;</p>' . "\n"),
			// array('<picture>', '<picture>', '<p>&lt;picture&gt;</p>' . "\n"),
			array('<pre>', '<pre>', '<p>&lt;pre&gt;</p>' . "\n"),
			// array('<progress>', '<progress>', '<p>&lt;progress&gt;</p>' . "\n"),
			array('<q>', '<q>', '<p>&lt;q&gt;</p>' . "\n"),
			array('<rp>', '<rp>', '<p>&lt;rp&gt;</p>' . "\n"),
			array('<rt>', '<rt>', '<p>&lt;rt&gt;</p>' . "\n"),
			array('<ruby>', '<ruby>', '<p>&lt;ruby&gt;</p>' . "\n"),
			array('<s>', '<s>', '<p>&lt;s&gt;</p>' . "\n"),
			array('<samp>', '<samp>', '<p>&lt;samp&gt;</p>' . "\n"),
			array('<script>', '<script>', '<p>[removed]</p>' . "\n"),
			array('<section>', '<section>', '<p>&lt;section&gt;</p>' . "\n"),
			array('<select>', '<select>', '<p>&lt;select&gt;</p>' . "\n"),
			array('<small>', '<small>', '<p>&lt;small&gt;</p>' . "\n"),
			array('<source>', '<source>', '<p>&lt;source&gt;</p>' . "\n"),
			array('<span>', '<span>', '<p>&lt;span&gt;</p>' . "\n"),
			array('<strike>', '<strike>', '<p>&lt;strike&gt;</p>' . "\n"),
			array('<strong>', '<strong>', '<p>&lt;strong&gt;</p>' . "\n"),
			array('<style>', '<style>', '<p>&lt;style&gt;</p>' . "\n"),
			array('<sub>', '<sub>', '<p>&lt;sub&gt;</p>' . "\n"),
			array('<summary>', '<summary>', '<p>&lt;summary&gt;</p>' . "\n"),
			array('<sup>', '<sup>', '<p>&lt;sup&gt;</p>' . "\n"),
			array('<table>', '<table>', '<p>&lt;table&gt;</p>' . "\n"),
			array('<tbody>', '<tbody>', '<p>&lt;tbody&gt;</p>' . "\n"),
			array('<td>', '<td>', '<p>&lt;td&gt;</p>' . "\n"),
			array('<textarea>', '<textarea>', '<p>&lt;textarea&gt;</p>' . "\n"),
			array('<tfoot>', '<tfoot>', '<p>&lt;tfoot&gt;</p>' . "\n"),
			array('<th>', '<th>', '<p>&lt;th&gt;</p>' . "\n"),
			array('<thead>', '<thead>', '<p>&lt;thead&gt;</p>' . "\n"),
			array('<time>', '<time>', '<p>&lt;time&gt;</p>' . "\n"),
			array('<title>', '<title>', '<p>&lt;title&gt;</p>' . "\n"),
			array('<tr>', '<tr>', '<p>&lt;tr&gt;</p>' . "\n"),
			array('<track>', '<track>', '<p>&lt;track&gt;</p>' . "\n"),
			array('<tt>', '<tt>', '<p>&lt;tt&gt;</p>' . "\n"),
			array('<u>', '<u>', '<p>&lt;u&gt;</p>' . "\n"),
			array('<ul>', '<ul>', '<p>&lt;ul&gt;</p>' . "\n"),
			array('<var>', '<var>', '<p>&lt;var&gt;</p>' . "\n"),
			array('<video>', '<video>', '<p>&lt;video&gt;</p>' . "\n"),
			array('<wbr>', '<wbr>', '<p>&lt;wbr&gt;</p>' . "\n"),
		);
	}

	protected function HTMLWithContentData()
	{
		return array(
			array('<!-- foobar -->', '<!-- foobar -->', '<p>&lt;!&#8211; foobar &#8211;&gt;</p>' . "\n"),
			array('<a>foobar</a>', '<a>foobar</a>', '<p>&lt;a&gt;foobar&lt;/a&gt;</p>' . "\n"),
			// array('<abbr>foobar</abbr>', '<abbr>foobar</abbr>', '<p>&lt;abbr&gt;foobar&lt;/abbr&gt;</p>' . "\n"),
			// array('<acronym>foobar</acronym>', '<acronym>foobar</acronym>', '<p>&lt;acronym&gt;foobar&lt;/acronym&gt;</p>' . "\n"),
			// array('<address>foobar</address>', '<address>foobar</address>', '<p>&lt;address&gt;foobar&lt;/address&gt;</p>' . "\n"),
			// array('<applet>foobar</applet>', '<applet>foobar</applet>', '<p>&lt;applet&gt;foobar&lt;/applet&gt;</p>' . "\n"),
			// array('<area>foobar</area>', '<area>foobar</area>', '<p>&lt;area&gt;foobar&lt;/area&gt;</p>' . "\n"),
			// array('<article>foobar</article>', '<article>foobar</article>', '<p>&lt;article&gt;foobar&lt;/article&gt;</p>' . "\n"),
			// array('<aside>foobar</aside>', '<aside>foobar</aside>', '<p>&lt;aside&gt;foobar&lt;/aside&gt;</p>' . "\n"),
			// array('<audio>foobar</audio>', '<audio>foobar</audio>', '<p>&lt;audio&gt;foobar&lt;/audio&gt;</p>' . "\n"),
			array('<b>foobar</b>', '<b>foobar</b>', '<p><b>foobar</b></p>' . "\n"),
			array('<base>foobar</base>', '<base>foobar</base>', '<p>&lt;base&gt;foobar&lt;/base&gt;</p>' . "\n"),
			array('<basefont>foobar</basefont>', '<basefont>foobar</basefont>', '<p>&lt;basefont&gt;foobar&lt;/basefont&gt;</p>' . "\n"),
			array('<bdi>foobar</bdi>', '<bdi>foobar</bdi>', '<p>&lt;bdi&gt;foobar&lt;/bdi&gt;</p>' . "\n"),
			array('<bdo>foobar</bdo>', '<bdo>foobar</bdo>', '<p>&lt;bdo&gt;foobar&lt;/bdo&gt;</p>' . "\n"),
			array('<big>foobar</big>', '<big>foobar</big>', '<p>&lt;big&gt;foobar&lt;/big&gt;</p>' . "\n"),
            // array('<blockquote>foobar</blockquote>', '<blockquote>foobar</blockquote>', "<blockquote><p>foobar</p>\n</blockquote>"),
			array('<body>foobar</body>', '<body>foobar</body>', '<p>&lt;body&gt;foobar&lt;/body&gt;</p>' . "\n"),
			array('<button>foobar</button>', '<button>foobar</button>', '<p>&lt;button&gt;foobar&lt;/button&gt;</p>' . "\n"),
			array('<canvas>foobar</canvas>', '<canvas>foobar</canvas>', '<p>&lt;canvas&gt;foobar&lt;/canvas&gt;</p>' . "\n"),
			array('<caption>foobar</caption>', '<caption>foobar</caption>', '<p>&lt;caption&gt;foobar&lt;/caption&gt;</p>' . "\n"),
			array('<center>foobar</center>', '<center>foobar</center>', '<p>&lt;center&gt;foobar&lt;/center&gt;</p>' . "\n"),
			array('<cite>foobar</cite>', '<cite>foobar</cite>', '<p><cite>foobar</cite></p>' . "\n"),
			array('<code>foobar</code>', '<code>foobar</code>', '<p><code>foobar</code></p>' . "\n"),
			array('<col>foobar</col>', '<col>foobar</col>', '<p>&lt;col&gt;foobar&lt;/col&gt;</p>' . "\n"),
			array('<colgroup>foobar</colgroup>', '<colgroup>foobar</colgroup>', '<p>&lt;colgroup&gt;foobar&lt;/colgroup&gt;</p>' . "\n"),
			array('<datalist>foobar</datalist>', '<datalist>foobar</datalist>', '<p>&lt;datalist&gt;foobar&lt;/datalist&gt;</p>' . "\n"),
			array('<dd>foobar</dd>', '<dd>foobar</dd>', '<p>&lt;dd&gt;foobar&lt;/dd&gt;</p>' . "\n"),
			array('<del>foobar</del>', '<del>foobar</del>', '<p><del>foobar</del></p>' . "\n"),
			array('<details>foobar</details>', '<details>foobar</details>', '<p>&lt;details&gt;foobar&lt;/details&gt;</p>' . "\n"),
			array('<dfn>foobar</dfn>', '<dfn>foobar</dfn>', '<p>&lt;dfn&gt;foobar&lt;/dfn&gt;</p>' . "\n"),
			array('<dialog>foobar</dialog>', '<dialog>foobar</dialog>', '<p>&lt;dialog&gt;foobar&lt;/dialog&gt;</p>' . "\n"),
			array('<dir>foobar</dir>', '<dir>foobar</dir>', '<p>&lt;dir&gt;foobar&lt;/dir&gt;</p>' . "\n"),
			array('<div>foobar</div>', '<div>foobar</div>', '<p>&lt;div&gt;foobar&lt;/div&gt;</p>' . "\n"),
			array('<dl>foobar</dl>', '<dl>foobar</dl>', '<p>&lt;dl&gt;foobar&lt;/dl&gt;</p>' . "\n"),
			array('<dt>foobar</dt>', '<dt>foobar</dt>', '<p>&lt;dt&gt;foobar&lt;/dt&gt;</p>' . "\n"),
			array('<em>foobar</em>', '<em>foobar</em>', '<p><em>foobar</em></p>' . "\n"),
			array('<embed>foobar</embed>', '<embed>foobar</embed>', '<p>&lt;embed&gt;foobar&lt;/embed&gt;</p>' . "\n"),
			array('<fieldset>foobar</fieldset>', '<fieldset>foobar</fieldset>', '<p>&lt;fieldset&gt;foobar&lt;/fieldset&gt;</p>' . "\n"),
			array('<figcaption>foobar</figcaption>', '<figcaption>foobar</figcaption>', '<p>&lt;figcaption&gt;foobar&lt;/figcaption&gt;</p>' . "\n"),
			array('<figure>foobar</figure>', '<figure>foobar</figure>', '<p>&lt;figure&gt;foobar&lt;/figure&gt;</p>' . "\n"),
			array('<font>foobar</font>', '<font>foobar</font>', '<p>&lt;font&gt;foobar&lt;/font&gt;</p>' . "\n"),
			array('<footer>foobar</footer>', '<footer>foobar</footer>', '<p>&lt;footer&gt;foobar&lt;/footer&gt;</p>' . "\n"),
			array('<form>foobar</form>', '<form>foobar</form>', '<p>&lt;form&gt;foobar&lt;/form&gt;</p>' . "\n"),
			array('<frame>foobar</frame>', '<frame>foobar</frame>', '<p>&lt;frame&gt;foobar&lt;/frame&gt;</p>' . "\n"),
			array('<frameset>foobar</frameset>', '<frameset>foobar</frameset>', '<p>&lt;frameset&gt;foobar&lt;/frameset&gt;</p>' . "\n"),
			array('<h1>foobar</h1>', '<h1>foobar</h1>', '<p>&lt;h1&gt;foobar&lt;/h1&gt;</p>' . "\n"),
			array('<h2>foobar</h2>', '<h2>foobar</h2>', '<h2>foobar</h2>' . "\n"),
			array('<h3>foobar</h3>', '<h3>foobar</h3>', '<h3>foobar</h3>' . "\n"),
			array('<h4>foobar</h4>', '<h4>foobar</h4>', '<h4>foobar</h4>' . "\n"),
			array('<h5>foobar</h5>', '<h5>foobar</h5>', '<h5>foobar</h5>' . "\n"),
			array('<h6>foobar</h6>', '<h6>foobar</h6>', '<h6>foobar</h6>' . "\n"),
			array('<head>foobar</head>', '<head>foobar</head>', '<p>&lt;head&gt;foobar&lt;/head&gt;</p>' . "\n"),
			array('<header>foobar</header>', '<header>foobar</header>', '<p>&lt;header&gt;foobar&lt;/header&gt;</p>' . "\n"),
			array('<html>foobar</html>', '<html>foobar</html>', '<p>&lt;html&gt;foobar&lt;/html&gt;</p>' . "\n"),
			array('<i>foobar</i>', '<i>foobar</i>', '<p><i>foobar</i></p>' . "\n"),
			array('<iframe>foobar</iframe>', '<iframe>foobar</iframe>', '<p>&lt;iframe&gt;foobar&lt;/iframe&gt;</p>' . "\n"),
			array('<ins>foobar</ins>', '<ins>foobar</ins>', '<p><ins>foobar</ins></p>' . "\n"),
			array('<kbd>foobar</kbd>', '<kbd>foobar</kbd>', '<p>&lt;kbd&gt;foobar&lt;/kbd&gt;</p>' . "\n"),
			array('<keygen>foobar</keygen>', '<keygen>foobar</keygen>', '<p>&lt;keygen&gt;foobar&lt;/keygen&gt;</p>' . "\n"),
			array('<label>foobar</label>', '<label>foobar</label>', '<p>&lt;label&gt;foobar&lt;/label&gt;</p>' . "\n"),
			array('<legend>foobar</legend>', '<legend>foobar</legend>', '<p>&lt;legend&gt;foobar&lt;/legend&gt;</p>' . "\n"),
			array('<li>foobar</li>', '<li>foobar</li>', '<p>&lt;li&gt;foobar&lt;/li&gt;</p>' . "\n"),
			array('<link>foobar</link>', '<link>foobar</link>', '<p>&lt;link&gt;foobar&lt;/link&gt;</p>' . "\n"),
			array('<main>foobar</main>', '<main>foobar</main>', '<p>&lt;main&gt;foobar&lt;/main&gt;</p>' . "\n"),
			array('<map>foobar</map>', '<map>foobar</map>', '<p>&lt;map&gt;foobar&lt;/map&gt;</p>' . "\n"),
			array('<mark>foobar</mark>', '<mark>foobar</mark>', '<p><mark>foobar</mark></p>' . "\n"),
			array('<menu>foobar</menu>', '<menu>foobar</menu>', '<p>&lt;menu&gt;foobar&lt;/menu&gt;</p>' . "\n"),
			array('<menuitem>foobar</menuitem>', '<menuitem>foobar</menuitem>', '<p>&lt;menuitem&gt;foobar&lt;/menuitem&gt;</p>' . "\n"),
			array('<meta>foobar</meta>', '<meta>foobar</meta>', '<p>&lt;meta&gt;foobar&lt;/meta&gt;</p>' . "\n"),
			array('<meter>foobar</meter>', '<meter>foobar</meter>', '<p>&lt;meter&gt;foobar&lt;/meter&gt;</p>' . "\n"),
			array('<nav>foobar</nav>', '<nav>foobar</nav>', '<p>&lt;nav&gt;foobar&lt;/nav&gt;</p>' . "\n"),
			array('<noframes>foobar</noframes>', '<noframes>foobar</noframes>', '<p>&lt;noframes&gt;foobar&lt;/noframes&gt;</p>' . "\n"),
			array('<noscript>foobar</noscript>', '<noscript>foobar</noscript>', '<p>&lt;noscript&gt;foobar&lt;/noscript&gt;</p>' . "\n"),
			array('<object>foobar</object>', '<object>foobar</object>', '<p>&lt;object&gt;foobar&lt;/object&gt;</p>' . "\n"),
			array('<ol>foobar</ol>', '<ol>foobar</ol>', '<p>&lt;ol&gt;foobar&lt;/ol&gt;</p>' . "\n"),
			array('<optgroup>foobar</optgroup>', '<optgroup>foobar</optgroup>', '<p>&lt;optgroup&gt;foobar&lt;/optgroup&gt;</p>' . "\n"),
			array('<option>foobar</option>', '<option>foobar</option>', '<p>&lt;option&gt;foobar&lt;/option&gt;</p>' . "\n"),
			array('<output>foobar</output>', '<output>foobar</output>', '<p>&lt;output&gt;foobar&lt;/output&gt;</p>' . "\n"),
			array('<p>foobar</p>', '<p>foobar</p>', '<p>foobar</p>' . "\n"),
			// array('<param>foobar</param>', '<param>foobar</param>', '<p>&lt;param&gt;foobar&lt;/param&gt;</p>' . "\n"),
			// array('<picture>foobar</picture>', '<picture>foobar</picture>', '<p>&lt;picture&gt;foobar&lt;/picture&gt;</p>' . "\n"),
			array('<pre>foobar</pre>', '<pre>foobar</pre>', '<pre>foobar</pre>' . "\n"),
			// array('<progress>foobar</progress>', '<progress>foobar</progress>', '<p>&lt;progress&gt;foobar&lt;/progress&gt;</p>' . "\n"),
			array('<q>foobar</q>', '<q>foobar</q>', '<p>&lt;q&gt;foobar&lt;/q&gt;</p>' . "\n"),
			array('<rp>foobar</rp>', '<rp>foobar</rp>', '<p>&lt;rp&gt;foobar&lt;/rp&gt;</p>' . "\n"),
			array('<rt>foobar</rt>', '<rt>foobar</rt>', '<p>&lt;rt&gt;foobar&lt;/rt&gt;</p>' . "\n"),
			array('<ruby>foobar</ruby>', '<ruby>foobar</ruby>', '<p>&lt;ruby&gt;foobar&lt;/ruby&gt;</p>' . "\n"),
			array('<s>foobar</s>', '<s>foobar</s>', '<p>&lt;s&gt;foobar&lt;/s&gt;</p>' . "\n"),
			array('<samp>foobar</samp>', '<samp>foobar</samp>', '<p>&lt;samp&gt;foobar&lt;/samp&gt;</p>' . "\n"),
			array('<script>foobar</script>', '<script>foobar</script>', '<p>[removed]foobar[removed]</p>' . "\n"),
			array('<section>foobar</section>', '<section>foobar</section>', '<p>&lt;section&gt;foobar&lt;/section&gt;</p>' . "\n"),
			array('<select>foobar</select>', '<select>foobar</select>', '<p>&lt;select&gt;foobar&lt;/select&gt;</p>' . "\n"),
			array('<small>foobar</small>', '<small>foobar</small>', '<p>&lt;small&gt;foobar&lt;/small&gt;</p>' . "\n"),
			array('<source>foobar</source>', '<source>foobar</source>', '<p>&lt;source&gt;foobar&lt;/source&gt;</p>' . "\n"),
			array('<span>foobar</span>', '<span>foobar</span>', '<p><span>foobar</span></p>' . "\n"),
			array('<strike>foobar</strike>', '<strike>foobar</strike>', '<p>&lt;strike&gt;foobar&lt;/strike&gt;</p>' . "\n"),
			array('<strong>foobar</strong>', '<strong>foobar</strong>', '<p><strong>foobar</strong></p>' . "\n"),
			array('<style>foobar</style>', '<style>foobar</style>', '<p>&lt;style&gt;foobar&lt;/style&gt;</p>' . "\n"),
			array('<sub>foobar</sub>', '<sub>foobar</sub>', '<p><sub>foobar</sub></p>' . "\n"),
			array('<summary>foobar</summary>', '<summary>foobar</summary>', '<p>&lt;summary&gt;foobar&lt;/summary&gt;</p>' . "\n"),
			array('<sup>foobar</sup>', '<sup>foobar</sup>', '<p><sup>foobar</sup></p>' . "\n"),
			array('<table>foobar</table>', '<table>foobar</table>', '<p>&lt;table&gt;foobar&lt;/table&gt;</p>' . "\n"),
			array('<tbody>foobar</tbody>', '<tbody>foobar</tbody>', '<p>&lt;tbody&gt;foobar&lt;/tbody&gt;</p>' . "\n"),
			array('<td>foobar</td>', '<td>foobar</td>', '<p>&lt;td&gt;foobar&lt;/td&gt;</p>' . "\n"),
			array('<textarea>foobar</textarea>', '<textarea>foobar</textarea>', '<p>&lt;textarea&gt;foobar&lt;/textarea&gt;</p>' . "\n"),
			array('<tfoot>foobar</tfoot>', '<tfoot>foobar</tfoot>', '<p>&lt;tfoot&gt;foobar&lt;/tfoot&gt;</p>' . "\n"),
			array('<th>foobar</th>', '<th>foobar</th>', '<p>&lt;th&gt;foobar&lt;/th&gt;</p>' . "\n"),
			array('<thead>foobar</thead>', '<thead>foobar</thead>', '<p>&lt;thead&gt;foobar&lt;/thead&gt;</p>' . "\n"),
			array('<time>foobar</time>', '<time>foobar</time>', '<p>&lt;time&gt;foobar&lt;/time&gt;</p>' . "\n"),
			array('<title>foobar</title>', '<title>foobar</title>', '<p>&lt;title&gt;foobar&lt;/title&gt;</p>' . "\n"),
			array('<tr>foobar</tr>', '<tr>foobar</tr>', '<p>&lt;tr&gt;foobar&lt;/tr&gt;</p>' . "\n"),
			array('<track>foobar</track>', '<track>foobar</track>', '<p>&lt;track&gt;foobar&lt;/track&gt;</p>' . "\n"),
			array('<tt>foobar</tt>', '<tt>foobar</tt>', '<p>&lt;tt&gt;foobar&lt;/tt&gt;</p>' . "\n"),
			array('<u>foobar</u>', '<u>foobar</u>', '<p>&lt;u&gt;foobar&lt;/u&gt;</p>' . "\n"),
			array('<ul>foobar</ul>', '<ul>foobar</ul>', '<p>&lt;ul&gt;foobar&lt;/ul&gt;</p>' . "\n"),
			array('<var>foobar</var>', '<var>foobar</var>', '<p>&lt;var&gt;foobar&lt;/var&gt;</p>' . "\n"),
			array('<video>foobar</video>', '<video>foobar</video>', '<p>&lt;video&gt;foobar&lt;/video&gt;</p>' . "\n"),
			array('<wbr>foobar</wbr>', '<wbr>foobar</wbr>', '<p>&lt;wbr&gt;foobar&lt;/wbr&gt;</p>' . "\n"),
		);
	}

	protected function HTMLAttributesData()
	{
		return array(
			array('async', '<div async>', '<p>&lt;div async&gt;</p>' . "\n"),
			array('autofocus', '<div autofocus>', '<p>&lt;div autofocus&gt;</p>' . "\n"),
			array('autoplay', '<div autoplay>', '<p>&lt;div autoplay&gt;</p>' . "\n"),
			array('challenge', '<div challenge>', '<p>&lt;div challenge&gt;</p>' . "\n"),
			array('checked', '<div checked>', '<p>&lt;div checked&gt;</p>' . "\n"),
			array('controls', '<div controls>', '<p>&lt;div controls&gt;</p>' . "\n"),
			array('default', '<div default>', '<p>&lt;div default&gt;</p>' . "\n"),
			array('defer', '<div defer>', '<p>&lt;div defer&gt;</p>' . "\n"),
			array('disabled', '<div disabled>', '<p>&lt;div disabled&gt;</p>' . "\n"),
			array('hidden', '<div hidden>', '<p>&lt;div hidden&gt;</p>' . "\n"),
			array('ismap', '<div ismap>', '<p>&lt;div ismap&gt;</p>' . "\n"),
			array('loop', '<div loop>', '<p>&lt;div loop&gt;</p>' . "\n"),
			array('multiple', '<div multiple>', '<p>&lt;div multiple&gt;</p>' . "\n"),
			array('muted', '<div muted>', '<p>&lt;div muted&gt;</p>' . "\n"),
			array('novalidate', '<div novalidate>', '<p>&lt;div novalidate&gt;</p>' . "\n"),
			array('readonly', '<div readonly>', '<p>&lt;div readonly&gt;</p>' . "\n"),
			array('required', '<div required>', '<p>&lt;div required&gt;</p>' . "\n"),
			array('reversed', '<div reversed>', '<p>&lt;div reversed&gt;</p>' . "\n"),
			array('sandbox', '<div sandbox>', '<p>&lt;div sandbox&gt;</p>' . "\n"),
			array('scoped', '<div scoped>', '<p>&lt;div scoped&gt;</p>' . "\n"),
			array('selected', '<div selected>', '<p>&lt;div selected&gt;</p>' . "\n"),

			array('accept', '<div accept="foo">', '<p>&lt;div accept=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('accept-charset', '<div accept-charset="foo">', '<p>&lt;div accept-charset=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('accesskey', '<div accesskey="foo">', '<p>&lt;div accesskey=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('action', '<div action="foo">', '<p>&lt;div action=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('align', '<div align="foo">', '<p>&lt;div align=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('alt', '<div alt="foo">', '<p>&lt;div alt=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('autocomplete', '<div autocomplete="foo">', '<p>&lt;div autocomplete=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('bgcolor', '<div bgcolor="foo">', '<p>&lt;div bgcolor=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('border', '<div border="foo">', '<p>&lt;div border=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('charset', '<div charset="foo">', '<p>&lt;div charset=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('cite', '<div cite="foo">', '<p>&lt;div cite=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('class', '<div class="foo">', '<p>&lt;div class=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('color', '<div color="foo">', '<p>&lt;div color=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('cols', '<div cols="foo">', '<p>&lt;div cols=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('colspan', '<div colspan="foo">', '<p>&lt;div colspan=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('content', '<div content="foo">', '<p>&lt;div content=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('contenteditable', '<div contenteditable="foo">', '<p>&lt;div contenteditable=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('contextmenu', '<div contextmenu="foo">', '<p>&lt;div contextmenu=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('coords', '<div coords="foo">', '<p>&lt;div coords=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('data', '<div data="foo">', '<p>&lt;div data=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('data', '<div data="foo">', '<p>&lt;div data=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('datetime', '<div datetime="foo">', '<p>&lt;div datetime=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('dir', '<div dir="foo">', '<p>&lt;div dir=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('dirname', '<div dirname="foo">', '<p>&lt;div dirname=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('download', '<div download="foo">', '<p>&lt;div download=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('draggable', '<div draggable="foo">', '<p>&lt;div draggable=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('dropzone', '<div dropzone="foo">', '<p>&lt;div dropzone=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('enctype', '<div enctype="foo">', '<p>&lt;div enctype=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('for', '<div for="foo">', '<p>&lt;div for=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('form', '<div form="foo">', '<p>&lt;div form=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('formaction', '<div formaction="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('headers', '<div headers="foo">', '<p>&lt;div headers=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('height', '<div height="foo">', '<p>&lt;div height=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('high', '<div high="foo">', '<p>&lt;div high=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('href', '<div href="foo">', '<p>&lt;div href=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('hreflang', '<div hreflang="foo">', '<p>&lt;div hreflang=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('http', '<div http="foo">', '<p>&lt;div http=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('id', '<div id="foo">', '<p>&lt;div id=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('keytype', '<div keytype="foo">', '<p>&lt;div keytype=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('kind', '<div kind="foo">', '<p>&lt;div kind=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('label', '<div label="foo">', '<p>&lt;div label=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('lang', '<div lang="foo">', '<p>&lt;div lang=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('list', '<div list="foo">', '<p>&lt;div list=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('low', '<div low="foo">', '<p>&lt;div low=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('max', '<div max="foo">', '<p>&lt;div max=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('maxlength', '<div maxlength="foo">', '<p>&lt;div maxlength=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('media', '<div media="foo">', '<p>&lt;div media=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('method', '<div method="foo">', '<p>&lt;div method=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('min', '<div min="foo">', '<p>&lt;div min=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('name', '<div name="foo">', '<p>&lt;div name=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('onabort', '<div onabort="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onafterprint', '<div onafterprint="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onbeforeprint', '<div onbeforeprint="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onbeforeunload', '<div onbeforeunload="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onblur', '<div onblur="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncanplay', '<div oncanplay="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncanplaythrough', '<div oncanplaythrough="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onchange', '<div onchange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onclick', '<div onclick="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncontextmenu', '<div oncontextmenu="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncopy', '<div oncopy="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncuechange', '<div oncuechange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oncut', '<div oncut="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondblclick', '<div ondblclick="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondrag', '<div ondrag="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondragend', '<div ondragend="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondragenter', '<div ondragenter="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondragleave', '<div ondragleave="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondragover', '<div ondragover="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondragstart', '<div ondragstart="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondrop', '<div ondrop="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ondurationchange', '<div ondurationchange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onemptied', '<div onemptied="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onended', '<div onended="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onerror', '<div onerror="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onfocus', '<div onfocus="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onhashchange', '<div onhashchange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oninput', '<div oninput="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('oninvalid', '<div oninvalid="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onkeydown', '<div onkeydown="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onkeypress', '<div onkeypress="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onkeyup', '<div onkeyup="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onload', '<div onload="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onloadeddata', '<div onloadeddata="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onloadedmetadata', '<div onloadedmetadata="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onloadstart', '<div onloadstart="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmousedown', '<div onmousedown="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmousemove', '<div onmousemove="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmouseout', '<div onmouseout="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmouseover', '<div onmouseover="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmouseup', '<div onmouseup="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onmousewheel', '<div onmousewheel="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onoffline', '<div onoffline="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ononline', '<div ononline="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onpagehide', '<div onpagehide="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onpageshow', '<div onpageshow="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onpaste', '<div onpaste="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onpause', '<div onpause="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onplay', '<div onplay="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onplaying', '<div onplaying="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onpopstate', '<div onpopstate="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onprogress', '<div onprogress="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onratechange', '<div onratechange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onreset', '<div onreset="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onresize', '<div onresize="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onscroll', '<div onscroll="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onsearch', '<div onsearch="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onseeked', '<div onseeked="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onseeking', '<div onseeking="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onselect', '<div onselect="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onshow', '<div onshow="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onstalled', '<div onstalled="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onstorage', '<div onstorage="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onsubmit', '<div onsubmit="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onsuspend', '<div onsuspend="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ontimeupdate', '<div ontimeupdate="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('ontoggle', '<div ontoggle="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onunload', '<div onunload="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onvolumechange', '<div onvolumechange="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onwaiting', '<div onwaiting="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('onwheel', '<div onwheel="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('open', '<div open="foo">', '<p>&lt;div open=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('optimum', '<div optimum="foo">', '<p>&lt;div optimum=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('pattern', '<div pattern="foo">', '<p>&lt;div pattern=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('placeholder', '<div placeholder="foo">', '<p>&lt;div placeholder=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('poster', '<div poster="foo">', '<p>&lt;div poster=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('preload', '<div preload="foo">', '<p>&lt;div preload=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('rel', '<div rel="foo">', '<p>&lt;div rel=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('rows', '<div rows="foo">', '<p>&lt;div rows=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('rowspan', '<div rowspan="foo">', '<p>&lt;div rowspan=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('scope', '<div scope="foo">', '<p>&lt;div scope=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('shape', '<div shape="foo">', '<p>&lt;div shape=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('size', '<div size="foo">', '<p>&lt;div size=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('sizes', '<div sizes="foo">', '<p>&lt;div sizes=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('span', '<div span="foo">', '<p>&lt;div span=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('spellcheck', '<div spellcheck="foo">', '<p>&lt;div spellcheck=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('src', '<div src="foo">', '<p>&lt;div src=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('srcdoc', '<div srcdoc="foo">', '<p>&lt;div srcdoc=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('srclang', '<div srclang="foo">', '<p>&lt;div srclang=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('srcset', '<div srcset="foo">', '<p>&lt;div srcset=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('start', '<div start="foo">', '<p>&lt;div start=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('step', '<div step="foo">', '<p>&lt;div step=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('style', '<div style="foo">', '<p>&lt;div &gt;</p>' . "\n"),
			array('tabindex', '<div tabindex="foo">', '<p>&lt;div tabindex=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('target', '<div target="foo">', '<p>&lt;div target=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('title', '<div title="foo">', '<p>&lt;div title=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('translate', '<div translate="foo">', '<p>&lt;div translate=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('type', '<div type="foo">', '<p>&lt;div type=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('usemap', '<div usemap="foo">', '<p>&lt;div usemap=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('value', '<div value="foo">', '<p>&lt;div value=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('width', '<div width="foo">', '<p>&lt;div width=&#8221;foo&#8221;&gt;</p>' . "\n"),
			array('wrap', '<div wrap="foo">', '<p>&lt;div wrap=&#8221;foo&#8221;&gt;</p>' . "\n"),
		);
	}

	protected function HTMLWithAttributesData()
	{
		$all_attributes = 'async autofocus autoplay challenge checked controls default defer disabled hidden ismap loop multiple muted novalidate readonly required reversed sandbox scoped selected accept="foo" accept-charset="foo" accesskey="foo" action="foo" align="foo" alt="foo" autocomplete="foo" bgcolor="foo" border="foo" charset="foo" cite="foo" class="foo" color="foo" cols="foo" colspan="foo" content="foo" contenteditable="foo" contextmenu="foo" coords="foo" data="foo" data="foo" datetime="foo" dir="foo" dirname="foo" download="foo" draggable="foo" dropzone="foo" enctype="foo" for="foo" form="foo" formaction="foo" headers="foo" height="foo" high="foo" href="foo" hreflang="foo" http="foo" id="foo" keytype="foo" kind="foo" label="foo" lang="foo" list="foo" low="foo" max="foo" maxlength="foo" media="foo" method="foo" min="foo" name="foo" onabort="foo" onafterprint="foo" onbeforeprint="foo" onbeforeunload="foo" onblur="foo" oncanplay="foo" oncanplaythrough="foo" onchange="foo" onclick="foo" oncontextmenu="foo" oncopy="foo" oncuechange="foo" oncut="foo" ondblclick="foo" ondrag="foo" ondragend="foo" ondragenter="foo" ondragleave="foo" ondragover="foo" ondragstart="foo" ondrop="foo" ondurationchange="foo" onemptied="foo" onended="foo" onerror="foo" onfocus="foo" onhashchange="foo" oninput="foo" oninvalid="foo" onkeydown="foo" onkeypress="foo" onkeyup="foo" onload="foo" onloadeddata="foo" onloadedmetadata="foo" onloadstart="foo" onmousedown="foo" onmousemove="foo" onmouseout="foo" onmouseover="foo" onmouseup="foo" onmousewheel="foo" onoffline="foo" ononline="foo" onpagehide="foo" onpageshow="foo" onpaste="foo" onpause="foo" onplay="foo" onplaying="foo" onpopstate="foo" onprogress="foo" onratechange="foo" onreset="foo" onresize="foo" onscroll="foo" onsearch="foo" onseeked="foo" onseeking="foo" onselect="foo" onshow="foo" onstalled="foo" onstorage="foo" onsubmit="foo" onsuspend="foo" ontimeupdate="foo" ontoggle="foo" onunload="foo" onvolumechange="foo" onwaiting="foo" onwheel="foo" open="foo" optimum="foo" pattern="foo" placeholder="foo" poster="foo" preload="foo" rel="foo" rows="foo" rowspan="foo" scope="foo" shape="foo" size="foo" sizes="foo" span="foo" spellcheck="foo" src="foo" srcdoc="foo" srclang="foo" srcset="foo" start="foo" step="foo" style="foo" tabindex="foo" target="foo" title="foo" translate="foo" type="foo" usemap="foo" value="foo" width="foo" wrap="foo"';
		$allowed_attributes = 'async autofocus autoplay challenge checked controls default defer disabled hidden ismap loop multiple muted novalidate readonly required reversed sandbox scoped selected accept=&#8221;foo&#8221; accept-charset=&#8221;foo&#8221; accesskey=&#8221;foo&#8221; action=&#8221;foo&#8221; align=&#8221;foo&#8221; alt=&#8221;foo&#8221; autocomplete=&#8221;foo&#8221; bgcolor=&#8221;foo&#8221; border=&#8221;foo&#8221; charset=&#8221;foo&#8221; cite=&#8221;foo&#8221; class=&#8221;foo&#8221; color=&#8221;foo&#8221; cols=&#8221;foo&#8221; colspan=&#8221;foo&#8221; content=&#8221;foo&#8221; contenteditable=&#8221;foo&#8221; contextmenu=&#8221;foo&#8221; coords=&#8221;foo&#8221; data=&#8221;foo&#8221; data=&#8221;foo&#8221; datetime=&#8221;foo&#8221; dir=&#8221;foo&#8221; dirname=&#8221;foo&#8221; download=&#8221;foo&#8221; draggable=&#8221;foo&#8221; dropzone=&#8221;foo&#8221; enctype=&#8221;foo&#8221; for=&#8221;foo&#8221; form=&#8221;foo&#8221;  headers=&#8221;foo&#8221; height=&#8221;foo&#8221; high=&#8221;foo&#8221; href=&#8221;foo&#8221; hreflang=&#8221;foo&#8221; http=&#8221;foo&#8221; id=&#8221;foo&#8221; keytype=&#8221;foo&#8221; kind=&#8221;foo&#8221; label=&#8221;foo&#8221; lang=&#8221;foo&#8221; list=&#8221;foo&#8221; low=&#8221;foo&#8221; max=&#8221;foo&#8221; maxlength=&#8221;foo&#8221; media=&#8221;foo&#8221; method=&#8221;foo&#8221; min=&#8221;foo&#8221; name=&#8221;foo&#8221;                                                                        open=&#8221;foo&#8221; optimum=&#8221;foo&#8221; pattern=&#8221;foo&#8221; placeholder=&#8221;foo&#8221; poster=&#8221;foo&#8221; preload=&#8221;foo&#8221; rel=&#8221;foo&#8221; rows=&#8221;foo&#8221; rowspan=&#8221;foo&#8221; scope=&#8221;foo&#8221; shape=&#8221;foo&#8221; size=&#8221;foo&#8221; sizes=&#8221;foo&#8221; span=&#8221;foo&#8221; spellcheck=&#8221;foo&#8221; src=&#8221;foo&#8221; srcdoc=&#8221;foo&#8221; srclang=&#8221;foo&#8221; srcset=&#8221;foo&#8221; start=&#8221;foo&#8221; step=&#8221;foo&#8221;  tabindex=&#8221;foo&#8221; target=&#8221;foo&#8221; title=&#8221;foo&#8221; translate=&#8221;foo&#8221; type=&#8221;foo&#8221; usemap=&#8221;foo&#8221; value=&#8221;foo&#8221; width=&#8221;foo&#8221; wrap=&#8221;foo&#8221;';

		return array(
			array('<a> with attributes', '<a ' . $all_attributes . '></a>', '<p><a href="http://foo%22accept=%22foo" rel="foo" title="foo" class="foo" target="foo"></a></p>' . "\n"),
			// array('<abbr> with attributes', '<abbr ' . $all_attributes . '></abbr>', '<p>&lt;abbr ' . $allowed_attributes . '&gt;&lt;/abbr&gt;</p>' . "\n"),
			// array('<acronym> with attributes', '<acronym ' . $all_attributes . '></acronym>', '<p>&lt;acronym ' . $allowed_attributes . '&gt;&lt;/acronym&gt;</p>' . "\n"),
			// array('<address> with attributes', '<address ' . $all_attributes . '></address>', '<p>&lt;address ' . $allowed_attributes . '&gt;&lt;/address&gt;</p>' . "\n"),
			// array('<applet> with attributes', '<applet ' . $all_attributes . '></applet>', '<p>&lt;applet ' . $allowed_attributes . '&gt;&lt;/applet&gt;</p>' . "\n"),
			// array('<area> with attributes', '<area ' . $all_attributes . '></area>', '<p>&lt;area ' . $allowed_attributes . '&gt;&lt;/area&gt;</p>' . "\n"),
			// array('<article> with attributes', '<article ' . $all_attributes . '></article>', '<p>&lt;article ' . $allowed_attributes . '&gt;&lt;/article&gt;</p>' . "\n"),
			// array('<aside> with attributes', '<aside ' . $all_attributes . '></aside>', '<p>&lt;aside ' . $allowed_attributes . '&gt;&lt;/aside&gt;</p>' . "\n"),
			// array('<audio> with attributes', '<audio ' . $all_attributes . '></audio>', '<p>&lt;audio ' . $allowed_attributes . '&gt;&lt;/audio&gt;</p>' . "\n"),
			array('<b> with attributes', '<b ' . $all_attributes . '></b>', '<p>&lt;b ' . $allowed_attributes . '&gt;&lt;/b&gt;</p>' . "\n"),
			array('<base> with attributes', '<base ' . $all_attributes . '></base>', '<p>&lt;base ' . $allowed_attributes . '&gt;&lt;/base&gt;</p>' . "\n"),
			array('<basefont> with attributes', '<basefont ' . $all_attributes . '></basefont>', '<p>&lt;basefont ' . $allowed_attributes . '&gt;&lt;/basefont&gt;</p>' . "\n"),
			array('<bdi> with attributes', '<bdi ' . $all_attributes . '></bdi>', '<p>&lt;bdi ' . $allowed_attributes . '&gt;&lt;/bdi&gt;</p>' . "\n"),
			array('<bdo> with attributes', '<bdo ' . $all_attributes . '></bdo>', '<p>&lt;bdo ' . $allowed_attributes . '&gt;&lt;/bdo&gt;</p>' . "\n"),
			array('<big> with attributes', '<big ' . $all_attributes . '></big>', '<p>&lt;big ' . $allowed_attributes . '&gt;&lt;/big&gt;</p>' . "\n"),
			array('<blockquote> with attributes', '<blockquote ' . $all_attributes . '></blockquote>', '<p>&lt;blockquote ' . $allowed_attributes . '&gt;&lt;/blockquote&gt;</p>' . "\n"),
			array('<body> with attributes', '<body ' . $all_attributes . '></body>', '<p>&lt;body ' . $allowed_attributes . '&gt;&lt;/body&gt;</p>' . "\n"),
			// array('<br> with attributes', '<br ' . $all_attributes . '>', "\n"),
			array('<button> with attributes', '<button ' . $all_attributes . '></button>', '<p>&lt;button ' . $allowed_attributes . '&gt;&lt;/button&gt;</p>' . "\n"),
			array('<canvas> with attributes', '<canvas ' . $all_attributes . '></canvas>', '<p>&lt;canvas ' . $allowed_attributes . '&gt;&lt;/canvas&gt;</p>' . "\n"),
			array('<caption> with attributes', '<caption ' . $all_attributes . '></caption>', '<p>&lt;caption ' . $allowed_attributes . '&gt;&lt;/caption&gt;</p>' . "\n"),
			array('<center> with attributes', '<center ' . $all_attributes . '></center>', '<p>&lt;center ' . $allowed_attributes . '&gt;&lt;/center&gt;</p>' . "\n"),
			array('<cite> with attributes', '<cite ' . $all_attributes . '></cite>', '<p>&lt;cite ' . $allowed_attributes . '&gt;&lt;/cite&gt;</p>' . "\n"),
			array('<code> with attributes', '<code ' . $all_attributes . '></code>', '<p><code class="foo"></code></p>' . "\n"),
			array('<col> with attributes', '<col ' . $all_attributes . '></col>', '<p>&lt;col ' . $allowed_attributes . '&gt;&lt;/col&gt;</p>' . "\n"),
			array('<colgroup> with attributes', '<colgroup ' . $all_attributes . '></colgroup>', '<p>&lt;colgroup ' . $allowed_attributes . '&gt;&lt;/colgroup&gt;</p>' . "\n"),
			array('<datalist> with attributes', '<datalist ' . $all_attributes . '></datalist>', '<p>&lt;datalist ' . $allowed_attributes . '&gt;&lt;/datalist&gt;</p>' . "\n"),
			array('<dd> with attributes', '<dd ' . $all_attributes . '></dd>', '<p>&lt;dd ' . $allowed_attributes . '&gt;&lt;/dd&gt;</p>' . "\n"),
			array('<del> with attributes', '<del ' . $all_attributes . '></del>', '<p>&lt;del ' . $allowed_attributes . '&gt;&lt;/del&gt;</p>' . "\n"),
			array('<details> with attributes', '<details ' . $all_attributes . '></details>', '<p>&lt;details ' . $allowed_attributes . '&gt;&lt;/details&gt;</p>' . "\n"),
			array('<dfn> with attributes', '<dfn ' . $all_attributes . '></dfn>', '<p>&lt;dfn ' . $allowed_attributes . '&gt;&lt;/dfn&gt;</p>' . "\n"),
			array('<dialog> with attributes', '<dialog ' . $all_attributes . '></dialog>', '<p>&lt;dialog ' . $allowed_attributes . '&gt;&lt;/dialog&gt;</p>' . "\n"),
			array('<dir> with attributes', '<dir ' . $all_attributes . '></dir>', '<p>&lt;dir ' . $allowed_attributes . '&gt;&lt;/dir&gt;</p>' . "\n"),
			array('<div> with attributes', '<div ' . $all_attributes . '></div>', '<p>&lt;div ' . $allowed_attributes . '&gt;&lt;/div&gt;</p>' . "\n"),
			array('<dl> with attributes', '<dl ' . $all_attributes . '></dl>', '<p>&lt;dl ' . $allowed_attributes . '&gt;&lt;/dl&gt;</p>' . "\n"),
			array('<dt> with attributes', '<dt ' . $all_attributes . '></dt>', '<p>&lt;dt ' . $allowed_attributes . '&gt;&lt;/dt&gt;</p>' . "\n"),
			array('<em> with attributes', '<em ' . $all_attributes . '></em>', '<p>&lt;em ' . $allowed_attributes . '&gt;&lt;/em&gt;</p>' . "\n"),
			array('<embed> with attributes', '<embed ' . $all_attributes . '></embed>', '<p>&lt;embed ' . $allowed_attributes . '&gt;&lt;/embed&gt;</p>' . "\n"),
			array('<fieldset> with attributes', '<fieldset ' . $all_attributes . '></fieldset>', '<p>&lt;fieldset ' . $allowed_attributes . '&gt;&lt;/fieldset&gt;</p>' . "\n"),
			array('<figcaption> with attributes', '<figcaption ' . $all_attributes . '></figcaption>', '<p>&lt;figcaption ' . $allowed_attributes . '&gt;&lt;/figcaption&gt;</p>' . "\n"),
			array('<figure> with attributes', '<figure ' . $all_attributes . '></figure>', '<p>&lt;figure ' . $allowed_attributes . '&gt;&lt;/figure&gt;</p>' . "\n"),
			array('<font> with attributes', '<font ' . $all_attributes . '></font>', '<p>&lt;font ' . $allowed_attributes . '&gt;&lt;/font&gt;</p>' . "\n"),
			array('<footer> with attributes', '<footer ' . $all_attributes . '></footer>', '<p>&lt;footer ' . $allowed_attributes . '&gt;&lt;/footer&gt;</p>' . "\n"),
			array('<form> with attributes', '<form ' . $all_attributes . '></form>', '<p>&lt;form ' . $allowed_attributes . '&gt;&lt;/form&gt;</p>' . "\n"),
			array('<frame> with attributes', '<frame ' . $all_attributes . '></frame>', '<p>&lt;frame ' . $allowed_attributes . '&gt;&lt;/frame&gt;</p>' . "\n"),
			array('<frameset> with attributes', '<frameset ' . $all_attributes . '></frameset>', '<p>&lt;frameset ' . $allowed_attributes . '&gt;&lt;/frameset&gt;</p>' . "\n"),
			// array('<h1> with attributes', '<h1 ' . $all_attributes . '></h1>', '<p>&lt;h1 ' . $allowed_attributes . '&gt;&lt;/h1&gt;</p>' . "\n"),
			// array('<h2> with attributes', '<h2 ' . $all_attributes . '></h2>', '<p>&lt;h2 ' . $allowed_attributes . '&gt;&lt;/h2&gt;</p>' . "\n"),
			// array('<h3> with attributes', '<h3 ' . $all_attributes . '></h3>', '<p>&lt;h3 ' . $allowed_attributes . '&gt;&lt;/h3&gt;</p>' . "\n"),
			// array('<h4> with attributes', '<h4 ' . $all_attributes . '></h4>', '<p>&lt;h4 ' . $allowed_attributes . '&gt;&lt;/h4&gt;</p>' . "\n"),
			// array('<h5> with attributes', '<h5 ' . $all_attributes . '></h5>', '<p>&lt;h5 ' . $allowed_attributes . '&gt;&lt;/h5&gt;</p>' . "\n"),
			// array('<h6> with attributes', '<h6 ' . $all_attributes . '></h6>', '<p>&lt;h6 ' . $allowed_attributes . '&gt;&lt;/h6&gt;</p>' . "\n"),
			array('<head> with attributes', '<head ' . $all_attributes . '></head>', '<p>&lt;head ' . $allowed_attributes . '&gt;&lt;/head&gt;</p>' . "\n"),
			array('<header> with attributes', '<header ' . $all_attributes . '></header>', '<p>&lt;header ' . $allowed_attributes . '&gt;&lt;/header&gt;</p>' . "\n"),
			array('<html> with attributes', '<html ' . $all_attributes . '></html>', '<p>&lt;html ' . $allowed_attributes . '&gt;&lt;/html&gt;</p>' . "\n"),
			array('<i> with attributes', '<i ' . $all_attributes . '></i>', '<p>&lt;i ' . $allowed_attributes . '&gt;&lt;/i&gt;</p>' . "\n"),
			array('<iframe> with attributes', '<iframe ' . $all_attributes . '></iframe>', '<p>&lt;iframe ' . $allowed_attributes . '&gt;&lt;/iframe&gt;</p>' . "\n"),
			// array('<img> with attributes', '<img ' . $all_attributes . '>', '<p>&lt;img ' . $allowed_attributes . '&gt;</p>' . "\n"),
			array('<input> with attributes', '<input ' . $all_attributes . '>', '<p>&lt;input ' . $allowed_attributes . '&gt;</p>' . "\n"),
			array('<ins> with attributes', '<ins ' . $all_attributes . '></ins>', '<p>&lt;ins ' . $allowed_attributes . '&gt;&lt;/ins&gt;</p>' . "\n"),
			array('<kbd> with attributes', '<kbd ' . $all_attributes . '></kbd>', '<p>&lt;kbd ' . $allowed_attributes . '&gt;&lt;/kbd&gt;</p>' . "\n"),
			array('<keygen> with attributes', '<keygen ' . $all_attributes . '></keygen>', '<p>&lt;keygen ' . $allowed_attributes . '&gt;&lt;/keygen&gt;</p>' . "\n"),
			array('<label> with attributes', '<label ' . $all_attributes . '></label>', '<p>&lt;label ' . $allowed_attributes . '&gt;&lt;/label&gt;</p>' . "\n"),
			array('<legend> with attributes', '<legend ' . $all_attributes . '></legend>', '<p>&lt;legend ' . $allowed_attributes . '&gt;&lt;/legend&gt;</p>' . "\n"),
			array('<li> with attributes', '<li ' . $all_attributes . '></li>', '<p>&lt;li ' . $allowed_attributes . '&gt;&lt;/li&gt;</p>' . "\n"),
			array('<link> with attributes', '<link ' . $all_attributes . '></link>', '<p>&lt;link ' . $allowed_attributes . '&gt;&lt;/link&gt;</p>' . "\n"),
			array('<main> with attributes', '<main ' . $all_attributes . '></main>', '<p>&lt;main ' . $allowed_attributes . '&gt;&lt;/main&gt;</p>' . "\n"),
			array('<map> with attributes', '<map ' . $all_attributes . '></map>', '<p>&lt;map ' . $allowed_attributes . '&gt;&lt;/map&gt;</p>' . "\n"),
			array('<mark> with attributes', '<mark ' . $all_attributes . '></mark>', '<p><mark class="foo"></mark></p>' . "\n"),
			array('<menu> with attributes', '<menu ' . $all_attributes . '></menu>', '<p>&lt;menu ' . $allowed_attributes . '&gt;&lt;/menu&gt;</p>' . "\n"),
			array('<menuitem> with attributes', '<menuitem ' . $all_attributes . '></menuitem>', '<p>&lt;menuitem ' . $allowed_attributes . '&gt;&lt;/menuitem&gt;</p>' . "\n"),
			array('<meta> with attributes', '<meta ' . $all_attributes . '></meta>', '<p>&lt;meta ' . $allowed_attributes . '&gt;&lt;/meta&gt;</p>' . "\n"),
			array('<meter> with attributes', '<meter ' . $all_attributes . '></meter>', '<p>&lt;meter ' . $allowed_attributes . '&gt;&lt;/meter&gt;</p>' . "\n"),
			array('<nav> with attributes', '<nav ' . $all_attributes . '></nav>', '<p>&lt;nav ' . $allowed_attributes . '&gt;&lt;/nav&gt;</p>' . "\n"),
			array('<noframes> with attributes', '<noframes ' . $all_attributes . '></noframes>', '<p>&lt;noframes ' . $allowed_attributes . '&gt;&lt;/noframes&gt;</p>' . "\n"),
			array('<noscript> with attributes', '<noscript ' . $all_attributes . '></noscript>', '<p>&lt;noscript ' . $allowed_attributes . '&gt;&lt;/noscript&gt;</p>' . "\n"),
			array('<object> with attributes', '<object ' . $all_attributes . '></object>', '<p>&lt;object ' . $allowed_attributes . '&gt;&lt;/object&gt;</p>' . "\n"),
			array('<ol> with attributes', '<ol ' . $all_attributes . '></ol>', '<p>&lt;ol ' . $allowed_attributes . '&gt;&lt;/ol&gt;</p>' . "\n"),
			array('<optgroup> with attributes', '<optgroup ' . $all_attributes . '></optgroup>', '<p>&lt;optgroup ' . $allowed_attributes . '&gt;&lt;/optgroup&gt;</p>' . "\n"),
			array('<option> with attributes', '<option ' . $all_attributes . '></option>', '<p>&lt;option ' . $allowed_attributes . '&gt;&lt;/option&gt;</p>' . "\n"),
			array('<output> with attributes', '<output ' . $all_attributes . '></output>', '<p>&lt;output ' . $allowed_attributes . '&gt;&lt;/output&gt;</p>' . "\n"),
			array('<p> with attributes', '<p ' . $all_attributes . '></p>', '' . "\n"),
			// array('<param> with attributes', '<param ' . $all_attributes . '></param>', '<p>&lt;param ' . $allowed_attributes . '&gt;&lt;/param&gt;</p>' . "\n"),
			// array('<picture> with attributes', '<picture ' . $all_attributes . '></picture>', '<p>&lt;picture ' . $allowed_attributes . '&gt;&lt;/picture&gt;</p>' . "\n"),
			array('<pre> with attributes', '<pre ' . $all_attributes . '></pre>', '<p>&lt;pre&gt;&lt;/pre&gt;</p>' . "\n"),
			// array('<progress> with attributes', '<progress ' . $all_attributes . '></progress>', '<p>&lt;progress ' . $allowed_attributes . '&gt;&lt;/progress&gt;</p>' . "\n"),
			array('<q> with attributes', '<q ' . $all_attributes . '></q>', '<p>&lt;q ' . $allowed_attributes . '&gt;&lt;/q&gt;</p>' . "\n"),
			array('<rp> with attributes', '<rp ' . $all_attributes . '></rp>', '<p>&lt;rp ' . $allowed_attributes . '&gt;&lt;/rp&gt;</p>' . "\n"),
			array('<rt> with attributes', '<rt ' . $all_attributes . '></rt>', '<p>&lt;rt ' . $allowed_attributes . '&gt;&lt;/rt&gt;</p>' . "\n"),
			array('<ruby> with attributes', '<ruby ' . $all_attributes . '></ruby>', '<p>&lt;ruby ' . $allowed_attributes . '&gt;&lt;/ruby&gt;</p>' . "\n"),
			array('<s> with attributes', '<s ' . $all_attributes . '></s>', '<p>&lt;s ' . $allowed_attributes . '&gt;&lt;/s&gt;</p>' . "\n"),
			array('<samp> with attributes', '<samp ' . $all_attributes . '></samp>', '<p>&lt;samp ' . $allowed_attributes . '&gt;&lt;/samp&gt;</p>' . "\n"),
			array('<script> with attributes', '<script ' . $all_attributes . '></script>', '<p>[removed][removed]</p>' . "\n"),
			array('<section> with attributes', '<section ' . $all_attributes . '></section>', '<p>&lt;section ' . $allowed_attributes . '&gt;&lt;/section&gt;</p>' . "\n"),
			array('<select> with attributes', '<select ' . $all_attributes . '></select>', '<p>&lt;select ' . $allowed_attributes . '&gt;&lt;/select&gt;</p>' . "\n"),
			array('<small> with attributes', '<small ' . $all_attributes . '></small>', '<p>&lt;small ' . $allowed_attributes . '&gt;&lt;/small&gt;</p>' . "\n"),
			array('<source> with attributes', '<source ' . $all_attributes . '></source>', '<p>&lt;source ' . $allowed_attributes . '&gt;&lt;/source&gt;</p>' . "\n"),
			array('<span> with attributes', '<span ' . $all_attributes . '></span>', '<p><span class="foo"></span></p>' . "\n"),
			array('<strike> with attributes', '<strike ' . $all_attributes . '></strike>', '<p>&lt;strike ' . $allowed_attributes . '&gt;&lt;/strike&gt;</p>' . "\n"),
			array('<strong> with attributes', '<strong ' . $all_attributes . '></strong>', '<p>&lt;strong ' . $allowed_attributes . '&gt;&lt;/strong&gt;</p>' . "\n"),
			array('<style> with attributes', '<style ' . $all_attributes . '></style>', '<p>&lt;style ' . $allowed_attributes . '&gt;&lt;/style&gt;</p>' . "\n"),
			array('<sub> with attributes', '<sub ' . $all_attributes . '></sub>', '<p>&lt;sub ' . $allowed_attributes . '&gt;&lt;/sub&gt;</p>' . "\n"),
			array('<summary> with attributes', '<summary ' . $all_attributes . '></summary>', '<p>&lt;summary ' . $allowed_attributes . '&gt;&lt;/summary&gt;</p>' . "\n"),
			array('<sup> with attributes', '<sup ' . $all_attributes . '></sup>', '<p>&lt;sup ' . $allowed_attributes . '&gt;&lt;/sup&gt;</p>' . "\n"),
			array('<table> with attributes', '<table ' . $all_attributes . '></table>', '<p>&lt;table ' . $allowed_attributes . '&gt;&lt;/table&gt;</p>' . "\n"),
			array('<tbody> with attributes', '<tbody ' . $all_attributes . '></tbody>', '<p>&lt;tbody ' . $allowed_attributes . '&gt;&lt;/tbody&gt;</p>' . "\n"),
			array('<td> with attributes', '<td ' . $all_attributes . '></td>', '<p>&lt;td ' . $allowed_attributes . '&gt;&lt;/td&gt;</p>' . "\n"),
			array('<textarea> with attributes', '<textarea ' . $all_attributes . '></textarea>', '<p>&lt;textarea ' . $allowed_attributes . '&gt;&lt;/textarea&gt;</p>' . "\n"),
			array('<tfoot> with attributes', '<tfoot ' . $all_attributes . '></tfoot>', '<p>&lt;tfoot ' . $allowed_attributes . '&gt;&lt;/tfoot&gt;</p>' . "\n"),
			array('<th> with attributes', '<th ' . $all_attributes . '></th>', '<p>&lt;th ' . $allowed_attributes . '&gt;&lt;/th&gt;</p>' . "\n"),
			array('<thead> with attributes', '<thead ' . $all_attributes . '></thead>', '<p>&lt;thead ' . $allowed_attributes . '&gt;&lt;/thead&gt;</p>' . "\n"),
			array('<time> with attributes', '<time ' . $all_attributes . '></time>', '<p>&lt;time ' . $allowed_attributes . '&gt;&lt;/time&gt;</p>' . "\n"),
			array('<title> with attributes', '<title ' . $all_attributes . '></title>', '<p>&lt;title ' . $allowed_attributes . '&gt;&lt;/title&gt;</p>' . "\n"),
			array('<tr> with attributes', '<tr ' . $all_attributes . '></tr>', '<p>&lt;tr ' . $allowed_attributes . '&gt;&lt;/tr&gt;</p>' . "\n"),
			array('<track> with attributes', '<track ' . $all_attributes . '></track>', '<p>&lt;track ' . $allowed_attributes . '&gt;&lt;/track&gt;</p>' . "\n"),
			array('<tt> with attributes', '<tt ' . $all_attributes . '></tt>', '<p>&lt;tt ' . $allowed_attributes . '&gt;&lt;/tt&gt;</p>' . "\n"),
			array('<u> with attributes', '<u ' . $all_attributes . '></u>', '<p>&lt;u ' . $allowed_attributes . '&gt;&lt;/u&gt;</p>' . "\n"),
			array('<ul> with attributes', '<ul ' . $all_attributes . '></ul>', '<p>&lt;ul ' . $allowed_attributes . '&gt;&lt;/ul&gt;</p>' . "\n"),
			array('<var> with attributes', '<var ' . $all_attributes . '></var>', '<p>&lt;var ' . $allowed_attributes . '&gt;&lt;/var&gt;</p>' . "\n"),
			array('<video> with attributes', '<video ' . $all_attributes . '></video>', '<p>&lt;video ' . $allowed_attributes . '&gt;&lt;/video&gt;</p>' . "\n"),
			array('<wbr> with attributes', '<wbr ' . $all_attributes . '></wbr>', '<p>&lt;wbr ' . $allowed_attributes . '&gt;&lt;/wbr&gt;</p>' . "\n"),
		);
	}

	protected function markdownData()
	{
		$data = array(
			// Automatic Escaping
			array('Ampersands', 'AT&T', "<p>AT&amp;T</p>\n"),
			array('HTML Entity', '&copy;', "<p>&copy;</p>\n"),
			array('Angle brackets', '4 < 5 and 3 > 4', "<p>4 &lt; 5 and 3 > 4</p>\n"),

			// Links
			// array('Link with title attribute', 'This is [an example](http://example.com/ "Title") inline link.', ""),
			array('Link without title attribute', '[This link](http://example.net/) has no title attribute.', "<p><a href=\"http://example.net/\">This link</a> has no title attribute.</p>\n"),
			array('Relative URLs', 'See my [About](/about/) page for details.', "<p>See my <a href=\"/about/\">About</a> page for details.</p>\n"),
			array('Refernce style link', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with space)', "This is [an example] [id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			// array('Refernce style link (with single quote)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  'Optional Title Here'", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with parenthesis)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  (Optional Title Here)", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with angle brackets)', "This is [an example][id] reference-style link.\n\n[id]: <http://example.com/>  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with title on newline)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/\n\t\"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style implicit link', "Visit [Daring Fireball][] for more information.\n\n[Daring Fireball]: http://daringfireball.net/", "<p>Visit <a href=\"http://daringfireball.net/\">Daring Fireball</a> for more information.</p>\n"),
			array('Automatic link', '<http://example.com>', '<p><a href="http://example.com">http://example.com</a></p>' . "\n"),
			array('Automatic email ink', '<address@example.com>', '<p><a href="&#109;&#x61;&#x69;&#108;&#x74;&#x6f;&#58;&#x61;&#x64;&#100;&#114;&#x65;&#115;&#115;&#x40;&#101;&#120;&#x61;m&#112;&#x6c;e&#46;&#x63;&#x6f;&#109;">&#x61;&#x64;&#100;&#114;&#x65;&#115;&#115;&#x40;&#101;&#120;&#x61;m&#112;&#x6c;e&#46;&#x63;&#x6f;&#109;</a></p>' . "\n"),

			// Emphasis
			array('Single asterisks', '*single asterisks*', "<p><em>single asterisks</em></p>\n"),
			array('Single underscores', '_single underscores_', "<p><em>single underscores</em></p>\n"),
			array('Double asterisks', '**double asterisks**', "<p><strong>double asterisks</strong></p>\n"),
			array('Double underscores', '__double underscores__', "<p><strong>double underscores</strong></p>\n"),
			array('Single asterisks in the middle of a word', 'un*frigging*believable', "<p>un<em>frigging</em>believable</p>\n"),
			array('Double asterisks in the middle of a word', 'un**frigging**believable', "<p>un<strong>frigging</strong>believable</p>\n"),
			array('Literal asterisk', '8 * 7 = 56', "<p>8 * 7 = 56</p>\n"),
			array('Literal underscore', 'Literal _ underscore', "<p>Literal _ underscore</p>\n"),
			array('Escaped asterisk', '\*this text is surrounded by literal asterisks\*', "<p>&#42;this text is surrounded by literal asterisks&#42;</p>\n"),
			array('Escaped underscore', '\_this text is surrounded by literal asterisks\_', "<p>&#95;this text is surrounded by literal asterisks&#95;</p>\n"),

			// Code
			array('Span of code', 'Use the `printf()` function.', "<p>Use the <code>printf()</code> function.</p>\n"),
			array('Literal backtick', '``There is a literal backtick (`) here.``', "<p><code>There is a literal backtick (`) here.</code></p>\n"),
			array('Encoded angle brackets inside code span', "Please don't use any `<blink>` tags.", "<p>Please don&#8217;t use any <code>&lt;blink&gt;</code> tags.</p>\n"),
			array('Encoded ampersands inside code span', '`&#8212;` is the decimal-encoded equivalent of `&mdash;`.', "<p><code>&amp;#8212;</code> is the decimal-encoded equivalent of <code>&amp;mdash;</code>.</p>\n"),

			// Images
			array('Image tag', '![Alt text](/path/to/img.jpg)', "<p><img src=\"/path/to/img.jpg\" alt=\"Alt text\" /></p>\n"),
			// array('Image tag with title', '![Alt text](/path/to/img.jpg "Optional title")', "\n"),
			array('Reference style image tag', "![Alt text][id]\n\n[id]: url/to/image  \"Optional title attribute\"\n", "<p><img src=\"url/to/image\" alt=\"Alt text\" title=\"Optional title attribute\" /></p>\n"),

			// Escapes
			array('Escaped backslash', '\\\\', "<p>&#92;</p>\n"),
			array('Escaped backtick', '\`', "<p>&#96;</p>\n"),
			array('Escaped asterisk', '\*', "<p>&#42;</p>\n"),
			array('Escaped underscore', '\_', "<p>&#95;</p>\n"),
			array('Escaped curly braces', '\{\}', "<p>&#123;&#125;</p>\n"),
			array('Escaped square brackets', '\[\]', "<p>&#91;&#93;</p>\n"),
			array('Escaped parentheses', '\(\)', "<p>&#40;&#41;</p>\n"),
			array('Escaped hash mark', '\#', "<p>&#35;</p>\n"),
			array('Escaped plus sign', '\+', "<p>&#43;</p>\n"),
			array('Escaped hyphen', '\-', "<p>&#45;</p>\n"),
			array('Escaped dot', '\.', "<p>&#46;</p>\n"),
			array('Escaped exclamation mark', '\!', "<p>&#33;</p>\n"),

			// Horizontal rules
			array('HR by "* * *"', '* * *', "<hr />\n"),
			array('HR by "***"', '***', "<hr />\n"),
			array('HR by "*****"', '*****', "<hr />\n"),
			array('HR by "---"', '---', "<hr />\n"),
			array('HR by "- - -"', '- - -', "<hr />\n"),
			array('HR by "-----"', '-----', "<hr />\n"),
			array('HR by "___"', '___', "<hr />\n"),
			array('HR by "_ _ _"', '_ _ _', "<hr />\n"),
			array('HR by "_____"', '_____', "<hr />\n"),

			// Headers
			array('# H1', '# This is an H1', "<h1>This is an H1</h1>\n"),
			array('## H2', '## This is an H2', "<h2>This is an H2</h2>\n"),
			array('### H3', '### This is an H3', "<h3>This is an H3</h3>\n"),
			array('#### H4', '#### This is an H4', "<h4>This is an H4</h4>\n"),
			array('##### H5', '##### This is an H5', "<h5>This is an H5</h5>\n"),
			array('###### H6', '###### This is an H6', "<h6>This is an H6</h6>\n"),
			array('# H1 #', '# This is an H1 #', "<h1>This is an H1</h1>\n"),
			array('## H2 ##', '## This is an H2 ##', "<h2>This is an H2</h2>\n"),
			array('### H3 ###', '### This is an H3 ###', "<h3>This is an H3</h3>\n"),
			array('#### H4 ####', '#### This is an H4 ####', "<h4>This is an H4</h4>\n"),
			array('##### H5 #####', '##### This is an H5 #####', "<h5>This is an H5</h5>\n"),
			array('###### H6 ######', '###### This is an H6 ######', "<h6>This is an H6</h6>\n"),
			array('H1 by underscore', "This is an H1\n=============", "<h1>This is an H1</h1>\n"),
			array('H2 by underscore', "This is an H2\n-------------", "<h2>This is an H2</h2>\n"),

			// Blockquotes
			array('Email style blockquote', $this->getContentForMarkup('email-style-blockquote.in.md'), $this->getContentForMarkup('email-style-blockquote.out.md')),
			array('Lazy style blockquote', $this->getContentForMarkup('lazy-style-blockquote.in.md'), $this->getContentForMarkup('lazy-style-blockquote.out.md')),
			array('Nested blockquotes', $this->getContentForMarkup('nested-blockquotes.in.md'), $this->getContentForMarkup('nested-blockquotes.out.md')),
			array('Markdown inside blockquote', $this->getContentForMarkup('markdown-in-blockquote.in.md'), $this->getContentForMarkup('markdown-in-blockquote.out.md')),

			// Lists
			array('List by asterisk', $this->getContentForMarkup('list-by-asterisk.in.md'), $this->getContentForMarkup('list-by-asterisk.out.md')),
			array('List by plus', $this->getContentForMarkup('list-by-plus.in.md'), $this->getContentForMarkup('list-by-plus.out.md')),
			array('List by hyphen', $this->getContentForMarkup('list-by-hyphen.in.md'), $this->getContentForMarkup('list-by-hyphen.out.md')),
			array('Ordered list', $this->getContentForMarkup('ordered-list.in.md'), $this->getContentForMarkup('ordered-list.out.md')),
			array('Wrapped lists', $this->getContentForMarkup('wrapped-lists.in.md'), $this->getContentForMarkup('wrapped-lists.out.md')),
			array('Lists with paragraph tags', $this->getContentForMarkup('lists-with-paragraph-tags.in.md'), $this->getContentForMarkup('lists-with-paragraph-tags.out.md')),
			array('Lists with paragraphs', $this->getContentForMarkup('lists-with-paragraphs.in.md'), $this->getContentForMarkup('lists-with-paragraphs.out.md')),
			array('Lists with blockquotes', $this->getContentForMarkup('lists-with-blockquotes.in.md'), $this->getContentForMarkup('lists-with-blockquotes.out.md')),
			array('Lists with code blocks', $this->getContentForMarkup('lists-with-code-blocks.in.md'), $this->getContentForMarkup('lists-with-code-blocks.out.md')),
			array('Not a list', '1986\. What a great season.', "<p>1986&#46; What a great season.</p>\n"),

			// Code blocks
			array('Code block by 4 spaces', $this->getContentForMarkup('codeblock-by-4-spaces.in.md'), $this->getContentForMarkup('codeblock-by-4-spaces.out.md')),
			array('Code block by 5 spaces', $this->getContentForMarkup('codeblock-by-5-spaces.in.md'), $this->getContentForMarkup('codeblock-by-5-spaces.out.md')),
			array('Code block by 1 tab', $this->getContentForMarkup('codeblock-by-1-tab.in.md'), $this->getContentForMarkup('codeblock-by-1-tab.out.md')),
			array('Code block by 2 tabs', $this->getContentForMarkup('codeblock-by-2-tabs.in.md'), $this->getContentForMarkup('codeblock-by-2-tabs.out.md')),
			array('Code block with encoded ampersands', $this->getContentForMarkup('codeblock-with-encoded-ampersands.in.md'), $this->getContentForMarkup('codeblock-with-encoded-ampersands.out.md')),
			array('Code block with encoded angle brackets', $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.in.md'), $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.out.md')),
		);

    	return array_merge($data, $this->markdownExtraData());
	}

	protected function markdownExtraData()
	{
		return array(
			array('Markdown inside HTML blocks', $this->getContentForMarkup('markdown-inside-html-blocks.in.md'), $this->getContentForMarkup('markdown-inside-html-blocks.out.md')),

			// Special Attributes
			array('Header: ID', '## Header 2 {#header2}', "<h2 id=\"header2\">Header 2</h2>\n"),
			array('Header: Class names', '## Header 2 {.main}', "<h2 class=\"main\">Header 2</h2>\n"),
			array('Header: Custom attributes', '## Le Header 2 {lang=fr}', "<h2 lang=\"fr\">Le Header 2</h2>\n"),
			array('Header: Multiple attributes', '## Le Header 2 {.main .shine lang=fr #header2}', "<h2 id=\"header2\" class=\"main shine\" lang=\"fr\">Le Header 2</h2>\n"),
			array('Link: ID', '[link](/url){#header2}', "<p><a href=\"/url\" title=\"\" id=\"header2\">link</a></p>\n"),
			array('Link: Class names', '[link](/url){.main}', "<p><a href=\"/url\" title=\"\" class=\"main\">link</a></p>\n"),
			array('Link: Custom attributes', '[link](/url){lang=fr}', "<p><a href=\"/url\" title=\"\" lang=\"fr\">link</a></p>\n"),
			array('Link: Multiple attributes', '[link](/url){.main .shine lang=fr #header2}', "<p><a href=\"/url\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\">link</a></p>\n"),
			array('Reference Link: ID', "[link][linkref]\n\n[linkref]: /url {#header2}", "<p><a href=\"/url\" title=\"\" id=\"header2\">link</a></p>\n"),
			array('Reference Link: Class names', "[link][linkref]\n\n[linkref]: /url {.main}", "<p><a href=\"/url\" title=\"\" class=\"main\">link</a></p>\n"),
			array('Reference Link: Custom attributes', "[link][linkref]\n\n[linkref]: /url {lang=fr}", "<p><a href=\"/url\" title=\"\" lang=\"fr\">link</a></p>\n"),
			array('Reference Link: Multiple attributes', "[link][linkref]\n\n[linkref]: /url {.main .shine lang=fr #header2}", "<p><a href=\"/url\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\">link</a></p>\n"),
			array('Image: ID', '![link](/url){#header2}', "<p><img src=\"/url\" alt=\"link\" title=\"\" id=\"header2\" /></p>\n"),
			array('Image: Class names', '![link](/url){.main}', "<p><img src=\"/url\" alt=\"link\" title=\"\" class=\"main\" /></p>\n"),
			array('Image: Custom attributes', '![link](/url){lang=fr}', "<p><img src=\"/url\" alt=\"link\" title=\"\" lang=\"fr\" /></p>\n"),
			array('Image: Multiple attributes', '![link](/url){.main .shine lang=fr #header2}', "<p><img src=\"/url\" alt=\"link\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\" /></p>\n"),
			array('Fenced code block: ID', "~~~ {#header2}\ncode block\n~~~\n", "<pre><code id=\"header2\">code block\n</code></pre>\n"),
			array('Fenced code block: Class names', "~~~ {.main}\ncode block\n~~~\n", "<pre><code class=\"main\">code block\n</code></pre>\n"),
			array('Fenced code block: Custom attributes', "~~~ {lang=fr}\ncode block\n~~~\n", "<pre><code lang=\"fr\">code block\n</code></pre>\n"),
			array('Fenced code block: Multiple attributes', "~~~ {.main .shine lang=fr #header2}\ncode block\n~~~\n", "<pre><code id=\"header2\" class=\"main shine\" lang=\"fr\">code block\n</code></pre>\n"),

			// Fenced Code Blocks
			array('Fenced code block by 3 tildes', $this->getContentForMarkup('codeblock-by-3-tildes.in.md'), $this->getContentForMarkup('codeblock-by-3-tildes.out.md')),
			array('Fenced code block by 4 tildes', $this->getContentForMarkup('codeblock-by-4-tildes.in.md'), $this->getContentForMarkup('codeblock-by-4-tildes.out.md')),
			array('Fenced code block by 3 backticks', $this->getContentForMarkup('codeblock-by-3-backticks.in.md'), $this->getContentForMarkup('codeblock-by-3-backticks.out.md')),
			array('Fenced code block by 4 backticks', $this->getContentForMarkup('codeblock-by-4-backticks.in.md'), $this->getContentForMarkup('codeblock-by-4-backticks.out.md')),
			array('Fenced code block beginning and ending with blank lines', $this->getContentForMarkup('codeblock-begin-end-blank-lines.in.md'), $this->getContentForMarkup('codeblock-begin-end-blank-lines.out.md')),
			array('Fenced code block after a list', $this->getContentForMarkup('codeblock-after-list.in.md'), $this->getContentForMarkup('codeblock-after-list.out.md')),

			// Tables
			array('Table', $this->getContentForMarkup('table.in.md'), $this->getContentForMarkup('table.out.md')),
			array('Table with leading and tailing pipes', $this->getContentForMarkup('table-with-pipes.in.md'), $this->getContentForMarkup('table-with-pipes.out.md')),
			array('Table with alignment', $this->getContentForMarkup('table-with-alignment.in.md'), $this->getContentForMarkup('table-with-alignment.out.md')),
			array('Table with span-level formatting', $this->getContentForMarkup('table-with-formatting.in.md'), $this->getContentForMarkup('table-with-formatting.out.md')),

			// Definition Lists
			array('Definition list', $this->getContentForMarkup('definition-list.in.md'), $this->getContentForMarkup('definition-list.out.md')),
			array('Definition list wrapped', $this->getContentForMarkup('definition-list-wrapped.in.md'), $this->getContentForMarkup('definition-list-wrapped.out.md')),
			array('Definition list indented', $this->getContentForMarkup('definition-list-indented.in.md'), $this->getContentForMarkup('definition-list-indented.out.md')),
			array('Definition list multiple definitions', $this->getContentForMarkup('definition-list-multiple.in.md'), $this->getContentForMarkup('definition-list-multiple.out.md')),
			array('Definition list with paragraph tags', $this->getContentForMarkup('definition-list-with-paragraph-tags.in.md'), $this->getContentForMarkup('definition-list-with-paragraph-tags.out.md')),
			array('Definition list with multiple paragraphs', $this->getContentForMarkup('definition-list-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('definition-list-with-multiple-paragraphs.out.md')),

			// Footnotes
			array('Footnote first', $this->getContentForMarkup('footnote-first.in.md'), $this->getContentForMarkup('footnote-first.out.md')),
			array('Footnote intermingled', $this->getContentForMarkup('footnote-intermingled.in.md'), $this->getContentForMarkup('footnote-intermingled.out.md')),
			array('Footnote last', $this->getContentForMarkup('footnote-last.in.md'), $this->getContentForMarkup('footnote-last.out.md')),
			array('Footnote with multiple paragraphs', $this->getContentForMarkup('footnote-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('footnote-with-multiple-paragraphs.out.md')),

			// Abbreviations
			array('Abbreviation definition first', "*[HTML]: Hyper Text Markup Language\n\nThe HTML specification", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n"),
			array('Abbreviation definition middle', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language\n\nis dry", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n\n<p>is dry</p>\n"),
			array('Abbreviation definition last', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n"),
			array('Multiword abbreviation', "*[Foo Bar]: Fubar\n\nI saw a Foo Bar once", "<p>I saw a <abbr title=\"Fubar\">Foo Bar</abbr> once</p>\n"),
			array('Empty abbreviateion', "Operation Tigra Genesis is going well.\n\n*[Tigra Genesis]:", "<p>Operation <abbr>Tigra Genesis</abbr> is going well.</p>\n"),

			array('Single underscores in the middle of a word', 'un_frigging_believable', "<p>un_frigging_believable</p>\n"),
			array('Double underscores in the middle of a word', 'un__frigging__believable', "<p>un__frigging__believable</p>\n"),
		);
	}

	protected function BBCodeData()
	{
		return array(
            array('[abbr] tag', '[abbr="Cascading Style Sheets"]CSS[/abbr]', '<p><abbr title="Cascading Style Sheets">CSS</abbr></p>' . "\n"),
            array('[abbr] tag with property', '[abbr title="Cascading Style Sheets"]CSS[/abbr]', '<p><abbr title="Cascading Style Sheets">CSS</abbr></p>' . "\n"),
            array('[b] tag', '[b]some bold text[/b]', '<p><b>some bold text</b></p>' . "\n"),
            array('[blockquote] tag', '[blockquote]Some text. blah, blah, blah...[/blockquote]', "<blockquote>Some text. blah, blah, blah&#8230;</blockquote>\n"),
            // array('[cite] tag', '[cite="some place"]some text[/cite]', '' . "\n"),
            // array('[code] tag', '[code]Some pre-formatted text...[/code]', '<p><code>Some pre-formatted text...</code></p>' . "\n"),
            array('[color] tag', '[color=green]Some green text[/color]', '<p><span style="color:green;">Some green text</span></p>' . "\n"),
            array('[del] tag', 'This is [del]very[/del] exciting.', '<p>This is <del>very</del> exciting.</p>' . "\n"),
            array('[em] tag', '[em]some em text[/em]', '<p><em>some em text</em></p>' . "\n"),
            // array('[email] tag', '[email]you@example.com[/email]', "<span data-eeEncEmail_qqaBvHJmAg='1'>.encoded_email</span><script type=\"text/javascript\">/*<![CDATA[*/var out = '',el = document.getElementsByTagName('span' . "\n"),l = ['>','a','/','<',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121','>','\"',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121',':','o','t','l','i','a','m','\\\"','=','f','e','r','h','a ','<'],i = l.length,j = el.length;while (--i >= 0)out += unescape(l[i].replace(/^\s\s*/, '&#'));while (--j >= 0)if (el[j].getAttribute('data-eeEncEmail_qqaBvHJmAg'))el[j].innerHTML = out;/*]]>*/</script>"),
            // array('[email] tag with value', '[email=you@example.com]click here to email[/email]', '' . "\n"),
            array('[h2] tag', '[h2]some text[/h2]', '<h2>some text</h2>' . "\n"),
            array('[h3] tag', '[h3]some text[/h3]', '<h3>some text</h3>' . "\n"),
            array('[h4] tag', '[h4]some text[/h4]', '<h4>some text</h4>' . "\n"),
            array('[h5] tag', '[h5]some text[/h5]', '<h5>some text</h5>' . "\n"),
            array('[h6] tag', '[h6]some text[/h6]', '<h6>some text</h6>' . "\n"),
            array('[i] tag', '[i]some italic text[/i]', '<p><i>some italic text</i></p>' . "\n"),
            // array('[img] tag', '[img]http://example.com/pic.jpg[/img]', '' . "\n"),
            array('[ins] tag', '[ins]some text[/ins]', '<p><ins>some text</ins></p>' . "\n"),
            array('[mark] tag', '[mark]some text[/mark]', '<p><mark>some text</mark></p>' . "\n"),
            array('[pre] tag', '[pre]Some pre-formatted text...[/pre]', '<pre>Some pre-formatted text...</pre>' . "\n"),
            array('[quote] tag', '[quote]Some text. blah, blah, blah...[/quote]', "<blockquote>Some text. blah, blah, blah&#8230;</blockquote>\n"),
            array('[size=1] tag', '[size=1]some text[/size]', '<p><span style="font-size:9px;">some text</span></p>' . "\n"),
            array('[size=2] tag', '[size=2]some text[/size]', '<p><span style="font-size:11px;">some text</span></p>' . "\n"),
            array('[size=3] tag', '[size=3]some text[/size]', '<p><span style="font-size:14px;">some text</span></p>' . "\n"),
            array('[size=4] tag', '[size=4]some text[/size]', '<p><span style="font-size:16px;">some text</span></p>' . "\n"),
            array('[size=5] tag', '[size=5]some text[/size]', '<p><span style="font-size:18px;">some text</span></p>' . "\n"),
            array('[size=6] tag', '[size=6]some text[/size]', '<p><span style="font-size:20px;">some text</span></p>' . "\n"),
            array('[span] tag', '[span]some text[/span]', '<p><span>some text</span></p>' . "\n"),
            array('[strike] tag', '[strike]some text[/strike]', '<p><del>some text</del></p>' . "\n"),
            array('[strong] tag', '[strong]some strong text[/strong]', '<p><strong>some strong text</strong></p>' . "\n"),
            array('[style] tag', '[style=class_name]your content[/style]', '<p><span class="class_name">your content</span></p>' . "\n"),
            array('[sub] tag', '[sub]some text[/sub]', '<p><sub>some text</sub></p>' . "\n"),
            array('[sup] tag', '[sup]some text[/sup]', '<p><sup>some text</sup></p>' . "\n"),
            array('[u] tag', '[u]some underlined text[/u]', '<p><em>some underlined text</em></p>' . "\n"),
            array('[url] tag', '[url]http://example.com/[/url]', '<p><a href="http://example.com/">http://example.com/</a></p>' . "\n"),
            array('[url] tag with value', '[url=http://example.com/]my site[/url]', '<p><a href="http://example.com/">my site</a></p>' . "\n"),
            array('[url] tag with value and property', '[url=http://example.com/ class="link"]my site[/url]', '<p><a href="http://example.com/" class="link">my site</a></p>' . "\n"),
		);
	}

}

// EOF
