<?php

require_once SYSPATH.'ee/EllisLab/ExpressionEngine/Boot/boot.common.php';
require_once APPPATH.'helpers/string_helper.php';
require_once APPPATH.'helpers/security_helper.php';
require_once APPPATH.'libraries/Functions.php';
require_once APPPATH.'libraries/Typography.php';
require_once APPPATH.'libraries/typography/Markdown/Michelf/MarkdownExtra.inc.php';

if ( ! defined('PATH_ADDONS'))
{
	define('PATH_ADDONS', APPPATH.'modules/');
}

if ( ! defined('REQ'))
{
	define('REQ', FALSE);
}


class MarkdownAllTest extends \PHPUnit_Framework_TestCase {

		private $typography;

	public function tearDown()
	{
		unset($this->typography);
	}


	public function setUp()
	{
		$this->typography = new EE_Typography();
	}

	private function getContentForMarkup($name)
	{
		$path = realpath(__DIR__.'/../../../../support/typography/' . $name);
		return file_get_contents($path);
	}

	/**
	 * There are number of preferences we can pass to the parse_type
	 * method that we need to test:
	 *
	 *  - text_format (xhtml, markdown, br, none, lite)
	 *  - html_format (safe, all, none)
	 *  - auto_links (y, n)
	 *  - allow_img_url (n, y)
	 */

	/**
	 * @dataProvider dataProvider
	 */
    public function testParseType($description, $in, $out)
    {
        $prefs = array(
            'text_format' => 'markdown',
            'html_format' => 'all',
            'auto_links' => 'n',
            'allow_img_url' => 'y',
        );

        $parsed = $this->typography->parse_type($in, $prefs);
        $this->assertEquals($out, $parsed, '[Markdown/All] ' . $description);
    }

	public function dataProvider()
	{
		$data = array(
			array('Empty string', '', ''),
		);

		$data = array_merge(
			$this->whitespaceData(),
			$this->punctuationData(),
			$this->HTMLWithClosingTagsData(),
			$this->HTMLWithoutClosingTagsData(),
			$this->HTMLWithContentData(),
			// $this->HTMLAttributesData(), // @TODO these are all broken
			$this->HTMLWithAttributesData(),
			$this->markdownData(),
			$this->BBCodeData(),
			$data
		);

		return $data;
	}

	protected function whitespaceData()
	{
		return array(
			array('Single spaces', 'a b', '<p>a b</p>' . "\n"),
			array('Double spaces', 'a  b', '<p>a  b</p>' . "\n"),
			array('Double spaces after a sentence', 'Word.  Word', '<p>Word.  Word</p>' . "\n"),
			array('A tab converts to a space', "a    b", "<p>a    b</p>\n"),
			array('Tabs convert to spaces', "a        b", "<p>a        b</p>\n"),
			array('A return is a <br>', "a\nb", "<p>a\nb</p>\n"),
			array('Multiple returns are not converted', "a\n\nb", "<p>a</p>\n\n<p>b</p>\n"),
		);
	}

	protected function punctuationData()
	{
		return array(
			array('Backtick', '`', '<p>`</p>' . "\n"),
			array('Tilde', '~', '<p>~</p>' . "\n"),
			array('Exclamation point', '!', '<p>!</p>' . "\n"),
			array('At sign', '@', '<p>@</p>' . "\n"),
			array('Pound/hash sign', '#', '<p>#</p>' . "\n"),
			array('Dollar sign', '$', '<p>$</p>' . "\n"),
			array('Percent sign', '%', '<p>%</p>' . "\n"),
			array('Circumflex', '^', '<p>^</p>' . "\n"),
			array('Ampersand', '&', '<p>&amp;</p>' . "\n"),
			array('Asterisk', '*', '<p>*</p>' . "\n"),
			array('Parentheses', '()', '<p>()</p>' . "\n"),
			array('Underscore', '_', '<p>_</p>' . "\n"),
			array('Hyphen', '-', '<p>-</p>' . "\n"),
			array('Equals sign', '=', '<p>=</p>' . "\n"),
			array('Plus sign', '+', '<p>+</p>' . "\n"),
			array('Brackets', '[]', '<p>[]</p>' . "\n"),
			array('Braces', '{}', '<p>&#123;&#125;</p>' . "\n"),
			array('Backslash', '\\', '<p>\\</p>' . "\n"),
			array('Pipe', '|', '<p>|</p>' . "\n"),
			array('Semicolon', ';', '<p>;</p>' . "\n"),
			array('Colon', ':', '<p>:</p>' . "\n"),
			array('Single quote', "'", "<p>&#8216;</p>\n"),
			array('Double quote', '"', '<p>&#8220;</p>' . "\n"),
			array('Comma', ',', '<p>,</p>' . "\n"),
			array('Period', '.', '<p>.</p>' . "\n"),
			// array('Angle brackets', '<>', '<p>&lt;&gt;</p>' . "\n"),
			array('Forward slash', '/', '<p>/</p>' . "\n"),
			array('Question mark', '?', '<p>?</p>' . "\n"),
			array('Em dash', '--', '<p>&#8211;</p>' . "\n"),
			array('Ellipses', 'you know...', '<p>you know&#8230;</p>' . "\n"),
			array('Apostrophy', "It's its", "<p>It&#8217;s its</p>\n"),
			array('US quote no whitespace', '"Hello"', '<p>&#8220;Hello&#8221;</p>' . "\n"),
			array('UK quote no whitespace', "'Hello'", '<p>&#8216;Hello&#8217;</p>' . "\n"),
			array('Simple nested US quote', '"I said, \'Hello\'"', '<p>&#8220;I said, &#8216;Hello&#8217;&#8221;</p>' . "\n"),
			array('Simple nested UK quote', "'I said, \"Hello\"'", '<p>&#8216;I said, &#8220;Hello&#8221;&#8217;</p>' . "\n"),
			array('US quote surrounded by whitespace', 'Foo "Bar" Baz', '<p>Foo &#8220;Bar&#8221; Baz</p>' . "\n"),
			array('UK quote surrounded by whitespace', "Foo 'Bar' Baz", '<p>Foo &#8216;Bar&#8217; Baz</p>' . "\n"),
		);
	}

	protected function HTMLWithClosingTagsData()
	{
		return array(
			array('<!-- -->', '<!-- -->', '<!-- -->' . "\n"),
			array('<a></a>', '<a></a>', '<p><a></a></p>' . "\n"),
            array('<abbr></abbr>', '<abbr></abbr>', '<p><abbr></abbr></p>' . "\n"),
            array('<acronym></acronym>', '<acronym></acronym>', '<p><acronym></acronym></p>' . "\n"),
            array('<address></address>', '<address></address>', '<address></address>' . "\n"),
            array('<applet></applet>', '<applet></applet>', '<p><applet></applet></p>' . "\n"),
            array('<area></area>', '<area></area>', '<p><area></area></p>' . "\n"),
            array('<article></article>', '<article></article>', '<article></article>' . "\n"),
            array('<aside></aside>', '<aside></aside>', '<aside></aside>' . "\n"),
            array('<audio></audio>', '<audio></audio>','<p><audio></audio></p>' . "\n"),
			array('<b></b>', '<b></b>', '<p><b></b></p>' . "\n"),
            array('<base></base>', '<base></base>', '<p><base></base></p>' . "\n"),
            array('<basefont></basefont>', '<basefont></basefont>', '<p><basefont></basefont></p>' . "\n"),
            array('<bdi></bdi>', '<bdi></bdi>', '<p><bdi></bdi></p>' . "\n"),
			array('<bdo></bdo>', '<bdo></bdo>', '<p><bdo></bdo></p>' . "\n"),
			array('<big></big>', '<big></big>', '<p><big></big></p>' . "\n"),
			array('<blockquote></blockquote>', '<blockquote></blockquote>', '<blockquote></blockquote>' . "\n"),
            array('<body></body>', '<body></body>', '<p><body></body></p>' . "\n"),
			array('<button></button>', '<button></button>', '<p><button></button></p>' . "\n"),
			array('<canvas></canvas>', '<canvas></canvas>', '<p><canvas></canvas></p>' . "\n"),
            array('<caption></caption>', '<caption></caption>', '<p><caption></caption></p>' . "\n"),
            array('<center></center>', '<center></center>', '<p><center></center></p>' . "\n"),
			array('<cite></cite>', '<cite></cite>', '<p><cite></cite></p>' . "\n"),
			array('<code></code>', '<code></code>', '<p><code></code></p>' . "\n"),
            array('<col></col>', '<col></col>', '<p><col></col></p>' . "\n"),
            array('<colgroup></colgroup>', '<colgroup></colgroup>', '<p><colgroup></colgroup></p>' . "\n"),
            array('<datalist></datalist>', '<datalist></datalist>', '<p><datalist></datalist></p>' . "\n"),
            array('<dd></dd>', '<dd></dd>', '<p><dd></dd></p>' . "\n"),
			array('<del></del>', '<del></del>', '<p><del></del></p>' . "\n"),
            array('<details></details>', '<details></details>', '<p><details></details></p>' . "\n"),
			array('<dfn></dfn>', '<dfn></dfn>', '<p><dfn></dfn></p>' . "\n"),
            array('<dialog></dialog>', '<dialog></dialog>', '<p><dialog></dialog></p>' . "\n"),
            array('<dir></dir>', '<dir></dir>', '<p><dir></dir></p>' . "\n"),
			array('<div></div>', '<div></div>', '<div></div>' . "\n"),
			array('<dl></dl>', '<dl></dl>', '<dl></dl>' . "\n"),
            array('<dt></dt>', '<dt></dt>', '<p><dt></dt></p>' . "\n"),
			array('<em></em>', '<em></em>', '<p><em></em></p>' . "\n"),
            array('<embed></embed>', '<embed></embed>', '<p><embed></embed></p>' . "\n"),
			array('<fieldset></fieldset>', '<fieldset></fieldset>', '<fieldset></fieldset>' . "\n"),
			array('<figcaption></figcaption>', '<figcaption></figcaption>', '<figcaption></figcaption>' . "\n"),
			array('<figure></figure>', '<figure></figure>', '<figure></figure>' . "\n"),
            array('<font></font>', '<font></font>', '<p><font></font></p>' . "\n"),
			array('<footer></footer>', '<footer></footer>', '<footer></footer>' . "\n"),
			array('<form></form>', '<form></form>', '<form></form>' . "\n"),
            array('<frame></frame>', '<frame></frame>', '<p><frame></frame></p>' . "\n"),
            array('<frameset></frameset>', '<frameset></frameset>', '<p><frameset></frameset></p>' . "\n"),
			array('<h1></h1>', '<h1></h1>', '<h1></h1>' . "\n"),
			array('<h2></h2>', '<h2></h2>', '<h2></h2>' . "\n"),
			array('<h3></h3>', '<h3></h3>', '<h3></h3>' . "\n"),
			array('<h4></h4>', '<h4></h4>', '<h4></h4>' . "\n"),
			array('<h5></h5>', '<h5></h5>', '<h5></h5>' . "\n"),
			array('<h6></h6>', '<h6></h6>', '<h6></h6>' . "\n"),
            array('<head></head>', '<head></head>', '<p><head></head></p>' . "\n"),
			array('<header></header>', '<header></header>', '<header></header>' . "\n"),
            array('<html></html>', '<html></html>', '<p><html></html></p>' . "\n"),
			array('<i></i>', '<i></i>', '<p><i></i></p>' . "\n"),
            array('<iframe></iframe>', '<iframe></iframe>', '<iframe></iframe>' . "\n"),
			array('<ins></ins>', '<ins></ins>', '<p><ins></ins></p>' . "\n"),
			array('<kbd></kbd>', '<kbd></kbd>', '<p><kbd></kbd></p>' . "\n"),
            array('<keygen></keygen>', '<keygen></keygen>', '<p><keygen></keygen></p>' . "\n"),
			array('<label></label>', '<label></label>', '<p><label></label></p>' . "\n"),
            array('<legend></legend>', '<legend></legend>', '<legend></legend>' . "\n"),
            array('<li></li>', '<li></li>', '<p><li></li></p>' . "\n"),
            array('<link></link>', '<link></link>', '<p><link></link></p>' . "\n"),
            array('<main></main>', '<main></main>', '<p><main></main></p>' . "\n"),
			array('<map></map>', '<map></map>', '<p><map></map></p>' . "\n"),
			array('<mark></mark>', '<mark></mark>', '<p><mark></mark></p>' . "\n"),
            array('<menu></menu>', '<menu></menu>', '<p><menu></menu></p>' . "\n"),
            array('<menuitem></menuitem>', '<menuitem></menuitem>', '<p><menuitem></menuitem></p>' . "\n"),
            array('<meta></meta>', '<meta></meta>', '<p><meta></meta></p>' . "\n"),
            array('<meter></meter>', '<meter></meter>', '<p><meter></meter></p>' . "\n"),
            array('<nav></nav>', '<nav></nav>', '<nav></nav>' . "\n"),
            array('<noframes></noframes>', '<noframes></noframes>', '<p><noframes></noframes></p>' . "\n"),
			array('<noscript></noscript>', '<noscript></noscript>', '<p><noscript></noscript></p>' . "\n"),
			array('<object></object>', '<object></object>', '<p><object></object></p>' . "\n"),
			array('<ol></ol>', '<ol></ol>', '<ol></ol>' . "\n"),
            array('<optgroup></optgroup>', '<optgroup></optgroup>', '<p><optgroup></optgroup></p>' . "\n"),
            array('<option></option>', '<option></option>', '<p><option></option></p>' . "\n"),
			array('<output></output>', '<output></output>', '<p><output></output></p>' . "\n"),
			array('<p></p>', '<p></p>', '<p></p>' . "\n"),
            array('<param></param>', '<param></param>', '<p><param></param></p>' . "\n"),
            array('<picture></picture>','<picture></picture>','<p><picture></picture></p>' . "\n"),
			array('<pre></pre>', '<pre></pre>', '<pre></pre>' . "\n"),
            array('<progress></progress>', '<progress></progress>', '<p><progress></progress></p>' . "\n"),
			array('<q></q>', '<q></q>', '<p><q></q></p>' . "\n"),
            array('<rp></rp>', '<rp></rp>', '<p><rp></rp></p>' . "\n"),
            array('<rt></rt>', '<rt></rt>', '<p><rt></rt></p>' . "\n"),
            array('<ruby></ruby>', '<ruby></ruby>', '<p><ruby></ruby></p>' . "\n"),
            array('<s></s>', '<s></s>', '<p><s></s></p>' . "\n"),
			array('<samp></samp>', '<samp></samp>', '<p><samp></samp></p>' . "\n"),
			array('<script></script>', '<script></script>', '<script></script>' . "\n"),
			array('<section></section>', '<section></section>', '<section></section>' . "\n"),
			array('<select></select>', '<select></select>', '<p><select></select></p>' . "\n"),
			array('<small></small>', '<small></small>', '<p><small></small></p>' . "\n"),
            array('<source></source>', '<source></source>', '<p><source></source></p>' . "\n"),
			array('<span></span>', '<span></span>', '<p><span></span></p>' . "\n"),
            array('<strike></strike>', '<strike></strike>', '<p><strike></strike></p>' . "\n"),
			array('<strong></strong>', '<strong></strong>', '<p><strong></strong></p>' . "\n"),
            array('<style></style>', '<style></style>', '<style></style>' . "\n"),
			array('<sub></sub>', '<sub></sub>', '<p><sub></sub></p>' . "\n"),
            array('<summary></summary>', '<summary></summary>', '<p><summary></summary></p>' . "\n"),
			array('<sup></sup>', '<sup></sup>', '<p><sup></sup></p>' . "\n"),
			array('<table></table>', '<table></table>', '<table></table>' . "\n"),
            array('<tbody></tbody>', '<tbody></tbody>', '<p><tbody></tbody></p>' . "\n"),
            array('<td></td>', '<td></td>', '<p><td></td></p>' . "\n"),
			array('<textarea></textarea>', '<textarea></textarea>', '<p><textarea></textarea></p>' . "\n"),
            array('<tfoot></tfoot>', '<tfoot></tfoot>', '<p><tfoot></tfoot></p>' . "\n"),
            array('<th></th>', '<th></th>', '<p><th></th></p>' . "\n"),
            array('<thead></thead>', '<thead></thead>', '<p><thead></thead></p>' . "\n"),
            array('<time></time>', '<time></time>', '<p><time></time></p>' . "\n"),
            array('<title></title>', '<title></title>', '<p><title></title></p>' . "\n"),
            array('<tr></tr>', '<tr></tr>', '<p><tr></tr></p>' . "\n"),
            array('<track></track>', '<track></track>', '<p><track></track></p>' . "\n"),
			array('<tt></tt>', '<tt></tt>', '<p><tt></tt></p>' . "\n"),
            array('<u></u>', '<u></u>', '<p><u></u></p>' . "\n"),
			array('<ul></ul>', '<ul></ul>', '<ul></ul>' . "\n"),
			array('<var></var>', '<var></var>', '<p><var></var></p>' . "\n"),
			array('<video></video>', '<video></video>', '<p><video></video></p>' . "\n"),
            array('<wbr></wbr>', '<wbr></wbr>', '<p><wbr></wbr></p>' . "\n"),
		);
	}

	protected function HTMLWithoutClosingTagsData()
	{
		return array(
            array('<!--', '<!--', '<p>&lt;!&#8211;</p>' . "\n"),
			array('<a>', '<a>', '<p><a></p>' . "\n"),
			array('<abbr>', '<abbr>', '<p><abbr></p>' . "\n"),
			array('<acronym>', '<acronym>', '<p><acronym></p>' . "\n"),
			// array('<address>', '<address>', '<address>' . "\n"),
			array('<applet>', '<applet>', '<p><applet></p>' . "\n"),
			array('<area>', '<area>', '<p><area></p>' . "\n"),
			// array('<article>', '<article>', '<article>' . "\n"),
			// array('<aside>', '<aside>', '<aside>' . "\n"),
			// array('<audio>', '<audio>', '<audio>' . "\n"),
			array('<b>', '<b>', '<p><b></p>' . "\n"),
			array('<base>', '<base>', '<p><base></p>' . "\n"),
			array('<basefont>', '<basefont>', '<p><basefont></p>' . "\n"),
			array('<bdi>', '<bdi>', '<p><bdi></p>' . "\n"),
			array('<bdo>', '<bdo>', '<p><bdo></p>' . "\n"),
			array('<big>', '<big>', '<p><big></p>' . "\n"),
			// array('<blockquote>', '<blockquote>', '<blockquote>' . "\n"),
			array('<body>', '<body>', '<p><body></p>' . "\n"),
            array('<br>', '<br>', '<p><br></p>' . "\n"),
			array('<button>', '<button>', '<p><button></p>' . "\n"),
			// array('<canvas>', '<canvas>', '<canvas>' . "\n"),
			array('<caption>', '<caption>', '<p><caption></p>' . "\n"),
			array('<center>', '<center>', '<p><center></p>' . "\n"),
			array('<cite>', '<cite>', '<p><cite></p>' . "\n"),
			array('<code>', '<code>', '<p><code></p>' . "\n"),
			array('<col>', '<col>', '<p><col></p>' . "\n"),
			array('<colgroup>', '<colgroup>', '<p><colgroup></p>' . "\n"),
			array('<datalist>', '<datalist>', '<p><datalist></p>' . "\n"),
			array('<dd>', '<dd>', '<p><dd></p>' . "\n"),
			// array('<del>', '<del>', '<p><del></p>' . "\n"),
			array('<details>', '<details>', '<p><details></p>' . "\n"),
			array('<dfn>', '<dfn>', '<p><dfn></p>' . "\n"),
			array('<dialog>', '<dialog>', '<p><dialog></p>' . "\n"),
			array('<dir>', '<dir>', '<p><dir></p>' . "\n"),
			// array('<div>', '<div>', '<div>' . "\n"),
			// array('<dl>', '<dl>', '<dl>' . "\n"),
			array('<dt>', '<dt>', '<p><dt></p>' . "\n"),
			array('<em>', '<em>', '<p><em></p>' . "\n"),
			array('<embed>', '<embed>', '<p><embed></p>' . "\n"),
			// array('<fieldset>', '<fieldset>', '<fieldset>' . "\n"),
			// array('<figcaption>', '<figcaption>', '<p><figcaption></p>' . "\n"),
			// array('<figure>', '<figure>', '<figure>' . "\n"),
			array('<font>', '<font>', '<p><font></p>' . "\n"),
			// array('<footer>', '<footer>', '<footer>' . "\n"),
			// array('<form>', '<form>', '<form>' . "\n"),
			array('<frame>', '<frame>', '<p><frame></p>' . "\n"),
			array('<frameset>', '<frameset>', '<p><frameset></p>' . "\n"),
			// array('<h1>', '<h1>', '<h1>' . "\n"),
			// array('<h2>', '<h2>', '<h2>' . "\n"),
			// array('<h3>', '<h3>', '<h3>' . "\n"),
			// array('<h4>', '<h4>', '<h4>' . "\n"),
			// array('<h5>', '<h5>', '<h5>' . "\n"),
			// array('<h6>', '<h6>', '<h6>' . "\n"),
			array('<head>', '<head>', '<p><head></p>' . "\n"),
			// array('<header>', '<header>', '<header>' . "\n"),
			array('<hr>', '<hr>', '<hr>' . "\n"),
			array('<html>', '<html>', '<p><html></p>' . "\n"),
			array('<i>', '<i>', '<p><i></p>' . "\n"),
			// array('<iframe>', '<iframe>', '<p><iframe></p>' . "\n"),
			array('<img>', '<img>', '<p><img></p>' . "\n"),
			array('<input>', '<input>', '<p><input></p>' . "\n"),
			// array('<ins>', '<ins>', '<p><ins></p>' . "\n"),
			array('<kbd>', '<kbd>', '<p><kbd></p>' . "\n"),
			array('<keygen>', '<keygen>', '<p><keygen></p>' . "\n"),
			array('<label>', '<label>', '<p><label></p>' . "\n"),
			// array('<legend>', '<legend>', '<p><legend></p>' . "\n"),
			array('<li>', '<li>', '<p><li></p>' . "\n"),
			array('<link>', '<link>', '<p><link></p>' . "\n"),
			array('<main>', '<main>', '<p><main></p>' . "\n"),
			array('<map>', '<map>', '<p><map></p>' . "\n"),
			array('<mark>', '<mark>', '<p><mark></p>' . "\n"),
			array('<menu>', '<menu>', '<p><menu></p>' . "\n"),
			array('<menuitem>', '<menuitem>', '<p><menuitem></p>' . "\n"),
			array('<meta>', '<meta>', '<p><meta></p>' . "\n"),
			array('<meter>', '<meter>', '<p><meter></p>' . "\n"),
			// array('<nav>', '<nav>', '<p><nav></p>' . "\n"),
			array('<noframes>', '<noframes>', '<p><noframes></p>' . "\n"),
			// array('<noscript>', '<noscript>', '<noscript>' . "\n"),
			// array('<object>', '<object>', '<object>' . "\n"),
			// array('<ol>', '<ol>', '<ol>' . "\n"),
			array('<optgroup>', '<optgroup>', '<p><optgroup></p>' . "\n"),
			array('<option>', '<option>', '<p><option></p>' . "\n"),
			// array('<output>', '<output>', '<output>' . "\n"),
			// array('<p>', '<p>', '<p>' . "\n"),
			array('<param>', '<param>', '<param>' . "\n"),
			// array('<picture>', '<picture>', '<picture>' . "\n"),
			// array('<pre>', '<pre>', '<pre>' . "\n"),
			array('<progress>', '<progress>', '<p><progress></p>' . "\n"),
			array('<q>', '<q>', '<p><q></p>' . "\n"),
			array('<rp>', '<rp>', '<p><rp></p>' . "\n"),
			array('<rt>', '<rt>', '<p><rt></p>' . "\n"),
			array('<ruby>', '<ruby>', '<p><ruby></p>' . "\n"),
			array('<s>', '<s>', '<p><s></p>' . "\n"),
			array('<samp>', '<samp>', '<p><samp></p>' . "\n"),
			// array('<script>', '<script>', '<script>' . "\n"),
			// array('<section>', '<section>', '<section>' . "\n"),
			array('<select>', '<select>', '<p><select></p>' . "\n"),
			array('<small>', '<small>', '<p><small></p>' . "\n"),
			// array('<source>', '<source>', '<p><source></p>' . "\n"),
			array('<span>', '<span>', '<p><span></p>' . "\n"),
			array('<strike>', '<strike>', '<p><strike></p>' . "\n"),
			array('<strong>', '<strong>', '<p><strong></p>' . "\n"),
			// array('<style>', '<style>', '<p><style></p>' . "\n"),
			array('<sub>', '<sub>', '<p><sub></p>' . "\n"),
			array('<summary>', '<summary>', '<p><summary></p>' . "\n"),
			array('<sup>', '<sup>', '<p><sup></p>' . "\n"),
			// array('<table>', '<table>', '<table>' . "\n"),
			array('<tbody>', '<tbody>', '<p><tbody></p>' . "\n"),
			array('<td>', '<td>', '<p><td></p>' . "\n"),
			array('<textarea>', '<textarea>', '<p><textarea></p>' . "\n"),
			array('<tfoot>', '<tfoot>', '<p><tfoot></p>' . "\n"),
			array('<th>', '<th>', '<p><th></p>' . "\n"),
			array('<thead>', '<thead>', '<p><thead></p>' . "\n"),
			array('<time>', '<time>', '<p><time></p>' . "\n"),
			array('<title>', '<title>', '<p><title></p>' . "\n"),
			array('<tr>', '<tr>', '<p><tr></p>' . "\n"),
			// array('<track>', '<track>', '<p><track></p>' . "\n"),
			array('<tt>', '<tt>', '<p><tt></p>' . "\n"),
			array('<u>', '<u>', '<p><u></p>' . "\n"),
			// array('<ul>', '<ul>', '<ul>' . "\n"),
			array('<var>', '<var>', '<p><var></p>' . "\n"),
			// array('<video>', '<video>', '<video>' . "\n"),
			array('<wbr>', '<wbr>', '<p><wbr></p>' . "\n"),
		);
	}

	protected function HTMLWithContentData()
	{
		return array(
			array('<!-- foobar -->', '<!-- foobar -->', '<!-- foobar -->' . "\n"),
			array('<a>foobar</a>', '<a>foobar</a>', '<p><a>foobar</a></p>' . "\n"),
            array('<abbr>foobar</abbr>', '<abbr>foobar</abbr>', '<p><abbr>foobar</abbr></p>' . "\n"),
            array('<acronym>foobar</acronym>', '<acronym>foobar</acronym>', '<p><acronym>foobar</acronym></p>' . "\n"),
            array('<address>foobar</address>', '<address>foobar</address>', '<address>foobar</address>' . "\n"),
            array('<applet>foobar</applet>', '<applet>foobar</applet>', '<p><applet>foobar</applet></p>' . "\n"),
            array('<area>foobar</area>', '<area>foobar</area>', '<p><area>foobar</area></p>' . "\n"),
            array('<article>foobar</article>', '<article>foobar</article>', '<article>foobar</article>' . "\n"),
            array('<aside>foobar</aside>', '<aside>foobar</aside>', '<aside>foobar</aside>' . "\n"),
            array('<audio>foobar</audio>', '<audio>foobar</audio>', '<p><audio>foobar</audio></p>' . "\n"),
			array('<b>foobar</b>', '<b>foobar</b>', '<p><b>foobar</b></p>' . "\n"),
            array('<base>foobar</base>', '<base>foobar</base>', '<p><base>foobar</base></p>' . "\n"),
            array('<basefont>foobar</basefont>', '<basefont>foobar</basefont>', '<p><basefont>foobar</basefont></p>' . "\n"),
            array('<bdi>foobar</bdi>', '<bdi>foobar</bdi>', '<p><bdi>foobar</bdi></p>' . "\n"),
			array('<bdo>foobar</bdo>', '<bdo>foobar</bdo>', '<p><bdo>foobar</bdo></p>' . "\n"),
			array('<big>foobar</big>', '<big>foobar</big>', '<p><big>foobar</big></p>' . "\n"),
            array('<blockquote>foobar</blockquote>', '<blockquote>foobar</blockquote>', '<blockquote>foobar</blockquote>' . "\n"),
            array('<body>foobar</body>', '<body>foobar</body>', '<p><body>foobar</body></p>' . "\n"),
			array('<button>foobar</button>', '<button>foobar</button>', '<p><button>foobar</button></p>' . "\n"),
			array('<canvas>foobar</canvas>', '<canvas>foobar</canvas>', '<p><canvas>foobar</canvas></p>' . "\n"),
            array('<caption>foobar</caption>', '<caption>foobar</caption>', '<p><caption>foobar</caption></p>' . "\n"),
            array('<center>foobar</center>', '<center>foobar</center>', '<p><center>foobar</center></p>' . "\n"),
			array('<cite>foobar</cite>', '<cite>foobar</cite>', '<p><cite>foobar</cite></p>' . "\n"),
			array('<code>foobar</code>', '<code>foobar</code>', '<p><code>foobar</code></p>' . "\n"),
            array('<col>foobar</col>', '<col>foobar</col>', '<p><col>foobar</col></p>' . "\n"),
            array('<colgroup>foobar</colgroup>', '<colgroup>foobar</colgroup>', '<p><colgroup>foobar</colgroup></p>' . "\n"),
            array('<datalist>foobar</datalist>', '<datalist>foobar</datalist>', '<p><datalist>foobar</datalist></p>' . "\n"),
            array('<dd>foobar</dd>', '<dd>foobar</dd>', '<p><dd>foobar</dd></p>' . "\n"),
			array('<del>foobar</del>', '<del>foobar</del>', '<p><del>foobar</del></p>' . "\n"),
            array('<details>foobar</details>', '<details>foobar</details>', '<p><details>foobar</details></p>' . "\n"),
			array('<dfn>foobar</dfn>', '<dfn>foobar</dfn>', '<p><dfn>foobar</dfn></p>' . "\n"),
            array('<dialog>foobar</dialog>', '<dialog>foobar</dialog>', '<p><dialog>foobar</dialog></p>' . "\n"),
            array('<dir>foobar</dir>', '<dir>foobar</dir>', '<p><dir>foobar</dir></p>' . "\n"),
			array('<div>foobar</div>', '<div>foobar</div>', '<div>foobar</div>' . "\n"),
			array('<dl>foobar</dl>', '<dl>foobar</dl>', '<dl>foobar</dl>' . "\n"),
            array('<dt>foobar</dt>', '<dt>foobar</dt>', '<p><dt>foobar</dt></p>' . "\n"),
			array('<em>foobar</em>', '<em>foobar</em>', '<p><em>foobar</em></p>' . "\n"),
            array('<embed>foobar</embed>', '<embed>foobar</embed>', '<p><embed>foobar</embed></p>' . "\n"),
			array('<fieldset>foobar</fieldset>', '<fieldset>foobar</fieldset>', '<fieldset>foobar</fieldset>' . "\n"),
			array('<figcaption>foobar</figcaption>', '<figcaption>foobar</figcaption>', '<figcaption>foobar</figcaption>' . "\n"),
			array('<figure>foobar</figure>', '<figure>foobar</figure>', '<figure>foobar</figure>' . "\n"),
            array('<font>foobar</font>', '<font>foobar</font>', '<p><font>foobar</font></p>' . "\n"),
			array('<footer>foobar</footer>', '<footer>foobar</footer>', '<footer>foobar</footer>' . "\n"),
			array('<form>foobar</form>', '<form>foobar</form>', '<form>foobar</form>' . "\n"),
            array('<frame>foobar</frame>', '<frame>foobar</frame>', '<p><frame>foobar</frame></p>' . "\n"),
            array('<frameset>foobar</frameset>', '<frameset>foobar</frameset>', '<p><frameset>foobar</frameset></p>' . "\n"),
			array('<h1>foobar</h1>', '<h1>foobar</h1>', '<h1>foobar</h1>' . "\n"),
			array('<h2>foobar</h2>', '<h2>foobar</h2>', '<h2>foobar</h2>' . "\n"),
			array('<h3>foobar</h3>', '<h3>foobar</h3>', '<h3>foobar</h3>' . "\n"),
			array('<h4>foobar</h4>', '<h4>foobar</h4>', '<h4>foobar</h4>' . "\n"),
			array('<h5>foobar</h5>', '<h5>foobar</h5>', '<h5>foobar</h5>' . "\n"),
			array('<h6>foobar</h6>', '<h6>foobar</h6>', '<h6>foobar</h6>' . "\n"),
            array('<head>foobar</head>', '<head>foobar</head>', '<p><head>foobar</head></p>' . "\n"),
			array('<header>foobar</header>', '<header>foobar</header>', '<header>foobar</header>' . "\n"),
            array('<html>foobar</html>', '<html>foobar</html>', '<p><html>foobar</html></p>' . "\n"),
			array('<i>foobar</i>', '<i>foobar</i>', '<p><i>foobar</i></p>' . "\n"),
            array('<iframe>foobar</iframe>', '<iframe>foobar</iframe>', '<iframe>foobar</iframe>' . "\n"),
			array('<ins>foobar</ins>', '<ins>foobar</ins>', '<p><ins>foobar</ins></p>' . "\n"),
			array('<kbd>foobar</kbd>', '<kbd>foobar</kbd>', '<p><kbd>foobar</kbd></p>' . "\n"),
            array('<keygen>foobar</keygen>', '<keygen>foobar</keygen>', '<p><keygen>foobar</keygen></p>' . "\n"),
			array('<label>foobar</label>', '<label>foobar</label>', '<p><label>foobar</label></p>' . "\n"),
            array('<legend>foobar</legend>', '<legend>foobar</legend>', '<legend>foobar</legend>' . "\n"),
            array('<li>foobar</li>', '<li>foobar</li>', '<p><li>foobar</li></p>' . "\n"),
            array('<link>foobar</link>', '<link>foobar</link>', '<p><link>foobar</link></p>' . "\n"),
            array('<main>foobar</main>', '<main>foobar</main>', '<p><main>foobar</main></p>' . "\n"),
			array('<map>foobar</map>', '<map>foobar</map>', '<p><map>foobar</map></p>' . "\n"),
			array('<mark>foobar</mark>', '<mark>foobar</mark>', '<p><mark>foobar</mark></p>' . "\n"),
            array('<menu>foobar</menu>', '<menu>foobar</menu>', '<p><menu>foobar</menu></p>' . "\n"),
            array('<menuitem>foobar</menuitem>', '<menuitem>foobar</menuitem>', '<p><menuitem>foobar</menuitem></p>' . "\n"),
            array('<meta>foobar</meta>', '<meta>foobar</meta>', '<p><meta>foobar</meta></p>' . "\n"),
            array('<meter>foobar</meter>', '<meter>foobar</meter>', '<p><meter>foobar</meter></p>' . "\n"),
            array('<nav>foobar</nav>', '<nav>foobar</nav>', '<nav>foobar</nav>' . "\n"),
            array('<noframes>foobar</noframes>', '<noframes>foobar</noframes>', '<p><noframes>foobar</noframes></p>' . "\n"),
			array('<noscript>foobar</noscript>', '<noscript>foobar</noscript>', '<p><noscript>foobar</noscript></p>' . "\n"),
			array('<object>foobar</object>', '<object>foobar</object>', '<p><object>foobar</object></p>' . "\n"),
			array('<ol>foobar</ol>', '<ol>foobar</ol>', '<ol>foobar</ol>' . "\n"),
            array('<optgroup>foobar</optgroup>', '<optgroup>foobar</optgroup>', '<p><optgroup>foobar</optgroup></p>' . "\n"),
            array('<option>foobar</option>', '<option>foobar</option>', '<p><option>foobar</option></p>' . "\n"),
			array('<output>foobar</output>', '<output>foobar</output>', '<p><output>foobar</output></p>' . "\n"),
			array('<p>foobar</p>', '<p>foobar</p>', '<p>foobar</p>' . "\n"),
            array('<param>foobar</param>', '<param>foobar</param>', '<p><param>foobar</param></p>' . "\n"),
            array('<picture>foobar</picture>', '<picture>foobar</picture>','<p><picture>foobar</picture></p>' . "\n"),
			array('<pre>foobar</pre>', '<pre>foobar</pre>', '<pre>foobar</pre>' . "\n"),
            array('<progress>foobar</progress>', '<progress>foobar</progress>', '<p><progress>foobar</progress></p>' . "\n"),
			array('<q>foobar</q>', '<q>foobar</q>', '<p><q>foobar</q></p>' . "\n"),
            array('<rp>foobar</rp>', '<rp>foobar</rp>', '<p><rp>foobar</rp></p>' . "\n"),
            array('<rt>foobar</rt>', '<rt>foobar</rt>', '<p><rt>foobar</rt></p>' . "\n"),
            array('<ruby>foobar</ruby>', '<ruby>foobar</ruby>', '<p><ruby>foobar</ruby></p>' . "\n"),
            array('<s>foobar</s>', '<s>foobar</s>', '<p><s>foobar</s></p>' . "\n"),
			array('<samp>foobar</samp>', '<samp>foobar</samp>', '<p><samp>foobar</samp></p>' . "\n"),
			array('<script>foobar</script>', '<script>foobar</script>', '<script>foobar</script>' . "\n"),
			array('<section>foobar</section>', '<section>foobar</section>', '<section>foobar</section>' . "\n"),
			array('<select>foobar</select>', '<select>foobar</select>', '<p><select>foobar</select></p>' . "\n"),
			array('<small>foobar</small>', '<small>foobar</small>', '<p><small>foobar</small></p>' . "\n"),
            array('<source>foobar</source>', '<source>foobar</source>', '<p><source>foobar</source></p>' . "\n"),
			array('<span>foobar</span>', '<span>foobar</span>', '<p><span>foobar</span></p>' . "\n"),
            array('<strike>foobar</strike>', '<strike>foobar</strike>', '<p><strike>foobar</strike></p>' . "\n"),
			array('<strong>foobar</strong>', '<strong>foobar</strong>', '<p><strong>foobar</strong></p>' . "\n"),
            array('<style>foobar</style>', '<style>foobar</style>', '<style>foobar</style>' . "\n"),
			array('<sub>foobar</sub>', '<sub>foobar</sub>', '<p><sub>foobar</sub></p>' . "\n"),
            array('<summary>foobar</summary>', '<summary>foobar</summary>', '<p><summary>foobar</summary></p>' . "\n"),
			array('<sup>foobar</sup>', '<sup>foobar</sup>', '<p><sup>foobar</sup></p>' . "\n"),
			array('<table>foobar</table>', '<table>foobar</table>', '<table>foobar</table>' . "\n"),
            array('<tbody>foobar</tbody>', '<tbody>foobar</tbody>', '<p><tbody>foobar</tbody></p>' . "\n"),
            array('<td>foobar</td>', '<td>foobar</td>', '<p><td>foobar</td></p>' . "\n"),
			array('<textarea>foobar</textarea>', '<textarea>foobar</textarea>', '<p><textarea>foobar</textarea></p>' . "\n"),
            array('<tfoot>foobar</tfoot>', '<tfoot>foobar</tfoot>', '<p><tfoot>foobar</tfoot></p>' . "\n"),
            array('<th>foobar</th>', '<th>foobar</th>', '<p><th>foobar</th></p>' . "\n"),
            array('<thead>foobar</thead>', '<thead>foobar</thead>', '<p><thead>foobar</thead></p>' . "\n"),
            array('<time>foobar</time>', '<time>foobar</time>', '<p><time>foobar</time></p>' . "\n"),
            array('<title>foobar</title>', '<title>foobar</title>', '<p><title>foobar</title></p>' . "\n"),
            array('<tr>foobar</tr>', '<tr>foobar</tr>', '<p><tr>foobar</tr></p>' . "\n"),
            array('<track>foobar</track>', '<track>foobar</track>', '<p><track>foobar</track></p>' . "\n"),
			array('<tt>foobar</tt>', '<tt>foobar</tt>', '<p><tt>foobar</tt></p>' . "\n"),
            array('<u>foobar</u>', '<u>foobar</u>', '<p><u>foobar</u></p>' . "\n"),
			array('<ul>foobar</ul>', '<ul>foobar</ul>', '<ul>foobar</ul>' . "\n"),
			array('<var>foobar</var>', '<var>foobar</var>', '<p><var>foobar</var></p>' . "\n"),
			array('<video>foobar</video>', '<video>foobar</video>', '<p><video>foobar</video></p>' . "\n"),
            array('<wbr>foobar</wbr>', '<wbr>foobar</wbr>', '<p><wbr>foobar</wbr></p>' . "\n"),
		);
	}

	protected function HTMLAttributesData()
	{
		return array(
			array('async', '<div async>', '<div async>' . "\n"),
			array('autofocus', '<div autofocus>', '<div autofocus>' . "\n"),
			array('autoplay', '<div autoplay>', '<div autoplay>' . "\n"),
			array('challenge', '<div challenge>', '<div challenge>' . "\n"),
			array('checked', '<div checked>', '<div checked>' . "\n"),
			array('controls', '<div controls>', '<div controls>' . "\n"),
			array('default', '<div default>', '<div default>' . "\n"),
			array('defer', '<div defer>', '<div defer>' . "\n"),
			array('disabled', '<div disabled>', '<div disabled>' . "\n"),
			array('hidden', '<div hidden>', '<div hidden>' . "\n"),
			array('ismap', '<div ismap>', '<div ismap>' . "\n"),
			array('loop', '<div loop>', '<div loop>' . "\n"),
			array('multiple', '<div multiple>', '<div multiple>' . "\n"),
			array('muted', '<div muted>', '<div muted>' . "\n"),
			array('novalidate', '<div novalidate>', '<div novalidate>' . "\n"),
			array('readonly', '<div readonly>', '<div readonly>' . "\n"),
			array('required', '<div required>', '<div required>' . "\n"),
			array('reversed', '<div reversed>', '<div reversed>' . "\n"),
			array('sandbox', '<div sandbox>', '<div sandbox>' . "\n"),
			array('scoped', '<div scoped>', '<div scoped>' . "\n"),
			array('selected', '<div selected>', '<div selected>' . "\n"),

			array('accept', '<div accept="foo">', '<div accept="foo">' . "\n"),
			array('accept-charset', '<div accept-charset="foo">', '<div accept-charset="foo">' . "\n"),
			array('accesskey', '<div accesskey="foo">', '<div accesskey="foo">' . "\n"),
			array('action', '<div action="foo">', '<div action="foo">' . "\n"),
			array('align', '<div align="foo">', '<div align="foo">' . "\n"),
			array('alt', '<div alt="foo">', '<div alt="foo">' . "\n"),
			array('autocomplete', '<div autocomplete="foo">', '<div autocomplete="foo">' . "\n"),
			array('bgcolor', '<div bgcolor="foo">', '<div bgcolor="foo">' . "\n"),
			array('border', '<div border="foo">', '<div border="foo">' . "\n"),
			array('charset', '<div charset="foo">', '<div charset="foo">' . "\n"),
			array('cite', '<div cite="foo">', '<div cite="foo">' . "\n"),
			array('class', '<div class="foo">', '<div class="foo">' . "\n"),
			array('color', '<div color="foo">', '<div color="foo">' . "\n"),
			array('cols', '<div cols="foo">', '<div cols="foo">' . "\n"),
			array('colspan', '<div colspan="foo">', '<div colspan="foo">' . "\n"),
			array('content', '<div content="foo">', '<div content="foo">' . "\n"),
			array('contenteditable', '<div contenteditable="foo">', '<div contenteditable="foo">' . "\n"),
			array('contextmenu', '<div contextmenu="foo">', '<div contextmenu="foo">' . "\n"),
			array('coords', '<div coords="foo">', '<div coords="foo">' . "\n"),
			array('data', '<div data="foo">', '<div data="foo">' . "\n"),
			array('data', '<div data="foo">', '<div data="foo">' . "\n"),
			array('datetime', '<div datetime="foo">', '<div datetime="foo">' . "\n"),
			array('dir', '<div dir="foo">', '<div dir="foo">' . "\n"),
			array('dirname', '<div dirname="foo">', '<div dirname="foo">' . "\n"),
			array('download', '<div download="foo">', '<div download="foo">' . "\n"),
			array('draggable', '<div draggable="foo">', '<div draggable="foo">' . "\n"),
			array('dropzone', '<div dropzone="foo">', '<div dropzone="foo">' . "\n"),
			array('enctype', '<div enctype="foo">', '<div enctype="foo">' . "\n"),
			array('for', '<div for="foo">', '<div for="foo">' . "\n"),
			array('form', '<div form="foo">', '<div form="foo">' . "\n"),
			array('formaction', '<div formaction="foo">', '<div formaction="foo">' . "\n"),
			array('headers', '<div headers="foo">', '<div headers="foo">' . "\n"),
			array('height', '<div height="foo">', '<div height="foo">' . "\n"),
			array('high', '<div high="foo">', '<div high="foo">' . "\n"),
			array('href', '<div href="foo">', '<div href="foo">' . "\n"),
			array('hreflang', '<div hreflang="foo">', '<div hreflang="foo">' . "\n"),
			array('http', '<div http="foo">', '<div http="foo">' . "\n"),
			array('id', '<div id="foo">', '<div id="foo">' . "\n"),
			array('keytype', '<div keytype="foo">', '<div keytype="foo">' . "\n"),
			array('kind', '<div kind="foo">', '<div kind="foo">' . "\n"),
			array('label', '<div label="foo">', '<div label="foo">' . "\n"),
			array('lang', '<div lang="foo">', '<div lang="foo">' . "\n"),
			array('list', '<div list="foo">', '<div list="foo">' . "\n"),
			array('low', '<div low="foo">', '<div low="foo">' . "\n"),
			array('max', '<div max="foo">', '<div max="foo">' . "\n"),
			array('maxlength', '<div maxlength="foo">', '<div maxlength="foo">' . "\n"),
			array('media', '<div media="foo">', '<div media="foo">' . "\n"),
			array('method', '<div method="foo">', '<div method="foo">' . "\n"),
			array('min', '<div min="foo">', '<div min="foo">' . "\n"),
			array('name', '<div name="foo">', '<div name="foo">' . "\n"),
			array('onabort', '<div onabort="foo">', '<div onabort="foo">' . "\n"),
			array('onafterprint', '<div onafterprint="foo">', '<div onafterprint="foo">' . "\n"),
			array('onbeforeprint', '<div onbeforeprint="foo">', '<div onbeforeprint="foo">' . "\n"),
			array('onbeforeunload', '<div onbeforeunload="foo">', '<div onbeforeunload="foo">' . "\n"),
			array('onblur', '<div onblur="foo">', '<div onblur="foo">' . "\n"),
			array('oncanplay', '<div oncanplay="foo">', '<div oncanplay="foo">' . "\n"),
			array('oncanplaythrough', '<div oncanplaythrough="foo">', '<div oncanplaythrough="foo">' . "\n"),
			array('onchange', '<div onchange="foo">', '<div onchange="foo">' . "\n"),
			array('onclick', '<div onclick="foo">', '<div onclick="foo">' . "\n"),
			array('oncontextmenu', '<div oncontextmenu="foo">', '<div oncontextmenu="foo">' . "\n"),
			array('oncopy', '<div oncopy="foo">', '<div oncopy="foo">' . "\n"),
			array('oncuechange', '<div oncuechange="foo">', '<div oncuechange="foo">' . "\n"),
			array('oncut', '<div oncut="foo">', '<div oncut="foo">' . "\n"),
			array('ondblclick', '<div ondblclick="foo">', '<div ondblclick="foo">' . "\n"),
			array('ondrag', '<div ondrag="foo">', '<div ondrag="foo">' . "\n"),
			array('ondragend', '<div ondragend="foo">', '<div ondragend="foo">' . "\n"),
			array('ondragenter', '<div ondragenter="foo">', '<div ondragenter="foo">' . "\n"),
			array('ondragleave', '<div ondragleave="foo">', '<div ondragleave="foo">' . "\n"),
			array('ondragover', '<div ondragover="foo">', '<div ondragover="foo">' . "\n"),
			array('ondragstart', '<div ondragstart="foo">', '<div ondragstart="foo">' . "\n"),
			array('ondrop', '<div ondrop="foo">', '<div ondrop="foo">' . "\n"),
			array('ondurationchange', '<div ondurationchange="foo">', '<div ondurationchange="foo">' . "\n"),
			array('onemptied', '<div onemptied="foo">', '<div onemptied="foo">' . "\n"),
			array('onended', '<div onended="foo">', '<div onended="foo">' . "\n"),
			array('onerror', '<div onerror="foo">', '<div onerror="foo">' . "\n"),
			array('onfocus', '<div onfocus="foo">', '<div onfocus="foo">' . "\n"),
			array('onhashchange', '<div onhashchange="foo">', '<div onhashchange="foo">' . "\n"),
			array('oninput', '<div oninput="foo">', '<div oninput="foo">' . "\n"),
			array('oninvalid', '<div oninvalid="foo">', '<div oninvalid="foo">' . "\n"),
			array('onkeydown', '<div onkeydown="foo">', '<div onkeydown="foo">' . "\n"),
			array('onkeypress', '<div onkeypress="foo">', '<div onkeypress="foo">' . "\n"),
			array('onkeyup', '<div onkeyup="foo">', '<div onkeyup="foo">' . "\n"),
			array('onload', '<div onload="foo">', '<div onload="foo">' . "\n"),
			array('onloadeddata', '<div onloadeddata="foo">', '<div onloadeddata="foo">' . "\n"),
			array('onloadedmetadata', '<div onloadedmetadata="foo">', '<div onloadedmetadata="foo">' . "\n"),
			array('onloadstart', '<div onloadstart="foo">', '<div onloadstart="foo">' . "\n"),
			array('onmousedown', '<div onmousedown="foo">', '<div onmousedown="foo">' . "\n"),
			array('onmousemove', '<div onmousemove="foo">', '<div onmousemove="foo">' . "\n"),
			array('onmouseout', '<div onmouseout="foo">', '<div onmouseout="foo">' . "\n"),
			array('onmouseover', '<div onmouseover="foo">', '<div onmouseover="foo">' . "\n"),
			array('onmouseup', '<div onmouseup="foo">', '<div onmouseup="foo">' . "\n"),
			array('onmousewheel', '<div onmousewheel="foo">', '<div onmousewheel="foo">' . "\n"),
			array('onoffline', '<div onoffline="foo">', '<div onoffline="foo">' . "\n"),
			array('ononline', '<div ononline="foo">', '<div ononline="foo">' . "\n"),
			array('onpagehide', '<div onpagehide="foo">', '<div onpagehide="foo">' . "\n"),
			array('onpageshow', '<div onpageshow="foo">', '<div onpageshow="foo">' . "\n"),
			array('onpaste', '<div onpaste="foo">', '<div onpaste="foo">' . "\n"),
			array('onpause', '<div onpause="foo">', '<div onpause="foo">' . "\n"),
			array('onplay', '<div onplay="foo">', '<div onplay="foo">' . "\n"),
			array('onplaying', '<div onplaying="foo">', '<div onplaying="foo">' . "\n"),
			array('onpopstate', '<div onpopstate="foo">', '<div onpopstate="foo">' . "\n"),
			array('onprogress', '<div onprogress="foo">', '<div onprogress="foo">' . "\n"),
			array('onratechange', '<div onratechange="foo">', '<div onratechange="foo">' . "\n"),
			array('onreset', '<div onreset="foo">', '<div onreset="foo">' . "\n"),
			array('onresize', '<div onresize="foo">', '<div onresize="foo">' . "\n"),
			array('onscroll', '<div onscroll="foo">', '<div onscroll="foo">' . "\n"),
			array('onsearch', '<div onsearch="foo">', '<div onsearch="foo">' . "\n"),
			array('onseeked', '<div onseeked="foo">', '<div onseeked="foo">' . "\n"),
			array('onseeking', '<div onseeking="foo">', '<div onseeking="foo">' . "\n"),
			array('onselect', '<div onselect="foo">', '<div onselect="foo">' . "\n"),
			array('onshow', '<div onshow="foo">', '<div onshow="foo">' . "\n"),
			array('onstalled', '<div onstalled="foo">', '<div onstalled="foo">' . "\n"),
			array('onstorage', '<div onstorage="foo">', '<div onstorage="foo">' . "\n"),
			array('onsubmit', '<div onsubmit="foo">', '<div onsubmit="foo">' . "\n"),
			array('onsuspend', '<div onsuspend="foo">', '<div onsuspend="foo">' . "\n"),
			array('ontimeupdate', '<div ontimeupdate="foo">', '<div ontimeupdate="foo">' . "\n"),
			array('ontoggle', '<div ontoggle="foo">', '<div ontoggle="foo">' . "\n"),
			array('onunload', '<div onunload="foo">', '<div onunload="foo">' . "\n"),
			array('onvolumechange', '<div onvolumechange="foo">', '<div onvolumechange="foo">' . "\n"),
			array('onwaiting', '<div onwaiting="foo">', '<div onwaiting="foo">' . "\n"),
			array('onwheel', '<div onwheel="foo">', '<div onwheel="foo">' . "\n"),
			array('open', '<div open="foo">', '<div open="foo">' . "\n"),
			array('optimum', '<div optimum="foo">', '<div optimum="foo">' . "\n"),
			array('pattern', '<div pattern="foo">', '<div pattern="foo">' . "\n"),
			array('placeholder', '<div placeholder="foo">', '<div placeholder="foo">' . "\n"),
			array('poster', '<div poster="foo">', '<div poster="foo">' . "\n"),
			array('preload', '<div preload="foo">', '<div preload="foo">' . "\n"),
			array('rel', '<div rel="foo">', '<div rel="foo">' . "\n"),
			array('rows', '<div rows="foo">', '<div rows="foo">' . "\n"),
			array('rowspan', '<div rowspan="foo">', '<div rowspan="foo">' . "\n"),
			array('scope', '<div scope="foo">', '<div scope="foo">' . "\n"),
			array('shape', '<div shape="foo">', '<div shape="foo">' . "\n"),
			array('size', '<div size="foo">', '<div size="foo">' . "\n"),
			array('sizes', '<div sizes="foo">', '<div sizes="foo">' . "\n"),
			array('span', '<div span="foo">', '<div span="foo">' . "\n"),
			array('spellcheck', '<div spellcheck="foo">', '<div spellcheck="foo">' . "\n"),
			array('src', '<div src="foo">', '<div src="foo">' . "\n"),
			array('srcdoc', '<div srcdoc="foo">', '<div srcdoc="foo">' . "\n"),
			array('srclang', '<div srclang="foo">', '<div srclang="foo">' . "\n"),
			array('srcset', '<div srcset="foo">', '<div srcset="foo">' . "\n"),
			array('start', '<div start="foo">', '<div start="foo">' . "\n"),
			array('step', '<div step="foo">', '<div step="foo">' . "\n"),
			array('style', '<div style="foo">', '<div style="foo">' . "\n"),
			array('tabindex', '<div tabindex="foo">', '<div tabindex="foo">' . "\n"),
			array('target', '<div target="foo">', '<div target="foo">' . "\n"),
			array('title', '<div title="foo">', '<div title="foo">' . "\n"),
			array('translate', '<div translate="foo">', '<div translate="foo">' . "\n"),
			array('type', '<div type="foo">', '<div type="foo">' . "\n"),
			array('usemap', '<div usemap="foo">', '<div usemap="foo">' . "\n"),
			array('value', '<div value="foo">', '<div value="foo">' . "\n"),
			array('width', '<div width="foo">', '<div width="foo">' . "\n"),
			array('wrap', '<div wrap="foo">', '<div wrap="foo">' . "\n"),
		);
	}

	protected function HTMLWithAttributesData()
	{
		$all_attributes = 'async autofocus autoplay challenge checked controls default defer disabled hidden ismap loop multiple muted novalidate readonly required reversed sandbox scoped selected accept="foo" accept-charset="foo" accesskey="foo" action="foo" align="foo" alt="foo" autocomplete="foo" bgcolor="foo" border="foo" charset="foo" cite="foo" class="foo" color="foo" cols="foo" colspan="foo" content="foo" contenteditable="foo" contextmenu="foo" coords="foo" data="foo" data="foo" datetime="foo" dir="foo" dirname="foo" download="foo" draggable="foo" dropzone="foo" enctype="foo" for="foo" form="foo" formaction="foo" headers="foo" height="foo" high="foo" href="foo" hreflang="foo" http="foo" id="foo" keytype="foo" kind="foo" label="foo" lang="foo" list="foo" low="foo" max="foo" maxlength="foo" media="foo" method="foo" min="foo" name="foo" onabort="foo" onafterprint="foo" onbeforeprint="foo" onbeforeunload="foo" onblur="foo" oncanplay="foo" oncanplaythrough="foo" onchange="foo" onclick="foo" oncontextmenu="foo" oncopy="foo" oncuechange="foo" oncut="foo" ondblclick="foo" ondrag="foo" ondragend="foo" ondragenter="foo" ondragleave="foo" ondragover="foo" ondragstart="foo" ondrop="foo" ondurationchange="foo" onemptied="foo" onended="foo" onerror="foo" onfocus="foo" onhashchange="foo" oninput="foo" oninvalid="foo" onkeydown="foo" onkeypress="foo" onkeyup="foo" onload="foo" onloadeddata="foo" onloadedmetadata="foo" onloadstart="foo" onmousedown="foo" onmousemove="foo" onmouseout="foo" onmouseover="foo" onmouseup="foo" onmousewheel="foo" onoffline="foo" ononline="foo" onpagehide="foo" onpageshow="foo" onpaste="foo" onpause="foo" onplay="foo" onplaying="foo" onpopstate="foo" onprogress="foo" onratechange="foo" onreset="foo" onresize="foo" onscroll="foo" onsearch="foo" onseeked="foo" onseeking="foo" onselect="foo" onshow="foo" onstalled="foo" onstorage="foo" onsubmit="foo" onsuspend="foo" ontimeupdate="foo" ontoggle="foo" onunload="foo" onvolumechange="foo" onwaiting="foo" onwheel="foo" open="foo" optimum="foo" pattern="foo" placeholder="foo" poster="foo" preload="foo" rel="foo" rows="foo" rowspan="foo" scope="foo" shape="foo" size="foo" sizes="foo" span="foo" spellcheck="foo" src="foo" srcdoc="foo" srclang="foo" srcset="foo" start="foo" step="foo" style="foo" tabindex="foo" target="foo" title="foo" translate="foo" type="foo" usemap="foo" value="foo" width="foo" wrap="foo"';
		$allowed_attributes = $all_attributes;

		return array(
			array('<a> with attributes', '<a ' . $all_attributes . '></a>', '<p><a ' . $allowed_attributes . '></a></p>' . "\n"),
            array('<abbr> with attributes', '<abbr ' . $all_attributes . '></abbr>', '<p><abbr ' . $allowed_attributes . '></abbr></p>' . "\n"),
            array('<acronym> with attributes', '<acronym ' . $all_attributes . '></acronym>', '<p><acronym ' . $allowed_attributes . '></acronym></p>' . "\n"),
            array('<address> with attributes', '<address ' . $all_attributes . '></address>', '<address ' . $allowed_attributes . '></address>' . "\n"),
            array('<applet> with attributes', '<applet ' . $all_attributes . '></applet>', '<p><applet ' . $allowed_attributes . '></applet></p>' . "\n"),
            array('<area> with attributes', '<area ' . $all_attributes . '></area>', '<p><area ' . $allowed_attributes . '></area></p>' . "\n"),
            array('<article> with attributes', '<article ' . $all_attributes . '></article>', '<article ' . $allowed_attributes . '></article>' . "\n"),
            array('<aside> with attributes', '<aside ' . $all_attributes . '></aside>', '<aside ' . $allowed_attributes . '></aside>' . "\n"),
            array('<audio> with attributes', '<audio ' . $all_attributes . '></audio>', '<p><audio ' . $allowed_attributes . '></audio></p>' . "\n"),
			array('<b> with attributes', '<b ' . $all_attributes . '></b>', '<p><b ' . $allowed_attributes . '></b></p>' . "\n"),
            array('<base> with attributes', '<base ' . $all_attributes . '></base>', '<p><base ' . $allowed_attributes . '></base></p>' . "\n"),
            array('<basefont> with attributes', '<basefont ' . $all_attributes . '></basefont>', '<p><basefont ' . $allowed_attributes . '></basefont></p>' . "\n"),
            array('<bdi> with attributes', '<bdi ' . $all_attributes . '></bdi>', '<p><bdi ' . $allowed_attributes . '></bdi></p>' . "\n"),
			array('<bdo> with attributes', '<bdo ' . $all_attributes . '></bdo>', '<p><bdo ' . $allowed_attributes . '></bdo></p>' . "\n"),
			array('<big> with attributes', '<big ' . $all_attributes . '></big>', '<p><big ' . $allowed_attributes . '></big></p>' . "\n"),
			array('<blockquote> with attributes', '<blockquote ' . $all_attributes . '></blockquote>', '<blockquote ' . $allowed_attributes . '></blockquote>' . "\n"),
            array('<body> with attributes', '<body ' . $all_attributes . '></body>', '<p><body ' . $allowed_attributes . '></body></p>' . "\n"),
            array('<br> with attributes', '<br ' . $all_attributes . '>', '<p><br ' . $all_attributes . '></p>' . "\n"),
			array('<button> with attributes', '<button ' . $all_attributes . '></button>', '<p><button ' . $allowed_attributes . '></button></p>' . "\n"),
			array('<canvas> with attributes', '<canvas ' . $all_attributes . '></canvas>', '<p><canvas ' . $allowed_attributes . '></canvas></p>' . "\n"),
            array('<caption> with attributes', '<caption ' . $all_attributes . '></caption>', '<p><caption ' . $allowed_attributes . '></caption></p>' . "\n"),
            array('<center> with attributes', '<center ' . $all_attributes . '></center>', '<p><center ' . $allowed_attributes .'></center></p>' . "\n"),
			array('<cite> with attributes', '<cite ' . $all_attributes . '></cite>', '<p><cite ' . $allowed_attributes . '></cite></p>' . "\n"),
			array('<code> with attributes', '<code ' . $all_attributes . '></code>', '<p><code ' . $all_attributes . '></code></p>' . "\n"),
            array('<col> with attributes', '<col ' . $all_attributes . '></col>', '<p><col ' . $allowed_attributes . '></col></p>' . "\n"),
            array('<colgroup> with attributes', '<colgroup ' . $all_attributes . '></colgroup>', '<p><colgroup ' . $allowed_attributes . '></colgroup></p>' . "\n"),
            array('<datalist> with attributes', '<datalist ' . $all_attributes . '></datalist>', '<p><datalist ' . $allowed_attributes . '></datalist></p>' . "\n"),
            array('<dd> with attributes', '<dd ' . $all_attributes . '></dd>', '<p><dd ' . $allowed_attributes . '></dd></p>' . "\n"),
			array('<del> with attributes', '<del ' . $all_attributes . '></del>', '<p><del ' . $allowed_attributes . '></del></p>' . "\n"),
            array('<details> with attributes', '<details ' . $all_attributes . '></details>', '<p><details ' . $allowed_attributes . '></details></p>' . "\n"),
			array('<dfn> with attributes', '<dfn ' . $all_attributes . '></dfn>', '<p><dfn ' . $allowed_attributes . '></dfn></p>' . "\n"),
            array('<dialog> with attributes', '<dialog ' . $all_attributes . '></dialog>', '<p><dialog ' . $allowed_attributes . '></dialog></p>' . "\n"),
            array('<dir> with attributes', '<dir ' . $all_attributes . '></dir>', '<p><dir ' . $allowed_attributes . '></dir></p>' . "\n"),
			array('<div> with attributes', '<div ' . $all_attributes . '></div>', '<div ' . $allowed_attributes . '></div>' . "\n"),
			array('<dl> with attributes', '<dl ' . $all_attributes . '></dl>', '<dl ' . $allowed_attributes . '></dl>' . "\n"),
            array('<dt> with attributes', '<dt ' . $all_attributes . '></dt>', '<p><dt ' . $allowed_attributes . '></dt></p>' . "\n"),
			array('<em> with attributes', '<em ' . $all_attributes . '></em>', '<p><em ' . $allowed_attributes . '></em></p>' . "\n"),
            array('<embed> with attributes', '<embed ' . $all_attributes . '></embed>', '<p><embed ' . $allowed_attributes . '></embed></p>' . "\n"),
			array('<fieldset> with attributes', '<fieldset ' . $all_attributes . '></fieldset>', '<fieldset ' . $allowed_attributes . '></fieldset>' . "\n"),
			array('<figcaption> with attributes', '<figcaption ' . $all_attributes . '></figcaption>', '<figcaption ' . $allowed_attributes . '></figcaption>' . "\n"),
			array('<figure> with attributes', '<figure ' . $all_attributes . '></figure>', '<figure ' . $allowed_attributes . '></figure>' . "\n"),
            array('<font> with attributes', '<font ' . $all_attributes . '></font>', '<p><font ' . $allowed_attributes . '></font></p>' . "\n"),
			array('<footer> with attributes', '<footer ' . $all_attributes . '></footer>', '<footer ' . $allowed_attributes . '></footer>' . "\n"),
			array('<form> with attributes', '<form ' . $all_attributes . '></form>', '<form ' . $allowed_attributes . '></form>' . "\n"),
            array('<frame> with attributes', '<frame ' . $all_attributes . '></frame>', '<p><frame ' . $allowed_attributes . '></frame></p>' . "\n"),
            array('<frameset> with attributes', '<frameset ' . $all_attributes . '></frameset>', '<p><frameset ' . $allowed_attributes .'></frameset></p>' . "\n"),
            array('<h1> with attributes', '<h1 ' . $all_attributes . '></h1>', '<h1 ' . $allowed_attributes . '></h1>' . "\n"),
            array('<h2> with attributes', '<h2 ' . $all_attributes . '></h2>', '<h2 ' . $allowed_attributes . '></h2>' . "\n"),
            array('<h3> with attributes', '<h3 ' . $all_attributes . '></h3>', '<h3 ' . $allowed_attributes . '></h3>' . "\n"),
            array('<h4> with attributes', '<h4 ' . $all_attributes . '></h4>', '<h4 ' . $allowed_attributes . '></h4>' . "\n"),
            array('<h5> with attributes', '<h5 ' . $all_attributes . '></h5>', '<h5 ' . $allowed_attributes . '></h5>' . "\n"),
            array('<h6> with attributes', '<h6 ' . $all_attributes . '></h6>', '<h6 ' . $allowed_attributes . '></h6>' . "\n"),
            array('<head> with attributes', '<head ' . $all_attributes . '></head>', '<p><head ' . $allowed_attributes . '></head></p>' . "\n"),
			array('<header> with attributes', '<header ' . $all_attributes . '></header>', '<header ' . $allowed_attributes . '></header>' . "\n"),
            array('<html> with attributes', '<html ' . $all_attributes . '></html>', '<p><html ' . $allowed_attributes . '></html></p>' . "\n"),
			array('<i> with attributes', '<i ' . $all_attributes . '></i>', '<p><i ' . $allowed_attributes . '></i></p>' . "\n"),
            array('<iframe> with attributes', '<iframe ' . $all_attributes . '></iframe>', '<iframe ' . $allowed_attributes .'></iframe>' . "\n"),
            array('<img> with attributes', '<img ' . $all_attributes . '>', '<p><img ' . $allowed_attributes . '></p>' . "\n"),
			array('<input> with attributes', '<input ' . $all_attributes . '>', '<p><input ' . $allowed_attributes . '></p>' . "\n"),
			array('<ins> with attributes', '<ins ' . $all_attributes . '></ins>', '<p><ins ' . $allowed_attributes . '></ins></p>' . "\n"),
			array('<kbd> with attributes', '<kbd ' . $all_attributes . '></kbd>', '<p><kbd ' . $allowed_attributes . '></kbd></p>' . "\n"),
            array('<keygen> with attributes', '<keygen ' . $all_attributes . '></keygen>', '<p><keygen ' . $allowed_attributes . '></keygen></p>' . "\n"),
			array('<label> with attributes', '<label ' . $all_attributes . '></label>', '<p><label ' . $allowed_attributes . '></label></p>' . "\n"),
            array('<legend> with attributes', '<legend ' . $all_attributes . '></legend>', '<legend ' . $allowed_attributes . '></legend>' . "\n"),
            array('<li> with attributes', '<li ' . $all_attributes . '></li>', '<p><li ' . $allowed_attributes . '></li></p>' . "\n"),
            array('<link> with attributes', '<link ' . $all_attributes . '></link>', '<p><link ' . $allowed_attributes . '></link></p>' . "\n"),
            array('<main> with attributes', '<main ' . $all_attributes . '></main>', '<p><main ' . $allowed_attributes . '></main></p>' . "\n"),
			array('<map> with attributes', '<map ' . $all_attributes . '></map>', '<p><map ' . $allowed_attributes . '></map></p>' . "\n"),
			array('<mark> with attributes', '<mark ' . $all_attributes . '></mark>', '<p><mark ' . $all_attributes . '></mark></p>' . "\n"),
            array('<menu> with attributes', '<menu ' . $all_attributes . '></menu>', '<p><menu ' . $allowed_attributes . '></menu></p>' . "\n"),
            array('<menuitem> with attributes', '<menuitem ' . $all_attributes . '></menuitem>', '<p><menuitem ' . $allowed_attributes . '></menuitem></p>' . "\n"),
            array('<meta> with attributes', '<meta ' . $all_attributes . '></meta>', '<p><meta ' . $allowed_attributes . '></meta></p>' . "\n"),
            array('<meter> with attributes', '<meter ' . $all_attributes . '></meter>', '<p><meter ' . $allowed_attributes . '></meter></p>' . "\n"),
            array('<nav> with attributes', '<nav ' . $all_attributes . '></nav>', '<nav ' . $allowed_attributes . '></nav>' . "\n"),
            array('<noframes> with attributes', '<noframes ' . $all_attributes . '></noframes>', '<p><noframes ' . $allowed_attributes . '></noframes></p>' . "\n"),
			array('<noscript> with attributes', '<noscript ' . $all_attributes . '></noscript>', '<p><noscript ' . $allowed_attributes . '></noscript></p>' . "\n"),
			array('<object> with attributes', '<object ' . $all_attributes . '></object>', '<p><object ' . $allowed_attributes . '></object></p>' . "\n"),
			array('<ol> with attributes', '<ol ' . $all_attributes . '></ol>', '<ol ' . $allowed_attributes . '></ol>' . "\n"),
            array('<optgroup> with attributes', '<optgroup ' . $all_attributes . '></optgroup>', '<p><optgroup ' . $allowed_attributes . '></optgroup></p>' . "\n"),
            array('<option> with attributes', '<option ' . $all_attributes . '></option>', '<p><option ' . $allowed_attributes .'></option></p>' . "\n"),
			array('<output> with attributes', '<output ' . $all_attributes . '></output>', '<p><output ' . $allowed_attributes . '></output></p>' . "\n"),
			array('<p> with attributes', '<p ' . $all_attributes . '></p>', '<p ' . $all_attributes . '></p>' . "\n"),
            array('<param> with attributes', '<param ' . $all_attributes . '></param>', '<p><param ' . $allowed_attributes . '></param></p>' . "\n"),
            array('<picture> with attributes', '<picture ' . $all_attributes . '></picture>', '<p><picture ' . $allowed_attributes . '></picture></p>' . "\n"),
			array('<pre> with attributes', '<pre ' . $all_attributes . '></pre>', '<pre ' . $all_attributes . '></pre>' . "\n"),
            array('<progress> with attributes', '<progress ' . $all_attributes . '></progress>', '<p><progress ' . $allowed_attributes . '></progress></p>' . "\n"),
			array('<q> with attributes', '<q ' . $all_attributes . '></q>', '<p><q ' . $allowed_attributes . '></q></p>' . "\n"),
            array('<rp> with attributes', '<rp ' . $all_attributes . '></rp>', '<p><rp ' . $allowed_attributes . '></rp></p>' . "\n"),
            array('<rt> with attributes', '<rt ' . $all_attributes . '></rt>', '<p><rt ' . $allowed_attributes . '></rt></p>' . "\n"),
            array('<ruby> with attributes', '<ruby ' . $all_attributes . '></ruby>', '<p><ruby ' . $allowed_attributes . '></ruby></p>' . "\n"),
            array('<s> with attributes', '<s ' . $all_attributes . '></s>', '<p><s ' . $allowed_attributes . '></s></p>' . "\n"),
			array('<samp> with attributes', '<samp ' . $all_attributes . '></samp>', '<p><samp ' . $allowed_attributes . '></samp></p>' . "\n"),
			array('<script> with attributes', '<script ' . $all_attributes . '></script>', '<script ' . $all_attributes . '></script>' . "\n"),
			array('<section> with attributes', '<section ' . $all_attributes . '></section>', '<section ' . $allowed_attributes . '></section>' . "\n"),
			array('<select> with attributes', '<select ' . $all_attributes . '></select>', '<p><select ' . $allowed_attributes . '></select></p>' . "\n"),
			array('<small> with attributes', '<small ' . $all_attributes . '></small>', '<p><small ' . $allowed_attributes . '></small></p>' . "\n"),
            array('<source> with attributes', '<source ' . $all_attributes . '></source>', '<p><source ' . $allowed_attributes . '></source></p>' . "\n"),
			array('<span> with attributes', '<span ' . $all_attributes . '></span>', '<p><span ' . $all_attributes . '></span></p>' . "\n"),
            array('<strike> with attributes', '<strike ' . $all_attributes . '></strike>', '<p><strike ' . $allowed_attributes . '></strike></p>' . "\n"),
			array('<strong> with attributes', '<strong ' . $all_attributes . '></strong>', '<p><strong ' . $allowed_attributes . '></strong></p>' . "\n"),
            array('<style> with attributes', '<style ' . $all_attributes . '></style>', '<style ' . $allowed_attributes . '></style>' . "\n"),
			array('<sub> with attributes', '<sub ' . $all_attributes . '></sub>', '<p><sub ' . $allowed_attributes . '></sub></p>' . "\n"),
            array('<summary> with attributes', '<summary ' . $all_attributes . '></summary>', '<p><summary ' . $allowed_attributes . '></summary></p>' . "\n"),
			array('<sup> with attributes', '<sup ' . $all_attributes . '></sup>', '<p><sup ' . $allowed_attributes . '></sup></p>' . "\n"),
			array('<table> with attributes', '<table ' . $all_attributes . '></table>', '<table ' . $allowed_attributes . '></table>' . "\n"),
            array('<tbody> with attributes', '<tbody ' . $all_attributes . '></tbody>', '<p><tbody ' . $allowed_attributes . '></tbody></p>' . "\n"),
            array('<td> with attributes', '<td ' . $all_attributes . '></td>', '<p><td ' . $allowed_attributes . '></td></p>' . "\n"),
			array('<textarea> with attributes', '<textarea ' . $all_attributes . '></textarea>', '<p><textarea ' . $allowed_attributes . '></textarea></p>' . "\n"),
            array('<tfoot> with attributes', '<tfoot ' . $all_attributes . '></tfoot>', '<p><tfoot ' . $allowed_attributes . '></tfoot></p>' . "\n"),
            array('<th> with attributes', '<th ' . $all_attributes . '></th>', '<p><th ' . $allowed_attributes . '></th></p>' . "\n"),
            array('<thead> with attributes', '<thead ' . $all_attributes . '></thead>', '<p><thead ' . $allowed_attributes . '></thead></p>' . "\n"),
            array('<time> with attributes', '<time ' . $all_attributes . '></time>', '<p><time ' . $allowed_attributes . '></time></p>' . "\n"),
            array('<title> with attributes', '<title ' . $all_attributes . '></title>', '<p><title ' . $allowed_attributes . '></title></p>' . "\n"),
            array('<tr> with attributes', '<tr ' . $all_attributes . '></tr>', '<p><tr ' . $allowed_attributes . '></tr></p>' . "\n"),
            array('<track> with attributes', '<track ' . $all_attributes . '></track>', '<p><track ' . $allowed_attributes .'></track></p>' . "\n"),
			array('<tt> with attributes', '<tt ' . $all_attributes . '></tt>', '<p><tt ' . $allowed_attributes . '></tt></p>' . "\n"),
            array('<u> with attributes', '<u ' . $all_attributes . '></u>', '<p><u ' . $allowed_attributes . '></u></p>' . "\n"),
			array('<ul> with attributes', '<ul ' . $all_attributes . '></ul>', '<ul ' . $allowed_attributes . '></ul>' . "\n"),
			array('<var> with attributes', '<var ' . $all_attributes . '></var>', '<p><var ' . $allowed_attributes . '></var></p>' . "\n"),
			array('<video> with attributes', '<video ' . $all_attributes . '></video>', '<p><video ' . $allowed_attributes . '></video></p>' . "\n"),
            array('<wbr> with attributes', '<wbr ' . $all_attributes . '></wbr>', '<p><wbr ' . $allowed_attributes . '></wbr></p>' . "\n"),
		);
	}

	protected function markdownData()
	{
		$data = array(
			// Automatic Escaping
			array('Ampersands', 'AT&T', "<p>AT&amp;T</p>\n"),
			array('HTML Entity', '&copy;', "<p>&copy;</p>\n"),
			array('Angle brackets', '4 < 5 and 3 > 4', "<p>4 &lt; 5 and 3 > 4</p>\n"),

			// Links
			// array('Link with title attribute', 'This is [an example](http://example.com/ "Title") inline link.', ""),
			array('Link without title attribute', '[This link](http://example.net/) has no title attribute.', "<p><a href=\"http://example.net/\">This link</a> has no title attribute.</p>\n"),
			array('Relative URLs', 'See my [About](/about/) page for details.', "<p>See my <a href=\"/about/\">About</a> page for details.</p>\n"),
			array('Refernce style link', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with space)', "This is [an example] [id] reference-style link.\n\n[id]: http://example.com/  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			// array('Refernce style link (with single quote)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  'Optional Title Here'", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with parenthesis)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/  (Optional Title Here)", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with angle brackets)', "This is [an example][id] reference-style link.\n\n[id]: <http://example.com/>  \"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style link (with title on newline)', "This is [an example][id] reference-style link.\n\n[id]: http://example.com/\n\t\"Optional Title Here\"\n", "<p>This is <a href=\"http://example.com/\" title=\"Optional Title Here\">an example</a> reference-style link.</p>\n"),
			array('Refernce style implicit link', "Visit [Daring Fireball][] for more information.\n\n[Daring Fireball]: http://daringfireball.net/", "<p>Visit <a href=\"http://daringfireball.net/\">Daring Fireball</a> for more information.</p>\n"),
			array('Automatic link', '<http://example.com>', '<p><a href="http://example.com">http://example.com</a></p>' . "\n"),
			array('Automatic email link', '<address@example.com>', '<p><a href="&#109;&#x61;&#x69;&#108;&#x74;&#x6f;&#58;&#x61;&#x64;&#100;&#114;&#x65;&#115;&#115;&#x40;&#101;&#120;&#x61;m&#112;&#x6c;e&#46;&#x63;&#x6f;&#109;">&#x61;&#x64;&#100;&#114;&#x65;&#115;&#115;&#x40;&#101;&#120;&#x61;m&#112;&#x6c;e&#46;&#x63;&#x6f;&#109;</a></p>' . "\n"),

			// Emphasis
			array('Single asterisks', '*single asterisks*', "<p><em>single asterisks</em></p>\n"),
			array('Single underscores', '_single underscores_', "<p><em>single underscores</em></p>\n"),
			array('Double asterisks', '**double asterisks**', "<p><strong>double asterisks</strong></p>\n"),
			array('Double underscores', '__double underscores__', "<p><strong>double underscores</strong></p>\n"),
			array('Single asterisks in the middle of a word', 'un*frigging*believable', "<p>un<em>frigging</em>believable</p>\n"),
			array('Double asterisks in the middle of a word', 'un**frigging**believable', "<p>un<strong>frigging</strong>believable</p>\n"),
			array('Literal asterisk', '8 * 7 = 56', "<p>8 * 7 = 56</p>\n"),
			array('Literal underscore', 'Literal _ underscore', "<p>Literal _ underscore</p>\n"),
			array('Escaped asterisk', '\*this text is surrounded by literal asterisks\*', "<p>&#42;this text is surrounded by literal asterisks&#42;</p>\n"),
			array('Escaped underscore', '\_this text is surrounded by literal asterisks\_', "<p>&#95;this text is surrounded by literal asterisks&#95;</p>\n"),

			// Code
			array('Span of code', 'Use the `printf()` function.', "<p>Use the <code>printf()</code> function.</p>\n"),
			array('Literal backtick', '``There is a literal backtick (`) here.``', "<p><code>There is a literal backtick (`) here.</code></p>\n"),
			array('Encoded angle brackets inside code span', "Please don't use any `<blink>` tags.", "<p>Please don&#8217;t use any <code>&lt;blink&gt;</code> tags.</p>\n"),
			array('Encoded ampersands inside code span', '`&#8212;` is the decimal-encoded equivalent of `&mdash;`.', "<p><code>&amp;#8212;</code> is the decimal-encoded equivalent of <code>&amp;mdash;</code>.</p>\n"),

			// Images
			array('Image tag', '![Alt text](/path/to/img.jpg)', "<p><img src=\"/path/to/img.jpg\" alt=\"Alt text\" /></p>\n"),
			// array('Image tag with title', '![Alt text](/path/to/img.jpg "Optional title")', "\n"),
			array('Reference style image tag', "![Alt text][id]\n\n[id]: url/to/image  \"Optional title attribute\"\n", "<p><img src=\"url/to/image\" alt=\"Alt text\" title=\"Optional title attribute\" /></p>\n"),

			// Escapes
			array('Escaped backslash', '\\\\', "<p>&#92;</p>\n"),
			array('Escaped backtick', '\`', "<p>&#96;</p>\n"),
			array('Escaped asterisk', '\*', "<p>&#42;</p>\n"),
			array('Escaped underscore', '\_', "<p>&#95;</p>\n"),
			array('Escaped curly braces', '\{\}', "<p>&#123;&#125;</p>\n"),
			array('Escaped square brackets', '\[\]', "<p>&#91;&#93;</p>\n"),
			array('Escaped parentheses', '\(\)', "<p>&#40;&#41;</p>\n"),
			array('Escaped hash mark', '\#', "<p>&#35;</p>\n"),
			array('Escaped plus sign', '\+', "<p>&#43;</p>\n"),
			array('Escaped hyphen', '\-', "<p>&#45;</p>\n"),
			array('Escaped dot', '\.', "<p>&#46;</p>\n"),
			array('Escaped exclamation mark', '\!', "<p>&#33;</p>\n"),

			// Horizontal rules
			array('HR by "* * *"', '* * *', "<hr />\n"),
			array('HR by "***"', '***', "<hr />\n"),
			array('HR by "*****"', '*****', "<hr />\n"),
			array('HR by "---"', '---', "<hr />\n"),
			array('HR by "- - -"', '- - -', "<hr />\n"),
			array('HR by "-----"', '-----', "<hr />\n"),
			array('HR by "___"', '___', "<hr />\n"),
			array('HR by "_ _ _"', '_ _ _', "<hr />\n"),
			array('HR by "_____"', '_____', "<hr />\n"),

			// Headers
			array('# H1', '# This is an H1', "<h1>This is an H1</h1>\n"),
			array('## H2', '## This is an H2', "<h2>This is an H2</h2>\n"),
			array('### H3', '### This is an H3', "<h3>This is an H3</h3>\n"),
			array('#### H4', '#### This is an H4', "<h4>This is an H4</h4>\n"),
			array('##### H5', '##### This is an H5', "<h5>This is an H5</h5>\n"),
			array('###### H6', '###### This is an H6', "<h6>This is an H6</h6>\n"),
			array('# H1 #', '# This is an H1 #', "<h1>This is an H1</h1>\n"),
			array('## H2 ##', '## This is an H2 ##', "<h2>This is an H2</h2>\n"),
			array('### H3 ###', '### This is an H3 ###', "<h3>This is an H3</h3>\n"),
			array('#### H4 ####', '#### This is an H4 ####', "<h4>This is an H4</h4>\n"),
			array('##### H5 #####', '##### This is an H5 #####', "<h5>This is an H5</h5>\n"),
			array('###### H6 ######', '###### This is an H6 ######', "<h6>This is an H6</h6>\n"),
			array('H1 by underscore', "This is an H1\n=============", "<h1>This is an H1</h1>\n"),
			array('H2 by underscore', "This is an H2\n-------------", "<h2>This is an H2</h2>\n"),

			// Blockquotes
			array('Email style blockquote', $this->getContentForMarkup('email-style-blockquote.in.md'), $this->getContentForMarkup('email-style-blockquote.out.md')),
			array('Lazy style blockquote', $this->getContentForMarkup('lazy-style-blockquote.in.md'), $this->getContentForMarkup('lazy-style-blockquote.out.md')),
			array('Nested blockquotes', $this->getContentForMarkup('nested-blockquotes.in.md'), $this->getContentForMarkup('nested-blockquotes.out.md')),
			array('Markdown inside blockquote', $this->getContentForMarkup('markdown-in-blockquote.in.md'), $this->getContentForMarkup('markdown-in-blockquote.out.md')),

			// Lists
			array('List by asterisk', $this->getContentForMarkup('list-by-asterisk.in.md'), $this->getContentForMarkup('list-by-asterisk.out.md')),
			array('List by plus', $this->getContentForMarkup('list-by-plus.in.md'), $this->getContentForMarkup('list-by-plus.out.md')),
			array('List by hyphen', $this->getContentForMarkup('list-by-hyphen.in.md'), $this->getContentForMarkup('list-by-hyphen.out.md')),
			array('Ordered list', $this->getContentForMarkup('ordered-list.in.md'), $this->getContentForMarkup('ordered-list.out.md')),
			array('Wrapped lists', $this->getContentForMarkup('wrapped-lists.in.md'), $this->getContentForMarkup('wrapped-lists.out.md')),
			array('Lists with paragraph tags', $this->getContentForMarkup('lists-with-paragraph-tags.in.md'), $this->getContentForMarkup('lists-with-paragraph-tags.out.md')),
			array('Lists with paragraphs', $this->getContentForMarkup('lists-with-paragraphs.in.md'), $this->getContentForMarkup('lists-with-paragraphs.out.md')),
			array('Lists with blockquotes', $this->getContentForMarkup('lists-with-blockquotes.in.md'), $this->getContentForMarkup('lists-with-blockquotes.out.md')),
			array('Lists with code blocks', $this->getContentForMarkup('lists-with-code-blocks.in.md'), $this->getContentForMarkup('lists-with-code-blocks.out.md')),
			array('Not a list', '1986\. What a great season.', "<p>1986&#46; What a great season.</p>\n"),

			// Code blocks
			array('Code block by 4 spaces', $this->getContentForMarkup('codeblock-by-4-spaces.in.md'), $this->getContentForMarkup('codeblock-by-4-spaces.out.md')),
			array('Code block by 5 spaces', $this->getContentForMarkup('codeblock-by-5-spaces.in.md'), $this->getContentForMarkup('codeblock-by-5-spaces.out.md')),
			array('Code block by 1 tab', $this->getContentForMarkup('codeblock-by-1-tab.in.md'), $this->getContentForMarkup('codeblock-by-1-tab.out.md')),
			array('Code block by 2 tabs', $this->getContentForMarkup('codeblock-by-2-tabs.in.md'), $this->getContentForMarkup('codeblock-by-2-tabs.out.md')),
			array('Code block with encoded ampersands', $this->getContentForMarkup('codeblock-with-encoded-ampersands.in.md'), $this->getContentForMarkup('codeblock-with-encoded-ampersands.out.md')),
			array('Code block with encoded angle brackets', $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.in.md'), $this->getContentForMarkup('codeblock-with-encoded-angle-brackets.out.md')),
		);

		return array_merge($data, $this->markdownExtraData());
	}

	protected function markdownExtraData()
	{
		return array(
			array('Markdown inside HTML blocks', $this->getContentForMarkup('markdown-inside-html-blocks.in.md'), $this->getContentForMarkup('markdown-inside-html-blocks.out.md')),

			// Special Attributes
			array('Header: ID', '## Header 2 {#header2}', "<h2 id=\"header2\">Header 2</h2>\n"),
			array('Header: Class names', '## Header 2 {.main}', "<h2 class=\"main\">Header 2</h2>\n"),
			array('Header: Custom attributes', '## Le Header 2 {lang=fr}', "<h2 lang=\"fr\">Le Header 2</h2>\n"),
			array('Header: Multiple attributes', '## Le Header 2 {.main .shine lang=fr #header2}', "<h2 id=\"header2\" class=\"main shine\" lang=\"fr\">Le Header 2</h2>\n"),
			array('Link: ID', '[link](/url){#header2}', "<p><a href=\"/url\" title=\"\" id=\"header2\">link</a></p>\n"),
			array('Link: Class names', '[link](/url){.main}', "<p><a href=\"/url\" title=\"\" class=\"main\">link</a></p>\n"),
			array('Link: Custom attributes', '[link](/url){lang=fr}', "<p><a href=\"/url\" title=\"\" lang=\"fr\">link</a></p>\n"),
			array('Link: Multiple attributes', '[link](/url){.main .shine lang=fr #header2}', "<p><a href=\"/url\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\">link</a></p>\n"),
			array('Reference Link: ID', "[link][linkref]\n\n[linkref]: /url {#header2}", "<p><a href=\"/url\" title=\"\" id=\"header2\">link</a></p>\n"),
			array('Reference Link: Class names', "[link][linkref]\n\n[linkref]: /url {.main}", "<p><a href=\"/url\" title=\"\" class=\"main\">link</a></p>\n"),
			array('Reference Link: Custom attributes', "[link][linkref]\n\n[linkref]: /url {lang=fr}", "<p><a href=\"/url\" title=\"\" lang=\"fr\">link</a></p>\n"),
			array('Reference Link: Multiple attributes', "[link][linkref]\n\n[linkref]: /url {.main .shine lang=fr #header2}", "<p><a href=\"/url\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\">link</a></p>\n"),
			array('Image: ID', '![link](/url){#header2}', "<p><img src=\"/url\" alt=\"link\" title=\"\" id=\"header2\" /></p>\n"),
			array('Image: Class names', '![link](/url){.main}', "<p><img src=\"/url\" alt=\"link\" title=\"\" class=\"main\" /></p>\n"),
			array('Image: Custom attributes', '![link](/url){lang=fr}', "<p><img src=\"/url\" alt=\"link\" title=\"\" lang=\"fr\" /></p>\n"),
			array('Image: Multiple attributes', '![link](/url){.main .shine lang=fr #header2}', "<p><img src=\"/url\" alt=\"link\" title=\"\" id=\"header2\" class=\"main shine\" lang=\"fr\" /></p>\n"),
			array('Fenced code block: ID', "~~~ {#header2}\ncode block\n~~~\n", "<pre><code id=\"header2\">code block\n</code></pre>\n"),
			array('Fenced code block: Class names', "~~~ {.main}\ncode block\n~~~\n", "<pre><code class=\"main\">code block\n</code></pre>\n"),
			array('Fenced code block: Custom attributes', "~~~ {lang=fr}\ncode block\n~~~\n", "<pre><code lang=\"fr\">code block\n</code></pre>\n"),
			array('Fenced code block: Multiple attributes', "~~~ {.main .shine lang=fr #header2}\ncode block\n~~~\n", "<pre><code id=\"header2\" class=\"main shine\" lang=\"fr\">code block\n</code></pre>\n"),

			// Fenced Code Blocks
			array('Fenced code block by 3 tildes', $this->getContentForMarkup('codeblock-by-3-tildes.in.md'), $this->getContentForMarkup('codeblock-by-3-tildes.out.md')),
			array('Fenced code block by 4 tildes', $this->getContentForMarkup('codeblock-by-4-tildes.in.md'), $this->getContentForMarkup('codeblock-by-4-tildes.out.md')),
			array('Fenced code block by 3 backticks', $this->getContentForMarkup('codeblock-by-3-backticks.in.md'), $this->getContentForMarkup('codeblock-by-3-backticks.out.md')),
			array('Fenced code block by 4 backticks', $this->getContentForMarkup('codeblock-by-4-backticks.in.md'), $this->getContentForMarkup('codeblock-by-4-backticks.out.md')),
			// array('Fenced code block beginning and ending with blank lines', $this->getContentForMarkup('codeblock-begin-end-blank-lines.in.md'), $this->getContentForMarkup('codeblock-begin-end-blank-lines.out.md')),
			array('Fenced code block after a list', $this->getContentForMarkup('codeblock-after-list.in.md'), $this->getContentForMarkup('codeblock-after-list.out.md')),

			// Tables
			array('Table', $this->getContentForMarkup('table.in.md'), $this->getContentForMarkup('table.out.md')),
			array('Table with leading and tailing pipes', $this->getContentForMarkup('table-with-pipes.in.md'), $this->getContentForMarkup('table-with-pipes.out.md')),
			array('Table with alignment', $this->getContentForMarkup('table-with-alignment.in.md'), $this->getContentForMarkup('table-with-alignment.out.md')),
			array('Table with span-level formatting', $this->getContentForMarkup('table-with-formatting.in.md'), $this->getContentForMarkup('table-with-formatting.out.md')),

			// Definition Lists
			array('Definition list', $this->getContentForMarkup('definition-list.in.md'), $this->getContentForMarkup('definition-list.out.md')),
			array('Definition list wrapped', $this->getContentForMarkup('definition-list-wrapped.in.md'), $this->getContentForMarkup('definition-list-wrapped.out.md')),
			array('Definition list indented', $this->getContentForMarkup('definition-list-indented.in.md'), $this->getContentForMarkup('definition-list-indented.out.md')),
			array('Definition list multiple definitions', $this->getContentForMarkup('definition-list-multiple.in.md'), $this->getContentForMarkup('definition-list-multiple.out.md')),
			array('Definition list with paragraph tags', $this->getContentForMarkup('definition-list-with-paragraph-tags.in.md'), $this->getContentForMarkup('definition-list-with-paragraph-tags.out.md')),
			array('Definition list with multiple paragraphs', $this->getContentForMarkup('definition-list-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('definition-list-with-multiple-paragraphs.out.md')),

			// Footnotes
			array('Footnote first', $this->getContentForMarkup('footnote-first.in.md'), $this->getContentForMarkup('footnote-first.out.md')),
			array('Footnote intermingled', $this->getContentForMarkup('footnote-intermingled.in.md'), $this->getContentForMarkup('footnote-intermingled.out.md')),
			array('Footnote last', $this->getContentForMarkup('footnote-last.in.md'), $this->getContentForMarkup('footnote-last.out.md')),
			array('Footnote with multiple paragraphs', $this->getContentForMarkup('footnote-with-multiple-paragraphs.in.md'), $this->getContentForMarkup('footnote-with-multiple-paragraphs.out.md')),

			// Abbreviations
			array('Abbreviation definition first', "*[HTML]: Hyper Text Markup Language\n\nThe HTML specification", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n"),
			array('Abbreviation definition middle', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language\n\nis dry", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n\n<p>is dry</p>\n"),
			array('Abbreviation definition last', "The HTML specification\n\n*[HTML]: Hyper Text Markup Language", "<p>The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification</p>\n"),
			array('Multiword abbreviation', "*[Foo Bar]: Fubar\n\nI saw a Foo Bar once", "<p>I saw a <abbr title=\"Fubar\">Foo Bar</abbr> once</p>\n"),
			array('Empty abbreviateion', "Operation Tigra Genesis is going well.\n\n*[Tigra Genesis]:", "<p>Operation <abbr>Tigra Genesis</abbr> is going well.</p>\n"),

			array('Single underscores in the middle of a word', 'un_frigging_believable', "<p>un_frigging_believable</p>\n"),
			array('Double underscores in the middle of a word', 'un__frigging__believable', "<p>un__frigging__believable</p>\n"),
		);
	}

	protected function BBCodeData()
	{
		return array(
            array('[abbr] tag', '[abbr="Cascading Style Sheets"]CSS[/abbr]', '<p><abbr title="Cascading Style Sheets">CSS</abbr></p>' . "\n"),
            array('[abbr] tag with property', '[abbr title="Cascading Style Sheets"]CSS[/abbr]', '<p><abbr title="Cascading Style Sheets">CSS</abbr></p>' . "\n"),
            array('[b] tag', '[b]some bold text[/b]', '<p><b>some bold text</b></p>' . "\n"),
            array('[blockquote] tag', '[blockquote]Some text. blah, blah, blah...[/blockquote]', "<blockquote>Some text. blah, blah, blah&#8230;</blockquote>\n"),
            // array('[cite] tag', '[cite="some place"]some text[/cite]', '' . "\n"),
            // array('[code] tag', '[code]Some pre-formatted text...[/code]', '<p><code>Some pre-formatted text...</code></p>' . "\n"),
            array('[color] tag', '[color=green]Some green text[/color]', '<p><span style="color:green;">Some green text</span></p>' . "\n"),
            array('[del] tag', 'This is [del]very[/del] exciting.', '<p>This is <del>very</del> exciting.</p>' . "\n"),
            array('[em] tag', '[em]some em text[/em]', '<p><em>some em text</em></p>' . "\n"),
            // array('[email] tag', '[email]you@example.com[/email]', "<span data-eeEncEmail_qqaBvHJmAg='1'>.encoded_email</span><script type=\"text/javascript\">/*<![CDATA[*/var out = '',el = document.getElementsByTagName('span' . "\n"),l = ['>','a','/','<',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121','>','\"',' 109',' 111',' 99',' 46',' 101',' 108',' 112',' 109',' 97',' 120',' 101',' 64',' 117',' 111',' 121',':','o','t','l','i','a','m','\\\"','=','f','e','r','h','a ','<'],i = l.length,j = el.length;while (--i >= 0)out += unescape(l[i].replace(/^\s\s*/, '&#'));while (--j >= 0)if (el[j].getAttribute('data-eeEncEmail_qqaBvHJmAg'))el[j].innerHTML = out;/*]]>*/</script>"),
            // array('[email] tag with value', '[email=you@example.com]click here to email[/email]', '' . "\n"),
            array('[h2] tag', '[h2]some text[/h2]', '<h2>some text</h2>' . "\n"),
            array('[h3] tag', '[h3]some text[/h3]', '<h3>some text</h3>' . "\n"),
            array('[h4] tag', '[h4]some text[/h4]', '<h4>some text</h4>' . "\n"),
            array('[h5] tag', '[h5]some text[/h5]', '<h5>some text</h5>' . "\n"),
            array('[h6] tag', '[h6]some text[/h6]', '<h6>some text</h6>' . "\n"),
            array('[i] tag', '[i]some italic text[/i]', '<p><i>some italic text</i></p>' . "\n"),
            // array('[img] tag', '[img]http://example.com/pic.jpg[/img]', '' . "\n"),
            array('[ins] tag', '[ins]some text[/ins]', '<p><ins>some text</ins></p>' . "\n"),
            array('[mark] tag', '[mark]some text[/mark]', '<p><mark>some text</mark></p>' . "\n"),
            array('[pre] tag', '[pre]Some pre-formatted text...[/pre]', '<pre>Some pre-formatted text...</pre>' . "\n"),
            array('[quote] tag', '[quote]Some text. blah, blah, blah...[/quote]', "<blockquote>Some text. blah, blah, blah&#8230;</blockquote>\n"),
            array('[size=1] tag', '[size=1]some text[/size]', '<p><span style="font-size:9px;">some text</span></p>' . "\n"),
            array('[size=2] tag', '[size=2]some text[/size]', '<p><span style="font-size:11px;">some text</span></p>' . "\n"),
            array('[size=3] tag', '[size=3]some text[/size]', '<p><span style="font-size:14px;">some text</span></p>' . "\n"),
            array('[size=4] tag', '[size=4]some text[/size]', '<p><span style="font-size:16px;">some text</span></p>' . "\n"),
            array('[size=5] tag', '[size=5]some text[/size]', '<p><span style="font-size:18px;">some text</span></p>' . "\n"),
            array('[size=6] tag', '[size=6]some text[/size]', '<p><span style="font-size:20px;">some text</span></p>' . "\n"),
            array('[span] tag', '[span]some text[/span]', '<p><span>some text</span></p>' . "\n"),
            array('[strike] tag', '[strike]some text[/strike]', '<p><del>some text</del></p>' . "\n"),
            array('[strong] tag', '[strong]some strong text[/strong]', '<p><strong>some strong text</strong></p>' . "\n"),
            array('[style] tag', '[style=class_name]your content[/style]', '<p><span class="class_name">your content</span></p>' . "\n"),
            array('[sub] tag', '[sub]some text[/sub]', '<p><sub>some text</sub></p>' . "\n"),
            array('[sup] tag', '[sup]some text[/sup]', '<p><sup>some text</sup></p>' . "\n"),
            array('[u] tag', '[u]some underlined text[/u]', '<p><em>some underlined text</em></p>' . "\n"),
            array('[url] tag', '[url]http://example.com/[/url]', '<p><a href="http://example.com/">http://example.com/</a></p>' . "\n"),
            array('[url] tag with value', '[url=http://example.com/]my site[/url]', '<p><a href="http://example.com/">my site</a></p>' . "\n"),
            array('[url] tag with value and property', '[url=http://example.com/ class="link"]my site[/url]', '<p><a href="http://example.com/" class="link">my site</a></p>' . "\n"),
		);
	}

}

// EOF
