<?php
/**
 * ExpressionEngine - by EllisLab
 *
 * @package		ExpressionEngine
 * @author		ExpressionEngine Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://expressionengine.com/user_guide/license.html
 * @link		http://expressionengine.com
 * @since		Version 2.0
 * @filesource
 */
 
// ------------------------------------------------------------------------

/**
 * ExpressionEngine Country Codes
 *
 * @package		ExpressionEngine
 * @subpackage	Config
 * @category	Config
 * @author		ExpressionEngine Dev Team
 * @link		http://expressionengine.com
 */
$countries = array(
					'af' => 'Afghanistan',
					'ax' => 'Aland Islands',
					'al' => 'Albania',
					'dz' => 'Algeria',
					'as' => 'American Samoa',
					'ad' => 'Andorra',
					'ao' => 'Angola',
					'ai' => 'Anguilla',
					'aq' => 'Antarctica',
					'ag' => 'Antigua and Barbuda',
					'ar' => 'Argentina',
					'am' => 'Armenia',
					'aw' => 'Aruba',
					'ap' => 'Asia-Pacific',
					'au' => 'Australia',
					'at' => 'Austria',
					'az' => 'Azerbaijan',
					'bs' => 'Bahamas',
					'bh' => 'Bahrain',
					'bd' => 'Bangladesh',
					'bb' => 'Barbados',
					'by' => 'Belarus',
					'be' => 'Belgium',
					'bz' => 'Belize',
					'bj' => 'Benin',
					'bm' => 'Bermuda',
					'bt' => 'Bhutan',
					'bo' => 'Bolivia',
					'ba' => 'Bosnia and Herzegovina',
					'bw' => 'Botswana',
					'bv' => 'Bouvet Island',
					'br' => 'Brazil',
					'io' => 'British Indian Ocean Territory',
					'bn' => 'Brunei Darussalam',
					'bg' => 'Bulgaria',
					'bf' => 'Burkina Faso',
					'mm' => 'Burma (Myanmar)',
					'bi' => 'Burundi',
					'kh' => 'Cambodia',
					'cm' => 'Cameroon',
					'ca' => 'Canada',
					'cv' => 'Cape Verde',
					'ky' => 'Cayman Islands',
					'cf' => 'Central African Republic',
					'td' => 'Chad',
					'cl' => 'Chile',
					'cn' => 'China',
					'cx' => 'Christmas Island',
					'cc' => 'Cocos (Keeling) Islands',
					'co' => 'Colombia',
					'km' => 'Comoros',
					'cg' => 'Congo',
					'ck' => 'Cook Islands',
					'cr' => 'Costa Rica',
					'hr' => 'Croatia (Hrvatska)',
					'cu' => 'Cuba',
					'cy' => 'Cyprus',
					'cz' => 'Czech Republic',
					'cs' => 'Czechoslovakia (former)',
					'cd' => 'Democratic Republic of Congo',
					'dk' => 'Denmark',
					'dj' => 'Djibouti',
					'dm' => 'Dominica',
					'do' => 'Dominican Republic',
					'ec' => 'Ecuador',
					'eg' => 'Egypt',
					'sv' => 'El Salvador',
					'gq' => 'Equatorial Guinea',
					'er' => 'Eritrea',
					'ee' => 'Estonia',
					'et' => 'Ethiopia',
					'eu' => 'Europe',
					'fk' => 'Falkland Islands (Malvinas)',
					'fo' => 'Faroe Islands',
					'fj' => 'Fiji',
					'fi' => 'Finland',
					'fr' => 'France',
					'gf' => 'French Guiana',
					'pf' => 'French Polynesia',
					'tf' => 'French Southern Territories',
					'ga' => 'Gabon',
					'gm' => 'Gambia',
					'ge' => 'Georgia',
					'de' => 'Germany',
					'gh' => 'Ghana',
					'gi' => 'Gibraltar',
					'gb' => 'Great Britain (UK)',
					'gr' => 'Greece',
					'gl' => 'Greenland',
					'gd' => 'Grenada',
					'gp' => 'Guadeloupe',
					'gu' => 'Guam',
					'gt' => 'Guatemala',
					'gn' => 'Guinea',
					'gw' => 'Guinea-Bissau',
					'gy' => 'Guyana',
					'ht' => 'Haiti',
					'hm' => 'Heard and McDonald Islands',
					'hn' => 'Honduras',
					'hk' => 'Hong Kong',
					'hu' => 'Hungary',
					'is' => 'Iceland',
					'in' => 'India',
					'id' => 'Indonesia',
					'ir' => 'Iran',
					'iq' => 'Iraq',
					'ie' => 'Ireland',
					'il' => 'Israel',
					'it' => 'Italy',
					'ci' => 'Ivory Coast',
					'jm' => 'Jamaica',
					'jp' => 'Japan',
					'jo' => 'Jordan',
					'kz' => 'Kazakhstan',
					'ke' => 'Kenya',
					'ki' => 'Kiribati',
					'kp' => 'Korea (North)',
					'kr' => 'Korea (South)',
					'kw' => 'Kuwait',
					'kg' => 'Kyrgyzstan',
					'la' => 'Laos',
					'lv' => 'Latvia',
					'lb' => 'Lebanon',
					'ls' => 'Lesotho',
					'lr' => 'Liberia',
					'ly' => 'Libya',
					'li' => 'Liechtenstein',
					'lt' => 'Lithuania',
					'lu' => 'Luxembourg',
					'mo' => 'Macau',
					'mk' => 'Macedonia',
					'mg' => 'Madagascar',
					'mw' => 'Malawi',
					'my' => 'Malaysia',
					'mv' => 'Maldives',
					'ml' => 'Mali',
					'mt' => 'Malta',
					'mh' => 'Marshall Islands',
					'mq' => 'Martinique',
					'mr' => 'Mauritania',
					'mu' => 'Mauritius',
					'yt' => 'Mayotte',
					'mx' => 'Mexico',
					'fm' => 'Micronesia',
					'md' => 'Moldova',
					'mc' => 'Monaco',
					'mn' => 'Mongolia',
					'ms' => 'Montserrat',
					'ma' => 'Morocco',
					'mz' => 'Mozambique',
					'na' => 'Namibia',
					'nr' => 'Nauru',
					'np' => 'Nepal',
					'nl' => 'Netherlands',
					'an' => 'Netherlands Antilles',
					'nt' => 'Neutral Zone',
					'nc' => 'New Caledonia',
					'nz' => 'New Zealand (Aotearoa)',
					'ni' => 'Nicaragua',
					'ne' => 'Niger',
					'ng' => 'Nigeria',
					'nu' => 'Niue',
					'nf' => 'Norfolk Island',
					'mp' => 'Northern Mariana Islands',
					'no' => 'Norway',
					'om' => 'Oman',
					'pk' => 'Pakistan',
					'ps' => 'Palestinian Territory, Occupied',
					'pw' => 'Palau',
					'pa' => 'Panama',
					'pg' => 'Papua New Guinea',
					'py' => 'Paraguay',
					'pe' => 'Peru',
					'ph' => 'Philippines',
					'pn' => 'Pitcairn',
					'pl' => 'Poland',
					'pt' => 'Portugal',
					'01' => 'Private',
					'pr' => 'Puerto Rico',
					'qa' => 'Qatar',
					're' => 'Reunion',
					'rs' => 'Republic of Serbia',
					'ro' => 'Romania',
					'ru' => 'Russia',
					'rw' => 'Rwanda',
					'gs' => 'S. Georgia and S. Sandwich Isls.',
					'kn' => 'Saint Kitts and Nevis',
					'lc' => 'Saint Lucia',
					'vc' => 'Saint Vincent and the Grenadines',
					'ws' => 'Samoa',
					'sm' => 'San Marino',
					'st' => 'Sao Tome and Principe',
					'sa' => 'Saudi Arabia',
					'sn' => 'Senegal',
					'sc' => 'Seychelles',
					'sl' => 'Sierra Leone',
					'sg' => 'Singapore',
					'sk' => 'Slovak Republic',
					'si' => 'Slovenia',
					'sb' => 'Solomon Islands',
					'so' => 'Somalia',
					'za' => 'South Africa',
					'es' => 'Spain',
					'lk' => 'Sri Lanka',
					'sh' => 'St. Helena',
					'pm' => 'St. Pierre and Miquelon',
					'sd' => 'Sudan',
					'sr' => 'Suriname',
					'sj' => 'Svalbard and Jan Mayen Islands',
					'sz' => 'Swaziland',
					'se' => 'Sweden',
					'ch' => 'Switzerland',
					'sy' => 'Syria',
					'tw' => 'Taiwan',
					'tj' => 'Tajikistan',
					'tz' => 'Tanzania',
					'th' => 'Thailand',
					'tl' => 'Timor-Leste',
					'tg' => 'Togo',
					'tk' => 'Tokelau',
					'to' => 'Tonga',
					'tt' => 'Trinidad and Tobago',
					'tn' => 'Tunisia',
					'tr' => 'Turkey',
					'tm' => 'Turkmenistan',
					'tc' => 'Turks and Caicos Islands',
					'tv' => 'Tuvalu',
					'ug' => 'Uganda',
					'ua' => 'Ukraine',
					'ae' => 'United Arab Emirates',
					'uk' => 'United Kingdom',
					'us' => 'United States',
					'uy' => 'Uruguay',
					'uz' => 'Uzbekistan',
					'vu' => 'Vanuatu',
					'va' => 'Vatican City State (Holy See)',
					've' => 'Venezuela',
					'vn' => 'Viet Nam',
					'vg' => 'Virgin Islands (British)',
					'vi' => 'Virgin Islands (U.S.)',
					'wf' => 'Wallis and Futuna Islands',
					'eh' => 'Western Sahara',
					'ye' => 'Yemen',
					'yu' => 'Yugoslavia',
					'zm' => 'Zambia',
					'zw' => 'Zimbabwe'
);


/* End of file countries.php */
/* Location: ./system/expressionengine/config/countries.php */