/*!
// ----------------------------------------------------------------------------
// markItUp! Universal MarkUp Engine, JQuery plugin
// v 1.1.7
// Dual licensed under the MIT and GPL licenses.
// ----------------------------------------------------------------------------
// Copyright (C) 2007-2010 Jay Salvat
// http://markitup.jaysalvat.com/
// ----------------------------------------------------------------------------
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// ----------------------------------------------------------------------------
*/

(function(b){b.fn.markItUp=function(s,q){var c,j,k,t;j=k=t=false;c={id:"",nameSpace:"",root:"",previewInWindow:"",previewAutoRefresh:true,previewPosition:"after",previewTemplatePath:"~/templates/preview.html",previewParserPath:"",previewParserVar:"data",resizeHandle:true,beforeInsert:"",afterInsert:"",onEnter:{},onShiftEnter:{},onCtrlEnter:{},onTab:{},markupSet:[{}]};b.extend(c,s,q);c.root||b("script").each(function(v,y){miuScript=b(y).get(0).src.match(/(.*)jquery\.markitup(\.pack)?\.js$/);if(miuScript!==
null)c.root=miuScript[1]});return this.each(function(){function v(a,d){if(d)return a.replace(/("|')~\//g,"$1"+c.root);return a.replace(/^~\//,c.root)}function y(a){var d=b("<ul></ul>"),g=0;b("li:hover > ul",d).css("display","block");b.each(a,function(){var e=this,n="",z,A;z=e.key?(e.name||"")+" [Ctrl+"+e.key+"]":e.name||"";key=e.key?'accesskey="'+e.key+'"':"";if(e.separator)n=b('<li class="markItUpSeparator">'+(e.separator||"")+"</li>").appendTo(d);else{g++;for(A=w.length-1;A>=0;A--)n+=w[A]+"-";n=
b('<li class="markItUpButton markItUpButton'+n+g+" "+(e.className||"")+'"><a href="" '+key+' title="'+z+'">'+(e.name||"")+"</a></li>").bind("contextmenu",function(){return false}).click(function(){return false}).mousedown(function(){e.call&&eval(e.call)();setTimeout(function(){u(e)},1);return false}).hover(function(){b("> ul",this).show();b(document).one("click",function(){b("ul ul",B).hide()})},function(){b("> ul",this).hide()}).appendTo(d);if(e.dropMenu){w.push(g);b(n).addClass("markItUpDropMenu").append(y(e.dropMenu))}}});
w.pop();return d}function L(a){if(a){a=a.toString();a=a.replace(/\(\!\(([\s\S]*?)\)\!\)/g,function(d,g){var e=g.split("|!|");return t===true?e[1]!==undefined?e[1]:e[0]:e[1]===undefined?"":e[0]});return a=a.replace(/\[\!\[([\s\S]*?)\]\!\]/g,function(d,g){var e=g.split(":!:");if(x===true)return false;value=prompt(e[0],e[1]?e[1]:"");if(value===null)x=true;return value})}return""}function l(a){if(b.isFunction(a))a=a(r);return L(a)}function C(a){openWith=l(o.openWith);placeHolder=l(o.placeHolder);replaceWith=
l(o.replaceWith);closeWith=l(o.closeWith);block=replaceWith!==""?openWith+replaceWith+closeWith:selection===""&&placeHolder!==""?openWith+placeHolder+closeWith:openWith+(a||selection)+closeWith;return{block:block,openWith:openWith,replaceWith:replaceWith,placeHolder:placeHolder,closeWith:closeWith}}function u(a){var d,g;r=o=a;D();b.extend(r,{line:"",root:c.root,textarea:i,selection:selection||"",caretPosition:h,ctrlKey:j,shiftKey:k,altKey:t});l(c.beforeInsert);l(o.beforeInsert);j===true&&k===true&&
l(o.beforeMultiInsert);b.extend(r,{line:1});if(j===true&&k===true){lines=selection.split(/\r?\n/);a=0;d=lines.length;for(g=0;g<d;g++)if(b.trim(lines[g])!==""){b.extend(r,{line:++a,selection:lines[g]});lines[g]=C(lines[g]).block}else lines[g]="";string={block:lines.join("\n")};start=h;a=string.block.length+(b.browser.opera?d:0)}else if(j===true){string=C(selection);start=h+string.openWith.length;a=string.block.length-string.openWith.length-string.closeWith.length;a-=F(string.block)}else if(k===true){string=
C(selection);start=h;a=string.block.length;a-=F(string.block)}else{string=C(selection);start=h+string.block.length;a=0;start-=F(string.block)}if(selection===""&&string.replaceWith===""){m+=G(string.block);start=h+string.openWith.length;a=string.block.length-string.openWith.length-string.closeWith.length;m=f.val().substring(h,f.val().length).length;m-=G(f.val().substring(0,h))}b.extend(r,{caretPosition:h,scrollPosition:E});if(string.block!==selection&&x===false){d=string.block;if(document.selection)document.selection.createRange().text=
d;else f.val(f.val().substring(0,h)+d+f.val().substring(h+selection.length,f.val().length));H(start,a)}else m=-1;D();b.extend(r,{line:"",selection:selection});j===true&&k===true&&l(o.afterMultiInsert);l(o.afterInsert);l(c.afterInsert);p&&c.previewAutoRefresh&&M();k=t=j=x=false}function G(a){if(b.browser.opera)return a.length-a.replace(/\n*/g,"").length;return 0}function F(a){if(b.browser.msie)return a.length-a.replace(/\r*/g,"").length;return 0}function H(a,d){if(i.createTextRange){if(b.browser.opera&&
b.browser.version>=9.5&&d==0)return false;range=i.createTextRange();range.collapse(true);range.moveStart("character",a);range.moveEnd("character",d);range.select()}else i.setSelectionRange&&i.setSelectionRange(a,a+d);i.scrollTop=E;i.focus()}function D(){i.focus();E=i.scrollTop;if(document.selection){selection=document.selection.createRange().text;if(b.browser.msie){var a=document.selection.createRange(),d=a.duplicate();d.moveToElementText(i);for(h=-1;d.inRange(a);){d.moveStart("character");h++}}else h=
i.selectionStart}else{h=i.selectionStart;selection=f.val().substring(h,i.selectionEnd)}return selection}function M(){if(c.previewParserPath!=="")b.ajax({type:"POST",url:c.previewParserPath,data:c.previewParserVar+"="+encodeURIComponent(f.val()),success:function(a){I(v(a,1))}});else N||b.ajax({url:c.previewTemplatePath,success:function(a){I(v(a,1).replace(/<!-- content --\>/g,f.val()))}});return false}function I(a){if(p.document){try{sp=p.document.documentElement.scrollTop}catch(d){sp=0}p.document.open();
p.document.write(a);p.document.close();p.document.documentElement.scrollTop=sp}c.previewInWindow&&p.focus()}function J(a){k=a.shiftKey;t=a.altKey;j=!(a.altKey&&a.ctrlKey)?a.ctrlKey:false;if(a.type==="keydown"){if(j===true){li=b("a[accesskey="+String.fromCharCode(a.keyCode)+"]",B).parent("li");if(li.length!==0){j=false;setTimeout(function(){li.triggerHandler("mousedown")},1);return false}}if(a.keyCode===13||a.keyCode===10)if(j===true){j=false;u(c.onCtrlEnter);return c.onCtrlEnter.keepDefault}else if(k===
true){k=false;u(c.onShiftEnter);return c.onShiftEnter.keepDefault}else{u(c.onEnter);return c.onEnter.keepDefault}if(a.keyCode===9){if(k==true||j==true||t==true)return false;if(m!==-1){D();m=f.val().length-m;H(m,0);m=-1;return false}else{u(c.onTab);return c.onTab.keepDefault}}}}var f,i,w,E,h,m,o,r,B,K,p,N,x;f=b(this);i=this;w=[];x=false;E=h=0;m=-1;c.previewParserPath=v(c.previewParserPath);c.previewTemplatePath=v(c.previewTemplatePath);(function(){nameSpace=id="";if(c.id)id='id="'+c.id+'"';else if(f.attr("id"))id=
'id="markItUp'+f.attr("id").substr(0,1).toUpperCase()+f.attr("id").substr(1)+'"';if(c.nameSpace)nameSpace='class="'+c.nameSpace+'"';f.wrap("<div "+nameSpace+"></div>");f.wrap("<div "+id+' class="markItUp"></div>');f.wrap('<div class="markItUpContainer"></div>');f.addClass("markItUpEditor");B=b('<div class="markItUpHeader"></div>').insertBefore(f);b(y(c.markupSet)).appendTo(B);K=b('<div class="markItUpFooter"></div>').insertAfter(f);if(c.resizeHandle===true&&b.browser.safari!==true){resizeHandle=b('<div class="markItUpResizeHandle"></div>').insertAfter(f).bind("mousedown",
function(a){var d=f.height(),g=a.clientY,e,n;e=function(z){f.css("height",Math.max(20,z.clientY+d-g)+"px");return false};n=function(){b("html").unbind("mousemove",e).unbind("mouseup",n);return false};b("html").bind("mousemove",e).bind("mouseup",n)});K.append(resizeHandle)}f.keydown(J).keyup(J);f.bind("insertion",function(a,d){d.target!==false&&D();i===b.markItUp.focused&&u(d)});f.focus(function(){b.markItUp.focused=this})})()})};b.fn.markItUpRemove=function(){return this.each(function(){var s=b(this).unbind().removeClass("markItUpEditor");
s.parent("div").parent("div.markItUp").parent("div").replaceWith(s)})};b.markItUp=function(s){var q={target:false};b.extend(q,s);if(q.target)return b(q.target).each(function(){b(this).focus();b(this).trigger("insertion",[q])});else b("textarea").trigger("insertion",[q])}})(jQuery);
