/**
 * jquery.Jcrop.js v0.9.8
 * jQuery Image Cropping Plugin
 * @author Kelly Hallman <khallman@gmail.com>
 * Copyright (c) 2008-2009 Kelly Hallman - released under MIT License {{{
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:

 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.

 * }}}
 */

(function(g){g.Jcrop=function(y,C){function f(a){return""+parseInt(a)+"px"}function R(a){a=g(a).offset();return[a.left,a.top]}function F(a){return[a.pageX-P[0],a.pageY-P[1]]}function ga(a,e){return function(p){if(b.aspectRatio)switch(a){case "e":p[1]=e.y+1;break;case "w":p[1]=e.y+1;break;case "n":p[0]=e.x+1;break;case "s":p[0]=e.x+1}else switch(a){case "e":p[1]=e.y2;break;case "w":p[1]=e.y2;break;case "n":p[0]=e.x2;break;case "s":p[0]=e.x2}s.setCurrent(p);r.update()}}function ha(a){var b=a;S.watchKeys();
return function(a){s.moveOffset([a[0]-b[0],a[1]-b[1]]);b=a;r.update()}}function Y(a){switch(a){case "n":return"sw";case "s":return"nw";case "e":return"nw";case "w":return"ne";case "ne":return"sw";case "nw":return"se";case "se":return"nw";case "sw":return"ne"}}function Z(a){return function(e){if(b.disabled||"move"==a&&!b.allowMove)return!1;J=!0;var p=F(e);P=R(u);E.setCursor("move"==a?a:a+"-resize");if("move"==a)E.activateHandlers(ha(p),T);else{var p=s.getFixed(),x=Y(a),c=s.getCorner(Y(x));s.setPressed(s.getCorner(x));
s.setCurrent(c);E.activateHandlers(ga(a,p),T)}e.stopPropagation();e.preventDefault();return!1}}function U(a){return{x:parseInt(a.x*A),y:parseInt(a.y*D),x2:parseInt(a.x2*A),y2:parseInt(a.y2*D),w:parseInt(a.w*A),h:parseInt(a.h*D)}}function T(a){a=s.getFixed();a.w>b.minSelect[0]&&a.h>b.minSelect[1]?(r.enableHandles(),r.done()):r.release();E.setCursor(b.allowSelect?"crosshair":"default")}function ia(a){s.setCurrent(a);r.update()}function $(){var a=g("<div></div>").addClass(b.baseClass+"-tracker");g.browser.msie&&
a.css({opacity:0,backgroundColor:"white"});return a}function aa(a){ba([a[0]/A,a[1]/D,a[2]/A,a[3]/D])}function ba(a){s.setPressed([a[0],a[1]]);s.setCurrent([a[2],a[3]]);r.update()}function ca(a){"object"!=typeof a&&(a={});b=g.extend(b,a);"function"!==typeof b.onChange&&(b.onChange=function(){});"function"!==typeof b.onSelect&&(b.onSelect=function(){})}function V(a){b.allowResize?a?r.enableOnly():r.enableHandles():r.disableHandles();E.setCursor(b.allowSelect?"crosshair":"default");r.setCursor(b.allowMove?
"move":"default");W.css("backgroundColor",b.bgColor);"setSelect"in b&&(aa(C.setSelect),r.done(),delete b.setSelect);"trueSize"in b&&(A=b.trueSize[0]/t,D=b.trueSize[1]/q);K=b.maxSize[0]||0;L=b.maxSize[1]||0;M=b.minSize[0]||0;N=b.minSize[1]||0;"outerImage"in b&&(u.attr("src",b.outerImage),delete b.outerImage);r.refresh()}"object"!==typeof y&&(y=g(y)[0]);"object"!==typeof C&&(C={});"trackDocument"in C||(C.trackDocument=g.browser.msie?!1:!0,g.browser.msie&&"8"==g.browser.version.split(".")[0]&&(C.trackDocument=
!0));"keySupport"in C||(C.keySupport=g.browser.msie?!1:!0);var b={trackDocument:!1,baseClass:"jcrop",addClass:null,bgColor:"black",bgOpacity:0.6,borderOpacity:0.4,handleOpacity:0.5,handlePad:5,handleSize:9,handleOffset:5,edgeMargin:14,aspectRatio:0,keySupport:!0,cornerHandles:!0,sideHandles:!0,drawBorders:!0,dragEdges:!0,boxWidth:0,boxHeight:0,boundary:8,animationDelay:20,swingSpeed:3,allowSelect:!0,allowMove:!0,allowResize:!0,minSelect:[0,0],maxSize:[0,0],minSize:[0,0],onChange:function(){},onSelect:function(){}};
ca(C);var G=g(y),u=G.clone().removeAttr("id").css({position:"absolute"});u.width(G.width());u.height(G.height());G.after(u).hide();(function(a,b,p){var x=a.width(),c=a.height();x>b&&0<b&&(x=b,c=b/a.width()*a.height());c>p&&0<p&&(c=p,x=p/a.height()*a.width());A=a.width()/x;D=a.height()/c;a.width(x).height(c)})(u,b.boxWidth,b.boxHeight);var t=u.width(),q=u.height(),W=g("<div />").width(t).height(q).addClass(b.baseClass+"-holder").css({position:"relative",backgroundColor:b.bgColor}).insertAfter(G).append(u);
b.addClass&&W.addClass(b.addClass);var da=g("<img />").attr("src",u.attr("src")).css("position","absolute").width(t).height(q),X=g("<div />").width("100%").height("100%").css({zIndex:310,position:"absolute",overflow:"hidden"}).append(da),I=g("<div />").width("100%").height("100%").css("zIndex",320),Q=g("<div />").css({position:"absolute",zIndex:300}).insertBefore(u).append(X,I),H=b.boundary,O=$().width(t+2*H).height(q+2*H).css({position:"absolute",top:f(-H),left:f(-H),zIndex:290}).mousedown(function(a){if(b.disabled||
!b.allowSelect)return!1;J=!0;P=R(u);r.disableHandles();"crosshair"!=ea&&(E.setCursor("crosshair"),ea="crosshair");var e=F(a);s.setPressed(e);E.activateHandlers(ia,T);S.watchKeys();r.update();a.stopPropagation();a.preventDefault();return!1}),K,L,M,N,A,D,P=R(u),J,ea,fa,ja,s=function(){function a(){if(!b.aspectRatio){var a=m-c,z=l-d;K&&Math.abs(a)>K&&(m=0<a?c+K:c-K);L&&Math.abs(z)>L&&(l=0<z?d+L:d-L);N&&Math.abs(z)<N&&(l=0<z?d+N:d-N);M&&Math.abs(a)<M&&(m=0<a?c+M:c-M);0>c&&(m-=c,c-=c);0>d&&(l-=d,d-=d);
0>m&&(c-=m,m-=m);0>l&&(d-=l,l-=l);m>t&&(a=m-t,c-=a,m-=a);l>q&&(a=l-q,d-=a,l-=a);c>t&&(a=c-q,l-=a,d-=a);d>q&&(a=d-q,l-=a,d-=a);return x(p(c,d,m,l))}var a=b.aspectRatio,z=b.minSize[0]/A,e=b.maxSize[0]/A,f=m-c,g=l-d,n=Math.abs(f),k=Math.abs(g);0==e&&(e=10*t);n/k<a?(n=l,w=k*a,k=0>f?c-w:w+c,0>k?(k=0,h=Math.abs((k-c)/a),n=0>g?d-h:h+d):k>t&&(k=t,h=Math.abs((k-c)/a),n=0>g?d-h:h+d)):(k=m,h=n/a,n=0>g?d-h:d+h,0>n?(n=0,w=Math.abs((n-d)*a),k=0>f?c-w:w+c):n>q&&(n=q,w=Math.abs(n-d)*a,k=0>f?c-w:w+c));k>c?(k-c<z?
k=c+z:k-c>e&&(k=c+e),n=n>d?d+(k-c)/a:d-(k-c)/a):k<c&&(c-k<z?k=c-z:c-k>e&&(k=c-e),n=n>d?d+(c-k)/a:d-(c-k)/a);0>k?(c-=k,k=0):k>t&&(c-=k-t,k=t);0>n?(d-=n,n=0):n>q&&(d-=n-q,n=q);return last=x(p(c,d,k,n))}function e(a){0>a[0]&&(a[0]=0);0>a[1]&&(a[1]=0);a[0]>t&&(a[0]=t);a[1]>q&&(a[1]=q);return[a[0],a[1]]}function p(a,c,b,d){var e=a,f=b,k=c,g=d;b<a&&(e=b,f=a);d<c&&(k=d,g=c);return[Math.round(e),Math.round(k),Math.round(f),Math.round(g)]}function x(a){return{x:a[0],y:a[1],x2:a[2],y2:a[3],w:a[2]-a[0],h:a[3]-
a[1]}}var c=0,d=0,m=0,l=0,f,g;return{flipCoords:p,setPressed:function(a){a=e(a);m=c=a[0];l=d=a[1]},setCurrent:function(a){a=e(a);f=a[0]-m;g=a[1]-l;m=a[0];l=a[1]},getOffset:function(){return[f,g]},moveOffset:function(a){var b=a[0];a=a[1];0>c+b&&(b-=b+c);0>d+a&&(a-=a+d);q<l+a&&(a+=q-(l+a));t<m+b&&(b+=t-(m+b));c+=b;m+=b;d+=a;l+=a},getCorner:function(b){var c=a();switch(b){case "ne":return[c.x2,c.y];case "nw":return[c.x,c.y];case "se":return[c.x2,c.y2];case "sw":return[c.x,c.y2]}},getFixed:a}}(),r=function(){function a(a){a=
g("<div />").css({position:"absolute",opacity:b.borderOpacity}).addClass(b.baseClass+"-"+a);X.append(a);return a}function e(a,b){var c=g("<div />").mousedown(Z(a)).css({cursor:a+"-resize",position:"absolute",zIndex:b});I.append(c);return c}function p(a){var c=b.handleSize,d=k,g=c;switch(a){case "n":case "s":c="100%";break;case "e":case "w":g="100%"}return e(a,A++).width(c).height(g).css({top:f(-d+1),left:f(-d+1)})}function x(a){for(i in a)v[a[i]]=e(a[i],A++).css({top:f(-k+1),left:f(-k+1),opacity:b.handleOpacity}).addClass(b.baseClass+
"-handle")}function c(a){var c=Math.round(a.h/2-k),b=Math.round(a.w/2-k);west=-k+1;var d=a.w-k;a=a.h-k;"e"in v&&v.e.css({top:f(c),left:f(d)})&&v.w.css({top:f(c)})&&v.s.css({top:f(a),left:f(b)})&&v.n.css({left:f(b)});"ne"in v&&v.ne.css({left:f(d)})&&v.se.css({top:f(a),left:f(d)})&&v.sw.css({top:f(a)});"b"in v&&v.b.css({top:f(a)})&&v.r.css({left:f(d)})}function d(){var a=s.getFixed();s.setPressed([a.x,a.y]);s.setCurrent([a.x2,a.y2]);m()}function m(){if(z)return l()}function l(){var a=s.getFixed(),d=
a.h;Q.width(a.w).height(d);var d=a.x,e=a.y;da.css({top:f(-e),left:f(-d)});Q.css({top:f(e),left:f(d)});b.drawBorders&&B.right.css({left:f(a.w-1)})&&B.bottom.css({top:f(a.h-1)});n&&c(a);z||(Q.show(),u.css("opacity",b.bgOpacity),z=!0);b.onChange(U(a))}function r(){n=!0;if(b.allowResize)return c(s.getFixed()),I.show(),!0}function q(){n=!1;I.hide()}function t(a){(fa=a)?q():r()}var z,A=370,B={},v={},n=!1,k=b.handleOffset;b.drawBorders&&(B={top:a("hline").css("top",g.browser.msie?f(-1):f(0)),bottom:a("hline"),
left:a("vline"),right:a("vline")});b.dragEdges&&(v.t=p("n"),v.b=p("s"),v.r=p("e"),v.l=p("w"));b.sideHandles&&x(["n","s","e","w"]);b.cornerHandles&&x(["sw","nw","ne","se"]);var y=$().mousedown(Z("move")).css({cursor:"move",position:"absolute",zIndex:360});X.append(y);q();return{updateVisible:m,update:l,release:function(){q();Q.hide();u.css("opacity",1);z=!1},refresh:d,setCursor:function(a){y.css("cursor",a)},enableHandles:r,enableOnly:function(){n=!0},showHandles:function(){n&&(c(s.getFixed()),I.show())},
disableHandles:q,animMode:t,done:function(){t(!1);d()}}}(),E=function(){function a(a){f(F(a))}function e(d){d.preventDefault();d.stopPropagation();J&&(J=!1,x(F(d)),b.onSelect(U(s.getFixed())),O.css({zIndex:290}),c&&g(document).unbind("mousemove",a).unbind("mouseup",e),f=function(){},x=function(){});return!1}var f=function(){},x=function(){},c=b.trackDocument;c||O.mousemove(a).mouseup(e).mouseout(e);u.before(O);return{activateHandlers:function(b,m){J=!0;f=b;x=m;O.css({zIndex:450});c&&g(document).mousemove(a).mouseup(e);
return!1},setCursor:function(a){O.css("cursor",a)}}}(),S=function(){function a(a,c,d){b.allowMove&&(s.moveOffset([c,d]),r.updateVisible());a.preventDefault();a.stopPropagation()}var e=g('<input type="radio" />').css({position:"absolute",left:"-30px"}).keypress(function(b){if(b.ctrlKey)return!0;var c=(ja=b.shiftKey?!0:!1)?10:1;switch(b.keyCode){case 37:a(b,-c,0);break;case 39:a(b,c,0);break;case 38:a(b,0,-c);break;case 40:a(b,0,c);break;case 27:r.release();break;case 9:return!0}return nothing(b)}).blur(function(a){e.hide()}),
f=g("<div />").css({position:"absolute",overflow:"hidden"}).append(e);b.keySupport&&f.insertBefore(u);return{watchKeys:function(){b.keySupport&&(e.show(),e.focus())}}}();I.hide();V(!0);H={animateTo:function(a){var e=a[0]/A,f=a[1]/D,g=a[2]/A,c=a[3]/D;if(!fa){a=s.flipCoords(e,f,g,c);var e=s.getFixed(),d=initcr=[e.x,e.y,e.x2,e.y2],m=b.animationDelay,l=d[0],q=d[1],g=d[2],c=d[3],t=a[0]-initcr[0],u=a[1]-initcr[1],z=a[2]-initcr[2],y=a[3]-initcr[3],B=0,v=b.swingSpeed;r.animMode(!0);var n=function(){return function(){B+=
(100-B)/v;d[0]=l+B/100*t;d[1]=q+B/100*u;d[2]=g+B/100*z;d[3]=c+B/100*y;100>B?window.setTimeout(n,m):r.done();99.8<=B&&(B=100);ba(d)}}();window.setTimeout(n,m)}},setSelect:aa,setOptions:function(a){ca(a);V()},tellSelect:function(){return U(s.getFixed())},tellScaled:function(){return s.getFixed()},disable:function(){b.disabled=!0;r.disableHandles();r.setCursor("default");E.setCursor("default")},enable:function(){b.disabled=!1;V()},cancel:function(){r.done();E.activateHandlers(null,null)},focus:S.watchKeys,
getBounds:function(){return[t*A,q*D]},getWidgetSize:function(){return[t,q]},release:r.release,destroy:function(){W.remove();G.show()}};G.data("Jcrop",H);return H};g.fn.Jcrop=function(y){function C(f){var C=y.useImg||f.src,F=new Image;F.onload=function(){g.Jcrop(f,y)};F.src=C}"object"!==typeof y&&(y={});this.each(function(){if(g(this).data("Jcrop")){if("api"==y)return g(this).data("Jcrop");g(this).data("Jcrop").setOptions(y)}else C(this)});return this}})(jQuery);
